### ISSUE TITLE
请问目前能支持centos7系统吗

### ISSUE THREAD

**Issue by Muyi030** [opendatalab/MinerU#1000]
请问目前能支持centos7系统吗？还是只能在Ubuntu 22.04上使用

**Comment by myhloli** [comment]
有反馈在centos7上安装某些依赖会失败，您可以尝试创建conda虚拟环境安装，如果装不上可以用我们的dockerfile自行build一个基于ubuntu22.04构建的环境

**Comment by Muyi030** [comment]
好的谢谢！
我尝试使用dockerfile进行构建，但是好像报错，是dockerfile里面detectron2什么版本需要修改吗？
ERROR: Ignored the following versions that require a different python version: 0.0.10 Requires-Python >=3.6,<=3.10; 0.0.9 Requires-Python >=3.6,<=3.10
ERROR: Could not find a version that satisfies the requirement detectron2 (from versions: none)
ERROR: No matching distribution found for detectron2
The command '/bin/sh -c /bin/bash -c "source /opt/mineru_venv/bin/activate &&     pip3 install --upgrade pip &&     wget https://gitee.com/myhloli/MinerU/raw/master/requirements-docker.txt &&     pip3 install -r requirements-docker.txt --extra-index-url https://wheels.myhloli.com -i https://mirrors.aliyun.com/pypi/simple &&     pip3 install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/"' returned a non-zero code: 1

**Comment by myhloli** [comment]
你构建docker的设备是arm处理器吗

**Comment by Muyi030** [comment]
不是的，我是在mac上构建的，是不是需要指定目标对象为arm架构呀

**Comment by myhloli** [comment]
构建ubuntu镜像需要指定架构为x86-64，因为我们不支持arm linux
你的mac是arm架构，默认构建了arm的linux，所以后续的安装命令会失败

**Comment by Muyi030** [comment]
好的感谢！我调整一下

**Comment by myhloli** [comment]
centos7 的临时解决方案

https://github.com/opendatalab/MinerU/issues/1004

**Comment by wyupupup** [comment]
> 你构建docker的设备是arm处理器吗

我是X86_64架构的Linux虚拟机，构建docker也报错returned a non-zero code: 100，请问应该怎么解决？
