### ISSUE TITLE
一些较老系统如Centos7不再获得长期支持的说明

### ISSUE THREAD

**Issue by myhloli** [opendatalab/MinerU#1004]
近日收到多起较老操作系统安装新版本失败导致版本回退的反馈，经排查发现，部分依赖包在python>=3.12环境上不再支持manylinux2014和manylinux_2_17这两个标签。我们始终致力于对本地部署环境最广泛的兼容性，但随着时间的推移，会有更多的依赖包停止对`old linux`的支持和维护，我们目前推荐使用以下较新的操作系统来部署本项目：

1. CentOS/RHEL
CentOS 8 和 RHEL 8 及其后续版本
2. Ubuntu
Ubuntu 20.04 LTS (Focal Fossa) 及其后续版本
3. Debian
Debian 10 (Buster) 及其后续版本
4. Fedora
Fedora 30 及其后续版本

如果您仍在使用更老的linux系统，可以尝试使用以下方案部署MinerU，但我们不保证在未来的某个节点随着python环境的升级以及依赖包的更新，停止对这些linux系统的适配工作。

```
conda create -n mineru python=3.11 -y
conda activate mineru
pip install  "mineru[pipeline_old_linux]<2.2"
```

**Comment by Daliuq** [comment]
？

**Comment by xiao10ma** [comment]
You can follow [this blog ](https://xujinzh.github.io/2024/01/05/ubuntu-18-04-install-glibc2-28/index.html) to download glibc 2.28.

**Comment by xiaohangguo** [comment]
2025.01.13
您好，我建议，把这个centos 7 的更新写入readme，要不我提个pr吧，我也是安装出错了来看了下，才找到答案

**Comment by myhloli** [comment]
@xiaohangguo centos7是一款2014年发布的操作系统，且已在2024年结束生命周期。鉴于此，本项目不推荐继续使用已停止更新和支持的操作系统。因此，CentOS 7不会被列入我们项目的主线支持列表中。然而，对于那些正处于从CentOS 7迁移到其他更新的Linux发行版过渡期的用户，您仍然可以通过当前issue中的指南来安装本项目。请注意，这并不被视为官方推荐的安装方式，因为依赖于过时的软件包可能会使您的系统面临无法获得必要的安全更新的风险。

**Comment by Flanwale** [comment]
用老版本安装之后，运行magic-pdf --version报错

**Comment by myhloli** [comment]
> 用老版本安装之后，运行magic-pdf --version报错

报错内容发出来看下呢

**Comment by tj-lg100** [comment]
> > 用老版本安装之后，运行magic-pdf --version报错
> 
> 报错内容发出来看下呢
/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:711: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Traceback (most recent call last):
  File "/root/miniconda3/envs/MinerU/bin/magic-pdf", line 5, in <module>
    from magic_pdf.tools.cli import cli
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/tools/cli.py", line 12, in <module>
    from magic_pdf.tools.common import do_parse, parse_pdf_methods
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/tools/common.py", line 13, in <module>
    from magic_pdf.model.doc_analyze_by_custom_model import doc_analyze
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 15, in <module>
    from magic_pdf.model.batch_analyze import BatchAnalyze
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/batch_analyze.py", line 3, in <module>
    import cv2
ImportError: dlopen: cannot load any more object with static TLS

**Comment by 2339539741** [comment]
(For reference only)I encountered the same error and installed it successfully after I specified its version as 1.4.7. (Although it will be reminded every time that the version is too old, at least it can be used)

**Comment by tj-lg100** [comment]
> (For reference only)I encountered the same error and installed it successfully after I specified its version as 1.4.7. (Although it will be reminded every time that the version is too old, at least it can be used)

Thank you for your help! I would like to know which version of the dependency package you are talking about 1.4.7? I solved the problem by chance on my previous machine, but I'm having the same problem again in my new environment.
