### ISSUE TITLE
FastAPI的PDF解析接口,解析完的md文件和图片在哪里可以看到

### ISSUE THREAD

**Issue by asenasen123** [opendatalab/MinerU#1008]
### Description of the bug | 错误描述

FastAPI的PDF解析接口,解析完的md文件和图片在哪里可以看到

### How to reproduce the bug | 如何复现

https://github.com/opendatalab/MinerU/blob/master/projects/web_api/README.md

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by lmolhw5252** [comment]
填写output_dir，进docker内部这个目录下找到了
