### ISSUE TITLE
标题识别和代码识别需求

### ISSUE THREAD

**Issue by Tian14267** [opendatalab/MinerU#1009]
**  哈喽，各位大神们好。我想问下，咱们这个工具，目前在标题识别和代码、公式这块的效果都挺差的。咱们有啥优化提升吗 **

![image](https://github.com/user-attachments/assets/7231b64d-1b61-4ca5-84b0-f68a415f5aa9)
![image](https://github.com/user-attachments/assets/75dfb7de-3523-4ee7-becd-25d3422141a8)

**Comment by myhloli** [comment]
你要不试试开启强制ocr呢？感觉你这文档有些字其实是图片？

**Comment by Tian14267** [comment]
@myhloli 哈喽。我看了一下，是正常的PDF，不是图片形式。文字都可以直接复制的。应该是word转成的pdf。但是这些文字的识别就很拉跨。是不是有字体的限制呀

**Comment by myhloli** [comment]
文档发一下？

**Comment by Tian14267** [comment]
@myhloli 我上传到夸克盘了哈。

我用夸克网盘分享了「hello-algo-1.1.0-zh-c.pdf」，点击链接即可保存。打开「夸克APP」在线查看，支持多种文档格式转换。
链接：https://pan.quark.cn/s/99e66d4675ad

**Comment by arwinleecg** [comment]
等个后续

**Comment by myhloli** [comment]
@Tian14267 span不规范，不知道是不是word转的pdf都这样，一行有正常三行宽，影响后续的处理逻辑。如果你都是这种类型的文档，可以直接开启强制ocr功能
本文档：
![image](https://github.com/user-attachments/assets/e442ea98-0280-4a7c-b079-1aeb618092ae)
正常文档：
![image](https://github.com/user-attachments/assets/92ea4ade-0736-4162-ad7e-4c74bd583ff9)
