### ISSUE TITLE
【QA】mineru公式后处理问题

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#1014]
### Description of the bug | 错误描述

识别结果
![image](https://github.com/user-attachments/assets/5f54777f-0e60-4e58-a02e-89927746065e)

公式与文本拼接的时候，拼接了多于的text
![image](https://github.com/user-attachments/assets/51088728-3817-415a-82ad-bc6942584f09)
原pdf:
![image](https://github.com/user-attachments/assets/8a3f0814-95b6-45eb-84f3-7eeb2dc27857)

### How to reproduce the bug | 如何复现

[test.zip](https://github.com/user-attachments/files/17800516/test.zip)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
fixed
