### ISSUE TITLE
ERROR: detectron2-0.6-cp310-cp310-macosx_10_9_universal2.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by CyberAsteroid** [opendatalab/MinerU#1015]
got a problem with running ".venv/bin/pip install detectron2-0.6-cp310-cp310-macosx_10_9_universal2.whl" on my intel chip computer.

**Comment by myhloli** [comment]
you need use conda create a python3.10 environment.

**Comment by CyberAsteroid** [comment]
> you need use conda create a python3.10 environment.

Thanks. I'll try it.
