### ISSUE TITLE
layout识别错位

### ISSUE THREAD

**Issue by FHhui** [opendatalab/MinerU#1020]
### Description of the bug | 错误描述

<img width="371" alt="微信图片_20241119102810" src="https://github.com/user-attachments/assets/566779fe-958a-49fc-8868-5c0b15bf16d8">

### How to reproduce the bug | 如何复现

[《中国药典》2020年版 一部0912-69.pdf](https://github.com/user-attachments/files/17808453/2020.0912-69.pdf)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
扫描书有90度旋转，可视化的时候框画不准，但是不影响正常解析

**Comment by FHhui** [comment]
> 扫描书有90度旋转，可视化的时候框画不准，但是不影响正常解析
那应该怎么让框画准呢

**Comment by myhloli** [comment]
试着画框的时候把坐标调过，不过画出来还是不准，可能是pymupdf库本身在画框的时候对旋转页面做过处理但是又没处理对的样子
