### ISSUE TITLE
新手想问问怎么启动源码？目的是想将识别为figure的强制ocr提取文本信息

### ISSUE THREAD

**Issue by aodingpeng** [opendatalab/MinerU#1021]

**Comment by myhloli** [comment]
pip install -e .[full]

**Comment by aodingpeng** [comment]
> pip install -e .[full]

您给的命令pip成功了  但是通过根目录下的setup.py或者是app.py启动都报错了
![image](https://github.com/user-attachments/assets/00958f0c-8931-4a83-8760-e8093fa2ecd0)
![image](https://github.com/user-attachments/assets/d05e4ca6-f746-45e6-af6f-9055ca0b7cce)

**Comment by myhloli** [comment]
模型没下载，看下readme里如何下载模型那段

**Comment by aodingpeng** [comment]
> 模型没下载，看下readme里如何下载模型那段
是这里嘛？我重新安装了这两个命令都成功了
![image](https://github.com/user-attachments/assets/c0d7872b-d065-42f5-958b-4aed3a928bd1)
启动setup.py和app.py依旧报错：
![image](https://github.com/user-attachments/assets/c60171a3-3106-481d-a09d-674bd65c02fc)
![image](https://github.com/user-attachments/assets/1db2d329-b96d-4e2b-b352-c16bd88e4ba9)

**Comment by aodingpeng** [comment]
> 模型没下载，看下readme里如何下载模型那段

是这里嘛？我重新安装了这两个命令都成功了
![image](https://github.com/user-attachments/assets/c0d7872b-d065-42f5-958b-4aed3a928bd1)

然后再次启动setup.py和app.py依旧报错：
![image](https://github.com/user-attachments/assets/c60171a3-3106-481d-a09d-674bd65c02fc)
![image](https://github.com/user-attachments/assets/1db2d329-b96d-4e2b-b352-c16bd88e4ba9)

**Comment by myhloli** [comment]
你仓库代码没更新

**Comment by aodingpeng** [comment]
> 你仓库代码没更新
我先删除了原来minerU-main文件，然后重新在下载minerU压缩包；之后又按照readme里下载模型（没有重新安装conda环境只只pip了），如图：
![image](https://github.com/user-attachments/assets/6bb0ce9e-78e6-4965-b78f-d884d87b5171)

最后按照您的命令pip install -e .[full]安装成功了，但是执行setup.py依旧报这个错：
![image](https://github.com/user-attachments/assets/77c6956d-c970-416c-8b2a-5246eabbe128)

难道启动源码不是根目录下的setup.py吗

**Comment by myhloli** [comment]
setup是用来安装源码的，使用和之前的方式一样用命令行

**Comment by aodingpeng** [comment]
> setup是用来安装源码的，使用和之前的方式一样用命令行

我想跑通这个程序做debug，再修改一点点代码逻辑；请问我该怎么做才能顺利启动？

**Comment by myhloli** [comment]
> > setup是用来安装源码的，使用和之前的方式一样用命令行
> 
> 我想跑通这个程序做debug，再修改一点点代码逻辑；请问我该怎么做才能顺利启动？

你现在是用源码安装的，直接改代码用命令行跑就行
