### ISSUE TITLE
请问NVIDIA-SMI 510.54       Driver Version: 510.54       CUDA Version: 11.6可以使用GPU加速吗

### ISSUE THREAD

**Issue by Muyi030** [opendatalab/MinerU#1026]
请问NVIDIA-SMI 510.54       Driver Version: 510.54       CUDA Version: 11.6可以使用GPU加速吗，还是必须要CUDA12.1以上？

**Comment by myhloli** [comment]
要更新驱动，到支持cuda12.1以上的版本

**Comment by Muyi030** [comment]
好的谢谢
