### ISSUE TITLE
使用RapidTable识别表格且已开启table-config中的识别表格功能，结果是图片而不是html

### ISSUE THREAD

**Issue by mrslimslim** [opendatalab/MinerU#1028]
### Description of the bug | 错误描述

使用RapidTable识别表格且已开启table-config中的识别表格功能，结果是图片而不是html

### How to reproduce the bug | 如何复现

具体图片：

![jljh201706004_page_4-0](https://github.com/user-attachments/assets/8526bbbd-51d1-4eb9-859b-5215a290368c)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
magic-pdf.json的内容发一下看看？

**Comment by mrslimslim** [comment]
> magic-pdf.json的内容发一下看看？

<img width="1179" alt="企业微信截图_d6d022c8-c855-44b2-98cb-e08ac836b90b" src="https://github.com/user-attachments/assets/ab9c813c-b4a4-4743-ba9d-a3f3de752dbe">

是这样的，辛苦看下，还有在Mineru官网测试和hf给的demo测试出来的效果也不一样。

**Comment by myhloli** [comment]
配置文件看着没啥问题，pdf文件能发一下吗

**Comment by mrslimslim** [comment]
> 配置文件看着没啥问题，pdf文件能发一下吗

这个是测试的几份文件，基本上用命令行转都有问题

[b13e299cab4e88d7125435f686751539_page_18-1.pdf](https://github.com/user-attachments/files/17823649/b13e299cab4e88d7125435f686751539_page_18-1.pdf)

[jljh201706004_page_4-0.pdf](https://github.com/user-attachments/files/17823640/jljh201706004_page_4-0.pdf)

[631775ee0b98483fe0e8525db9ff22c5_page_2-0.pdf](https://github.com/user-attachments/files/17823659/631775ee0b98483fe0e8525db9ff22c5_page_2-0.pdf)

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/092d05af-554a-4681-b9e8-069bc78bd186)
我这边测试是正常的，请自行查看magic-pdf的版本是否为0.9.3

**Comment by mrslimslim** [comment]
> ![image](https://private-user-images.githubusercontent.com/11393164/387967371-092d05af-554a-4681-b9e8-069bc78bd186.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwODg2NzcsIm5iZiI6MTczMjA4ODM3NywicGF0aCI6Ii8xMTM5MzE2NC8zODc5NjczNzEtMDkyZDA1YWYtNTU0YS00NjgxLWI5ZTgtMDY5YmM3OGJkMTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA3MzkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYmY5M2IxZGZmMTE1N2NkMTNhMjQwZWYzZTZiNjE3NGVhMWFmY2UzZjE2MTdiODdhZGI1YzZjMTFjMjYyNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.REb9evnsTGYZyEZbSUAxSYX1mZINbfntU8Urm0SHS38) 我这边测试是正常的，请自行查看magic-pdf的版本是否为0.9.3

在hf表现是正常的，但是在https://opendatalab.com/OpenSourceTools/Extractor/PDF和本地测试都是直接识别为图片了

**Comment by myhloli** [comment]
https://opendatalab.com/OpenSourceTools/Extractor/PDF 的发版周期更长，相对而言新功能的上线会更晚，本地部署的可以自行查看版本是否最新版，如果不是最新版需要自己手动更新。

**Comment by mrslimslim** [comment]
> https://opendatalab.com/OpenSourceTools/Extractor/PDF 的发版周期更长，相对而言新功能的上线会更晚，本地部署的可以自行查看版本是否最新版，如果不是最新版需要自己手动更新。

但是我们不是最新版本才支持rapid_table吗，不是最新版本应该用不了吧

**Comment by myhloli** [comment]
你 --version看下版本

**Comment by mrslimslim** [comment]
> 你 --version看下版本

版本确实是0.9.3
<img width="668" alt="企业微信截图_b6c080f4-3344-4d56-bafc-ce85cb3dfdad" src="https://github.com/user-attachments/assets/9150620a-45d4-4ca5-a66a-e694d6f3d15c">

**Comment by myhloli** [comment]
跑一下你的样本，看看日志有什么异常？

**Comment by mrslimslim** [comment]
> 跑一下你的样本，看看日志有什么异常？

具体看哪些呢 只有一块WARN其他都是INFO

<img width="1839" alt="企业微信截图_891524f8-6aff-441c-ad79-9edc91bd227a" src="https://github.com/user-attachments/assets/599e7f93-6816-4911-ae1e-f7190f870bcd">

我把具体的输出文件压缩发给你吧
[测试图片4.zip](https://github.com/user-attachments/files/17827242/4.zip)

**Comment by myhloli** [comment]
你跑的样本和你上传的不一样，你本地跑的图贴着顶格，你上传的表在页面中间，不建议使用这种样本进行测试，最好是符合真实文档结构的样式，不然layout模型无法准确识别区域和类别。

**Comment by mrslimslim** [comment]
> 你跑的样本和你上传的不一样，你本地跑的图贴着顶格，你上传的表在页面中间，不建议使用这种样本进行测试，最好是符合真实文档结构的样式，不然layout模型无法准确识别区域和类别。

好的感谢，我们定位到问题了

**Comment by LeiiiiiiiZ** [comment]
> > 你跑的样本和你上传的不一样，你本地跑的图贴着顶格，你上传的表在页面中间，不建议使用这种样本进行测试，最好是符合真实文档结构的样式，不然layout模型无法准确识别区域和类别。
> 
> 好的感谢，我们定位到问题了

你好，我也遇到了同样的问题，请问如何解决呢？

**Comment by mrslimslim** [comment]
> > > 你跑的样本和你上传的不一样，你本地跑的图贴着顶格，你上传的表在页面中间，不建议使用这种样本进行测试，最好是符合真实文档结构的样式，不然layout模型无法准确识别区域和类别。
> > 
> > 
> > 好的感谢，我们定位到问题了
> 
> 你好，我也遇到了同样的问题，请问如何解决呢？

一种是check你们的pdf的大小，保证是A4大小的。还有一种办法就是你直接调用底层模型RapidTable，不要经过mineru的排版分析逻辑，这样的效果应该会更好一点。
