### ISSUE TITLE
一张图片里有简体中文、英文、韩文、繁体中文、日文等多种语言 如何进行OCR识别

### ISSUE THREAD

**Issue by huyidu** [opendatalab/MinerU#1031]
### Description of the bug | 错误描述

一张图片里有简体中文、英文、韩文、繁体中文、日文等多种语言 如何进行OCR识别

### How to reproduce the bug | 如何复现

一张图片里有简体中文、英文、韩文、繁体中文、日文等多种语言 如何进行OCR识别

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
混合语言ocr是不支持的

**Comment by Sherler** [comment]
日语、俄语的单语言图片ocr、也不支持吗？我看PP-OCR的文档貌似是可以支持的

**Comment by myhloli** [comment]
> 日语、俄语的单语言图片ocr、也不支持吗？我看PP-OCR的文档貌似是可以支持的

需要通过参数手动指定语言，具体参数请查看--help
