### ISSUE TITLE
批量测试

### ISSUE THREAD

**Issue by lyc728** [opendatalab/MinerU#1035]
你好 我这边发现，循环推理的话，模型会反复初始化，这样对于创建服务是不友好的，请问有计划进行更新吗

**Comment by myhloli** [comment]
循环推理不会重复加载模型的，可以自行查看日志记录确认

**Comment by lyc728** [comment]
每个文件都不一样，你每次加载不同pdf，进行推理，模型是要初始化的呀
model_input = {
                            "ocr": ocr,
                            "show_log": show_log,
                            "models_dir": local_models_dir,
                            "device": device,
                            "table_config": table_config,
                            "layout_config": layout_config,
                            "formula_config": formula_config,
                            "lang": lang,
            }

            custom_model = CustomPEKModel(**model_input)
https://github.com/opendatalab/MinerU/blob/master/magic_pdf/model/doc_analyze_by_custom_model.py

**Comment by myhloli** [comment]
是否重复初始化可以自行通过日志确认
