### ISSUE TITLE
There are reading order problems in this published version

### ISSUE THREAD

**Issue by zahrarsl** [opendatalab/MinerU#1038]
### Description of the bug | 错误描述

I converted a number of pdf files to markdown files with this method, but there were some errors in all these files.  The order of the text is not observed.  Like the photos below.

![Screenshot 2024-11-20 130720](https://github.com/user-attachments/assets/46e90e0d-6e4c-47cf-9fb1-e240df73455c)
![Screenshot 2024-11-20 130706](https://github.com/user-attachments/assets/7603bfc6-aafa-4272-ad83-5eaab54188d8)

### How to reproduce the bug | 如何复现

I expected the text inside the markdown file to be exactly the same as the pdf file.

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
Can you upload this pdf file？We will fix it as soon as possible.

**Comment by zahrarsl** [comment]
[10.1016@j.is.2016.03.004.pdf](https://github.com/user-attachments/files/17828736/10.1016%40j.is.2016.03.004.pdf)
This file is sent as an example.  These cases have been observed in several places.  Is it because of the new version?
How accurate is the model?

**Comment by myhloli** [comment]
We have noticed issues with reading order and character loss in areas dense with formulas in text-based PDFs. We will thoroughly fix this problem in the next version.

**Comment by zahrarsl** [comment]
Thank you very much.

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/89fa1c4a-ce8c-4d73-abf2-9731943f9a69)
We are pleased that our new code performed well in this sample. In the coming days, we will release a new version to thoroughly address this issue.

**Comment by zahrarsl** [comment]
You are really great.

**Comment by zahrarsl** [comment]
[10.1016@j.aci.2014.05.001_origin.pdf](https://github.com/user-attachments/files/17829871/10.1016%40j.aci.2014.05.001_origin.pdf)
I'm sorry. In this file, there is a series of algorithm sections, some of which recognize the image and some others do not and read as text.  I suggest you consider this in the new version.  thanks

**Comment by myhloli** [comment]
fixed
