### ISSUE TITLE
rapidocr_paddle

### ISSUE THREAD

**Issue by lyc728** [opendatalab/MinerU#1042]
File "/usr/local/lib/python3.9/site-packages/rapidocr_paddle/utils/infer_engine.py", line 60, in __call__
    self.predictor.run()
    │    │         └ <instancemethod run at 0x7f1dad1df610>
    │    └ <paddle.base.libpaddle.PaddleInferPredictor object at 0x7f1d9d9f6df0>
    └ <rapidocr_paddle.utils.infer_engine.PaddleInferSession object at 0x7f1d9d9fe580>

OSError: (External) CUBLAS error(15). 
  [Hint: 'CUBLAS_STATUS_NOT_SUPPORTED'.  The functionality requested is not supported ] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:41)
  [operator < fc > error]

**Comment by myhloli** [comment]
paddle框架没装好或者系统不兼容，可以自行用干净的环境装一个paddleocr的damo跑一下试试

**Comment by lyc728** [comment]
<img width="534" alt="企业微信截图_17321748041653" src="https://github.com/user-attachments/assets/10704322-a1ef-4219-b6fb-0ce15a12befd">

你好 这个表格解析时间正常吗？我看ocr占据了绝大部分

**Comment by myhloli** [comment]
> <img alt="企业微信截图_17321748041653" width="534" src="https://private-user-images.githubusercontent.com/88084847/388403484-10704322-a1ef-4219-b6fb-0ce15a12befd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MTg4NTEsIm5iZiI6MTczMjUxODU1MSwicGF0aCI6Ii84ODA4NDg0Ny8zODg0MDM0ODQtMTA3MDQzMjItYTFlZi00MjE5LWI2ZmItMGNlMTVhMTJiZWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA3MDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyM2ViZDRkN2ExMjg0ODEyZWMxNTRkZjVkMDRmZjVkNmIyYTczNGQzODJjNjQwYWIzMjBlMDg3ODFiN2ZkMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e8PzWvn-I8KA17ibucg_IL_gVLjv_GM6Sa237ScM5Xk">
> 你好 这个表格解析时间正常吗？我看ocr占据了绝大部分

在开启paddlegpu加速的情况下，一张表正常不会超过2s，可以自行查阅readme开启ocr加速功能。

**Comment by lyc728** [comment]
官网更新了加载到gpu上了 你这个还没更新
```
table_engine = RapidTable()
# 开启onnx-gpu推理
# table_engine = RapidTable(use_cuda=True)
```
https://github.com/opendatalab/MinerU/blob/master/magic_pdf/model/sub_modules/table/rapidtable/rapid_table.py
