### ISSUE TITLE
表格布局识别不正确

### ISSUE THREAD

**Issue by squirrelfish** [opendatalab/MinerU#1044]
### Description of the bug | 错误描述

第4页4个表格识别成1个表格了

### How to reproduce the bug | 如何复现

[H3_AP202411191640951928_YB.pdf](https://github.com/user-attachments/files/17842325/H3_AP202411191640951928_YB.pdf)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
这种离得太近了，不太好识别

**Comment by yyxg** [comment]
https://github.com/opendatalab/MinerU/blob/master/demo/demo2.pdf
![WechatIMG835](https://github.com/user-attachments/assets/3a7efc11-ba11-460a-9de8-c660bad60462)
这个demo2.pdf 里面的表格为什么识别出来还是图片呢

**Comment by myhloli** [comment]
> https://github.com/opendatalab/MinerU/blob/master/demo/demo2.pdf ![WechatIMG835](https://private-user-images.githubusercontent.com/13608518/389347979-3a7efc11-ba11-460a-9de8-c660bad60462.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDMxNDAsIm5iZiI6MTczMjUwMjg0MCwicGF0aCI6Ii8xMzYwODUxOC8zODkzNDc5NzktM2E3ZWZjMTEtYmExMS00NjBhLTlkZTgtYzY2MGJhZDYwNDYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAyNDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMjMwODFmOWIzZTM2YjU1Y2Q1ZDYxMzFjNzc4NGM2OWM0NzQ5MTRjNGI0OTdlZDBmMTk3NWM2OWYxY2RhMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XGuVRoH83gKE_ISkOBHJURR-OLwHbD23T7bMujs1n4M) 这个demo2.pdf 里面的表格为什么识别出来还是图片呢

table1和Figure 4离太近了，layoutlmv3在细节上精度不够，没能给他分开，table2是正常的；
现在我们更新支持了doclayout-yolo作为layout识别模型，这个精度稍微高一些，可以将table1和figure4分开的
![image](https://github.com/user-attachments/assets/f663ed27-0f55-4b9e-9f48-94bba9a2e594)

**Comment by yyxg** [comment]
那我现在更新下载的还是LayoutLMv3模型？
![WechatIMG837](https://github.com/user-attachments/assets/ac51d9b5-355d-4739-96ad-53414d1ece5f)

**Comment by myhloli** [comment]
要参考readme中的内容修改配置文件切换layout模型的
https://github.com/opendatalab/MinerU#3-modify-the-configuration-file-for-additional-configuration
