### ISSUE TITLE
请问下，mineru支持对word文档的解析吗？

### ISSUE THREAD

**Issue by asenasen123** [opendatalab/MinerU#1051]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
对存在的问题进行清晰且简洁的描述。例如：我一直很困扰的是 [...]

**Describe the solution you'd like**
**描述您期望的解决方案**
清晰且简洁地描述您希望实现的内容。

**Describe alternatives you've considered**
**描述您已考虑的替代方案**
清晰且简洁地描述您已经考虑过的任何替代解决方案。

**Additional context**
**提供更多细节**
请附上任何相关截图、链接或文件，以帮助我们更好地理解您的请求。

**Comment by myhloli** [comment]
需要自己先用libreoffice等工具将word转成pdf再调用mineru解析

**Comment by asenasen123** [comment]
好的，多谢





------------------ 原始邮件 ------------------
发件人: Xiaomeng Zhao ***@***.***&gt;
发送时间: 2024年11月22日 18:32
收件人: opendatalab/MinerU ***@***.***&gt;
抄送: asenasen123 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [opendatalab/MinerU] 请问下，mineru支持对word文档的解析吗？ (Issue #1051)





 
需要自己先用libreoffice等工具将word转成pdf再调用mineru解析
