### ISSUE TITLE
pipe_mk_uni_format 要如何返回坐标

### ISSUE THREAD

**Issue by sph116** [opendatalab/MinerU#1057]
pipe_mk_uni_format 方法 要如何返回坐标

**Comment by myhloli** [comment]
需要修改这个方法：https://github.com/opendatalab/MinerU/blob/fcfaede87b7a26900be1646620e58fa237d77c5c/magic_pdf/dict2md/ocr_mkcontent.py#L185
将传入的para_block的bbox值写入para_content中
