### ISSUE TITLE
将MinerU作为新项目的一小部分，是否一定要将这个项目开源？

### ISSUE THREAD

**Issue by Han-0107** [opendatalab/MinerU#1078]
用MinerU的输出作为LLM的输入，不过要把MinerU、后续的处理流程和LLM集成起来，这样的情况是否需要开源整个项目？
谢谢！

**Comment by myhloli** [comment]
当您的项目使用了遵循AGPLv3.0（Affero General Public License version 3.0）许可的库时，您需要遵守该许可证的要求。AGPLv3.0是一种非常严格的开源许可证，它要求在某些情况下，如果您的软件使用了受此许可证保护的代码，您必须公开您的源代码。

具体来说，如果您以任何形式分发或允许他人远程与您的应用程序交互，而该应用程序包含了AGPLv3.0许可的组件，那么您就需要遵守以下几点：

1. **分发源代码**：如果您以任何形式分发包含AGPLv3.0库的软件（无论是作为独立产品还是作为更大系统的一部分），您必须提供整个项目的完整源代码，包括任何修改过的版本，以及编译或构建过程中使用的脚本。

2. **服务提供**：即使您没有直接分发软件，而是通过网络提供服务（例如，通过Web应用或API），根据AGPLv3.0的规定，您也必须向所有能够与您的应用程序进行网络交互的用户提供源代码。这意味着，如果您的软件是在线运行的，并且用户可以通过互联网访问它，那么您有义务提供源代码。

3. **修改和派生作品**：如果您对AGPLv3.0许可下的库进行了任何修改，或者创建了基于该库的新作品，您必须以相同的方式发布这些修改或新作品的源代码。

4. **保持许可**：您还需要确保您的项目继续遵循AGPLv3.0的条款，包括但不限于保持版权声明、许可声明和免责声明不变。

需要注意的是，如果您只是在内部使用该库而不对外分发软件或提供服务，则不需要公开您的源代码。但是，一旦涉及到外部分发或服务提供，就必须遵守上述规定。

如果您不确定自己的情况是否需要公开源代码，建议咨询法律专家或仔细阅读AGPLv3.0的具体条款。遵守开源软件的许可要求不仅是法律上的义务，也是对开源社区贡献者的尊重和支持。
