### ISSUE TITLE
Can't mix strings and bytes in path components

### ISSUE THREAD

**Issue by hukai520** [opendatalab/MinerU#1079]
### Description of the bug | 错误描述

当我使用简单的demo.py时显示如标题所示的错误，而当我使用magic_pdf_parse_main.py时，又会出现“string indices must be integers”的错误，非常感谢您的解答！

### How to reproduce the bug | 如何复现

![image](https://github.com/user-attachments/assets/7fa9ccf5-31fc-49d5-a012-45ef89c695d4)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
0.9.x到0.10.x重构了文件读写工具类，老的demo代码在0.10.x版本不适用了，今天已经更新了demo代码，并同步release了0.10.1版本，你可以将demo代码和模块全部更新到最新再试一下。
