### ISSUE TITLE
PDF里面的A0级版面尺寸的扫描件支持

### ISSUE THREAD

**Issue by fmx0717** [opendatalab/MinerU#1084]
PDF中的扫面件尺寸是A0纸张大小需要放大才能清晰看清的这种，就只能识别为一张图片了，无法正确识别其中的文字及其表格，请问是否会适配解析

**Comment by fmx0717** [comment]
主要是支持缩放比例100%的情况，不然因为页面太大默认比例小可能导致不清晰解析为图片

**Comment by myhloli** [comment]
我们没有缩放比例的说法，是按dpi缩放的，一般是200dpi，当然你如果是a0扫描件可能会因为分辨率太高使用72dpi缩放，我们目前的项目还是以论文书籍等信息提取为主，这种超大扫描件支持的不好也是正常的。如果能自己先切成A3或者A4大小可能会好识别一些
