### ISSUE TITLE
OCR会导致文本识别不全

### ISSUE THREAD

**Issue by FHhui** [opendatalab/MinerU#1087]
### Description of the bug | 错误描述

OCR会导致文本识别不全，可能是因为一个span一个span进行ocr识别的原因，如果换成整张图片进行识别的话会出现阅读顺序问题。

### How to reproduce the bug | 如何复现

[印刷体双列24-25.pdf](https://github.com/user-attachments/files/17911880/24-25.pdf)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
我这边测试没有发现文本不全和阅读顺序的问题，您升下0.10再试试呢？

**Comment by FHhui** [comment]
好的我试一下

**Comment by FHhui** [comment]
重构图、表与描述性文本的匹配逻辑，大幅提升 caption 和 footnote 与图表的匹配准确率，并将描述性文本的丢失率降至接近0
可以问一下这部分的逻辑在哪里么，感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "opendatalab/MinerU"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月26日(星期二) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [opendatalab/MinerU] OCR会导致文本识别不全 (Issue #1087)





 
我这边测试没有发现文本不全和阅读顺序的问题，您升下0.10再试试呢？
