### ISSUE TITLE
RapidTable非OCR文本提取

### ISSUE THREAD

**Issue by sirius219** [opendatalab/MinerU#1092]
在解析存在较容易混淆字符的表格时发现一个问题，例如`I/O`这样的字符，容易被OCR识别成数字1、0。根据现在的代码，提供给RapidTable的文本输入都是通过RapidOCR提取的。但实际上很多表格的内容和普通文本一样都可以用PyMuPDF提取，请问下之后表格内容有考虑像普通文本一样支持是否需要OCR的动态提取吗？

**Comment by myhloli** [comment]
目前的架构在模型解析和后处理pipeline是完全分离的，因此模型端只能访问文档页面截图而无法访问文档对象，pipeline则拿不到定位框与html结构的关系，所以表格的动态ocr需要对整个架构进行较大改动，短期内应该不会支持。
