### ISSUE TITLE
使用tablemaster OCR识别表格内容识别不全

### ISSUE THREAD

**Issue by Jonas0119** [opendatalab/MinerU#1093]
### Description of the bug | 错误描述

使用tablemaster OCR识别表格内容识别不全，特别是表格的最后一行，有些内容给丢了。我想问一下是识别table的用具本事如此，还是说咱们在处理识别的内容时超长度了，还是处理异常了。多谢!

我也使用rapid_table进行解析，但是针对我自己的文件上tablemaster效果上是最好的，就是有内容丢失

### How to reproduce the bug | 如何复现

使用的咱们docker imgaes，使用多显卡进行pdf文档解析。
原始pdf文件件附件
[datang_origin.pdf](https://github.com/user-attachments/files/17915175/datang_origin.pdf)

两个图片一个是原始的table
![识别前的table](https://github.com/user-attachments/assets/6a748f42-d475-4021-8a30-1a49710d809c)
，另一个识别后的table内容
![识别后的table](https://github.com/user-attachments/assets/37197eb5-27ef-473c-a85a-d8ca3ca293f1)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
短期内没有表格继续优化的计划，目前我们接入了三款不同的表格识别模型，可以根据自己的测试结果选择使用最适合自己的模型。

**Comment by Jonas0119** [comment]
收到，多谢
