### ISSUE TITLE
Detectron2在Linux aarch64上不支持

### ISSUE THREAD

**Issue by 2384441037** [opendatalab/MinerU#1096]
### Description of the bug | 错误描述

我想在我的服务器上运行minerU，但是detectron2没有支持aarch64的wheel，我怎么才能解决这个问题

### How to reproduce the bug | 如何复现

先执行
conda create -n MinerU python=3.10
conda activate MinerU
pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com -i https://mirrors.aliyun.com/pypi/simple
接着下载模型
然后运行magic-pdf pdf-command --pdf "demo1.pdf" --inside_model true
命令能执行成功，应该是因为demo里面存在demo1.json文件。
但是我执行magic-pdf pdf-command --pdf "nnU-net.pdf" --inside_model true就发生错误。
![image](https://github.com/user-attachments/assets/1ca6baae-1fe9-42be-9621-06fd2415da9f)
我怎么才能在aarch64上安装detectron2

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
可以尝试自己通过clone此仓库并通过源码编译安装：
https://github.com/facebookresearch/detectron2

**Comment by 2384441037** [comment]
@myhloli 
cd detectron2
python setup.py build develop
这样吗

**Comment by myhloli** [comment]
> @myhloli cd detectron2 python setup.py build develop 这样吗

```
python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
# (add --user if you don't have permission)

# Or, to install it from a local clone:
git clone https://github.com/facebookresearch/detectron2.git
python -m pip install -e detectron2
```

**Comment by 2384441037** [comment]
> > @myhloli cd detectron2 python setup.py build develop 这样吗
> 
> ```
> python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
> # (add --user if you don't have permission)
> 
> # Or, to install it from a local clone:
> git clone https://github.com/facebookresearch/detectron2.git
> python -m pip install -e detectron2
> ```
谢谢，我去试一下

**Comment by 2384441037** [comment]
> > @myhloli cd detectron2 python setup.py build develop 这样吗
> 
> ```
> python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
> # (add --user if you don't have permission)
> 
> # Or, to install it from a local clone:
> git clone https://github.com/facebookresearch/detectron2.git
> python -m pip install -e detectron2
> ```

![image](https://github.com/user-attachments/assets/84e45770-aa94-4f9d-b62e-ae15c714ab34)
安装成功了，版本显示的0.6，但是实际运行命令行还是会报错，这是为什么呢

**Comment by myhloli** [comment]
再执行一遍
```
pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com/ -i https://mirrors.aliyun.com/pypi/simple
```

**Comment by 2384441037** [comment]
> 再执行一遍
> 
> ```
> pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com/ -i https://mirrors.aliyun.com/pypi/simple
> ```
大佬，重新执行了一遍，下载中有个warning，然后在执行命令，还是显示detectron2不存在的问题
![image](https://github.com/user-attachments/assets/850a7281-25e7-47f6-a0da-f1444c7fa998)
![image](https://github.com/user-attachments/assets/998a818b-d225-457e-914f-cfa9f052a47f)
![image](https://github.com/user-attachments/assets/fee5351a-2b97-4937-8ba5-79b8f0c3f57a)

**Comment by myhloli** [comment]
应该是别的依赖不兼容arm导致没有装上新版本，你可以指定版本为0.10.1看看到底哪个包不兼容

**Comment by 2384441037** [comment]
> 应该是别的依赖不兼容arm导致没有装上新版本，你可以指定版本为0.10.1看看到底哪个包不兼容
![image](https://github.com/user-attachments/assets/e59353cf-0472-417a-8bc8-b664412f1601)
0.10.1里面torchtext 和 torchvision需要的torch版本是不是冲突了

**Comment by myhloli** [comment]
没冲突，应该是需要的版本没有arm的预编译包，也需要自己编译一下

**Comment by 2384441037** [comment]
> 没冲突，应该是需要的版本没有arm的预编译包，也需要自己编译一下

怎么操作呢？不太懂

**Comment by myhloli** [comment]
我们也没有针对arm做过具体的适配工作，建议换一台x86的服务器或者使用我们的在线api

https://opendatalab.com/OpenSourceTools/?tool=extract&openApplyModal=true

**Comment by 2384441037** [comment]
> 我们也没有针对arm做过具体的适配工作，建议换一台x86的服务器或者使用我们的在线api
> 
> https://opendatalab.com/OpenSourceTools/?tool=extract&openApplyModal=true

好的，谢谢你！
有什么方法可以绕过使用detectron2这个库吗，我想使用的就是demo.py里面的功能

**Comment by myhloli** [comment]
没有办法绕过，因为这是layoutlmv3的依赖

**Comment by 2384441037** [comment]
> 没有办法绕过，因为这是layoutlmv3的依赖

好吧，非常感谢！！！

**Comment by 2384441037** [comment]
> 没有办法绕过，因为这是layoutlmv3的依赖

我发现demo文件夹里面，如果同时存在pdf文件和json文件的话，aarch64就能执行
![image](https://github.com/user-attachments/assets/d3c6acae-afa1-46fb-bda1-f93bb2908dd9)
我怎么能通过代码，通过输入pdf得到他的json文件

**Comment by myhloli** [comment]
demo里的json是模型推理的中间文件，你应用安装不完整是没办法生成这个json的

**Comment by 2384441037** [comment]
> demo里的json是模型推理的中间文件，你应用安装不完整是没办法生成这个json的

好的，十分感谢，然后我要使用minerU提取网页信息的话，怎么操作呢，有教程吗
