### ISSUE TITLE
projects/web_api 缺少文件？

### ISSUE THREAD

**Issue by yyxg** [opendatalab/MinerU#1097]
![QQ_1732613476992](https://github.com/user-attachments/assets/b6ca1c5d-82c9-44ef-bb60-194a1804f9ee)
models和.paddleocr在项目目录里没有

**Comment by Metasymbols** [comment]
通过脚本下载

**Comment by myhloli** [comment]
参考readme运行模型下载脚本后你可以在用户目录找到模型文件目录
