### ISSUE TITLE
Can not extract text from images in the PDF file?

### ISSUE THREAD

**Issue by aidevmin** [opendatalab/MinerU#1111]
### Description of the bug | 错误描述

I set mode OCR but text is not extracted from images in PDF file. In the markdown, it links to the extracted images, not text in images.
Whether I correctly config.

### How to reproduce the bug | 如何复现

No

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
We will not extract any text information from images in any mode.

**Comment by aidevmin** [comment]
@myhloli 
Thanks. As my understanding it supports OCR to extract text, but actually it does not do it.
It means that I need to use other tool to extract text from extracted images.

**Comment by myhloli** [comment]
Our design intent is to generate markdown or JSON files that maintain the same format as the original document, with image areas being directly extracted rather than converted into text via OCR.
