### ISSUE TITLE
重构图、表与描述性文本的匹配逻辑，大幅提升 caption 和 footnote 与图表的匹配准确率，并将描述性文本的丢失率降至接近0

### ISSUE THREAD

**Issue by FHhui** [opendatalab/MinerU#1114]
重构图、表与描述性文本的匹配逻辑，大幅提升 caption 和 footnote 与图表的匹配准确率，并将描述性文本的丢失率降至接近0
可以问一下这部分的逻辑在哪里么，感谢

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/master/magic_pdf/model/magic_model.py
