### ISSUE TITLE
不可选中的标题文本内容缺失

### ISSUE THREAD

**Issue by sirius219** [opendatalab/MinerU#1115]
某些格式较为复杂的pdf可能存在部分文本可以选中另一部分不能，如果不可选中的部分为标题的话会出现内容识别缺失的情况。
根据代码看起来似乎只有text类型的才会在页面被自动识别为txt模式的时候额外执行ocr识别，title类型的并不会。
现阶段只有强制开启ocr模式可以解决这个问题，请问后续会考虑处理么？

**Comment by myhloli** [comment]
现在的版本应该支持所有文本块在提取不到文字的情况下自动调用ocr，当然也包括标题，您可以上传一份效果不佳的样本给我们分析一下为什么会失效。

**Comment by lyc728** [comment]
为什么布局是这样的
<img width="377" alt="企业微信截图_17327004083709" src="https://github.com/user-attachments/assets/c1b59e0e-efcd-403d-ad1b-fcc6931b6538">

**Comment by sirius219** [comment]
又试了一下发现问题原因了，的确不是逻辑层面把title类型除外了，而是不知为何这类标题的`span['content']`在经过处理后变成了一个有长度的空格字符串。而过滤空span的代码只是简单判断了下字符串的长度所以导致标题没有额外再调用ocr识别。
https://github.com/opendatalab/MinerU/blob/52ef1bc782ddf8fac0fae519fd61425eea3e5786/magic_pdf/pdf_parse_union_core_v2.py#L109C3-L109C38
我把这一行判断修改了一下，就可以正常识别了。

**Comment by myhloli** [comment]
pdf文件能发一份吗，我想看看为啥会填进去一个有长度的空字符…

**Comment by sirius219** [comment]
不好意思，遇到这个情况的pdf文件都是内部资料不方便分享，应该是PyMuPDF那边在这种span的区域里提取出了一个空格字符然后就被填进去了…

**Comment by myhloli** [comment]
emmm，也就是说文本区域本身是用图片展示的，但是还放了个空格占位吗

**Comment by sirius219** [comment]
不太懂这种pdf的格式，我直接选中复制整个页面的文本内容，里面是看不到这个空格的

**Comment by myhloli** [comment]
能用pymupdf提取所有的span然后把span框画出来看看吗

**Comment by sirius219** [comment]
嗯有空我试一下

**Comment by myhloli** [comment]
> 嗯有空我试一下

我写了一个普适性的修复方案，能把出现问题的单页通过浏览器的打印功能保存出来发到我的邮箱用于测试吗？我的邮箱是moe@myhloli.com
