### ISSUE TITLE
magic-pdf版本0.10.1，内网环境下需要请求外部连接问题

### ISSUE THREAD

**Issue by zxd-hue** [opendatalab/MinerU#1118]
### Description of the bug | 错误描述

错误信息：HTTPSConnectionPool(host='api.github.com',port=443):Max retries exceded with url:......
看到之前有人问过同样的问题，解决方法是升级至>=0.6.2b1版本，但我是0.10.1版本，依然遇到了这个问题，真诚求解。

### How to reproduce the bug | 如何复现

无法联网的情况下会出现这个问题

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
看看模型文件是否都下载完整，模型文件不完整的时候yolo会去github找模型

**Comment by zxd-hue** [comment]
> 看看模型文件是否都下载完整，模型文件不完整的时候yolo会去github找模型

感谢回复，已解决。
