### ISSUE TITLE
对于同一个文档，在线测试稳定版比开发版的公式识别准确多，什么原因？

### ISSUE THREAD

**Issue by THWBS111** [opendatalab/MinerU#1122]
### Description of the bug | 错误描述

对于同一个文档，在线测试稳定版比开发版的公式识别准确多，什么原因？下图中origin.png是原图，stable.png是稳定版转化的结果截图，test.png是测试版转化结果截图。
![origin](https://github.com/user-attachments/assets/d800ce03-d9d7-4454-b27c-bed153f799d1)
![stable](https://github.com/user-attachments/assets/accfa6f9-ee59-4fae-b3f1-d206e1f61649)
![test](https://github.com/user-attachments/assets/41928eb6-f41a-4641-a1aa-10229eb9ba60)

### How to reproduce the bug | 如何复现

测试截图如上。

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
一个是unimernet 0.1，一个是unimernet 0.2，在部分样例上可能会有些差异，但是在整体评测上0.2版本是比0.1强的

**Comment by THWBS111** [comment]
我看unimernet有4.9g的版本，但是MinerU用的是3.7g的版本，有什么区别

**Comment by myhloli** [comment]
模型的参数量不同
