### ISSUE TITLE
pdf表格不能识别成文本

### ISSUE THREAD

**Issue by zuanzuanshao** [opendatalab/MinerU#1123]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
0.10版本，cuda加速模式，提取pdf发现表格信息被识别成图片，期望识别成文本信息
对存在的问题进行清晰且简洁的描述。例如：我一直很困扰的是 [...]
表格信息没有识别为文本信息

**Describe the solution you'd like**
**描述您期望的解决方案**
清晰且简洁地描述您希望实现的内容。

**Describe alternatives you've considered**
**描述您已考虑的替代方案**
清晰且简洁地描述您已经考虑过的任何替代解决方案。

**Additional context**
**提供更多细节**
请附上任何相关截图、链接或文件，以帮助我们更好地理解您的请求。
[报价单_图片6.pdf](https://github.com/user-attachments/files/17933079/_.6.pdf)
[报价单_图片6.md](https://github.com/user-attachments/files/17933117/_.6.md)

**Comment by zuanzuanshao** [comment]
识别出来的md文档里面是一张图片，然后有的识别成文本了，有的没有。请问如果想要全部识别成文本，有没有什么参数可以达成目标呢，看了几个类似issue，没有发现解决方法。

**Comment by myhloli** [comment]
表格解析需要自己开下开关的，具体开启方法参考：
https://github.com/opendatalab/MinerU#3-modify-the-configuration-file-for-additional-configuration
