### ISSUE TITLE
Auto Install v0.6.1 instead of v0.10.X

### ISSUE THREAD

**Issue by Girrajjangid** [opendatalab/MinerU#1124]
### Description of the bug | 错误描述

I tried to install it on databricks runtime 15.4 LTS ML (includes Apache Spark 3.5.0, GPU, Scala 2.12). But it install lower version. 
As suggested by this doc [THIS DOC](https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_en_US.md#:~:text=If%20the%20version%20number%20is%20less%20than%200.7.0%2C%20please%20report%20the%20issue.)

### How to reproduce the bug | 如何复现

Command that I used to install
```
!pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com
```

Output that I got
```
!magic-pdf --version
magic-pdf, version 0.6.1
```

Installed Libraries:

```
- `transformers` version: 4.41.2
- Platform: Linux-5.15.0-1073-azure-x86_64-with-glibc2.35
- Python version: 3.11.0rc1
- Huggingface_hub version: 0.23.4
- Safetensors version: 0.4.2
- Accelerate version: 0.31.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Tensorflow version (GPU?): 2.16.1 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
We only support python3.10
