### ISSUE TITLE
docker打包后在服务器上加载再运行报错Segment Fault(Core Dumped)

### ISSUE THREAD

**Issue by daigangfan** [opendatalab/MinerU#1129]
### Description of the bug | 错误描述

在Windows Docker Desktop上dockerfile编译，能够正常运行
docker container commit 
docker image save
上传至一台无互联网连接的服务器docker运行magic-pdf报错Segment Fault(Core Dumped)
通过python api定位是opencv库报错
`from magic_pdf.pipe.OCRPipe import OCRPipe`
或者
`import cv2`
 都会报错Segment Fault
请问有没有解决经验或者避开cv2库的设置选项？

### How to reproduce the bug | 如何复现

Windows WSL2 
Docker-Desktop 4.35.1
编译dockerfile
```
wget https://github.com/opendatalab/MinerU/raw/master/Dockerfile
docker build -t mineru:latest .
docker run --rm -it --gpus=all mineru:latest /bin/bash
```
运行一次magic-pdf下载模型
通过docker container commit 和docker image save打包
新的服务器uname -a输出
Linux 8o96cklmlu9oo-0 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
看看你的服务器是不是不支持avx和avx2指令集

**Comment by daigangfan** [comment]
> 看看你的服务器是不是不支持avx和avx2指令集

通过lscpu看，支持的

**Comment by daigangfan** [comment]
我先手动重装opencv试试

**Comment by daigangfan** [comment]
卸载opencv-python 重装opencv-python-headless可以解决
