### ISSUE TITLE
表格识别问题

### ISSUE THREAD

**Issue by chk4991** [opendatalab/MinerU#1144]
### Description of the bug | 错误描述

表格被识别为一张图片，并在markdown中以引用的形式出现，请问如何才能把表格信息直接放入mawkdown中？auto 和 ocr 模式都用过了，结果一样。

### How to reproduce the bug | 如何复现

magic-pdf -p ***.pdf -o . -m ocr
magic-pdf -p ***.pdf -o . -m auto

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by yuxr20** [comment]
配置文件magic-pdf.json里的"table-config": {
        "model": "rapid_table",
        "enable": true,
        "max_time": 400
    },的enable是不是设置成默认的false了，这样会把表格当成图片，改成true应该就行了
