### ISSUE TITLE
表格识别——在容器里怎么修改table-config的"model"和"enable"参数

### ISSUE THREAD

**Issue by nameli0722** [opendatalab/MinerU#1148]
### Description of the bug | 错误描述

按README执行以下操作后，进入容器
wget https://github.com/opendatalab/MinerU/raw/master/Dockerfile
docker build -t mineru:latest .
docker run --rm -it --gpus=all mineru:latest /bin/bash

想修改magic-pdf.template.json ，修改里面的table-config的"model"和"enable"
原始参数如下：
![image](https://github.com/user-attachments/assets/12e5f5c1-689a-4bcd-bf5f-a9820e126df0)

修改后如下：
![image](https://github.com/user-attachments/assets/518a7612-fc57-46fe-9c81-b3316018d1db)

但是结果还是没有生效，请问怎么让它们生效，在容器内部。

没有生效，见下图
![image](https://github.com/user-attachments/assets/83a92eca-646c-443c-95cb-51783829dea9)

### How to reproduce the bug | 如何复现

wget https://github.com/opendatalab/MinerU/raw/master/Dockerfile
docker build -t mineru:latest .
docker run --rm -it --gpus=all -v /data:/home mineru:latest /bin/bash

root@375cf9aebb34:/# magic-pdf -p /home/lm/dataprocess/test_data_2/source/pdf_files -o /home/lm/dataprocess/test_data_2/output_2/pdf_files -m auto

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
容器里要改/root/magic-pdf.json这个文件

**Comment by nameli0722** [comment]
可以了，谢谢

**Comment by lmolhw5252** [comment]
改完后就生效了么？还是要重启下容器？
