### ISSUE TITLE
可编辑的pdf

### ISSUE THREAD

**Issue by lyc728** [opendatalab/MinerU#1149]
您好 现在项目整体流程已经跑通，但是有一些疑问请教下
1、首先由布局检测到标题、文本、表格这些，那是如何由这些坐标得到pdf中的文本呢？（我的疑问在于可编辑pdf是能拿到文本，但是我这边的坐标是如何同pdf中文本进行统一起来呢？这边pdf也是转成图片了吗？）

**Comment by myhloli** [comment]
用pymupdf可以获取文本的坐标定位，和模型分析的文本框匹配填充即可

**Comment by lyc728** [comment]
magic_pdf/libs/coordinate_transform.py
在这个函数中 为什么要把布局里面的坐标转换为bbox，这个缩放比例是什么决定的，拿到了这个bbox，就可以和pdf里面的坐标进行匹配吗？
"""为所有模型数据添加bbox信息(缩放，poly->bbox)"""

**Comment by lyc728** [comment]
你好 我还有一个问题
`class PymuDocDataset(Dataset):
    def __init__(self, bits: bytes):
        """Initialize the dataset, which wraps the pymudoc documents.

        Args:
            bits (bytes): the bytes of the pdf
        """
        self._records = [Doc(v) for v in fitz.open('pdf', bits)]
        self._data_bits = bits
        self._raw_data = bits`

最开始已经读了pdf 为什么模型解析完后 还有再读一次，这次读取里面的内容，函数更多 ，它的主要功能是在干嘛呢？
