### ISSUE TITLE
docker-compose.yml 问题 —— docker-compose 启动后找不到magic-pdf命令

### ISSUE THREAD

**Issue by nameli0722** [opendatalab/MinerU#1150]
### Description of the bug | 错误描述

docker-compose.yml 如下：
![image](https://github.com/user-attachments/assets/561e8cc9-8869-4027-9ff9-702e99e8d367)

docker-compose up -d 后
which magic-pdf 找不到命令

![image](https://github.com/user-attachments/assets/dfe1ffa0-313f-464f-b681-a83eed4d4db0)

### How to reproduce the bug | 如何复现

docker-compose.yml如下：

version: '3.8'

services:
  mineru:
    image: mineru:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /data:/home
    stdin_open: true
    tty: true
    command: /bin/bash

执行  docker-compose up -d 

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
得进入虚拟环境吧

**Comment by nameli0722** [comment]
容器里已经安装好python环境了

**Comment by nameli0722** [comment]
镜像里已经安装好python环境了

**Comment by myhloli** [comment]
容器里是装在venv环境里的，你进容器也要进容器的虚拟环境

**Comment by nameli0722** [comment]
怎么进呢？

**Comment by nameli0722** [comment]
为什么docker run --rm -it --gpus=all mineru:latest /bin/bash这个命令不用进虚拟环境？

**Comment by myhloli** [comment]
因为dockerfile里配置了启动命令
