### ISSUE TITLE
gpu版的一个是安装需要很久，第二个是需要大量的存储，可以优化一下吗？

### ISSUE THREAD

**Issue by zky001** [opendatalab/MinerU#1151]
本来还有20多G的存储，都快用完了
![a122e5f446cc707f4527a261dbd205f](https://github.com/user-attachments/assets/51fcfd2e-3ae9-4936-923c-f38856fd3c3c)
还有就是第5步运行太久了吧
![image](https://github.com/user-attachments/assets/c2b99dab-2f34-43a9-8251-ad188372c6ec)

**Comment by myhloli** [comment]
和网速有关系的，因为要下载比较大的运行环境和推理模型。如果本地部署困难可以使用我们的api接口在线推理，我们后面也会推出微客户端方便用户使用的。
