### ISSUE TITLE
安装本library报错

### ISSUE THREAD

**Issue by yedewww** [opendatalab/MinerU#1160]
### Description of the bug | 错误描述

运行`pip install --quiet -U     "magic-pdf[full]==0.10.0" --extra-index-url https://wheels.myhloli.com`时报错，

ERROR: HTTP error 451 while getting https://wheels-1251341229.cos.ap-shanghai.myqcloud.com/assets/whl/detectron2/detectron2-0.6-cp310-cp310-linux_x86_64.whl (from https://wheels.myhloli.com/detectron2/)
ERROR: Could not install requirement detectron2 from https://wheels-1251341229.cos.ap-shanghai.myqcloud.com/assets/whl/detectron2/detectron2-0.6-cp310-cp310-linux_x86_64.whl (from magic-pdf[full]==0.10.0) because of HTTP error 451 Client Error: Unavailable For Legal Reasons for url: https://wheels-1251341229.cos.ap-shanghai.myqcloud.com/assets/whl/detectron2/detectron2-0.6-cp310-cp310-linux_x86_64.whl for URL https://wheels-1251341229.cos.ap-shanghai.myqcloud.com/assets/whl/detectron2/detectron2-0.6-cp310-cp310-linux_x86_64.whl (from https://wheels.myhloli.com/detectron2/)

### How to reproduce the bug | 如何复现

运行`pip install --quiet -U     "magic-pdf[full]==0.10.0" --extra-index-url https://wheels.myhloli.com`

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
流量太大把cos费用消耗完了，现在恢复了
