### ISSUE TITLE
模型下载报错：TypeError: snapshot_download() got an unexpected keyword argument 'allow_patterns'

### ISSUE THREAD

**Issue by charliedream1** [opendatalab/MinerU#1161]
### Description of the bug | 错误描述

model_dir = snapshot_download('opendatalab/PDF-Extract-Kit-1.0', allow_patterns=mineru_patterns)
TypeError: snapshot_download() got an unexpected keyword argument 'allow_patterns'

### How to reproduce the bug | 如何复现

调用scripts下download.py用modelscope下载模型

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
把modelscope更新到最新

**Comment by charliedream1** [comment]
谢谢，已解决。
