### ISSUE TITLE
报错：模型存储路径/PDF-Extract-Kit/models does not appear to have a file named config.json.需要从huggingface上检查并获取。但是我对照modelscope上的模型资源，我的模型文件应该是下载完整了的。

### ISSUE THREAD

**Issue by zxd-hue** [opendatalab/MinerU#1163]
### Description of the bug | 错误描述

报错：模型存储路径/PDF-Extract-Kit/models does not appear to have a file named config.json.需要从huggingface上检查并获取。但是我对照modelscope上的模型资源，我的模型文件应该是下载完整了的。请问这个问题如何结局？

### How to reproduce the bug | 如何复现

运行脚本报错

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
用教程中指定的模型下载脚本更新一下模型目录

**Comment by zxd-hue** [comment]
> 用教程中指定的模型下载脚本更新一下模型目录

感谢回复，已解决。
