### ISSUE TITLE
RapidTable表格提取用时较长

### ISSUE THREAD

**Issue by yuxr20** [opendatalab/MinerU#1168]
### Description of the bug | 错误描述

使用RapidTable在GPU上进行表格提取时间较长，大概1-2s/img，请问这正常吗，想问下您那边单表推理最快能达到多少，我看这里
https://rapidai.github.io/RapidOCRDocs/install_usage/rapidocr_paddle/usage/
报告的能到0.05s/img

### How to reproduce the bug | 如何复现

我的`/magic_pdf/model/sub_modules/table/rapidtable/rapid_table.py`文件如下：
```
import numpy as np
from rapid_table import RapidTable
from rapidocr_paddle import RapidOCR
# from rapidocr_onnxruntime import RapidOCR


class RapidTableModel(object):
    def __init__(self):
        self.table_model = RapidTable()
        self.ocr_engine = RapidOCR(det_use_cuda=True, cls_use_cuda=True, rec_use_cuda=True)

    def predict(self, image):
        ocr_result, _ = self.ocr_engine(np.asarray(image))
        html_code, table_cell_bboxes, elapse = self.table_model(np.asarray(image), ocr_result)
        return html_code, table_cell_bboxes, elapse
```

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
他那个是单张图ocr的时间，这个表格解析还有一步表格结构识别呢，这个不用时间的吗

**Comment by yuxr20** [comment]
但是我单独测试 OCR 这一步也需要0.5-1s/img左右，也和报告中差挺多的，还是想问下您单表推理开启全部加速情况下能达到的用时？

**Comment by myhloli** [comment]
> 但是我单独测试 OCR 这一步也需要0.5-1s/img左右，也和报告中差挺多的，还是想问下您单表推理开启全部加速情况下能达到的用时？

和图片大小，字数多少都有关系啊，大表跟小表，大图跟小图肯定不能一起比，这个只能通过同一张图比cpu和gpu的区别，而不是通过不同图不同gpu来比
