### ISSUE TITLE
解析速度过慢

### ISSUE THREAD

**Issue by zhongxin129** [opendatalab/MinerU#1171]
### Description of the bug | 错误描述

[国标测试.pdf](https://github.com/user-attachments/files/17975328/default.pdf)
您好，解析该文件用了839.63秒，而且过程中查看，好像没有用到GPU，只用了CPU，有没有办法能够解析的更快一些

### How to reproduce the bug | 如何复现

解析上传的文件即可

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
可以看下解析过程中的log，上传一些页面的分阶段耗时情况，我们分析下是哪步耗时较长

**Comment by zhongxin129** [comment]
[log.txt](https://github.com/user-attachments/files/17975674/log.txt)
这是截取的日志，您看一下

**Comment by myhloli** [comment]
看了下是ocr比较慢，看下gpu加速教程安装下paddleocr呢
