### ISSUE TITLE
请问MinerU支持多卡并行操作吗

### ISSUE THREAD

**Issue by zxwsd** [opendatalab/MinerU#1173]
我现在docker中支持GPU运行，我想多卡并行运行，请问MinerU支持吗，CUDA_VISIBLE_DEVICES=0,1,2,3 magic-pdf --device cuda --input your_input_file使用类似这种命令可以做到多卡并行吗

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/tree/master/projects/multi_gpu
