### ISSUE TITLE
Getting Wrong order of the bboxes. Can u pls have a look?

### ISSUE THREAD

**Issue by vikas-singh16** [opendatalab/MinerU#1174]
Hi,
I tested layoutreader model **separately** on my input data which is the output of a layout detection model(doc-layout yolo). As you guys have used layoutreader in your repo, I have some questions to ask,

1. Is **Layoutreader** model from **"hantian/layoutreader"**  Huggingface works **fine**?
2. If **yes**, pls can u please guide me what modifiations have u made or have u made any?
3. If **no**, then how are you able to order the bboxes?

This is a just a test data that I was testing on and I am unable to get a good result.

"{{'boxes': [[95, 857, 816, 1804],
[870, 1473, 1505, 1815],
[869, 656, 1505, 997],
[275, 270, 654, 730],
[949, 287, 1486, 580],
[969, 1078, 1443, 1405],
[908, 1882, 1510, 2050],
[281, 152, 1525, 230],
[111, 778, 796, 852],
[60, 61, 276, 278],
[180, 1817, 733, 1892],
[59, 2057, 744, 2112],
[350, 1913, 531, 2048],
[887, 1012, 1486, 1046],
[886, 1826, 1486, 1859],
[1351, 2073, 1515, 2105],
[403, 79, 1356, 130],
[866, 611, 1395, 649],
[867, 1431, 1351, 1467],
[399, 693, 524, 728]],
'texts': ['table',
'table',
'table',
'figure',
'figure',
'figure',
'plain text',
'plain text',
'plain text',
'abandon',
'plain text',
'abandon',
'figure',
'plain text',
'plain text',
'abandon',
'title',
'title',
'table_caption',
'figure_caption'],
'width': 1675,
'height': 2175}"

Its annotated image looks like this,
![Annotated_img](https://github.com/user-attachments/assets/5505b0c7-44b9-4110-8943-7b0f7b4672a8)

After using the model , I am getting an output like this,
![Annotaed_with_wrong_order](https://github.com/user-attachments/assets/54dd1299-f213-4e91-9d51-28a292dc32a1)

Am I doing something wrong here, I am using the same code as provided in your **"pdf_parse_union_core_v2.py"** and layoutreader module. So can u pls have a look.

**Comment by myhloli** [comment]
`layoutreader` needs bbox information at the `line` level to sort properly. The input you provided is at the `block` level, which will result in poor sorting due to insufficient information.

**Comment by vikas-singh16** [comment]
Thank you for the quick response. Pls can u let me know how have you tackled this issue in your repo?

**Comment by myhloli** [comment]
Use DBNet to obtain the line boxes of all texts, calculate the median of the heights of all lines on the current page, and fill all images and tables with virtual lines. Sort all lines, and reorder the blocks based on the sorting results of the lines.

**Comment by vikas-singh16** [comment]
Thank you so much for the response. You guys have done phenomenal work. Keep it up.
