### ISSUE TITLE
询问11月22日更新的具体能力和实现方式

### ISSUE THREAD

**Issue by revalue-it** [opendatalab/MinerU#1175]
### Discussed in https://github.com/opendatalab/MinerU/discussions/1108

<div type='discussions-op-text'>

<sup>Originally posted by **ignore1999** November 27, 2024</sup>
请问11月22日更新的“混合OCR文本提取能力”具体是指什么，是如何实现的？
```
2024/11/22 0.10.0发布，通过引入混合OCR文本提取能力，
在公式密集、span区域不规范、部分文本使用图像表现等复杂文本分布场景下获得解析效果的显著提升
同时具备文本模式内容提取准确、速度更快与OCR模式span/line区域识别更准的双重优势
```</div>

**Comment by myhloli** [comment]
混合ocr是指有文本的pdf优先使用pymupdf提取对应的文本，如果文本区域的文本提取不到再通过少量动态调用ocr进行识别。
具体的实现方法可以参考源码：
https://github.com/opendatalab/MinerU/blob/master/magic_pdf/pdf_parse_union_core_v2.py
