### ISSUE TITLE
千分位识别为了小数点

### ISSUE THREAD

**Issue by magicyuan876** [opendatalab/MinerU#1176]
### Description of the bug | 错误描述

文档中的数值千分位被识别为了小数点

### How to reproduce the bug | 如何复现

[CDMO行业发展现状与未来趋势研究报告MinerU.pdf](https://github.com/user-attachments/files/17986565/CDMO.MinerU.pdf)
[CDMO行业发展现状与未来趋势研究报告MinerU.pdf.md](https://github.com/user-attachments/files/17986574/CDMO.MinerU.pdf.md)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
目前使用的ocr后端为paddleocr的基础版本，在分辨率稍低的图像上精度不是特别高，如果对ocr依赖比较重，可以自行尝试更换其他ocr后端以获得更好的解析效果
