### ISSUE TITLE
How to save extracted tables in the markdown format, Not html?

### ISSUE THREAD

**Issue by aidevmin** [opendatalab/MinerU#1179]
I want to extracted tables with markdown format for my RAG, not html. Because html structure has many text td, tr, it is not good for the RAG system. Thanks.

**Comment by myhloli** [comment]
Since markdown format tables do not support merged cells, we use HTML to represent the table, which can be easily rendered in markdown. If you need a markdown format table, you can convert the HTML to markdown format using other methods or tools.

**Comment by aidevmin** [comment]
Thanks. I understood.
