### ISSUE TITLE
pdf坐标提取

### ISSUE THREAD

**Issue by lyc728** [opendatalab/MinerU#1183]
你好在这个代码中magic_pdf/libs/coordinate_transform.py
为什么要把布局里面的坐标转换为bbox，这个缩放比例是什么决定的，拿到了这个bbox，就可以和pdf里面的坐标进行匹配吗？
"""为所有模型数据添加bbox信息(缩放，poly->bbox)"""

**Comment by lyc728** [comment]
你好 我还有一个问题

`class PymuDocDataset(Dataset):
def init(self, bits: bytes):
"""Initialize the dataset, which wraps the pymudoc documents.

    Args:
        bits (bytes): the bytes of the pdf
    """
    self._records = [Doc(v) for v in fitz.open('pdf', bits)]
    self._data_bits = bits
    self._raw_data = bits`
最开始已经读了pdf 为什么模型解析完后 还有再读一次，这次读取里面的内容，函数更多 ，它的主要功能是在干嘛呢？

**Comment by myhloli** [comment]
> 你好在这个代码中magic_pdf/libs/coordinate_transform.py
> 
> 为什么要把布局里面的坐标转换为bbox，这个缩放比例是什么决定的，拿到了这个bbox，就可以和pdf里面的坐标进行匹配吗？
> 
> """为所有模型数据添加bbox信息(缩放，poly->bbox)"""

poly是四角坐标，pipeline中使用两点坐标，需要通过dpi比例缩放并转换。
