### ISSUE TITLE
litServer ModuleNotFoundError: No module named 'paddleocr.paddleocr'; 'paddleocr' is not a package

### ISSUE THREAD

**Issue by alpha4501** [opendatalab/MinerU#1187]
### Description of the bug | 错误描述

未用litServe相同的代码并未报错，用了litServer后，报错，请大佬指教

### How to reproduce the bug | 如何复现

    from paddleocr.paddleocr import check_img, logger
ModuleNotFoundError: No module named 'paddleocr.paddleocr'; 'paddleocr' is not a package

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
升级下magic-pdf，之前的代码import的paddle不支持多线程
