### ISSUE TITLE
添加了list的解析后，出现错误

### ISSUE THREAD

**Issue by Maple0709** [opendatalab/MinerU#1189]
### Description of the bug | 错误描述

论文的参考文献解析后组合为list，但是内容为空。具体的内容如图：
![image](https://github.com/user-attachments/assets/ea730d78-be5c-4f50-923d-e3e26ca4205b)
解析后结果如图：
![image](https://github.com/user-attachments/assets/9daf3a2b-d876-43fc-a679-2da7806d1ea6)

### How to reproduce the bug | 如何复现

使用论文“基于卷积神经网络和模糊 PID 的掘进机控制系统研究.pdf”进行解析，第12页内容为空

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
向上合并到上一页了，被合并的段落会被置空
