### ISSUE TITLE
ocr模式如果版面分析漏检文字块 是否有其他方式兜底

### ISSUE THREAD

**Issue by sph116** [opendatalab/MinerU#1191]
ocr模式如果版面分析漏检文字块 是否有其他方式兜底

**Comment by myhloli** [comment]
后续所有流程均以版面分析结果为基础，这个漏了那就真漏了

**Comment by sph116** [comment]
> 后续所有流程均以版面分析结果为基础，这个漏了那就真漏了

是的 所以想探讨下是否可以在某个判断条件下 整页做一次全文识别 作为兜底策略

**Comment by myhloli** [comment]
后处理流程没办法知道layout漏了框的，存在信息差
