### ISSUE TITLE
ocr处理文字，某一行框起来的文字只检测到一半大小，最后这行未能检测出来，应该怎么解决呢？

### ISSUE THREAD

**Issue by zkq-afk** [opendatalab/MinerU#1194]
我想进行后处理，然后我的某一页pdf中，出现了漏检一行的情况，查看结果发现，检测这行的时候，只检测到一半的大小，这个问题可以从哪里进行修改呢？

**Comment by myhloli** [comment]
doclayout-yolo在某些情况下对于比较宽的行会出现看不全的情况，可以试试切换另一个layout模型

**Comment by zkq-afk** [comment]
我们的一个要求是不能改模型，因为模型是之前训练好的，想让我们用后处理的方法解决，我想问一下能通过改动这个magic_pdf/pre_proc/ocr_detect_all_bboxes.py文件去解决这个问题吗？这里面的框的大小能进行改动吗？

**Comment by myhloli** [comment]
框的大小在任何一个阶段都能改，但是改之前你怎么知道哪个框小了，又要改到多大呢？
