### ISSUE TITLE
BUG : magic_pdf/model/magic_model.py 743行， 距离和位置相加

### ISSUE THREAD

**Issue by dream-in-night** [opendatalab/MinerU#1195]
https://github.com/opendatalab/MinerU/blob/b9f3435cb7ad0cd8f4a23984b8368298eb45d2c1/magic_pdf/model/magic_model.py#L743C2-L748C27

```
                        if (
                            abs(left_sub_bbox_y_axis - l_y_axis)
                            + dis_by_directions['left'][i][0]
                            > abs(right_sub_bbox_y_axis - l_y_axis)
                            + dis_by_directions['right'][i][0]
                        ):
                            left_or_right = dis_by_directions['right'][i]
                        else:
                            left_or_right = dis_by_directions['left'][i]
```

**Comment by dream-in-night** [comment]
这里应该的确是写错了，这里是对比： 框的高度差+水平距离差
距离应该是第1个元素，这里写成第0个元素了，第0个元素是索引，是不对的。
![image](https://github.com/user-attachments/assets/e9c28190-e724-49b2-960b-1126adb2cff3)

**Comment by dream-in-night** [comment]
把原来的0改成1就行
```
                        if (
                            abs(left_sub_bbox_y_axis - l_y_axis) # 对比： 框的高度差+水平距离差
                            + dis_by_directions['left'][i][1]
                            > abs(right_sub_bbox_y_axis - l_y_axis)
                            + dis_by_directions['right'][i][1]
                        ):
```

**Comment by dream-in-night** [comment]
修改前的
![image](https://github.com/user-attachments/assets/d1acc852-09a4-4117-b581-73ed26dd80c8)
修改后的
![image](https://github.com/user-attachments/assets/df4add57-0b06-4127-9872-d7af2ed5bcc5)

**Comment by icecraft** [comment]
good catch!  could you issue an PR to resolve this problem? 
You can pull the latest dev branch and fork an new branch.

**Comment by dream-in-night** [comment]
此外，多栏的排序不对，可能是因为这里：
![image](https://github.com/user-attachments/assets/a9aa4011-de4c-48e1-8426-dd457dc05cfc)
https://github.com/opendatalab/MinerU/blob/b9f3435cb7ad0cd8f4a23984b8368298eb45d2c1/magic_pdf/model/magic_model.py#L642

使用左上角的欧式距离对框排序的

**Comment by icecraft** [comment]
@dream-in-night  目前排序是采用按照左上角的排序，没有按照不同的场景区分排序算法

**Comment by myhloli** [comment]
> 修改前的 ![image](https://private-user-images.githubusercontent.com/17213331/392742105-d1acc852-09a4-4117-b581-73ed26dd80c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTEwNTMsIm5iZiI6MTczMzM5MDc1MywicGF0aCI6Ii8xNzIxMzMzMS8zOTI3NDIxMDUtZDFhY2M4NTItMDlhNC00MTE3LWI1ODEtNzNlZDI2ZGQ4MGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA5MjU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZjJmYWI4N2EyOTA4MTJhOGYzYjI3YWNiY2M4MWQzY2Y5YzRkZTI4ZWI2MmUzNzM4NGE4OGRlOTkyNzhhMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hQ2QFalidRidg25Tplaqv89D-lIKzIRTl780VKfhQpM) 修改后的 ![image](https://private-user-images.githubusercontent.com/17213331/392742207-df4add57-0b06-4127-9872-d7af2ed5bcc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTEwNTMsIm5iZiI6MTczMzM5MDc1MywicGF0aCI6Ii8xNzIxMzMzMS8zOTI3NDIyMDctZGY0YWRkNTctMGIwNi00MTI3LTk4NzItZDdhZjJlZDViY2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA5MjU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OWY5OWRhMWYwMmM4MmVhNTU4YmE5YzVmYWM4NzQxNmQ3ZjBmYmIyNmUwY2I3ZGJjZmZjOGJlNDU4OTIxZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iGusIQxERPHiBwfeQO-i5j4y2-yeVaQSVHbcYwXm8Ts)

命令行里开下-d true，看看输出的line_sort.pdf的结果准吗

**Comment by dream-in-night** [comment]
> > 修改前的 ![image](https://private-user-images.githubusercontent.com/17213331/392742105-d1acc852-09a4-4117-b581-73ed26dd80c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTEwNTMsIm5iZiI6MTczMzM5MDc1MywicGF0aCI6Ii8xNzIxMzMzMS8zOTI3NDIxMDUtZDFhY2M4NTItMDlhNC00MTE3LWI1ODEtNzNlZDI2ZGQ4MGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA5MjU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZjJmYWI4N2EyOTA4MTJhOGYzYjI3YWNiY2M4MWQzY2Y5YzRkZTI4ZWI2MmUzNzM4NGE4OGRlOTkyNzhhMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hQ2QFalidRidg25Tplaqv89D-lIKzIRTl780VKfhQpM) 修改后的 ![image](https://private-user-images.githubusercontent.com/17213331/392742207-df4add57-0b06-4127-9872-d7af2ed5bcc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTEwNTMsIm5iZiI6MTczMzM5MDc1MywicGF0aCI6Ii8xNzIxMzMzMS8zOTI3NDIyMDctZGY0YWRkNTctMGIwNi00MTI3LTk4NzItZDdhZjJlZDViY2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA5MjU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OWY5OWRhMWYwMmM4MmVhNTU4YmE5YzVmYWM4NzQxNmQ3ZjBmYmIyNmUwY2I3ZGJjZmZjOGJlNDU4OTIxZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iGusIQxERPHiBwfeQO-i5j4y2-yeVaQSVHbcYwXm8Ts)
> 
> 命令行里开下-d true，看看输出的line_sort.pdf的结果准吗

我用的不是命令行版本的，我下了源码，创建了文件：
demo/demo_draw.py
```
import os

from loguru import logger

from magic_pdf.data.data_reader_writer import FileBasedDataWriter
from magic_pdf.pipe.UNIPipe import UNIPipe
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from magic_pdf.model.doc_analyze_by_custom_model import load_images_from_pdf
import argparse
from ultralytics.utils.plotting import Annotator, colors
from PIL import Image
from io import BytesIO
from pathlib import Path
import numpy as np
import cv2
ROOT = os.path.dirname(os.path.abspath(__file__))
# 
def parser_args():
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('pdf_path', type=str, help='The path to the PDF file')
    args = parser.parse_args()
    return args
def parse_pdf(pdf_path):
    try:
        current_script_dir = os.path.dirname(os.path.abspath(__file__))
        cache_label_path = os.path.join(current_script_dir, f'data_cache/{Path(pdf_path).stem}.txt')
        pdf_bytes = open(pdf_path, 'rb').read()
        if os.path.exists(cache_label_path):
            f = open(cache_label_path, 'r')
            pdf_mid_data = eval(f.read())
            f.close()
        else:
            jso_useful_key = {'_pdf_type': '', 'model_list': []}
            local_image_dir = os.path.join(current_script_dir, 'images')
            image_writer = FileBasedDataWriter(local_image_dir)
            pipe = UNIPipe(pdf_bytes, jso_useful_key, image_writer, pdf_path=pdf_path,
                        formula_enable=False,
                        table_enable=False)
            pipe.pipe_classify()
            image_dir = str(os.path.basename(local_image_dir))
            pipe.pipe_analyze()
            pipe.pipe_parse()
            pdf_mid_data = pipe.pdf_mid_data
            f = open(cache_label_path, 'w')
            f.write(str(pdf_mid_data))
            f.close()
            pdf_bytes = pipe.pdf_bytes
        im_dir = os.path.join(current_script_dir, f'images/{Path(pdf_path).stem}')
        os.makedirs(im_dir, exist_ok=True)
        images = load_images_from_pdf(pdf_bytes, pdf_file_path=pdf_path)
        # 创建PDF文件
        print("解析完毕, 画框")
        for i, page_block in enumerate(pdf_mid_data['pdf_info']):
            blocks = page_block['preproc_blocks']
            im = images[i]['img'][:,:,::-1]
            # tar = os.path.join(im_dir, f'{i:03d}_ori.png')
            # cv2.imwrite(tar, im)
            w, h = page_block['page_size']
            im = np.ascontiguousarray(im)
            im_pil = Image.fromarray(im)
            w1, h1 = im_pil.size
            if w1>1000 or h1>1000:
                w1, h1 = 1000, int(h1*1000/w1)
                im_pil = im_pil.resize((w1, h1))
            ann = Annotator(im_pil, line_width=3, font_size=30, pil=True)
            print(f"{i}/{len(pdf_mid_data['pdf_info'])}")
            ratioh, ratiow = h1/h, w1/w
            for j, block in enumerate(blocks):
                try:
                    bbox = block['bbox']
                    x1, y1, x2, y2 = bbox
                    x1, y1, x2, y2 = x1*ratiow, y1*ratioh, x2*ratiow, y2*ratioh
                    bbox = [x1, y1, x2, y2]
                    bbox = list(map(int, bbox))
                    bbox = tuple(bbox)
                    ann.box_label(bbox, f'{j}', color=colors(3))
                except:
                    pass
            im_tmp = ann.result()
            pil_image = Image.fromarray(im_tmp[:,:,::-1])
            tar = os.path.join(im_dir, f'{i:03d}_draw.png')
            pil_image.save(tar)

    except Exception as e:
        logger.exception(e)
if __name__=='__main__':
    args = parser_args()
    pdf_path = args.pdf_path
    parse_pdf(pdf_path)
```
我把这个文件上传到官网的demo看一下，啥也没有，但是显示提取成功
![image](https://github.com/user-attachments/assets/9c4cdbbd-4d12-4eeb-a4cd-f316344e115b)
显示的是提取成功：
![image](https://github.com/user-attachments/assets/6d29dd5a-e263-470f-a308-c85070a3aedf)
huggingface上的结果： 与我改了1以后预测的结果一致
![image](https://github.com/user-attachments/assets/0c624236-1435-4b65-8b6d-10bc13ee8269)

**Comment by myhloli** [comment]
pdf文件发一下？

**Comment by dream-in-night** [comment]
> good catch! could you issue an PR to resolve this problem? You can pull the latest dev branch and fork an new branch.

代码才刚看半天，等多看两天再弄吧 😂

**Comment by dream-in-night** [comment]
> pdf文件发一下？

OK，这里

[a.pdf](https://github.com/user-attachments/files/18021221/a.pdf)

**Comment by myhloli** [comment]
看了下这个linesort就相当不准了，导致后面block也不准，应该是排序模型的训练数据里这种排版的比较少，直接乱排了

**Comment by dream-in-night** [comment]
> 排序模型

我还没看到排序模型那部分，这个框架的排序模型的训练，是基于排版还是行的啊？

**Comment by myhloli** [comment]
基于行的
