### ISSUE TITLE
怎么样可以让论文中的表格图片和非表格提取出来之后标注文章中对应的名称呢，现在提取出来是类似下面这样的编号，并没有顺序，我想标注出文章中对应的table1、table2，fig1、fig2等等，这样可以实现吗

### ISSUE THREAD

**Issue by guozhetao** [opendatalab/MinerU#1196]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
对存在的问题进行清晰且简洁的描述。例如：我一直很困扰的是 [...]

**Describe the solution you'd like**
**描述您期望的解决方案**
清晰且简洁地描述您希望实现的内容。

**Describe alternatives you've considered**
**描述您已考虑的替代方案**
清晰且简洁地描述您已经考虑过的任何替代解决方案。

**Additional context**
**提供更多细节**
请附上任何相关截图、链接或文件，以帮助我们更好地理解您的请求。

**Comment by guozhetao** [comment]
![image](https://github.com/user-attachments/assets/125e23d1-d9ec-4006-8a7b-c0a01b63c7e5)

**Comment by myhloli** [comment]
截图的文件名是为了方便在s3中平铺存储使用的hash过的结果，一般解析完了不会直接根据文件名来找图片，建议通过解析成json的格式，通过关联的img/table capiton信息来查找图片
![image](https://github.com/user-attachments/assets/cfb32cae-d1de-4f85-b045-db39317f1cf5)
![image](https://github.com/user-attachments/assets/24bbe7a1-9ab1-4d35-b7fe-8559354de259)

**Comment by guozhetao** [comment]
好的，谢谢，我现在是记录表格在文件中出现的顺序，加了一个编号的步骤，已经解决了，谢谢~
