### ISSUE TITLE
参考使用magic_pdf/pdf_parse_union_core.py进行后处理

### ISSUE THREAD

**Issue by zkq-afk** [opendatalab/MinerU#1205]
参考使用magic_pdf/pdf_parse_union_core.py进行后处理后，出现漏检的情况，就是比如一页中，突然在中间漏了一行的情况，这种问题能修改哪部分进行解决呢？

**Comment by myhloli** [comment]
可以看下输出的layout.pdf如果这个里面有漏掉的框，说明是layout漏检，这种情况暂时无法修复。
