### ISSUE TITLE
litServe 下多GPU配置，ModuleNotFoundError: No module named 'paddleocr ppstructure paddleocr is not a package

### ISSUE THREAD

**Issue by alpha4501** [opendatalab/MinerU#1206]
### Description of the bug | 错误描述

ModuleNotFoundError: No module named 'paddleocr ppstructure paddleocr is not a package

### How to reproduce the bug | 如何复现

ModuleNotFoundError: No module named 'paddleocr ppstructure paddleocr is not a package

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
please update to 0.10.5

**Comment by alpha4501** [comment]
already 0.10.5
from paddleocr.ppstructure.table.predict_table import TableSystem
from paddleocr.ppstructure.utility import init_args
第一段报错
我单独将这块拎出来包成服务也不对

**Comment by alpha4501** [comment]
0.10.5是
from ppstructure.table.predict_table import TableSystem
from ppstructure.utility import init_args
这会报错，找不到ppstructure

**Comment by myhloli** [comment]
你加paddleocr.就不支持多线程，你删了这个虽然报错但是可以正常运行还能多线程

**Comment by alpha4501** [comment]
我试一下

**Comment by alpha4501** [comment]
File "/data/john/ocr_services/dw-table-parser-service/table_parser/core/model/tablemaster/tablemaster_paddle.py", line 7, in <module>
    from ppstructure.table.predict_table import TableSystem
ModuleNotFoundError: No module named 'ppstructure'

不太知道哪里出问题了，我将这个服务单独包成一个独立的服务，同样不行

**Comment by myhloli** [comment]
今天修复了多线程并做了测试，性能相比单线程没有任何提升，现在已经放弃多线程支持的发版了，建议用户也尽量通过多进程单线程的方式提升运行效率
