### ISSUE TITLE
TypeError: Can't mix strings and bytes in path components不知道咋回事，前面跑的都正常

### ISSUE THREAD

**Issue by yza99016** [opendatalab/MinerU#1217]
### Description of the bug | 错误描述

Traceback (most recent call last):

  File "/root/gotpdf/move.py", line 105, in <module>
    process_all_pdfs(input_directory, output_directory, parse_method='ocr')
    │                │                └ '../autodl-tmp/ocrpdf'
    │                └ '../autodl-tmp/merge'
    └ <function process_all_pdfs at 0x7f596068a5f0>

  File "/root/gotpdf/move.py", line 99, in process_all_pdfs
    pdf_parse_main(pdf_path, parse_method, output_dir)
    │              │         │             └ '../autodl-tmp/ocrpdf'
    │              │         └ 'ocr'
    │              └ '../autodl-tmp/merge/10094881.pdf'
    └ <function pdf_parse_main at 0x7f596068a560>

> File "/root/gotpdf/move.py", line 74, in pdf_parse_main
    pipe.pipe_parse()
    │    └ <function OCRPipe.pipe_parse at 0x7f59606897e0>
    └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7f58f354b940>

  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/OCRPipe.py", line 28, in pipe_parse
    self.pdf_mid_data = parse_ocr_pdf(self.pdf_bytes, self.model_list, self.image_writer, is_debug=self.is_debug,
    │    │              │             │    │          │    │           │    │                      │    └ False
    │    │              │             │    │          │    │           │    │                      └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7f58f354b940>
    │    │              │             │    │          │    │           │    └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x7f58f354bb20>
    │    │              │             │    │          │    │           └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7f58f354b940>
    │    │              │             │    │          │    └ [{'layout_dets': [{'category_id': 2, 'poly': [826.072998046875, 44.35260772705078, 1467.1549072265625, 44.35260772705078, 146...
    │    │              │             │    │          └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7f58f354b940>
    │    │              │             │    └ b'%PDF-1.4\n%\xf0\xea\xe6\xf3\xf5\xea\xed\xb9\xb7\xba\n3 0 obj\n  << /Type             /XObject\n     /Subtype          /Imag...
    │    │              │             └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7f58f354b940>
    │    │              └ <function parse_ocr_pdf at 0x7f5960689000>
    │    └ None
    └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7f58f354b940>
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/user_api.py", line 50, in parse_ocr_pdf
    pdf_info_dict = parse_pdf_by_ocr(
                    └ <function parse_pdf_by_ocr at 0x7f5ac2a411b0>
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_by_ocr.py", line 15, in parse_pdf_by_ocr
    return pdf_parse_union(dataset,
           │               └ <magic_pdf.data.dataset.PymuDocDataset object at 0x7f5950443730>
           └ <function pdf_parse_union at 0x7f5960688dc0>
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line 808, in pdf_parse_union
    page_info = parse_page_core(
                └ <function parse_page_core at 0x7f5960688d30>
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line 718, in parse_page_core
    spans = ocr_cut_image_and_table(
            └ <function ocr_cut_image_and_table at 0x7f5960677a30>
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pre_proc/cut_image.py", line 17, in ocr_cut_image_and_table
    span['image_path'] = cut_image(span['bbox'], page_id, page, return_path=return_path('images'),
    │                    │         │             │        │                 └ <function ocr_cut_image_and_table.<locals>.return_path at 0x7f58f3307d90>
    │                    │         │             │        └ <magic_pdf.data.dataset.Doc object at 0x7f58f34d0040>
    │                    │         │             └ 0
    │                    │         └ {'bbox': [334, 537, 507, 664], 'score': 0.9999051094055176, 'type': 'image'}
    │                    └ <function cut_image at 0x7f5ac2a66320>
    └ {'bbox': [334, 537, 507, 664], 'score': 0.9999051094055176, 'type': 'image'}
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/libs/pdf_image_tools.py", line 33, in cut_image
    imageWriter.write(img_hash256_path, byte_data)
    │           │     │                 └ b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00`\x00`\x00\x00\xff\xdb\x00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x02...
    │           │     └ '8899814104c246cfced9fd51d1816a6277de4c7f655604245ea3335dff8f013e.jpg'
    │           └ <function DiskReaderWriter.write at 0x7f596068a440>
    └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x7f58f354bb20>
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/rw/DiskReaderWriter.py", line 32, in write
    abspath = os.path.join(self.path, path)
              │  │    │    │    │     └ b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00`\x00`\x00\x00\xff\xdb\x00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x02...
              │  │    │    │    └ '../autodl-tmp/ocrpdf/10094881/images'
              │  │    │    └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x7f58f354bb20>
              │  │    └ <function join at 0x7f5ba25a6b90>
              │  └ <module 'posixpath' from '/root/miniconda3/envs/MinerU/lib/python3.10/posixpath.py'>
              └ <module 'os' from '/root/miniconda3/envs/MinerU/lib/python3.10/os.py'>
  File "/root/miniconda3/envs/MinerU/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
    │           │                        │   └ (b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00`\x00`\x00\x00\xff\xdb\x00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x0...
    │           │                        └ '../autodl-tmp/ocrpdf/10094881/images'
    │           └ <function _check_arg_types at 0x7f5ba25a69e0>
    └ <module 'genericpath' from '/root/miniconda3/envs/MinerU/lib/python3.10/genericpath.py'>
  File "/root/miniconda3/envs/MinerU/lib/python3.10/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None

TypeError: Can't mix strings and bytes in path components

### How to reproduce the bug | 如何复现

import os
import json
import copy
from loguru import logger
from magic_pdf.libs.draw_bbox import draw_layout_bbox, draw_span_bbox
from magic_pdf.pipe.UNIPipe import UNIPipe
from magic_pdf.pipe.OCRPipe import OCRPipe
from magic_pdf.pipe.TXTPipe import TXTPipe
from magic_pdf.rw.DiskReaderWriter import DiskReaderWriter

def json_md_dump(pipe, md_writer, pdf_name, content_list, md_content, orig_model_list):
    # 写入模型结果到 model.json
    md_writer.write(
        content=json.dumps(orig_model_list, ensure_ascii=False, indent=4),
        path=f"{pdf_name}_model.json"
    )

    # 写入中间结果到 middle.json
    md_writer.write(
        content=json.dumps(pipe.pdf_mid_data, ensure_ascii=False, indent=4),
        path=f"{pdf_name}_middle.json"
    )

    # text文本结果写入到 conent_list.json
    md_writer.write(
        content=json.dumps(content_list, ensure_ascii=False, indent=4),
        path=f"{pdf_name}_content_list.json"
    )

    # 写入结果到 .md 文件中
    md_writer.write(
        content=md_content,
        path=f"{pdf_name}.md"
    )

def draw_visualization_bbox(pdf_info, pdf_bytes, local_md_dir, pdf_file_name):
    draw_layout_bbox(pdf_info, pdf_bytes, local_md_dir, pdf_file_name)
    draw_span_bbox(pdf_info, pdf_bytes, local_md_dir, pdf_file_name)

def pdf_parse_main(pdf_path, parse_method, output_dir):
    try:
        pdf_name = os.path.basename(pdf_path).split(".")[0]
        output_path = os.path.join(output_dir, pdf_name)
        output_image_path = os.path.join(output_path, 'images')
        image_path_parent = os.path.basename(output_image_path)

        pdf_bytes = open(pdf_path, "rb").read()

        orig_model_list = []
        model_json = []

        # 执行解析步骤
        image_writer, md_writer = DiskReaderWriter(output_image_path), DiskReaderWriter(output_path)
        if parse_method == "auto":
            jso_useful_key = {"_pdf_type": "", "model_list": model_json}
            pipe = UNIPipe(pdf_bytes, jso_useful_key, image_writer)
        elif parse_method == "txt":
            pipe = TXTPipe(pdf_bytes, model_json, image_writer)
        elif parse_method == "ocr":
            pipe = OCRPipe(pdf_bytes, model_json, image_writer)
        else:
            logger.error("unknown parse method, only auto, ocr, txt allowed")
            return

        pipe.pipe_classify()

        if len(model_json) == 0:
            pipe.pipe_analyze()
            orig_model_list = copy.deepcopy(pipe.model_list)

        pipe.pipe_parse()

        content_list = pipe.pipe_mk_uni_format(image_path_parent, drop_mode="none")
        md_content = pipe.pipe_mk_markdown(image_path_parent, drop_mode="none")

        json_md_dump(pipe, md_writer, pdf_name, content_list, md_content, orig_model_list)
        draw_visualization_bbox(pipe.pdf_mid_data['pdf_info'], pdf_bytes, output_path, pdf_name)

    except Exception as e:
        logger.exception(f"Error processing {pdf_path}: {e}")

def process_all_pdfs(input_dir, output_dir, parse_method='ocr'):
    folder_dict = {}
    print(len(os.listdir(output_dir)))
    for folder_name in os.listdir(output_dir):
        folder_path = os.path.join(output_dir, folder_name)
        if os.path.isdir(folder_path):  # 确保是文件夹
            folder_dict[folder_name] = folder_path

    pdf_files = [os.path.join(input_dir, f) for f in os.listdir(input_dir) if f.endswith('.pdf') and os.path.splitext(f)[0] not in folder_dict]
    print(f"待处理的 PDF 文件数: {len(pdf_files)}")

    for pdf_path in pdf_files:
        print(f"正在处理: {pdf_path}")
        pdf_parse_main(pdf_path, parse_method, output_dir)

if __name__ == '__main__':
    input_directory = "../autodl-tmp/merge"
    output_directory = "../autodl-tmp/ocrpdf"
    process_all_pdfs(input_directory, output_directory, parse_method='ocr')
用的ocr

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
读写类重构了，请参考新的demo代码重新初始化readwriter类

**Comment by yza99016** [comment]
非常感谢，问题解决了
