### ISSUE TITLE
LaTex 公式未能正确识别

### ISSUE THREAD

**Issue by yiyibooks** [opendatalab/MinerU#122]
这个项目整体效果非常好！感谢各位贡献者！

本人在使用中发现数学公式未能正确识别为 LaTex 表达式。

以这个 PDF https://arxiv.org/pdf/2407.01906 为例，第二页的公式

![image](https://github.com/opendatalab/MinerU/assets/10433380/875c4b66-007c-46e2-8f67-de4cc119eead)

识别成了
![image](https://github.com/opendatalab/MinerU/assets/10433380/29cd6127-0e16-4423-9fd9-d04ad0719e60)

看项目介绍是可以将数学公式识别为 LaTex 的，请问应该如何做就可以将论文中的公式正确识别成 LaTex 表达式呢?

谢谢！

**Comment by myhloli** [comment]
我这边测试是正常识别的，您是用https://github.com/opendatalab/PDF-Extract-Kit
这个项目跑的模型解析结果调用本pipeline吗

![屏幕截图 2024-07-06 224920](https://github.com/opendatalab/MinerU/assets/11393164/2775ebd8-7411-4eff-9b4c-24695468485c)

**Comment by yiyibooks** [comment]
我是用 MinerU 的命令 magic-pdf pdf-command --pdf "2407.01906.pdf" 输出 Markdown 的。

请问您的输出是用什么命令得到的？感谢感谢！

**Comment by myhloli** [comment]
> 我是用 MinerU 的命令 magic-pdf pdf-command --pdf "2407.01906.pdf" 输出 Markdown 的。
> 
> 
> 
> 请问您的输出是用什么命令得到的？感谢感谢！
> 
> 

你的model json是怎么生成的，你这个命令缺少了modeljson的输入，理论应该无法执行

**Comment by yiyibooks** [comment]
是的，因为初看 MinerU 的文档看不出 model_json_path 怎么生成，所以我改了 magicpdf.py 代码中的 model_config.__use_inside_model__ = True, 让代码使用内置model解析

```
"""如果没有传入有效的模型数据，则使用内置model解析"""
    if len(model_list) == 0:
        if model_config.__use_inside_model__:
            pipe.pipe_analyze()
```

应该怎么生成 model_json_path 啊？

**Comment by myhloli** [comment]
> 是的，因为初看 MinerU 的文档看不出 model_json_path 怎么生成，所以我改了 magicpdf.py 代码中的 model_config.__use_inside_model__ = True, 让代码使用内置model解析
> 
> 
> 
> ```
> 
> """如果没有传入有效的模型数据，则使用内置model解析"""
> 
>     if len(model_list) == 0:
> 
>         if model_config.__use_inside_model__:
> 
>             pipe.pipe_analyze()
> 
> ```
> 
> 
> 
> 应该怎么生成 model_json_path 啊？

这个是内部的测试方案，不推荐用户使用的。请使用https://github.com/opendatalab/PDF-Extract-Kit 生成model json

**Comment by yiyibooks** [comment]
使用 https://github.com/opendatalab/PDF-Extract-Kit 生成 model json 后可以正确解析了，谢谢！
