### ISSUE TITLE
PDF识别结果重复

### ISSUE THREAD

**Issue by huyiwen** [opendatalab/MinerU#1221]
### Description of the bug | 错误描述

似乎是加粗的字体，每个字会重复三遍。

![image](https://github.com/user-attachments/assets/63591ade-81ca-42d3-ad33-c663b12b8102)

![image](https://github.com/user-attachments/assets/4b6738c0-7b9a-4c4e-b2ec-16b4f21ab1ba)

### How to reproduce the bug | 如何复现

PDF下载链接：http://www.nsmath.cn/filedownload/538713

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/ab0b6c1a-6ede-4b58-826a-9142d16fda0e)
放大看这里好像确实是三个字叠在一起了，这种叠字问题建议通过强制开启ocr的方式解决

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/8b1f7a09-cdb4-4a3b-b9f4-0091f87a57cc)

**Comment by huyiwen** [comment]
好的感谢

**Comment by myhloli** [comment]
fix at https://github.com/opendatalab/MinerU/pull/1329
