### ISSUE TITLE
请教 model_json 应该怎么才能生成？

### ISSUE THREAD

**Issue by ryzn0518** [opendatalab/MinerU#123]

**Comment by myhloli** [comment]
目前需要通过项目https://github.com/opendatalab/PDF-Extract-Kit 生成模型解析文件，在下个大版本更新（可能0.6.0）会完成前置模型解析和后处理流水线的集成工作。

**Comment by ryzn0518** [comment]
@myhloli 非常感谢，只是 https://github.com/opendatalab/PDF-Extract-Kit 的模型不支持解析 table，看起来当前可以应用的场景不多。

**Comment by drunkpig** [comment]
@diaojunxian table模型我们内部有一个，随后也会集成进来

**Comment by myhloli** [comment]
> @myhloli 非常感谢，只是 https://github.com/opendatalab/PDF-Extract-Kit 的模型不支持解析 table，看起来当前可以应用的场景不多。

我们希望能把现有的一些优秀能力(layout识别、公式检测与解析、高效的后端处理管线)先通过开源的方式分享出来，让有需要的同学可以先用起来。table的解析能力目前还没达到开放的标准，需要再耐心等待一些时间。

**Comment by xuquankun** [comment]
> 目前需要通过项目https://github.com/opendatalab/PDF-Extract-Kit 生成模型解析文件，在下个大版本更新（可能0.6.0）会完成前置模型解析和后处理流水线的集成工作。

请问在项目https://github.com/opendatalab/PDF-Extract-Kit中怎么生成model_json?

**Comment by myhloli** [comment]
@xuquankun 可以先看一下[PDF-Extract-Kit](https://github.com/opendatalab/PDF-Extract-Kit)的readme，如果安装过程中遇到问题可以再反馈。

**Comment by okamifish** [comment]
> > 目前需要通过项目https://github.com/opendatalab/PDF-Extract-Kit 生成模型解析文件，在下个大版本更新（可能0.6.0）会完成前置模型解析和后处理流水线的集成工作。
> 
> 请问在项目[https://github.com/opendatalab/PDF-Extract-Kit中怎么生成model_json](https://github.com/opendatalab/PDF-Extract-Kit%E4%B8%AD%E6%80%8E%E4%B9%88%E7%94%9F%E6%88%90model_json)?

同问，我也没有找到model_json的生成方法，[PDF-Extract-Kit](https://github.com/opendatalab/PDF-Extract-Kit)已经能够成功运行了，生成了一个由pdf转换的json文件，但不知道怎么用

**Comment by myhloli** [comment]
@okamifish 生成的这个json就是modeljson，可以用命令magic-pdf pdf-command --pdf "pdf_path" --model "model_json_path"

**Comment by lonngxiang** [comment]
model_json 同问，这个是哪里来的，写的不清楚

![image](https://github.com/user-attachments/assets/9954d854-ec20-4cfc-80d7-2e1f2daebd07)

**Comment by myhloli** [comment]
@lonngxiang 稍晚会更新内置模型的版本，不用再纠结model_json怎么生成的了。

**Comment by lonngxiang** [comment]
> @lonngxiang 稍晚会更新内置模型的版本，不用再纠结model_json怎么生成的了。

好的，更新后@下哈，体验体验

**Comment by myhloli** [comment]
> > @lonngxiang 稍晚会更新内置模型的版本，不用再纠结model_json怎么生成的了。
> 
> 好的，更新后@下哈，体验体验

已更新
