### ISSUE TITLE
Version is less then 0.7

### ISSUE THREAD

**Issue by pokecheater** [opendatalab/MinerU#1230]
### Description of the bug | 错误描述

Hi,
my verison is below 0.7 after fresh install.

![image](https://github.com/user-attachments/assets/a4334cdb-61ec-4752-95f2-3cc7f80de181)

I should report it as your manual states:

<img width="1179" alt="image" src="https://github.com/user-attachments/assets/3f4e7ac7-841e-4a8b-9eae-977be33bf9f6">

Also the -p parameter is not available.

![image](https://github.com/user-attachments/assets/083b8890-ca9a-4405-ab24-b33ed1c3ec64)

Python version 3.12 
Ubuntu 24..04.

Best regards :)

### How to reproduce the bug | 如何复现

Follow the steps of your own tutorial.

https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_en_US.md#6-download-models

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
We only support python3.10 now.

**Comment by pokecheater** [comment]
Okay got it, my fault.
Thx for that quick response. :), Like a real AI Bot ;).
