### ISSUE TITLE
请问在对PDF分类后，是个什么流程？我搜索了资料，但是没有理解透相关的流程

### ISSUE THREAD

**Issue by Rezen1997** [opendatalab/MinerU#1234]
您好，在PDF分类后，我有几个疑问还请您解答一下，如果能够得到解答，将万分感谢：
1.pdf分类后是进行布局检测吗？
2.布局检测会检测出行间和行内的公式吗，因为我看到还有专门的公式检测和识别的模型？
3.布局检测和公式检测的顺序是什么呢？是同时呢，还是有先后？他们都是对全文进行检测，然后标记出相应的模块吗？
4.对于行内的公式是怎么记录呢？也是坐标吗？

**Comment by myhloli** [comment]
1. 是的
2. 布局检测会检测行间公式，但是由于精度不高我们没有采用
3. 先布局检测，再公式检测 ，这是两个不同的模型，所以有先后
4. 行内公式是通过坐标记录的

参考资料：

https://github.com/opendatalab/MinerU/blob/a962824b3557a4ceac87e8c11977dfff660498fb/magic_pdf/model/pdf_extract_kit.py#L172

https://github.com/opendatalab/MinerU/blob/master/docs/output_file_zh_cn.md#some_pdf_modeljson

**Comment by Rezen1997** [comment]
谢谢您的解答！还有两个疑问想向您请教一下：
    1.我看到pipe.analyze()好像已经在执行了pdf布局检测和内容识别，请问pipe.parse()在做什么呢？
    2.如果我想要将pdf的内容划分的提取,请问是在middle.json的基础上来处理比较好，还是在md文件中直接剔除图片和表格更好呢？（这里的内容划分提取指的是：文本单独提取出文件，保留阅读顺序，文本内包含行内公式，内容存储为md格式；表格及表头单独提取出文件；图像单独存放到文件夹；公式单独存放到文件中）
     目前的想法是在md的基础上来获取文本，在middle.json中来获取表格、图片以及公式。但是我好像没办法在md的基础上去掉表格以及图片的caption。。。

**Comment by myhloli** [comment]
1. parse是后处理，因为model.json的结果是乱序且没有nms的
2. 我们考虑到了这个问题，可以直接使用输出目录中的content_list.json实现
