### ISSUE TITLE
你好，我目前使用的版本是0.9.3，请问是否有方法可以获得单个字的坐标

### ISSUE THREAD

**Issue by farierer** [opendatalab/MinerU#1236]

**Comment by myhloli** [comment]
建议参考文档：
https://github.com/opendatalab/MinerU/blob/master/docs/output_file_zh_cn.md

我们输出的最细粒度为span，不会到char级别。

**Comment by farierer** [comment]
我记得好像之前是获得每个字的坐标然后合成一个span的坐标，请问是否是这个版本直接跳过了获得每个字的过程

**Comment by myhloli** [comment]
分文本型和扫描型，文本型还是有每个字的坐标，占用容量太大，在后处理过程中删除了，扫描型的无法获得每个字的坐标。

**Comment by farierer** [comment]
能大概帮我指出一下具体是在哪一部分删除了每个字的坐标的吗

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/a962824b3557a4ceac87e8c11977dfff660498fb/magic_pdf/pdf_parse_union_core_v2.py#L67
