### ISSUE TITLE
有人知道Mac上如何使用么？

### ISSUE THREAD

**Issue by yray680** [opendatalab/MinerU#124]
readme我没看明白。

**Comment by myhloli** [comment]
现在需要同时使用两个模块，
PDF-Extract-Kit在Mac上的使用说明看这里
https://github.com/opendatalab/PDF-Extract-Kit/blob/main/docs/Install_in_macOS_zh_cn.md
MinerU直接pip装magic-pdf就可以在Mac上用，下个大版本更新会把两个模块打通的

**Comment by yray680** [comment]
谢谢回复
