### ISSUE TITLE
关于middle.json 和 model.json 中bbox坐标 的疑问

### ISSUE THREAD

**Issue by Skyer19** [opendatalab/MinerU#1240]
### Description of the bug | 错误描述

 你好，我使用MinerU生成相关的json文件后，发现`  middle.json `中bbox坐标是类似如下的形式：
```
  "preproc_blocks": [
                {
                    "type": "title",
                    "bbox": [
                        70,
                        188,
                        154,
                        206
                    ],
                    "lines": [
                        {
                            "bbox": [
                                70,
                                190,
                                155,
                                206
                            ],
                            "spans": [
                                {
                                    "bbox": [
                                        70,
                                        190,
                                        155,
                                        206
                                    ],
                                    "score": 1.0,
                                  
```
                                  
`model.json` 给出bbox坐标的形式是：
```
[
    {
        "layout_dets": [
            {
                "category_id": 0,
                "poly": [
                    195,
                    524,
                    430,
                    524,
                    430,
                    574,
                    195,
                    574
                ],
                "score": 0.904
            },
            {
                "category_id": 1,
                "poly": [
                    193,
                    762,
                    1489,
                    762,
                    1489,
                    836,
                    193,
                    836
                ],
                "score": 0.883
            },
```
问题：
1. 当我尝试直接使用`model.json` 给出的bbox坐标画出bbox时，发现与使用 `middle.json `中bbox坐标画出的结果不同
2. 源码中也是使用 middle.json 中bbox坐标画出bbox：
       [     draw_visualization_bbox(pipe.pdf_mid_data['pdf_info'], pdf_bytes, output_path, pdf_name)](https://github.com/opendatalab/MinerU/blob/a962824b3557a4ceac87e8c11977dfff660498fb/demo/magic_pdf_parse_main.py#L134)
       
想请问` model.json `给出的bbox坐标是什么形式，以及需要怎么使用？

谢谢！

          
                                  

### How to reproduce the bug | 如何复现

如上

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
model.json中使用dpi与middle.json一般不通，需要根据每页的宽高计算缩放比并缩放poly坐标到bbox绘制，具体逻辑可以跟踪进底层绘制部分的代码查看

**Comment by Skyer19** [comment]
@myhloli  谢谢您的回答。
但根据 https://github.com/opendatalab/MinerU/blob/master/docs/output_file_zh_cn.md 这里的描述，我理解 model.json 中的poly 所代表的四边形坐标即为有效的bbox 的坐标。如果按您所述，想问一下我该如何运用 来自于poly 所代表的四边形坐标呢？谢谢。

**Comment by Skyer19** [comment]
@myhloli 您好，我在UNIPipe.py 文件中看到一些测试代码：

```
if __name__ == '__main__':
    # 测试
    from magic_pdf.data.data_reader_writer import DataReader
    drw = DataReader(r'D:/project/20231108code-clean')

    pdf_file_path = r'linshixuqiu\19983-00.pdf'
    model_file_path = r'linshixuqiu\19983-00.json'
    pdf_bytes = drw.read(pdf_file_path)
    model_json_txt = drw.read(model_file_path).decode()
    model_list = json.loads(model_json_txt)
    write_path = r'D:\project\20231108code-clean\linshixuqiu\19983-00'
    img_bucket_path = 'imgs'
    img_writer = DataWriter(join_path(write_path, img_bucket_path))

    # pdf_type = UNIPipe.classify(pdf_bytes)
    # jso_useful_key = {
    #     "_pdf_type": pdf_type,
    #     "model_list": model_list
    # }

    jso_useful_key = {
        '_pdf_type': '',
        'model_list': model_list
    }
    pipe = UNIPipe(pdf_bytes, jso_useful_key, img_writer)
    pipe.pipe_classify()
    pipe.pipe_parse()
    md_content = pipe.pipe_mk_markdown(img_bucket_path)
    content_list = pipe.pipe_mk_uni_format(img_bucket_path)

    md_writer = DataWriter(write_path)
    md_writer.write_string('19983-00.md', md_content)
    md_writer.write_string('19983-00.json', json.dumps(pipe.pdf_mid_data, ensure_ascii=False, indent=4))
    md_writer.write_string('19983-00.txt', str(content_list))
```

请问能否告知这里的：
` model_file_path = r'linshixuqiu\19983-00.json'`
 
 是model.json 还是middle.json？ 谢谢。

**Comment by myhloli** [comment]
> @myhloli 谢谢您的回答。 但根据 https://github.com/opendatalab/MinerU/blob/master/docs/output_file_zh_cn.md 这里的描述，我理解 model.json 中的poly 所代表的四边形坐标即为有效的bbox 的坐标。如果按您所述，想问一下我该如何运用 来自于poly 所代表的四边形坐标呢？谢谢。

model.json中的坐标存在缩放，可以根据model.json中的页面宽高参数和pdf文件读取到的宽高参数求出每页的缩放倍率再还原回正常的坐标。

**Comment by myhloli** [comment]
> @myhloli 您好，我在UNIPipe.py 文件中看到一些测试代码：
> 
> ```
> if __name__ == '__main__':
>     # 测试
>     from magic_pdf.data.data_reader_writer import DataReader
>     drw = DataReader(r'D:/project/20231108code-clean')
> 
>     pdf_file_path = r'linshixuqiu\19983-00.pdf'
>     model_file_path = r'linshixuqiu\19983-00.json'
>     pdf_bytes = drw.read(pdf_file_path)
>     model_json_txt = drw.read(model_file_path).decode()
>     model_list = json.loads(model_json_txt)
>     write_path = r'D:\project\20231108code-clean\linshixuqiu\19983-00'
>     img_bucket_path = 'imgs'
>     img_writer = DataWriter(join_path(write_path, img_bucket_path))
> 
>     # pdf_type = UNIPipe.classify(pdf_bytes)
>     # jso_useful_key = {
>     #     "_pdf_type": pdf_type,
>     #     "model_list": model_list
>     # }
> 
>     jso_useful_key = {
>         '_pdf_type': '',
>         'model_list': model_list
>     }
>     pipe = UNIPipe(pdf_bytes, jso_useful_key, img_writer)
>     pipe.pipe_classify()
>     pipe.pipe_parse()
>     md_content = pipe.pipe_mk_markdown(img_bucket_path)
>     content_list = pipe.pipe_mk_uni_format(img_bucket_path)
> 
>     md_writer = DataWriter(write_path)
>     md_writer.write_string('19983-00.md', md_content)
>     md_writer.write_string('19983-00.json', json.dumps(pipe.pdf_mid_data, ensure_ascii=False, indent=4))
>     md_writer.write_string('19983-00.txt', str(content_list))
> ```
> 
> 请问能否告知这里的： ` model_file_path = r'linshixuqiu\19983-00.json'`
> 
> 是model.json 还是middle.json？ 谢谢。

model.json
