### ISSUE TITLE
是否可以将cuda降级到12.0以下

### ISSUE THREAD

**Issue by koeizhang** [opendatalab/MinerU#1242]
### Description of the bug | 错误描述

本人使用A100显卡，目前nvidia-smi为525.147.05，最高支持cuda12.0。
由于机器上有其他模型在运行，所以无法升级nvidia-smi。目前mineru的采用12.1的cuda环境无法运行。
请问是否可以将环境的cuda降为11.8？如何操作？

### How to reproduce the bug | 如何复现

![微信图片_20241209225625](https://github.com/user-attachments/assets/ada1c257-0e70-4dc9-8d93-d668fba99d4f)
![微信图片_20241209225632](https://github.com/user-attachments/assets/2244875e-a9ce-4c40-ab6b-86bb186c883f)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by koeizhang** [comment]
![微信图片_20241209225842](https://github.com/user-attachments/assets/99f064e8-fc82-452e-86e5-1dea99da2496)

**Comment by myhloli** [comment]
可以试试通过这个方式安装cu118兼容的torch，但是不保证不和paddle框架产生冲突
```
pip3 install torch==2.3.1 torchvision==0.18.1 --index-url https://download.pytorch.org/whl/cu118
```
如果产生冲突，请卸载paddlepaddle和paddlepaddle-gpu，并再次安装paddlepaddle==3.0.0b1

**Comment by koeizhang** [comment]
感谢支持

**Comment by EagleEyeKestrel** [comment]
> 感谢支持

请问您最后使用cuda12.0成功运行了吗
