### ISSUE TITLE
请问可以创建多个虚拟环境然后下载应用来实现多进程吗？

### ISSUE THREAD

**Issue by yzl256** [opendatalab/MinerU#1244]
因为要处理的文件比较多，所有想多进程处理，不知道可不可行？

**Comment by myhloli** [comment]
多进程是可以的，一个虚拟环境就可以了

**Comment by yzl256** [comment]
谢谢作者

**Comment by yzl256** [comment]
继续输入命令行就可以了吗？

**Comment by yzl256** [comment]
> 多进程是可以的，一个虚拟环境就可以了

继续输入命令行就可以了吗？

**Comment by myhloli** [comment]
命令行是最简单的方法，在多个终端窗口内分别输入命令调用即可

**Comment by yzl256** [comment]
> 命令行是最简单的方法，在多个终端窗口内分别输入命令调用即可

明白了，谢谢大佬！！！！
