### ISSUE TITLE
Missing parts in recognition - incomplete title and figures

### ISSUE THREAD

**Issue by madlogos** [opendatalab/MinerU#1246]
### Description of the bug | 错误描述

1. 文档标题缺字，似乎是因为与顶部guidelines文字相同

![screenshot-1733798612159](https://github.com/user-attachments/assets/30bd3b21-d081-4910-83e2-cc4ee50f7ea5)

2. 整个图表都未识别

![screenshot-1733798575102](https://github.com/user-attachments/assets/e384980d-6249-4486-ac8b-1fb54463d0a8)

### How to reproduce the bug | 如何复现

采用的magic-pdf.json
```json
{
    "models-dir":...,
    "device-mode":"cuda",
    "layout-config":{
        "model":"doclayout_yolo" 
    },
    "formula-config":{
        "mfd_model":"yolo_v8_mfd",
        "mfr_model":"unimernet_base",
        "enable":true
    },
    "table-config":{
        "model":"rapid_table",
        "enable":true,
        "max_time":400
    }
}
```

parse_mode为auto

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
把layout模型换成layoutlmv3，应该能好一点

**Comment by myhloli** [comment]
0.10.6优化了doclayout-yolo对较宽元素看不全的问题，可以通过更新升级修复此问题。
