### ISSUE TITLE
解析pdf后怎么保存图片

### ISSUE THREAD

**Issue by cjun0717** [opendatalab/MinerU#1248]
### Description of the bug | 错误描述

使用magic_pdf_parse_main.py中的代码解析pdf后，怎么把图片保存到本地，md和json文件中只有图片路径

### How to reproduce the bug | 如何复现

使用命令行解析pdf图片保存到images目录下，使用python调用的话图片怎么保存

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
默认情况下，magic_pdf_parse_main.py会写出图片到images目录
如果没有图片请：
1. magic-pdf -v 看下版本号是否为0.10.5
2. 从仓库获取最新的magic_pdf_parse_main.py代码重试
