### ISSUE TITLE
是否能提供从pdf_info中提取对应字段的脚本呢

### ISSUE THREAD

**Issue by LightingFx** [opendatalab/MinerU#1253]
感谢各位贡献者提供MinerU项目，他的pdf转换功能是目前用过的最好用。但现在有一个小的需求：
我处理的pdf是一些比较大的论文pdf，一般在100-300页。处理完成后，图片、表格以s3的hash命名，我需要提取相应图片信息，但是pdf_info文件太大，我纯靠if去鉴别不同字段是否为空，是否有用，太过于繁琐。请问有没有制作过提取pdf_info数据的一些小脚本呢？或者如何读取这个数据。十分感谢！

**Comment by myhloli** [comment]
看看输出目录的content_list.json能不能满足你的需求，这个足够精简

**Comment by LightingFx** [comment]
> 看看输出目录的content_list.json能不能满足你的需求，这个足够精简
感谢回复，我是用python来处理，我查看了给的官方示例，没有给出相应的输出content_list.json。请问是否有文档里介绍如何使用python来输出这个文件呢？按照官方给的示例代码，只有pdf_info信息

**Comment by LightingFx** [comment]
感谢回复，我是使用python来将pdf转换为markdown的，我看了官方给的示例，没有给出如何能输出content_list的介绍。是否有相关文档说明使用python得到这些输出结果呢？

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/master/demo/magic_pdf_parse_main.py

**Comment by LightingFx** [comment]
> https://github.com/opendatalab/MinerU/blob/master/demo/magic_pdf_parse_main.py

非常感谢， content_list.json的信息可以用于替换图片/表格名称。现在仍有个问题，不知道未来是否可以优化：
很多图片/表格（我的pdf300页，大概有300多张图片，这里大概60%的图片）的caption为空，我查看了下content，实际这张图片的caption在上一条或者上上条的text中。可能导致的原因1.是图片和标题不在同一页，这种确实不好解决？2.确实都在同一页，但是提取不到图片上面的标题，这个应该可以优化。
