### ISSUE TITLE
直接运行demo.py，表格直接保存为图片

### ISSUE THREAD

**Issue by yazheng0307** [opendatalab/MinerU#127]
直接运行demo.py，表格直接保存为图片，没有进行表格识别

**Comment by drunkpig** [comment]
@yazheng0307 表格目前只做了检测，没有做识别。表格识别应该在1个月左右放出。

**Comment by learningpro** [comment]
期待一下表格识别，最好是能做那种有合并单元格的表格的识别

**Comment by STEARGAZER** [comment]
如果能加上方向检测就更好了，切割图片+方向检测+表格识别基本做到自动化了，非常期待

**Comment by myhloli** [comment]
表格识别功能已在主线功能中加入
