### ISSUE TITLE
关于应用中的模型替换

### ISSUE THREAD

**Issue by Ne1roy** [opendatalab/MinerU#1274]
你好，请问我想在MinerU的使用过程中，在ocr识别模式下，用自己微调的paddleOCR模型替换掉原本默认使用的paddleOCR模型，该如何进行项目修改呢？

**Comment by myhloli** [comment]
替换用户目录下./paddleocr中的模型文件即可

**Comment by Ne1roy** [comment]
非常感谢！让我节省了很多时间
