### ISSUE TITLE
readme demo.py Simplest Processing Method link return 404

### ISSUE THREAD

**Issue by malingzhi58** [opendatalab/MinerU#1283]
### Description of the bug | 错误描述

readme demo.py Simplest Processing Method link return 404

### How to reproduce the bug | 如何复现

readme demo.py Simplest Processing Method link return 404

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
We have updated the sample code to a dedicated documentation page.

https://mineru.readthedocs.io/en/latest/user_guide/quick_start/to_markdown.html
