### ISSUE TITLE
'UNIPipe' object has no attribute 'pdf_bytes'

### ISSUE THREAD

**Issue by bhelm** [opendatalab/MinerU#1285]
### Description of the bug | 错误描述

and its true: https://github.com/opendatalab/MinerU/blob/master/magic_pdf/pipe/UNIPipe.py#L48C47

### How to reproduce the bug | 如何复现

tried version 0.10.6.

Look at the source (current master, see link above). pdf_bytes seems to be renamed to document with different type but the line linked was not updated.

Thanks

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
We have refactored the internal processing logic. Please refer to the sample code here to update your method calls.

https://mineru.readthedocs.io/en/latest/user_guide/quick_start/to_markdown.html

**Comment by bhelm** [comment]
I see, thanks. The method should be removed then?

**Comment by myhloli** [comment]
Yes, they will be removed in the near future.

**Comment by bhelm** [comment]
Thank you. Great work by the way, i love this project.
