### ISSUE TITLE
{  "error": "'UNIPipe' object has no attribute 'pdf_bytes'" }

### ISSUE THREAD

**Issue by yyxg** [opendatalab/MinerU#1286]
### Description of the bug | 错误描述

我在 projects/web_api目录下成功打出一个amd镜像，在镜像启动后解析一个pdf文件后报错

### How to reproduce the bug | 如何复现

1、修改dockfile
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/17410a12-7e2d-4aee-9bc0-491456855647" />

2、使用 modelscope/hub/opendatalab/PDF-Extract-Kit-1___0/models
3、docker build -t mineru:0.2 --platform=linux/amd64 .
4、调用接口
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/24ad821b-ecb5-4029-a3e1-6ce534263446" />

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
我们重构了内部调用逻辑，需要根据最新的文档更新调用的代码：

https://mineru.readthedocs.io/zh-cn/latest/user_guide/quick_start/to_markdown.html

**Comment by hustzxl** [comment]
> 我们重构了内部调用逻辑，需要根据最新的文档更新调用的代码：
> 
> https://mineru.readthedocs.io/zh-cn/latest/user_guide/quick_start/to_markdown.html
接口为啥变来变去的
