### ISSUE TITLE
信息丢失问题

### ISSUE THREAD

**Issue by prisssse** [opendatalab/MinerU#129]
我在把pdf文件转化为md，我的json文件里面存在{"category_id": 15, "poly": [276.0, 828.0, 677.0, 828.0, 677.0, 863.0, 276.0, 863.0], "score": 0.99, "text": "Figure 2: Lengths of instructions"}, 这个信息，但是在转化为md的时候“Figure 2: Lengths of instructions”这条信息直接丢失了。原本存在的两张图片虽然都被截取下来了，但是真正放入md文件的只有其中一张。附上我使用的pdf文件。
[testpdf.pdf](https://github.com/user-attachments/files/16191551/testpdf.pdf)

**Comment by myhloli** [comment]
<img width="620" alt="image" src="https://github.com/user-attachments/assets/104b4614-11b3-4b8c-956a-9fd309538eda">

看了下这两张图离太近了，算法把图3的caption和图2的本体当成一张图了，这样会丢掉图2的caption和图3的本体
已经反馈给开发这块功能的小哥了，预计下周修复

**Comment by myhloli** [comment]
已修复：https://github.com/opendatalab/MinerU/commit/ddff4b4258e3dba8cd3bcaed4e0865138934756c
<img width="871" alt="image" src="https://github.com/user-attachments/assets/e14cc472-df90-4acc-8dc7-d1b083859df7">
