### ISSUE TITLE
繁体字的识别问题

### ISSUE THREAD

**Issue by czhcc** [opendatalab/MinerU#1295]
### Description of the bug | 错误描述

在https://www.modelscope.cn/演示环境，可以识别出繁体字“轟”，但我本地运行却不能识别。请问可能是什么原因？

### How to reproduce the bug | 如何复现

我本地运行使用的magic-pdf.json内容：
```json
{
    "bucket_info": {
        "bucket-name-1": [
            "ak",
            "sk",
            "endpoint"
        ],
        "bucket-name-2": [
            "ak",
            "sk",
            "endpoint"
        ]
    },
    "models-dir": "/models/PDF-Extract-Kit-1.0/models",
    "layoutreader-model-dir": "/models/layoutreader",
    "device-mode": "cuda",
    "layout-config": {
        "model": "layoutlmv3"
    },
    "formula-config": {
        "mfd_model": "yolo_v8_mfd",
        "mfr_model": "unimernet_small",
        "enable": true
    },
    "table-config": {
        "model": "rapid_table",
        "enable": true,
        "max_time": 400
    },
    "config_version": "1.0.0"
}
```

代码如下：
```python
        pdf_bytes = open(pdf_path, 'rb').read()
        jso_useful_key = {'_pdf_type': '', 'model_list': []}
        local_image_dir = os.path.join(current_script_dir, 'images')
        image_dir = str(os.path.basename(local_image_dir))
        image_writer = FileBasedDataWriter(local_image_dir)
        pipe = UNIPipe(pdf_bytes, jso_useful_key, image_writer)
        pipe.pipe_classify()
        pipe.pipe_analyze()
        pipe.pipe_parse()
        md_content = pipe.pipe_mk_markdown(image_dir, drop_mode='none')
        with open(f'{current_script_dir}/test2.md', 'w', encoding='utf-8') as f:
            f.write(md_content)
```

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
非简中和英文ocr时需要输入lang参数，具体代码参考
https://github.com/opendatalab/MinerU/blob/3456b9e528572ba09598ae5a55ebddc96f853d75/magic_pdf/tools/common.py#L69

**Comment by czhcc** [comment]
在演示界面的Language栏，没有选择，解析时传入的是什么？

**Comment by myhloli** [comment]
不选择的时候传入空字符串，在代码中调用传入None也可以

**Comment by czhcc** [comment]
多谢。现在的问题是在演示界面，不选择Language，可以识别“轟”字，本地代码，lang=None不能识别出来，同一页面中其它的简体和一些繁体字能识别

**Comment by myhloli** [comment]
本地测试的版本和在线的版本一致？

**Comment by czhcc** [comment]
在线的是这个，应该是你们提供的
https://www.modelscope.cn/studios/OpenDataLab/MinerU
本地是0.10.5

**Comment by myhloli** [comment]
线上用的应该是0.10.6，虽然可能0.10.5到0.10.6的变化不会导致你这个情况出现，还是建议更新到最新版试试

**Comment by czhcc** [comment]
好的，我先更新一下，多谢

**Comment by czhcc** [comment]
已经更新到0.10.6，代码是参考
https://mineru.readthedocs.io/en/latest/user_guide/quick_start/to_markdown.html
这两行
    infer_result = ds.apply(doc_analyze, ocr=True)
    ## pipeline
    pipe_result = infer_result.pipe_ocr_mode(image_writer)
加不加
lang="chinese_cht"
都不会识别出“轟”字，不知道是怎么回事了，
https://www.modelscope.cn/studios/OpenDataLab/MinerU
这里确实能识别出来，Language栏没有选值

**Comment by myhloli** [comment]
你的测试样本能发一下吗

**Comment by czhcc** [comment]
[test1.pdf](https://github.com/user-attachments/files/18146498/test1.pdf)
好的，麻烦看一下

**Comment by myhloli** [comment]
你这个繁体字是在表格中的，在线demo不开表格识别的时候是截图处理的，目前表格识别应该是不支持繁体字的，你可以打开表格开关再试下

**Comment by czhcc** [comment]
好的，明白了。演示地址那个表格是以图片显示的，还以为是提取的。
