### ISSUE TITLE
DEMO program error （'PymuDocDataset' object has no attribute 'apply'）

### ISSUE THREAD

**Issue by zhukefucn** [opendatalab/MinerU#1296]
### Description of the bug | 错误描述

https://mineru.readthedocs.io/zh-cn/latest/user_guide/quick_start/to_markdown.html
转换为 Markdown 文件#本地文件示例
MinerU has install successfully in Ubuntu22.04 and comand run correctly.
Use this demo program error :  AttributeError: 'PymuDocDataset' object has no attribute 'apply'

### How to reproduce the bug | 如何复现

https://mineru.readthedocs.io/zh-cn/latest/user_guide/quick_start/to_markdown.html
转换为 Markdown 文件#本地文件示例
this demo program:
infer_result = ds.apply(doc_analyze, ocr=True) 
Use this demo program error :  AttributeError: 'PymuDocDataset' object has no attribute 'apply'

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by zhukefucn** [comment]
I review the model PymuDocDataset，it hasnot apply:
class PymuDocDataset(Dataset): 
def init(self, bits: bytes): """Initialize the dataset, which wraps the pymudoc documents. Args: bits (bytes): the bytes of the pdf """ self._records = [Doc(v) for v in fitz.open('pdf', bits)] self._data_bits = bits self._raw_data = bits def len(self) -> int: """The page number of the pdf.""" return len(self._records) def iter(self) -> Iterator[PageableData]: """Yield the page doc object.""" return iter(self._records) def supported_methods(self) -> list[SupportedPdfParseMethod]: """The method supported by this dataset. Returns: list[SupportedPdfParseMethod]: the supported methods """ return [SupportedPdfParseMethod.OCR, SupportedPdfParseMethod.TXT] def data_bits(self) -> bytes: """The pdf bits used to create this dataset.""" return self._data_bits def get_page(self, page_id: int) -> PageableData: """The page doc object. Args: page_id (int): the page doc index Returns: PageableData: the page doc object """

**Comment by myhloli** [comment]
check your magic-pdf version is 0.10.6 or not.

**Comment by zhukefucn** [comment]
I review dataset.py,find following:

    @abstractmethod
    def apply(self, proc: Callable, *args, **kwargs):
        """Apply callable method which.

        Args:
            proc (Callable): invoke proc as follows:
                proc(self, *args, **kwargs)

        Returns:
            Any: return the result generated by proc
        """
        pass

I think it should use Dataset instead of PymuDocDataset, But the progarm hasnot any arguments. So the program TypeError: Dataset() takes no arguments

please correct the error,thx!

**Comment by zhukefucn** [comment]
updata to newest version 10.6, OK
