### ISSUE TITLE
UNIPipe的pipe_classify方法问题

### ISSUE THREAD

**Issue by czhcc** [opendatalab/MinerU#1298]
### Description of the bug | 错误描述

在0.10.6版本的代码中，UNIPipe的pipe_classify方法
self.pdf_type = AbsPipe.classify(self.pdf_bytes)
是没有self.pdf_bytes这个成员变量了吗？但调用时还用这个变量。

main中的测试代码，
pipe = UNIPipe(pdf_bytes, jso_useful_key, img_writer)
pdf_bytes还是做为成员变量传入，但UNIPipe的构造方法里没有变量对应

### How to reproduce the bug | 如何复现

pipe = UNIPipe(pdf_bytes, jso_useful_key, image_writer)
pipe.pipe_classify()

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
0.10.6 把解析过程包装到另一个类中了，pipe类后面会被弃用
新版本的调用方式参考：
https://mineru.readthedocs.io/en/latest/user_guide/quick_start/to_markdown.html

**Comment by czhcc** [comment]
可以了
