### ISSUE TITLE
0.10.6 运行magic_pdf_parse_main.py直接报错

### ISSUE THREAD

**Issue by Ronass** [opendatalab/MinerU#1300]
### Description of the bug | 错误描述

magic_pdf-0.10.6-released 下载该版本源码安装环境后运行直接报错，分别运行了demo.py，magic_pdf_parse_main.py两个文件均不行，麻烦看下。

另外请问下 https://mineru.readthedocs.io/zh-cn/latest/user_guide/quick_start/to_markdown.html 这个地址的文档内容和demo, magic_pdf_parse_main使用的方式不一样，以哪个为准呢？我看master分支已经删除demo.py，magic_pdf_parse_main.py 这两个文件，按照文档怎样才能不写入文件，只是获取md内容呢，还是说只能写完了再次读取内容

### How to reproduce the bug | 如何复现

![image](https://github.com/user-attachments/assets/6a03e0bd-4589-4730-8d4d-64b22b302dda)
![image](https://github.com/user-attachments/assets/f9a9e5d6-c5bf-44d2-a8e1-841e5d18658e)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by icecraft** [comment]
@Ronass  `demo` 目录下的代码已经不维护了。
在已经获得 `pipe_result` 的基础上可以用

```
from magic_pdf.config.make_content_config import DropMode, MakeMode
from magic_pdf.dict2md.ocr_mkcontent import union_make

drop_mode=DropMode.WHOLE_PDF,
md_make_mode=MakeMode.MM_MD

img_dir_or_bucket_prefix = "/tmp"  # replace with real one 



pdf_info_list = pipe_result._pipe_res['pdf_info']      # replace `pipe_result` with realone
md_content = union_make(
            pdf_info_list, md_make_mode, drop_mode, img_dir_or_bucket_prefix
        )```

**Comment by Ronass** [comment]
> @Ronass `demo` 目录下的代码已经不维护了。 在已经获得 `pipe_result` 的基础上可以用
> 
> ```
> from magic_pdf.config.make_content_config import DropMode, MakeMode
> from magic_pdf.dict2md.ocr_mkcontent import union_make
> 
> drop_mode=DropMode.WHOLE_PDF,
> md_make_mode=MakeMode.MM_MD
> 
> img_dir_or_bucket_prefix = "/tmp"  # replace with real one 
> 
> 
> 
> pdf_info_list = pipe_result._pipe_res['pdf_info']      # replace `pipe_result` with realone
> md_content = union_make(
>             pdf_info_list, md_make_mode, drop_mode, img_dir_or_bucket_prefix
>         )``` 
> ```

感谢，已经按照最新的文档进行了，可以了
