### ISSUE TITLE
The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by yyxg** [opendatalab/MinerU#1302]
### Description of the bug | 错误描述

botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the GetObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.

### How to reproduce the bug | 如何复现

1、参考代码 对象存储文件示例：https://mineru.readthedocs.io/zh-cn/latest/user_guide/quick_start/to_markdown.html
2、我使用的对象存储是minio
3、我们支持minio的配置么？magic_pdf/data/data_reader_writer目录好像没有相应代码
4、在minio的api 文档https://min.io/docs/minio/linux/developers/javascript/API.html，我注意到 s3和minio的配置不太一样

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
使用对象存储需要配置bucket_name, ak, sk, endpoint_url这四个参数
据我所知，minio应该是兼容s3协议的，用户名和密码即为ak，sk

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/626300f3-e80a-4489-a0e2-197aac5d4830)

这是之前其他用户使用minio的配置，这个是用的老版本接口，仅供参考，他这个配置稍微有一点错误是endpoint忘了加http头，别的都是ok的

**Comment by yyxg** [comment]
非常感谢，读写都可以了； reader = S3DataReader("pdf/input/", "miniocr", "miniocr", "miniocr1216", "http://localhost:9000") 
之前配置的ak和sk是为用户创建的Access Key 和Secret key
<img width="1406" alt="image" src="https://github.com/user-attachments/assets/d6e1ac26-5526-4089-b8a7-477b1f48010d" />

因为我用Java相同的配置是没问题的
<img width="589" alt="image" src="https://github.com/user-attachments/assets/88987cde-be92-4ef1-88e5-f5a96acb3c27" />

**Comment by yyxg** [comment]
可能是我代码问题，我今天试了一下用Access Key 和Secret key也可以的
