### ISSUE TITLE
huggingface 上的表格提取用的是 structeqtable 么

### ISSUE THREAD

**Issue by lolocoo** [opendatalab/MinerU#1303]
huggingface 上的表格提取用的是 structeqtable 么， 直接使用 pdf-extract-kit 工具的表格提取，提取结果差距比较大。是用tablemaster 来提取的么？

**Comment by myhloli** [comment]
用的rapidtable

**Comment by zhukefucn** [comment]
不用rapidtable，报错啊ModuleNotFoundError: No module named 'magic_pdf.model.sub_modules.table.structeqtable'。我在magic-pdf.json里面删除了sub_model，怎么回事啊？

**Comment by myhloli** [comment]
> 不用rapidtable，报错啊ModuleNotFoundError: No module named 'magic_pdf.model.sub_modules.table.structeqtable'。我在magic-pdf.json里面删除了sub_model，怎么回事啊？
> 
> 

其他表格解析模型已被移除
