### ISSUE TITLE
AbsPipe __init__ 构造函数中  self.dataset = Dataset 赋值错误

### ISSUE THREAD

**Issue by TemporaryRen** [opendatalab/MinerU#1305]
### Description of the bug | 错误描述

在使用过程中 出现了 TypeError: object of type 'ABCMeta' has no len() 异常
经排查 是 pipe 的基类 AbsPipe 的构造方法有问题
self.dataset = Dataset 应为 self.dataset = dataset
![image](https://github.com/user-attachments/assets/0e889e8a-dd2d-439a-a483-dd550b3f4135)

### How to reproduce the bug | 如何复现

pipe.pipe_analyze()
方法 必报错

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by icecraft** [comment]
AbsPipe ， UNIPipe, OCRPipe, TXTPipe 已经不用了，将会在后续版本删除。 现在建议参考 `https://mineru.readthedocs.io/en/latest/user_guide/quick_start/to_markdown.html`

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/pull/1312
