### ISSUE TITLE
金融研报解析文本漏字很多

### ISSUE THREAD

**Issue by WendaDeng** [opendatalab/MinerU#1307]
### Description of the bug | 错误描述

在使用minerU在线Demo的过程中，上传了金融研报，从解析结果看，版面分析效果不错，但是实际提取出来的文本存在不少缺失。
使用的文件如下：
[2023-04-10：美国3月非农就业数据点评：劳动力参与率或已达高点.pdf.md](https://github.com/user-attachments/files/18161443/2023-04-10.3.pdf.md)
部分解析结果：
![image](https://github.com/user-attachments/assets/fd531c31-0d2b-4209-842a-9ed7ebb17fd8)
可以看到从第一段文字开始就存在较多文字缺漏。

### How to reproduce the bug | 如何复现

直接在minerU上上传相同的文件应该就可以复现解析结果

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
这个demo的版本比较老了，可以通过modelscope和huggingface的最新demo测试效果，应该不会有丢字的情况了

**Comment by WendaDeng** [comment]
去modelscope试了，效果很棒，没有漏字了。感谢！
