### ISSUE TITLE
增加pdf直接转word

### ISSUE THREAD

**Issue by ChjxL** [opendatalab/MinerU#1317]
作者您好，非常感谢你们开源这么有用的项目，我根据你们已有的脚本添加了一些小功能，实现从pdf直接转word的功能，不知道我是否可以为这个项目添加一个pdf转word的功能呢。

**Comment by myhloli** [comment]
欢迎提交pr，请提交到dev分支的

https://github.com/opendatalab/MinerU/blob/35eb3bd29b12169630eb9af6cc4df1d4621ec213/magic_pdf/dict2md/ocr_mkcontent.py#L252

方法中，通过make_mode == MakeMode.MM_WORD触发

**Comment by oldTomatoCN** [comment]
请问这个功能什么时候可以出？

**Comment by ChjxL** [comment]
> 请问这个功能什么时候可以出？

不好意思，一直忘记了，这两天提交pr

**Comment by oldTomatoCN** [comment]
我用python-docx效果不是特别好。原有是这样的

![Image](https://github.com/user-attachments/assets/cbebc69b-0621-4d68-a960-e9550d62b4b2)
转换后是这样的

![Image](https://github.com/user-attachments/assets/21e2ebbe-9b1e-4f66-9e7a-80ccce41bf05)

**Comment by Essence9999** [comment]
> 作者您好，非常感谢你们开源这么有用的项目，我根据你们已有的脚本添加了一些小功能，实现从pdf直接转word的功能，不知道我是否可以为这个项目添加一个pdf转word的功能呢。

大佬，你提交了没有？没找到啊？

**Comment by longsuyu** [comment]
现在有支持吗？
