### ISSUE TITLE
无法识别图片型PDF

### ISSUE THREAD

**Issue by hanmostudy** [opendatalab/MinerU#1319]
我发现目前的模型识别普通PDF还是不错的，但是如果我把PDF转换为图片型PDF，就一点都识别不出来了

**Comment by myhloli** [comment]
图片型的pdf方便上传一下吗

**Comment by hanmostudy** [comment]
[Uploading 拉米斯教材范式核心特征.pdf…]()

**Comment by hanmostudy** [comment]
好的，我上传一下
[拉米斯教材范式核心特征.pdf](https://github.com/user-attachments/files/18191230/default.pdf)

**Comment by myhloli** [comment]
我试了是正常的，可以在huggingface和modelscope的demo上自测一下

**Comment by hanmostudy** [comment]
好的，那我再去试一试，谢谢

**Comment by josenhadoop** [comment]
这个纯图片的pdf，在huggingface和modelscope的在线demo试了都正常，但是本地部署并跑完之后，没有报错，但输出的文件里面没有生成内容
![image](https://github.com/user-attachments/assets/da0671b6-5192-4266-b7e5-a6113d1b56a3)

**Comment by josenhadoop** [comment]
![image](https://github.com/user-attachments/assets/f50e20d4-526c-441a-a4af-07c7aac24509)

**Comment by josenhadoop** [comment]
![image](https://github.com/user-attachments/assets/a75e13a8-9815-44b5-97a9-2908f6916072)
跑完之后，输出文件夹是空的

**Comment by myhloli** [comment]
cpu跑paddleocr有内存泄漏的情况，请关注一下运行时的内存占用，如果在解析中途因为内存占用满了导致进程被杀的话是没有结果的
