### ISSUE TITLE
包含下划线的文字，会被转成图片

### ISSUE THREAD

**Issue by UXplayer** [opendatalab/MinerU#1320]
### Description of the bug | 错误描述

如下图，左侧是原始pdf、右侧是 Markdown
有下划线的这部分文字，直接被转成了图片、没有识别成文字
![image](https://github.com/user-attachments/assets/51c30d48-3613-4c74-898e-f8df93802375)

### How to reproduce the bug | 如何复现

使用的是在线 demo 版本、非本地部署

这是原始 pdf 附件：
[pass初中古诗文.pdf](https://github.com/user-attachments/files/18176188/pass.pdf)

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
我们有两个layout模型，我试了下，你这个样本切换到doclayout-yolo模型效果是比较好的，你可以自行测试下
