### ISSUE TITLE
ocr出现乱码

### ISSUE THREAD

**Issue by liujiyaoFDU** [opendatalab/MinerU#1324]
### Description of the bug | 错误描述

Hi~ 我在使用mineru的时候，出现转完md乱码的情况。请问是什么问题呢？

![image](https://github.com/user-attachments/assets/8aafcb9a-67c9-41e9-9eb4-160a5c6c40d6)

下面是我的运行代码：
```bash
magic-pdf -p software_tutorial_dataset/software_tutorial_raw/secuexpress_2_1.pdf -o software_tutorial_dataset/software_tutorial_processed/ -m ocr
```
paddle版本如下：
![image](https://github.com/user-attachments/assets/ce09c4a9-b934-4952-8960-cbbf740c243a)

这是我的pdf文件。
[secuexpress_2_1_origin.pdf](https://github.com/user-attachments/files/18186196/secuexpress_2_1_origin.pdf)

### How to reproduce the bug | 如何复现

```bash
magic-pdf -p software_tutorial_dataset/software_tutorial_raw/secuexpress_2_1.pdf -o software_tutorial_dataset/software_tutorial_processed/ -m ocr
```

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
显卡和paddle框架不兼容，使用ocr会乱码，你这篇文档直接用auto模式就好了，
如果一定需要使用ocr的话，把paddlepaddle和paddlepaddle-gpu都卸了再单独装paddlepaddle用cpu做ocr

**Comment by Maple0709** [comment]
> 显卡和paddle框架不兼容，使用ocr会乱码，你这篇文档直接用auto模式就好了， 如果一定需要使用ocr的话，把paddlepaddle和paddlepaddle-gpu都卸了再单独装paddlepaddle用cpu做ocr

pdf_type是txt类型的PDF文件，使用minerU识别后markdown中出现乱码

**Comment by liujiyaoFDU** [comment]
> 显卡和paddle框架不兼容，使用ocr会乱码，你这篇文档直接用auto模式就好了， 如果一定需要使用ocr的话，把paddlepaddle和paddlepaddle-gpu都卸了再单独装paddlepaddle用cpu做ocr

已解决，感谢~

**Comment by ufxelv80** [comment]
@liujiyaoFDU 你好请问一下你这个乱码是怎么解决的？我们也出现了乱码的情况
