### ISSUE TITLE
magic-pdf Mac版本的paddlepaddle依赖和linux版本不一致

### ISSUE THREAD

**Issue by moria97** [opendatalab/MinerU#1327]
### Description of the bug | 错误描述

本地开发和部署测试的时候需要管理两套不同依赖，比较麻烦，可以统一成3.0.0b1吗？

### How to reproduce the bug | 如何复现

pip install magic-pdf[full]=0.10.5
安装了不同的paddlepaddle，项目环境在Mac和linux下不兼容

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by moria97** [comment]
@myhloli

**Comment by moria97** [comment]
这里简单改了一下：https://github.com/opendatalab/MinerU/pull/1328

**Comment by myhloli** [comment]
3.0.0b1有性能下降的问题，目前只在linux下启用是由于2.6.1在linux有兼容性问题，不同操作系统使用不同的paddle版本和开发测试都没有关系的吧

**Comment by moria97** [comment]
> 3.0.0b1有性能下降的问题，目前只在linux下启用是由于2.6.1在linux有兼容性问题，不同操作系统使用不同的paddle版本和开发测试都没有关系的吧

好吧，3.0.0b1有问题那确实只能优先用旧版本。。主要是2.6.1限制只能用3.20.x的protobuf，一堆包有冲突。。

**Comment by myhloli** [comment]
> > 3.0.0b1有性能下降的问题，目前只在linux下启用是由于2.6.1在linux有兼容性问题，不同操作系统使用不同的paddle版本和开发测试都没有关系的吧
> 
> 好吧，3.0.0b1有问题那确实只能优先用旧版本。。主要是2.6.1限制只能用3.20.x的protobuf，一堆包有冲突。。

那你直接在mac上升级到3.0.0b1做开发也行，反正部署到linux也是用3.0，不会有影响
