### ISSUE TITLE
关于unimernet 0.2.2 的依赖

### ISSUE THREAD

**Issue by Rezen1997** [opendatalab/MinerU#1331]
您好，我这边遇到了依赖冲突，根据报错显示unimernet 0.2.2 requires transformers==4.42.4，但是我有一些文件是需要依赖transformers 4.43.4版本，然后我想请问您，这个是否有解决办法？

**Comment by myhloli** [comment]
没办法，unimernet对transformers的版本依赖很高，你可以创建虚拟环境来安装本项目以避免依赖冲突

**Comment by Rezen1997** [comment]
感谢您的解答，那没有办法了。我用的vllm 0.6.1.post2+mlu0.5.0.pt2.4 requires transformers==4.43.4，如果我使用4.42.4版本的话，这样好像没办法使用vllm了 0.0。您有什么建议吗？

**Comment by myhloli** [comment]
找找老版本的vllm看看有没有匹配的或者强行安装匹配vllm的transformers，试试看

**Comment by Rezen1997** [comment]
好的，万分感谢您的建议，我明天找一下看看有没有适配的版本，没有的话我强行匹配试试能否兼容。我想请问一下，您们是否有做ARM架构的计划呢？因为我接触最多的是ARM的机器，这么好的工具不支持ARM感觉很可惜

**Comment by myhloli** [comment]
ARM linux近期会适配
