### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by chaoStart** [opendatalab/MinerU#1335]
### Description of the bug | 错误描述

参照  https://github.com/opendatalab/MinerU/blob/master/docs/README_Windows_CUDA_Acceleration_zh_CN.md

的步骤，创建了**python=3.10.0**的虚拟环境，安装了**magic-pdf**，下载了Modelscope的模型，最后在终端执行命令行 **magic-pdf -p small_ocr.pdf -o ./output**报错，连接失败。
我的linux系统版本是CUDA Version: 12.2 
![显卡信息](https://github.com/user-attachments/assets/5702a531-323f-4715-913d-13d83d38fdc3)

### How to reproduce the bug | 如何复现

https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_zh_CN.md

根据这个操作文档，一步步操作都没有问题，一直到第8步，第一次运行，下载了pdf文件，执行magic-pdf -p small_ocr.pdf -o ./output报错，显示连接失败。

![minerU_error](https://github.com/user-attachments/assets/c242e20b-b80e-4009-a6ac-95a4982c3b73)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.6

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
ocr的模型需要联网下载，你这个linux机器没有网络吧

**Comment by chaoStart** [comment]
> ocr的模型需要联网下载，你这个linux机器没有网络吧

我觉得你说的有道理！后面不知道为什么又可以正常运行了，我估计可能是当时网络断了
