### ISSUE TITLE
pdf中如果是中文夹杂数字，markdown中的数字貌似解析的有问题

### ISSUE THREAD

**Issue by Dawei-Simayi** [opendatalab/MinerU#1343]
### Description of the bug | 错误描述

同比增长....，这个数据解析的有问题。

据中国家用电器协会数据，2018 年家电行业主营业务收入为1.49 万亿，同比增长 $9.\,9\%$ ；利润为1,225.5亿元，同比增长 $2,\,5\%$ 。

### How to reproduce the bug | 如何复现

[格力电器2018年财报.pdf](https://github.com/user-attachments/files/18219091/2018.pdf)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.6

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
你这篇文档不需要开公式识别，关了公式的开关就可以了
