### ISSUE TITLE
希望图片不要强制OCR

### ISSUE THREAD

**Issue by FenchD** [opendatalab/MinerU#1345]
非整页全图的PDF文档中，有些插图上面的文本并不具有实际业务含义（比如操作手册中，图片只是用于指引操作，其中的内容与本文档无关。或者部分文档中图片是用于演示，其实内容已经过期）。这类图片中的内容被OCR以后，会降低整体内容质量。
因此，希望可以通过参数设置是否需要对文档内图片进行OCR（但是对于全图PDF还是需要自动OCR的）。
感谢贡献这么棒的大模型基础设施。

**Comment by myhloli** [comment]
如果需要关停文本型pdf中的混合ocr，需要自行修改源码

https://github.com/opendatalab/MinerU/blob/c4f252d316a72b5dc51e164bffa62aa8adf2bba9/magic_pdf/pdf_parse_union_core_v2.py#L230

将这个if内部的逻辑pass掉。
这样会导致部分使用图片表示文本的文本型pdf的解析结果丢失文本信息，如果您可以接受这种损失，可以自行修改。
