### ISSUE TITLE
希望可以自由切换配置文件支持表格识别或不进行表格识别

### ISSUE THREAD

**Issue by lilChang9** [opendatalab/MinerU#1346]
使用 TableMaster 识别时有时会解析报错，在报错后想要通过关闭表格识别进行降级处理，但是目前好像不支持动态切换配置文件?如果切换成本地自定义的配置文件（将表格识别功能关闭），那么会报TypeError String Indices Must be Integers

**Comment by myhloli** [comment]
可以参考gradio demo的代码，在单个解析任务中传入 `table_enable=False` 即可
