### ISSUE TITLE
长图解析失败

### ISSUE THREAD

**Issue by Tuyohai** [opendatalab/MinerU#1347]
### Description of the bug | 错误描述

长图解析失败，我的思路是对图片进行切分，代价是丢失连接处数据，请问有没有什么好的方法
![image](https://github.com/user-attachments/assets/86f8f2df-806a-4a70-a265-8e01c5bfb37b)

### How to reproduce the bug | 如何复现

![半导体行业：OSAT厂商Q3表现亮眼，人工智能／汽车电子等为未来需求增长点_01](https://github.com/user-attachments/assets/6f7146ec-6f1b-4637-8570-babe09c75e4b)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
没什么好思路，版面分析模型不适用于长图，这种就是需要自己手动切成正常的页面大小才行
