### ISSUE TITLE
magic-pdf 用默认模型解析pdf报错

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#135]
1 复现步骤：按照usage 
pip install magic-pdf[full-cpu]
pip install detectron2 --extra-index-url https://myhloli.github.io/wheels/
download models
cp magic-pdf.template.json ~/magic-pdf.json
magic-pdf pdf-command --pdf "pdf_path" --inside_model true
2. 报错截图
<img width="767" alt="企业微信截图_17208440979052" src="https://github.com/user-attachments/assets/8ba59f03-5cb5-4785-83a9-1455eed0074e">
<img width="762" alt="企业微信截图_17208441168347" src="https://github.com/user-attachments/assets/e06aa947-ad6b-4b70-8601-f12f1dd65949">

**Comment by dt-yy** [comment]
补充linux版本
Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018

**Comment by myhloli** [comment]
可能是设备系统硬件与paddlepaddle库不兼容，请尝试
```bash
pip uninstall paddlepaddle
pip install paddlepaddle==2.5.2
```

**Comment by anfernees-iphone** [comment]
> 可能是设备系统硬件与paddlepaddle库不兼容，请尝试
> 
> ```shell
> pip uninstall paddlepaddle
> pip install paddlepaddle==2.5.2
> ```

按这个执行了，还是报这个错误

**Comment by myhloli** [comment]
We update [0.6.2b1 release](https://github.com/opendatalab/MinerU/releases/tag/magic_pdf-0.6.2b1-released), solved this problem.
