### ISSUE TITLE
magic_pdf.libs.draw_bbox 和 magic_pdf.pipe.operators出现循环依赖问题

### ISSUE THREAD

**Issue by Rezen1997** [opendatalab/MinerU#1350]
### Description of the bug | 错误描述

您好，我再执行demo提供的magic_pdf_parse_main.py的时候，出现循环依赖问题，似乎是在 magic_pdf.libs.draw_bbox 和 magic_pdf.pipe.operators 两个模块之间存在相互导入。

所运行的命令：(pytorch_infer) root@1fba385f05a0:/home/llm# python magic_pdf_parse_main.py 

相关报错信息如下
/torch/venv3/pytorch_infer/lib/python3.10/site-packages/jupyter_client/connect.py:22: DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
given by the platformdirs library.  To remove this warning and
see the appropriate new directories, set the environment variable
`JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
The use of platformdirs will be the default in `jupyter_core` v6
  from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
<frozen importlib._bootstrap>:241: DeprecationWarning: builtin type SwigPyPacked has no __module__ attribute
<frozen importlib._bootstrap>:241: DeprecationWarning: builtin type SwigPyObject has no __module__ attribute
<frozen importlib._bootstrap>:241: DeprecationWarning: builtin type swigvarlink has no __module__ attribute
Traceback (most recent call last):
  File "/home/llm/magic_pdf_parse_main.py", line 10, in <module>
    from magic_pdf.libs.draw_bbox import draw_layout_bbox, draw_span_bbox
  File "/torch/venv3/pytorch_infer/lib/python3.10/site-packages/magic_pdf/libs/draw_bbox.py", line 6, in <module>
    from magic_pdf.model.magic_model import MagicModel
  File "/torch/venv3/pytorch_infer/lib/python3.10/site-packages/magic_pdf/model/__init__.py", line 7, in <module>
    from magic_pdf.pipe.operators import PipeResult
  File "/torch/venv3/pytorch_infer/lib/python3.10/site-packages/magic_pdf/pipe/operators.py", line 10, in <module>
    from magic_pdf.libs.draw_bbox import (draw_layout_bbox, draw_line_sort_bbox,
ImportError: cannot import name 'draw_layout_bbox' from partially initialized module 'magic_pdf.libs.draw_bbox' (most likely due to a circular import) (/torch/venv3/pytorch_infer/lib/python3.10/site-packages/magic_pdf/libs/draw_bbox.py)
/opt/py3.10/lib/python3.10/tempfile.py:860: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpm0oy1wo_'>
  _warnings.warn(warn_message, ResourceWarning)
sys:1: DeprecationWarning: builtin type swigvarlink has no __module__ attribute

### How to reproduce the bug | 如何复现

您好，我是在一个docker容器里面安装的MinerU，我这个容器里面创建并使用的虚拟环境，我参考您所提供的dockerfile中的命令来构建MinerU，使用的命令如下：

apt-get update
apt-get install -y software-properties-common
add-apt-repository ppa:deadsnakes/ppa
apt-get update
apt-get install -y  wget git libgl1  libglib2.0-0 

wget https://gitee.com/myhloli/MinerU/raw/master/requirements-docker.txt
pip install -r requirements-docker.txt --extra-index-url https://wheels.myhloli.com -i https://mirrors.aliyun.com/pypi/simple

wget https://gitee.com/myhloli/MinerU/raw/master/magic-pdf.template.json && cp magic-pdf.template.json /root/magic-pdf.json 
pip install -U magic-pdf

pip install modelscope
wget https://gitee.com/myhloli/MinerU/raw/master/scripts/download_models.py
python download_models.py

请问如何解决问题呢

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
现在没有magic_pdf_parse_main.py吧，那个是适配老版本的，现在新版本需要用新的demo代码，可以pull下仓库，看看新的demo
