### ISSUE TITLE
使用webapi接口解析pdf，返回的json数据markdown内容中有图片路径，使用什么方式下载？

### ISSUE THREAD

**Issue by czhcc** [opendatalab/MinerU#1353]
### Description of the bug | 错误描述

例如生成的md中有
images/03d0e73571baf0c8fac4d1504c4cd266d46cfb49373f15fab19ab8a6964abf0b.jpg

### How to reproduce the bug | 如何复现

如上所述

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by uniqueSkeeter** [comment]
一样遇到这个问题了，目前我们把容器里的app.py改改，看下能不能把图片文件也拿到

**Comment by czhcc** [comment]
暂时将app.py改了，将图片转为base64，用
(data:image/jpeg;base64,图片的Base64编码)
这样的markdown方式一起返回

**Comment by tiptinker** [comment]
> 暂时将app.py改了，将图片转为base64，用 (data:image/jpeg;base64,图片的Base64编码) 这样的markdown方式一起返回

这是什么意思呢，能具体一点吗？
