### ISSUE TITLE
请正式版本中避免使用 pre-release 依赖 | avoid using pre-release dependencies in the final version

### ISSUE THREAD

**Issue by hongbo-miao** [opendatalab/MinerU#1354]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**

Improvement request.

**Describe the solution you'd like**
**描述您期望的解决方案**

Just a suggestion: it would be great to avoid using pre-release dependencies like paddlepaddle 3.0.0b1 in the final version. Thanks!
一个小建议：正式版本中，请尽量避免使用像 paddlepaddle 3.0.0b1 这样的 pre-release 依赖。谢谢！☺️

**Describe alternatives you've considered**
Use pip or conda.

**Additional context**
**提供更多细节**

起因是在使用 [uv](https://github.com/astral-sh/uv) 安装时，碰到了问题 https://github.com/astral-sh/uv/issues/10138

**Comment by myhloli** [comment]
很遗憾，paddle框架在2.6.x正式版中存在无法解决的兼容性bug，导致在linux系统无法正常使用，因此magic-pdf会指定在linux中使用paddle的预发布版本，如果uv不支持，请使用pip安装。

**Comment by hongbo-miao** [comment]
多谢背景信息 @myhloli !

另外，其他人帮助我，终于成功了！我发在了 https://github.com/astral-sh/uv/issues/10138#issuecomment-2560915898

**Comment by hongbo-miao** [comment]
多谢背景信息 @myhloli !

uv 那边其他人帮助我，终于成功了！我发在了 https://github.com/opendatalab/MinerU/discussions/1374
