### ISSUE TITLE
zsh: illegal hardware instruction  magic-pdf -v

### ISSUE THREAD

**Issue by qizhezhiyue** [opendatalab/MinerU#1358]
### Description of the bug | 错误描述

按照官方步骤安装了MinerU，但执行magic-pdf -v，显示illegal hardware instruction。

### How to reproduce the bug | 如何复现

(MinerU-test) qizhezhi@qizhezhideMBP 01_DEV % uname -m
arm64

(MinerU-test) qizhezhi@qizhezhideMBP 01_DEV % conda info  

     active environment : MinerU-test
    active env location : /Users/qizhezhi/miniconda3/envs/MinerU-test
            shell level : 2
       user config file : /Users/qizhezhi/.condarc
 populated config files : /Users/qizhezhi/miniconda3/.condarc
          conda version : 24.9.2
    conda-build version : not installed
         python version : 3.12.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.9.2=0
                          __osx=10.16=0
                          __unix=0=0
       base environment : /Users/qizhezhi/miniconda3  (writable)
      conda av data dir : /Users/qizhezhi/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/qizhezhi/miniconda3/pkgs
                          /Users/qizhezhi/.conda/pkgs
       envs directories : /Users/qizhezhi/miniconda3/envs
                          /Users/qizhezhi/.conda/envs
               platform : osx-64
             user-agent : conda/24.9.2 requests/2.32.3 CPython/3.12.7 Darwin/23.6.0 OSX/10.16 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 501:20
             netrc file : None
           offline mode : False

(MinerU-test) qizhezhi@qizhezhideMBP 01_DEV % python3.10
Python 3.10.16 (main, Dec 11 2024, 10:24:41) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> print(platform.machine())
x86_64

conda list
magic-pdf                 0.10.6                   pypi_0    pypi

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
没看懂你的环境到底是arm64还是x8664，python版本是3.12还是3.10？

**Comment by qizhezhiyue** [comment]
问题解决了，conda非arm导致的。重新下载了一个conda ARM版即可。
判断方式：
conda info
platform : osx-64         非ARM版
platform : osx-arm64   ARM版
