### ISSUE TITLE
配置中有个人信息

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#136]
1. 执行 magic-pdf pdf-command --pdf "pdf_path" --inside_model true
2. 
<img width="666" alt="企业微信截图_17208447432228" src="https://github.com/user-attachments/assets/14e8ee8b-6461-4337-83a1-81cc5cd5f332">

**Comment by myhloli** [comment]
done
https://github.com/opendatalab/MinerU/commit/81260a22d7be9451d77bc22a30da0065409ba455
