### ISSUE TITLE
s3读写器对windows路径不兼容

### ISSUE THREAD

**Issue by guoguo0646** [opendatalab/MinerU#1368]
### Description of the bug | 错误描述

magic_pdf\data\data_reader_writer\multi_bucket_s3.py，代码文件142行：path = os.path.join(self.default_prefix, path)，在windows下会导致s3上的图片路径中包含"\"影响了image_path

### How to reproduce the bug | 如何复现

建议修改为：path = os.path.join(self.default_prefix, path).replace("\\", "/")

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by icecraft** [comment]
请上传一些错误截图

**Comment by icecraft** [comment]
也不对， `os.path.join` 是系统库函数。应该不会出现错误分割符的问题。可以提供一下错误的截图和 错误的路径？

**Comment by guoguo0646** [comment]
下图是生成的截图image在s3的结果：
![Snipaste_2024-12-27_16-48-50](https://github.com/user-attachments/assets/2b05c6c0-bb20-40d0-8f8f-574f5ce14fc4)

下图是debug的截图
![Snipaste_2024-12-27_16-48-14](https://github.com/user-attachments/assets/fb404cf8-af71-4c96-b960-bd77522c2f64)

**Comment by icecraft** [comment]
好的，先修复到 dev 分支

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/pull/1370
