### ISSUE TITLE
按照gpu方式安装，进入容器后，为什么显示bash: magic-pdf: command not found

### ISSUE THREAD

**Issue by asenasen123** [opendatalab/MinerU#1369]
### Description of the bug | 错误描述

按照gpu方式安装，进入容器后，为什么显示bash: magic-pdf: command not found

### How to reproduce the bug | 如何复现

wget https://github.com/opendatalab/MinerU/raw/master/Dockerfile
docker build -t mineru:latest .
docker run --rm -it --gpus=all mineru:latest /bin/bash
magic-pdf --help

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
进容器之后先执行一遍source /opt/mineru_venv/bin/activate，激活虚拟环境试试

**Comment by asenasen123** [comment]
可以了，多谢

**Comment by asenasen123** [comment]
> 进容器之后先执行一遍source /opt/mineru_venv/bin/activate，激活虚拟环境试试

可以了，多谢
