### ISSUE TITLE
解析性能优化

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#137]
21页的PDF我跑了6分钟左右，使用的cuda 12.2 加速，GPU是 NVIDIA A100 8卡
[pic-21page.pdf](https://github.com/user-attachments/files/16200937/pic-21page.pdf)

**Comment by myhloli** [comment]
<img width="881" alt="image" src="https://github.com/user-attachments/assets/1b37b9c1-f7b7-493b-9c7a-fc6b2669c4be">

为保证兼容性，ocr目前使用cpu方式实现，在本地物理机用时一分钟完成，性能效率在预期之中。
请自行检测服务器资源是否被其他进程占用导致运行效率较低。

**Comment by liuxu4567** [comment]
你好，请问后续ocr会有gpu方式实现的计划吗？cpu的方式确实挺慢的

**Comment by myhloli** [comment]
> 你好，请问后续ocr会有gpu方式实现的计划吗？cpu的方式确实挺慢的

ocr使用gpu加速的兼容性问题已经解决，但是需要更多的显存，非ocr情况下，需要8G，开启ocr需要12~16G.具体的安装配置流程会在晚些时候更新。

**Comment by wangc7681** [comment]
> > 你好，请问后续ocr会有gpu方式实现的计划吗？cpu的方式确实挺慢的
> 
> ocr使用gpu加速的兼容性问题已经解决，但是需要更多的显存，非ocr情况下，需要8G，开启ocr需要12~16G.具体的安装配置流程会在晚些时候更新。

这个是否有具体的教程部署GPU模式

**Comment by myhloli** [comment]
> > > 你好，请问后续ocr会有gpu方式实现的计划吗？cpu的方式确实挺慢的
> > 
> > 
> > ocr使用gpu加速的兼容性问题已经解决，但是需要更多的显存，非ocr情况下，需要8G，开启ocr需要12~16G.具体的安装配置流程会在晚些时候更新。
> 
> 这个是否有具体的教程部署GPU模式

https://github.com/opendatalab/MinerU/blob/master/README_zh-CN.md#%E4%BD%BF%E7%94%A8gpu

根据自己的系统选择合适的教程
