### ISSUE TITLE
并发请求paddle报错，index is out of bounds

### ISSUE THREAD

**Issue by semi-yuhao** [opendatalab/MinerU#1378]
### Description of the bug | 错误描述

在将mineru部署为fast api服务，并同时处理多个请求时，偶发报错
![image](https://github.com/user-attachments/assets/7858718a-0738-4b14-97d7-d0bd77379194)
paddleocr官方有相关issue，https://github.com/PaddlePaddle/PaddleOCR/issues/9056，但是加线程锁未能解决问题

### How to reproduce the bug | 如何复现

在将mineru部署为fast api服务，并同时处理多个请求时，偶发报错
![image](https://github.com/user-attachments/assets/92739f3e-28cd-417f-a983-2522f094ebb6)
![image](https://github.com/user-attachments/assets/8100c26a-69f6-4a0f-9f60-a5c84987a24e)
![image](https://github.com/user-attachments/assets/f1939f65-3858-4397-a4a1-fb2015e6a02a)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
不要尝试通过多线程调用本项目，如果有并发需求，请使用多进程作为后端，再使用负载均衡作任务分发

**Comment by semi-yuhao** [comment]
> 不要尝试通过多线程调用本项目，如果有并发需求，请使用多进程作为后端，再使用负载均衡作任务分发

好的，感谢反馈，请问在原理上多线程会有什么问题吗？

**Comment by myhloli** [comment]
paddleocr不支持多线程，即使使用技巧让项目勉强在多线程环境运行起来，运行速度不会有任何提升。比如一个线程执行10次和5个线程执行2次或是10个线程执行1次的耗时是完全相同的。

**Comment by semi-yuhao** [comment]
> paddleocr不支持多线程，即使使用技巧让项目勉强在多线程环境运行起来，运行速度不会有任何提升。比如一个线程执行10次和5个线程执行2次或是10个线程执行1次的耗时是完全相同的。

感谢解答
