### ISSUE TITLE
yolo_v8_ft.pt在哪里可以找到

### ISSUE THREAD

**Issue by asenasen123** [opendatalab/MinerU#1381]
### Description of the bug | 错误描述

yolo_v8_ft.pt在哪里可以找到

### How to reproduce the bug | 如何复现

yolo_v8_ft.pt在哪里可以找到

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
看下readme里下载模型那段的说明
