### ISSUE TITLE
object of type 'ABCMeta' has no len()

### ISSUE THREAD

**Issue by asenasen123** [opendatalab/MinerU#1382]
### Description of the bug | 错误描述

object of type 'ABCMeta' has no len()

### How to reproduce the bug | 如何复现

object of type 'ABCMeta' has no len()

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/issues/1305
