### ISSUE TITLE
[问题] 如何将结果输出为HTML

### ISSUE THREAD

**Issue by solarhell** [opendatalab/MinerU#1383]
目前看到代码中dict2md包是负责将结果转换为markdown，如果需要拓展项目将结果转换为HTML，是自行将markdown结果转为HTML吗？是否有可以拓展的地方

**Comment by myhloli** [comment]
比较简单的方式就是调用pandoc将markdown转换成html

**Comment by solarhell** [comment]
试过确实可用，如果要追求精细化控制可以参考源码，自己对middle.json做处理生成HTML。
