### ISSUE TITLE
Windows install magic-pdf 問題

### ISSUE THREAD

**Issue by greedtea** [opendatalab/MinerU#142]
執行步驟
conda create -n MinerU python=3.10
conda activate MinerU
pip install magic-pdf[full-cpu]
pip install detectron2 --extra-index-url https://myhloli.github.io/wheels/
git lfs clone https://huggingface.co/wanderkid/PDF-Extract-Kit

windows 在哪個根目錄執行?
copy magic-pdf.template.json ~/magic-pdf.json

在c槽下 搜尋 magic-pdf.template.json
找不到任何檔案

![2024-07-14 14 09 32](https://github.com/user-attachments/assets/b50a1d8c-b7e5-46f5-a8d3-d54aff1f9c1f)

**Comment by myhloli** [comment]
在仓库根目录可以下载

**Comment by greedtea** [comment]
那下載後要放在哪裡?

C:\Users\User\anaconda3\envs\MinerU\Lib\site-packages\magic_pdf
or
C:\Users\User\PDF-Extract-Kit

哪一個目錄?

**Comment by myhloli** [comment]
执行命令

cp magic-pdf.template.json ~/magic-pdf.json
会拷贝到用户根目录

**Comment by greedtea** [comment]
copy magic-pdf.template.json C:\Users\xxxx\magic-pdf.json
magic-pdf pdf-command --pdf "Z:\aa\test.pdf" --inside_model true
正常執行

測試cpu 大約1分鐘 跟 cuda 大約3x秒
謝謝 myhloli
