### ISSUE TITLE
表格被当成图片了，无法解析。markdown中的标题层级都是同一级，没有正确识别

### ISSUE THREAD

**Issue by charliedream1** [opendatalab/MinerU#145]
### Description of the bug | 错误描述

表格被当成图片了，无法解析。markdown中的标题层级都是同一级，没有正确识别

### How to reproduce the bug | 如何复现

表格被当成图片了，无法解析。markdown中的标题层级都是同一级，没有正确识别

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
符合预期，表格解析有计划更新，标题识别暂时没有多级识别计划
