### ISSUE TITLE
你好，我遇到有些PDF可以解析，有的pdf文件报错

### ISSUE THREAD

**Issue by xuquankun** [opendatalab/MinerU#146]
### Description of the bug | 错误描述

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::framework::ir::SelfAttentionFusePass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::framework::ir::GraphPatternDetector::operator()(paddle::framework::ir::Graph*, std::function<void (std::map<paddle::framework::ir::PDNode*, paddle::framework::ir::Node*, paddle::framework::ir::GraphPatternDetector::PDNodeCompare, std::allocator<std::pair<paddle::framework::ir::PDNode* const, paddle::framework::ir::Node*> > > const&, paddle::framework::ir::Graph*)>)

----------------------
Error Message Summary:
----------------------
FatalError: `Illegal instruction` is detected by the operating system.
  [TimeInfo: *** Aborted at 1721031085 (unix time) try "date -d @1721031085" if you are using GNU date ***]
  [SignalInfo: *** SIGILL (@0x7f95b6ffa13a) received by PID 20020 (TID 0x7f96f055d180) from PID 18446744072484790586 ***]

非法指令 (核心已转储)

### How to reproduce the bug | 如何复现

按照最新配置好环境之后执行
magic-pdf pdf-command --pdf ../1.pdf  --inside_model true
有的文件会报核心已转储 的错误

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
需要上传产生报错的pdf文档进行复现验证

**Comment by xuquankun** [comment]
> 需要上传产生报错的pdf文档进行复现验证

[1.pdf](https://github.com/user-attachments/files/16231803/1.pdf)

**Comment by myhloli** [comment]
@xuquankun 看了下这个文档需要ocr，ocr目前使用的是paddleocr，paddleocr的依赖库paddlepaddle在某些linux版本存在不兼容的问题，可以参考https://github.com/opendatalab/MinerU/issues/135 试着给paddlepaddle降级看看能不能解决。

**Comment by myhloli** [comment]
如果降级paddlepaddle解决不了的话，可以尝试安装gpu版本的paddle
```bash
pip uninstall paddlepaddle
pip install paddlepaddle-gpu
```

**Comment by x19990416** [comment]
> 如果降级paddlepaddle解决不了的话，可以尝试安装gpu版本的paddle
> 
> ```shell
> pip uninstall paddlepaddle
> pip install paddlepaddle-gpu
> ```

我尝试了cpu和gpu的最新版和2.5.2 两个版本都是一样报错

**Comment by myhloli** [comment]
> > 如果降级paddlepaddle解决不了的话，可以尝试安装gpu版本的paddle
> > ```shell
> > pip uninstall paddlepaddle
> > pip install paddlepaddle-gpu
> > ```
> 
> 我尝试了cpu和gpu的最新版和2.5.2 两个版本都是一样报错

update to 3.0.0b1

https://github.com/opendatalab/MinerU/blob/master/docs/FAQ_zh_cn.md#5使用过程中遇到paddle相关的报错fatalerror-illegal-instruction-is-detected-by-the-operating-system

**Comment by clareliu1234** [comment]
楼主正确识别了pdf内容吗？我也遇到这种情况，pdf的文本识别出来是乱码
