### ISSUE TITLE
不能从HF下载权重，可以支持国内的modelscope吗？

### ISSUE THREAD

**Issue by wangzuohao** [opendatalab/MinerU#147]
### Description of the bug | 错误描述

我们的公司网络是在国内的，合规要求比较高，所以不能连HF，是否可以把模型权重上传到国内的平台？

### How to reproduce the bug | 如何复现

我们的公司网络是在国内的，合规要求比较高，所以不能连HF，是否可以把模型权重上传到国内的平台？

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
稍晚我们会在modelscope上传，上传完成后会更新文档。

**Comment by wangbinDL** [comment]
文档已更新， 请查看 [https://github.com/opendatalab/MinerU/blob/master/docs/how_to_download_models_zh_cn.md ](https://github.com/opendatalab/MinerU/blob/master/docs/how_to_download_models_zh_cn.md )
