### ISSUE TITLE
并没有找到tmp文件夹

### ISSUE THREAD

**Issue by a136214808** [opendatalab/MinerU#149]
### Description of the bug | 错误描述

<img width="482" alt="捕获" src="https://github.com/user-attachments/assets/697e1a5b-4904-463d-9c26-ef4e396b5515">
当代码执行完之后并没有 tmp的临时文件夹出现，不知道是不是我的操作有误还是其他原因

### How to reproduce the bug | 如何复现

直接执行代码

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
在某些系统上gui的文件管理器上tmp目录不直接可见，请在程序执行完毕后
```bash
cd /tmp
ls
```
确认是否存在magic-pdf目录
