### ISSUE TITLE
折行的单词有连接符且没有拼接

### ISSUE THREAD

**Issue by yiyibooks** [opendatalab/MinerU#150]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/363f9ffe-bff4-4d3d-a5c2-9de96e8b2dcb)

![image](https://github.com/user-attachments/assets/03851ead-cca4-495e-9fb1-fd57e774fc64)

如上图，在 PDF 文档里，如果一行文本的最后一个单词分在两行显示，会在行尾加上 '-' 连接符号。
转换成 Markdown 之后，'-' 连接符号依然纯在，单词被 '-' 加一个空白分开。

### How to reproduce the bug | 如何复现

可以使用这个 https://arxiv.org/pdf/2407.01906 pdf 复现

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
拼接逻辑没考虑到这种情况，后续可以排期开发

**Comment by kv1830** [comment]
论文里面基本都会是这种排版，即双列、破折号连接换行的词。这个功能是不是也不会非常复杂?
1.搞一个词典
2.换行处如果有破折号，去词典里查一下有没有这个词（带破折号）
→有：确认带破折号
→无：去词典里查去掉破折号的词
→→有：确认不带破折号
→→无：去词典里分别查破折号拆分的两个词
→→→都有：确认带破折号
→→→否则：确认不带破折号（此块还可以再补充，比如直接由大模型判断一下，是否人名、地名、专有名词等）

**Comment by myhloli** [comment]
0.8+的版本已经解决该问题
