### ISSUE TITLE
SDK不能使用GPU模型

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#151]
### Description of the bug | 错误描述

<img width="450" alt="企业微信截图_1721044200913" src="https://github.com/user-attachments/assets/8dfe8d88-e0b9-41af-ab20-f43be885389d">
<img width="860" alt="企业微信截图_17210441867202" src="https://github.com/user-attachments/assets/4ec04c03-87a1-430d-b719-bfe7f9b68693">

### How to reproduce the bug | 如何复现

<img width="450" alt="企业微信截图_1721044200913" src="https://github.com/user-attachments/assets/8dfe8d88-e0b9-41af-ab20-f43be885389d">

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
demo已更新：
https://github.com/opendatalab/MinerU/commit/b77ac5767614774696cd89f9b7496b6bb612eb61
https://github.com/opendatalab/MinerU/commit/30f06136ecd822cec760f8b88faa9eb302cfbcd7
