### ISSUE TITLE
magic-pdf pdf-command --pdf "pdf_path" --inside_model true报错

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#154]
### Description of the bug | 错误描述

<img width="833" alt="企业微信截图_17210956733839" src="https://github.com/user-attachments/assets/45122f50-a2ba-4772-b5d2-9b6eeb0b4c39">

### How to reproduce the bug | 如何复现

1. pip install magic-pdf[full-cpu]
2. pip install detectron2 --extra-index-url https://myhloli.github.io/wheels/
3. Downloading model weights files
4. pip install --force-reinstall torch==2.3.1 torchvision==0.18.1 --index-url https://download.pytorch.org/whl/cu118
5. magic-pdf pdf-command --pdf "pdf_path" --inside_model true

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.9

### Device mode | 设备模式

cuda

**Comment by xiaobai-marker** [comment]
我的python版本是win10  依然报了一样的错误

**Comment by myhloli** [comment]
> 我的python版本是win10  依然报了一样的错误

使用命令 magic-pdf --version看看应用版本号是不是0.6.0或者0.6.1，如果不是的话需要更新一下pip源

**Comment by xiaobai-marker** [comment]
> > 我的python版本是win10  依然报了一样的错误
> 
> 使用命令 magic-pdf --version看看应用版本号是不是0.6.0或者0.6.1，如果不是的话需要更新一下pip源

版本是0.5.3，但是我把pip更新到最新之后，安装的版本依然是0.5.3

**Comment by xiaobai-marker** [comment]
> > > 我的python版本是win10  依然报了一样的错误
> > 
> > 
> > 使用命令 magic-pdf --version看看应用版本号是不是0.6.0或者0.6.1，如果不是的话需要更新一下pip源
> 
> 版本是0.5.3，但是我把pip更新到最新之后，安装的版本依然是0.5.3

0.5.13

**Comment by myhloli** [comment]
> > > > 我的python版本是win10  依然报了一样的错误
> 
> > > 
> 
> > > 
> 
> > > 使用命令 magic-pdf --version看看应用版本号是不是0.6.0或者0.6.1，如果不是的话需要更新一下pip源
> 
> > 
> 
> > 版本是0.5.3，但是我把pip更新到最新之后，安装的版本依然是0.5.3
> 
> 
> 
> 0.5.13

你使用的镜像源没能同步，建议使用pypi官方源试试

**Comment by EthanChinaHuang** [comment]
Ubuntu 22.04 + Python 3.10 + magic-pdf version 0.6.1
同样是报错  Required dependency not installed ...

**Comment by myhloli** [comment]
> Ubuntu 22.04 + Python 3.10 + magic-pdf version 0.6.1
> 
> 同样是报错  Required dependency not installed ...

这是另一个问题，依赖没有完整安装，导致缺失依赖库

**Comment by EthanChinaHuang** [comment]
> > Ubuntu 22.04 + Python 3.10 + magic-pdf version 0.6.1
> > 同样是报错  Required dependency not installed ...
> 
> 这是另一个问题，依赖没有完整安装，导致缺失依赖库

import cv2 报错导致的，pip install opencv-contrib-python-headless 之后正常了

**Comment by myhloli** [comment]
> > > > 我的python版本是win10  依然报了一样的错误
> > > 
> > > 
> > > 使用命令 magic-pdf --version看看应用版本号是不是0.6.0或者0.6.1，如果不是的话需要更新一下pip源
> > 
> > 
> > 版本是0.5.3，但是我把pip更新到最新之后，安装的版本依然是0.5.3
> 
> 0.5.13

通过测试，发现在某些设备上可能由于依赖冲突导致无法安装0.6.x版本，pip会自动帮用户安装0.5.13版本
可以参考 https://github.com/opendatalab/MinerU/blob/master/docs/FAQ_zh_cn.md#3%E5%9C%A8intel-cpu-%E7%9A%84mac%E4%B8%8A-%E5%AE%89%E8%A3%85%E6%9C%80%E6%96%B0%E7%89%88%E7%9A%84-magic-pdffull-cpu-061-%E4%B8%8D%E6%88%90%E5%8A%9F 这个流程尝试使用全新环境逐步安装依赖

**Comment by JustStare** [comment]
2024-07-25 08:55:23.438 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:24 - Required dependency not installed, please install by 
"pip install magic-pdf[full-cpu] detectron2 --extra-index-url https://myhloli.github.io/wheels/"
(MinerU) xiaoi@xiaoi-7061:/opt/huashi/pdf_path$ magic-pdf --version
magic-pdf, version 0.6.1
我的版本是0.6.1 也有这个问题

**Comment by JustStare** [comment]
我也是这个问题

**Comment by forlifeproj** [comment]
> > > 我的python版本是win10  依然报了一样的错误
> > 
> > 
> > 使用命令 magic-pdf --version看看应用版本号是不是0.6.0或者0.6.1，如果不是的话需要更新一下pip源
> 
> 版本是0.5.3，但是我把pip更新到最新之后，安装的版本依然是0.5.3

我这也是

**Comment by myhloli** [comment]
We have updated to the [0.6.2b1 release](https://github.com/opendatalab/MinerU/releases/tag/magic_pdf-0.6.2b1-released), addressing and resolving the aforementioned issue.

**Comment by zooooooly** [comment]
> > > Ubuntu 22.04 + Python 3.10 + magic-pdf version 0.6.1
> > > 同样是报错  Required dependency not installed ...
> > 
> > 
> > 这是另一个问题，依赖没有完整安装，导致缺失依赖库
> 
> import cv2 报错导致的，pip install opencv-contrib-python-headless 之后正常了

安装之后会报错AttributeError: `np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead.，我尝试将版本降低又会报错Required dependency not installed, please install by
"pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/"

**Comment by myhloli** [comment]
> > > > Ubuntu 22.04 + Python 3.10 + magic-pdf version 0.6.1
> > > > 同样是报错  Required dependency not installed ...
> > > 
> > > 
> > > 这是另一个问题，依赖没有完整安装，导致缺失依赖库
> > 
> > 
> > import cv2 报错导致的，pip install opencv-contrib-python-headless 之后正常了
> 
> 安装之后会报错AttributeError: `np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead.，我尝试将版本降低又会报错Required dependency not installed, please install by "pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/"

NumPy 需要安装小于2.0的版本，报错请把详细堆栈信息发出来
