### ISSUE TITLE
运行demo报错

### ISSUE THREAD

**Issue by fanzz1** [opendatalab/MinerU#155]
### Description of the bug | 错误描述

2024-07-16 11:22:00.324 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 14, text_len: 26394, cid_chars_radio: 0.0005324003650745361
2024-07-16 11:22:00.329 | ERROR    | magic_pdf.user_api:parse_pdf:85 - list index out of range
Traceback (most recent call last):

  File "E:\MinerU-master\demo\demo.py", line 23, in <module>
    pipe.pipe_parse()
    │    └ <function UNIPipe.pipe_parse at 0x000001FE33EDD990>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001FE03BA2DD0>

  File "E:\MinerU-master\magic_pdf\pipe\UNIPipe.py", line 35, in pipe_parse
    self.pdf_mid_data = parse_union_pdf(self.pdf_bytes, self.model_list, self.image_writer,
    │    │              │               │    │          │    │           │    └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x000001FE03BA2E60>
    │    │              │               │    │          │    │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001FE03BA2DD0>
    │    │              │               │    │          │    └ []
    │    │              │               │    │          └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001FE03BA2DD0>
    │    │              │               │    └ b'%PDF-1.5\r%\x80\x84\x88\x8c\x90\x94\x98\x9c\xa0\xa4\xa8\xac\xb0\xb4\xb8\xbc\xc0\xc4\xc8\xcc\xd0\xd4\xd8\xdc\xe0\xe4\xe8\xec...
    │    │              │               └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001FE03BA2DD0>
    │    │              └ <function parse_union_pdf at 0x000001FE33EDD750>
    │    └ None
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001FE03BA2DD0>

  File "E:\MinerU-master\magic_pdf\user_api.py", line 88, in parse_union_pdf
    pdf_info_dict = parse_pdf(parse_pdf_by_txt)
                    │         └ <function parse_pdf_by_txt at 0x000001FE33EDD630>
                    └ <function parse_union_pdf.<locals>.parse_pdf at 0x000001FE037F3E20>

> File "E:\MinerU-master\magic_pdf\user_api.py", line 77, in parse_pdf
    return method(
           └ <function parse_pdf_by_txt at 0x000001FE33EDD630>

  File "E:\MinerU-master\magic_pdf\pdf_parse_by_txt.py", line 12, in parse_pdf_by_txt
    return pdf_parse_union(pdf_bytes,
           │               └ b'%PDF-1.5\r%\x80\x84\x88\x8c\x90\x94\x98\x9c\xa0\xa4\xa8\xac\xb0\xb4\xb8\xbc\xc0\xc4\xc8\xcc\xd0\xd4\xd8\xdc\xe0\xe4\xe8\xec...
           └ <function pdf_parse_union at 0x000001FE33EDD5A0>

  File "E:\MinerU-master\magic_pdf\pdf_parse_union_core.py", line 225, in pdf_parse_union
    page_info = parse_page_core(pdf_docs, magic_model, page_id, pdf_bytes_md5, imageWriter, parse_mode)
                │               │         │            │        │              │            └ 'txt'
                │               │         │            │        │              └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x000001FE03BA2E60>
                │               │         │            │        └ '036C1D1F6867C983E74EEA67B33E09D6'
                │               │         │            └ 0
                │               │         └ <magic_pdf.model.magic_model.MagicModel object at 0x000001FE354A3970>
                │               └ Document('', <memory, doc# 4>)
                └ <function parse_page_core at 0x000001FE33EDD510>

  File "E:\MinerU-master\magic_pdf\pdf_parse_union_core.py", line 83, in parse_page_core
    img_blocks = magic_model.get_imgs(page_id)
                 │           │        └ 0
                 │           └ <function MagicModel.get_imgs at 0x000001FE316320E0>
                 └ <magic_pdf.model.magic_model.MagicModel object at 0x000001FE354A3970>

  File "E:\MinerU-master\magic_pdf\model\magic_model.py", line 459, in get_imgs
    records, _ = self.__tie_up_category_by_distance(page_no, 3, 4)
                 │                                  └ 0
                 └ <magic_pdf.model.magic_model.MagicModel object at 0x000001FE354A3970>

  File "E:\MinerU-master\magic_pdf\model\magic_model.py", line 186, in __tie_up_category_by_distance
    self.__model_list[page_no]["layout_dets"],
    │                 └ 0
    └ <magic_pdf.model.magic_model.MagicModel object at 0x000001FE354A3970>

IndexError: list index out of range
2024-07-16 11:22:00.390 | WARNING  | magic_pdf.user_api:parse_union_pdf:90 - parse_pdf_by_txt drop or error, switch to parse_pdf_by_ocr
2024-07-16 11:22:00.390 | ERROR    | magic_pdf.model.doc_analyze_by_custom_model:custom_model_init:92 - use_inside_model is False, not allow to use inside model

进程已结束,退出代码1

### How to reproduce the bug | 如何复现

1

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
不好意思，文档忘了改了，代码中先加入写两行可以解决

import magic_pdf.model as model_config model_config.__use_inside_model__ = True

**Comment by myhloli** [comment]
demo已修复

**Comment by fanzz1** [comment]
仍然报同样的错误

**Comment by myhloli** [comment]
> 仍然报同样的错误

有试过命令行使用正常吗？

**Comment by fanzz1** [comment]
是否是因为我的权重文件放置位置有错误
当我在命令行中运行：magic-pdf pdf-command --pdf "1.pdf" --inside_model true
报错：FileNotFoundError: [Errno 2] No such file or directory: '\\tmp\\models\\MFD\\weights.pt'
可是我已经下载了权重文件，按照说明我是不是应该将模型文件放在图示位置呢？
![微信截图_20240716152903](https://github.com/user-attachments/assets/72668dab-6eca-4300-89e3-2f776671d48f)
谢谢！

**Comment by myhloli** [comment]
模型路径应为绝对路径，你可以cd到这个路径下pwd一下，看看绝对路径，再配置magic-pdf.json

**Comment by Jamly7** [comment]
增加了那两行代码后，仍然报错，并且use_inside_model依然是False，但我两行代码后，打印了use_inside_mode为True，(MinerU) root@quantum-slaver2:~/lh/MinerU# python3 MinerU.py 
True
2024-07-16 08:03:20.043 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 27, text_len: 8790, cid_chars_radio: 0.0031690140845070424
2024-07-16 08:03:20.056 | ERROR    | magic_pdf.user_api:parse_pdf:85 - list index out of range。代码如下：import os
import json

from loguru import logger

from magic_pdf.pipe.UNIPipe import UNIPipe
from magic_pdf.rw.DiskReaderWriter import DiskReaderWriter

import magic_pdf.model as model_config
model_config.use_inside_model = True

print(model_config.use_inside_model)

**Comment by Jamly7** [comment]
应该是model_config.__use_inside_model__ = True;少两个下划线

**Comment by myhloli** [comment]
> 应该是model_config.__use_inside_model__ = True;少两个下划线

你是对的，被markdown转义了
```python
model_config.__use_inside_model__ = True;
```

**Comment by ShadowCabnient** [comment]
> 是否是因为我的权重文件放置位置有错误 当我在命令行中运行：magic-pdf pdf-command --pdf "1.pdf" --inside_model true 报错：FileNotFoundError: [Errno 2] No such file or directory: '\tmp\models\MFD\weights.pt' 可是我已经下载了权重文件，按照说明我是不是应该将模型文件放在图示位置呢？ ![微信截图_20240716152903](https://private-user-images.githubusercontent.com/95949202/348984554-72668dab-6eca-4300-89e3-2f776671d48f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTg4NDYsIm5iZiI6MTcyMTcxODU0NiwicGF0aCI6Ii85NTk0OTIwMi8zNDg5ODQ1NTQtNzI2NjhkYWItNmVjYS00MzAwLTg5ZTMtMmY3NzY2NzFkNDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA3MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMGM0ODcxMjgyMjU2ZmQwMmY1ZmNlZWUxZDQ1OTEwOTEyMzg3Yjg3MmM1OGQxZWM3Mjk1NDBlZTkxZjc2ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yd62_XGmEpVxQhrTFHrOYlFnUPb2Kt2w4Ow--4pCB5E) 谢谢！

我的是windows系统运行的，也是报这个错误，cp 那一步看不明白意义是什么

**Comment by myhloli** [comment]
> > 是否是因为我的权重文件放置位置有错误 当我在命令行中运行：magic-pdf pdf-command --pdf "1.pdf" --inside_model true 报错：FileNotFoundError: [Errno 2] No such file or directory: '\tmp\models\MFD\weights.pt' 可是我已经下载了权重文件，按照说明我是不是应该将模型文件放在图示位置呢？ ![微信截图_20240716152903](https://private-user-images.githubusercontent.com/95949202/348984554-72668dab-6eca-4300-89e3-2f776671d48f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTg4NDYsIm5iZiI6MTcyMTcxODU0NiwicGF0aCI6Ii85NTk0OTIwMi8zNDg5ODQ1NTQtNzI2NjhkYWItNmVjYS00MzAwLTg5ZTMtMmY3NzY2NzFkNDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA3MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMGM0ODcxMjgyMjU2ZmQwMmY1ZmNlZWUxZDQ1OTEwOTEyMzg3Yjg3MmM1OGQxZWM3Mjk1NDBlZTkxZjc2ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yd62_XGmEpVxQhrTFHrOYlFnUPb2Kt2w4Ow--4pCB5E) 谢谢！
> 
> 我的是windows系统运行的，也是报这个错误，cp 那一步看不明白意义是什么

图没上传成功。。。

ps ：cp那一步是拷贝默认配置文件到你的user目录，程序后面很多运行参数需要读取这个配置文件。
windows可以在powershell中执行cp命令的。

**Comment by Sep24thLegend** [comment]
![image](https://github.com/user-attachments/assets/b1d8eb93-c91c-4c0f-bd7c-f52375492c4a)
下载好模型权重文件后，配置文件magic-pdf.json中的路径地址是要自己手动改一下嘛，还有模型权重文件的默认下载路径如上，需要跟自己待检测的pdf文件和输出的模型文件放在一个文件夹下嘛？

**Comment by myhloli** [comment]
> ![image](https://private-user-images.githubusercontent.com/185342677/382474062-b1d8eb93-c91c-4c0f-bd7c-f52375492c4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTM4NDYsIm5iZiI6MTczMDU1MzU0NiwicGF0aCI6Ii8xODUzNDI2NzcvMzgyNDc0MDYyLWIxZDhlYjkzLWM5MWMtNGMwZi1iZDdjLWY1MjM3NTQ5MmM0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMzE5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjIxMjVjNzc5Y2ZjZTliODc0ZjIwNWFhMGIzOGRkODY4YzY5N2IzZTQ1ZmJiMTMwNTgxODhmZmU0ZTVkZWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gqzsn63j8O7SfvKAKtPSLIII3Hw-UxKuXBXdarSv4FM) 下载好模型权重文件后，配置文件magic-pdf.json中的路径地址是要自己手动改一下嘛，还有模型权重文件的默认下载路径如上，需要跟自己待检测的pdf文件和输出的模型文件放在一个文件夹下嘛？

不需要改json里的路径，下载完成后就已经自动配置好了，模型文件也不需要移动位置，直接按教程下一步就行

**Comment by Sep24thLegend** [comment]
![image](https://github.com/user-attachments/assets/c6294731-31b4-484e-abd3-87fc22c86ba5)
求教这种情况是什么原因呢

**Comment by myhloli** [comment]
路径不要用{}包裹，所有的`\`换成`/`

**Comment by Sep24thLegend** [comment]
已解决（抱拳，多谢~）
