### ISSUE TITLE
输出的json是无序的，如何按照版面分析的顺序输出

### ISSUE THREAD

**Issue by 3030373635** [opendatalab/MinerU#156]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
对存在的问题进行清晰且简洁的描述。例如：我一直很困扰的是 [...]

**Describe the solution you'd like**
**描述您期望的解决方案**
清晰且简洁地描述您希望实现的内容。

**Describe alternatives you've considered**
**描述您已考虑的替代方案**
清晰且简洁地描述您已经考虑过的任何替代解决方案。

**Additional context**
**提供更多细节**
请附上任何相关截图、链接或文件，以帮助我们更好地理解您的请求。

**Comment by myhloli** [comment]
命令行执行完会有几个json文件，您说的是哪个json呢

**Comment by 3030373635** [comment]
> 命令行执行完会有几个json文件，您说的是哪个json呢

输出结果的那个json

**Comment by 3030373635** [comment]
> 命令行执行完会有几个json文件，您说的是哪个json呢

issue提错仓库了，是PDF-Extract-Kit这个仓库

**Comment by myhloli** [comment]
> > 命令行执行完会有几个json文件，您说的是哪个json呢
> 
> 
> 
> 输出结果的那个json

模型输出的结果是无序的，需要在mineru项目的pipeline中重组，你用mineru命令行试试，输出目录里会有几个json，应该会有你想要的

**Comment by 3030373635** [comment]
> > > 命令行执行完会有几个json文件，您说的是哪个json呢
> > 
> > 
> > 输出结果的那个json
> 
> 模型输出的结果是无序的，需要在mineru项目的pipeline中重组，你用mineru命令行试试，输出目录里会有几个json，应该会有你想要的

如何重组，有示例吗

**Comment by myhloli** [comment]
可以参考本项目cli/magicpdf.py中的实现

**Comment by 3030373635** [comment]
<img width="911" alt="Snipaste_2024-07-16_14-48-13" src="https://github.com/user-attachments/assets/4ed42e4f-103d-4e7e-90d3-3e51670a397d">
双栏被识别成ocr_text有问题吗，什么样子会被识别成这个类型。

**Comment by myhloli** [comment]
> <img width="911" alt="Snipaste_2024-07-16_14-48-13" src="https://github.com/user-attachments/assets/4ed42e4f-103d-4e7e-90d3-3e51670a397d">
> 
> 双栏被识别成ocr_text有问题吗，什么样子会被识别成这个类型。

符合预期
