### ISSUE TITLE
如何批量解析多个pdf文件

### ISSUE THREAD

**Issue by chosenduke** [opendatalab/MinerU#161]
有没有类似marker的那种命令，可以直接把一个文件夹内的pdf都解析出来，存入另一个文件夹中，开启多个worker加速，顺便这个项目有微信群可以添加吗，谢谢大佬！

**Comment by myhloli** [comment]
master分支已添加批量处理本地文件功能，pypi包要等发版release，如果急用可以clone仓库通过源码安装并使用。微信加opendatalab_yunying为好友，可以让她拉你进群讨论

**Comment by chosenduke** [comment]
是quyuan-01-patch1这个branch吗

**Comment by chosenduke** [comment]
> master分支已添加批量处理本地文件功能，pypi包要等发版release，如果急用可以clone仓库通过源码安装并使用。微信加opendatalab_yunying为好友，可以让她拉你进群讨论

是quyuan-01-patch1这个branch吗

**Comment by myhloli** [comment]
@chosenduke 不是，就是你直接clone的主分支

**Comment by chosenduke** [comment]
> @chosenduke 不是，就是你直接clone的主分支

感谢大佬，我已经git clone好了，是在哪个py文件里设置批量解析呢，谢谢！

**Comment by myhloli** [comment]
@chosenduke 和readme中使用命令行方式一致，--pdf 传入参数为xxx.list格式的list文件，list文件每行都是一个本地pdf的绝对路径即可

**Comment by myhloli** [comment]
参考：https://github.com/opendatalab/MinerU/commit/13788ca1ccde67aa3b7bb315ae5cd97c336883dd

**Comment by chosenduke** [comment]
> 参考：[13788ca](https://github.com/opendatalab/MinerU/commit/13788ca1ccde67aa3b7bb315ae5cd97c336883dd)

![image](https://github.com/user-attachments/assets/20a1b407-0808-45ca-9855-df9b5c53e972)
我这边还是报错了

**Comment by myhloli** [comment]
你这没有调用到clone的新代码，运行的还是pypi包中的逻辑，需要先卸载之后再通过源码安装
```bash
pip uninstall magic-pdf
python setup.py install
```

**Comment by HaoRenkk123** [comment]
可否出一个python批量处理pdf文件的脚本不依赖命令行的demo呢

**Comment by SaraiQX** [comment]
可否出一个python批量处理pdf文件的脚本不依赖命令行的demo呢  +1 感谢大佬
