### ISSUE TITLE
通过python调用时 每次识别都需要加载模型，能否将模型的加载分离出来，在外层加载模型，然后预测。这样就不必每预测一个都加载一遍模型了。

### ISSUE THREAD

**Issue by iwanglei1** [opendatalab/MinerU#164]
将模型的加载从代码中分离出来，作为参数传递

**Comment by myhloli** [comment]
模型加载已经做了单例，代码已经push到仓库了，只是还没有打release

**Comment by iwanglei1** [comment]
Thanks for your support. good night.获取Outlook for Android发件人: ***@***.*** ***@***.***> 代表 Xiaomeng Zhao ***@***.***>发送时间: 星期四, 七月 18, 2024 12:40:51 上午收件人: opendatalab/MinerU ***@***.***>抄送: iwanglei1 ***@***.***>; Author ***@***.***>主题: =?UTF-8?B?UmU6IFtvcGVuZGF0YWxhYi9NaW5lclVdIOmAmui/h3B5dGhvbuiwg+eUqOaXtiDmr4/mrKHor4bliKvpg73pnIDopoHliqDovb3mqKHlnovvvIzog73lkKblsIbmqKHlnovnmoTliqDovb3liIbnprvlh7rmnaXvvIzlnKjlpJblsYLliqDovb3mqKHlnovvvIznhLblkI7pooTmtYvjgILov5nmoLflsLHkuI3lv4Xmr4/pooTmtYvkuIDkuKrpg73liqDovb3kuIDpgY3mqKHlnovkuobjgIIgKElzc3VlICMxNjQp?=
模型加载已经做了单例，代码已经push到仓库了，只是还没有打release

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/commit/054abe33d6342c82d269a10027fd34a642133df5

**Comment by iwanglei1** [comment]
单例模式不支持fastapi模式的部署，模型还是会反复加载和释放
