### ISSUE TITLE
magic-pdf pdf-command --pdf "pdf_path" --inside_model true 报错缺少依赖

### ISSUE THREAD

**Issue by bigcat001** [opendatalab/MinerU#165]
### Description of the bug | 错误描述

报错：Required dependency not installed, please install by 
"pip install magic-pdf[full-cpu] detectron2 --extra-index-url https://myhloli.github.io/wheels/"

### How to reproduce the bug | 如何复现

macos、linux按照文档安装都会报这个错

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Device mode | 设备模式

cuda

**Comment by deepeye** [comment]
同问

**Comment by myhloli** [comment]
新的代码中加入了导入包失败时的报错详情，请clone仓库之后通过
```bash
python setup.py install
```
安装再尝试。

**Comment by bigcat001** [comment]
好的

**Comment by mactavishmeng** [comment]
我也遇到同样问题，我是import cv2 出错了：
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

搜索了一下，通过安装 apt install libgl1-mesa-dev ，似乎解决了这一报错

但又报新的错 ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

然后 apt install libglib2.0-0 

目前可以跑起来了

**Comment by forlifeproj** [comment]
magic-pdf pdf-command --pdf "test.pdf" --inside_model true
ERROR    | magic_pdf.model.pp_structure_v2:<module>:8 - paddleocr not installed, please install by "pip install magic-pdf[cpu]" or "pip install magic-pdf[gpu]"

pip list paddleocr 都安装了

**Comment by wangko27** [comment]
> 我也遇到同样问题，我是import cv2 出错了： ImportError: libGL.so.1: cannot open shared object file: No such file or directory
> 
> 搜索了一下，通过安装 apt install libgl1-mesa-dev ，似乎解决了这一报错
> 
> 但又报新的错 ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
> 
> 然后 apt install libglib2.0-0
> 
> 目前可以跑起来了

你最是棒的那个

**Comment by myhloli** [comment]
We have updated to the [0.6.2b1 release](https://github.com/opendatalab/MinerU/releases/tag/magic_pdf-0.6.2b1-released), addressing and resolving the aforementioned issue.
