### ISSUE TITLE
11页报错 CUDA out of memory. Tried to allocate 466.00 MiB. GPU

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#166]
### Description of the bug | 错误描述

[academic_literature_0b2c9c91f5232541a7ace8984df306b2.pdf](https://github.com/user-attachments/files/16278664/academic_literature_0b2c9c91f5232541a7ace8984df306b2.pdf)

### How to reproduce the bug | 如何复现

magic-pdf pdf-command --pdf “” --inside_model true
![image](https://github.com/user-attachments/assets/0fe148e7-5683-4006-a87e-2eb57c4fc40a)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
显存不足，请在程序不运行的时候通过nvidia-smi命令查看机器剩余显存情况，尽量在没有其他任务大量占用显存的时候运行本程序
