### ISSUE TITLE
Typo in video

### ISSUE THREAD

**Issue by dantetemplar** [opendatalab/MinerU#170]
### Description of the bug | 错误描述

Word "Markdown" is misspelled.

![image](https://github.com/user-attachments/assets/f5cba56f-e652-49f5-b124-753b962164da)

### How to reproduce the bug | 如何复现

-

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
fix done.
