### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by fanzz1** [opendatalab/MinerU#173]
### Description of the bug | 错误描述

Speed: 23.2ms preprocess, 3345.8ms inference, 0.0ms postprocess per image at shape (1, 3, 1888, 1408)
2024-07-19 15:57:08.869 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:166 - formula nums: 0, mfr time: 0.0
2024-07-19 15:57:08.869 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:116 - doc analyze cost: 373.20968651771545
'NoneType' object is not subscriptable
2024-07-19 15:57:08.889 | ERROR    | __main__:<module>:53 - 'NoneType' object is not subscriptable
Traceback (most recent call last):

> File "E:\MinerU-master\demo\demo.py", line 49, in <module>
    md_content = pipe.pipe_mk_markdown(image_dir, drop_mode="none")
                 │    │                └ 'images'
                 │    └ <function UNIPipe.pipe_mk_markdown at 0x000002447890A050>
                 └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000002441756DF90>

  File "E:\MinerU-master\magic_pdf\pipe\UNIPipe.py", line 47, in pipe_mk_markdown
    result = super().pipe_mk_markdown(img_parent_path, drop_mode, md_make_mode)
                                      │                │          └ 'mm_markdown'
                                      │                └ 'none'
                                      └ 'images'

  File "E:\MinerU-master\magic_pdf\pipe\AbsPipe.py", line 55, in pipe_mk_markdown
    md_content = AbsPipe.mk_markdown(self.get_compress_pdf_mid_data(), img_parent_path, drop_mode, md_make_mode)
                 │       │           │    │                            │                │          └ 'mm_markdown'
                 │       │           │    │                            │                └ 'none'
                 │       │           │    │                            └ 'images'
                 │       │           │    └ <function AbsPipe.get_compress_pdf_mid_data at 0x000002444E267910>
                 │       │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000002441756DF90>
                 │       └ <staticmethod(<function AbsPipe.mk_markdown at 0x000002444E267D90>)>
                 └ <class 'magic_pdf.pipe.AbsPipe.AbsPipe'>

  File "E:\MinerU-master\magic_pdf\pipe\AbsPipe.py", line 103, in mk_markdown
    pdf_info_list = pdf_mid_data["pdf_info"]
                    └ None

TypeError: 'NoneType' object is not subscriptable

进程已结束,退出代码0

### How to reproduce the bug | 如何复现

from magic_pdf.pipe.UNIPipe import UNIPipe
from magic_pdf.rw.DiskReaderWriter import DiskReaderWriter
import magic_pdf.model as model_config
from magic_pdf.model.pdf_extract_kit import CustomPEKModel, mfd_model_init

model_config.__use_inside_model__ = True

# 设置模型目录和权重文件路径
current_script_dir = os.path.dirname(os.path.abspath(__file__))
model_dir = os.path.abspath(os.path.join(current_script_dir, '..', 'tmp', 'models'))
weight_path = os.path.join(model_dir, 'MFD','weights.pt')

# 打印路径确认
print(f"Model directory: {model_dir}")
print(f"Weight file path: {weight_path}")

# 确保权重文件存在
if not os.path.exists(weight_path):
    # 提示用户权重文件不存在
    print(f"Please ensure the weights file is available at: {weight_path}")
    raise FileNotFoundError(f"Model weights not found at {weight_path}")

# 初始化模型
custom_model = CustomPEKModel(
    ocr=True, show_log=True, models_dir=model_dir, device='cpu'
)

try:
    demo_name = "demo1"
    pdf_path = os.path.join(current_script_dir, f"{demo_name}.pdf")
    model_path = os.path.join(current_script_dir, f"{demo_name}.json")
    pdf_bytes = open(pdf_path, "rb").read()

    model_json = []  # model_json传空list使用内置模型解析
    if not model_json:
        # Initialize model_json with a default non-empty list
        model_json = [{"layout_dets": []}]  # Example of a minimal valid model_json structure

    jso_useful_key = {"_pdf_type": "", "model_list": model_json}
    local_image_dir = os.path.join(current_script_dir, 'images')
    image_dir = str(os.path.basename(local_image_dir))
    image_writer = DiskReaderWriter(local_image_dir)
    pipe = UNIPipe(pdf_bytes, jso_useful_key, image_writer)
    pipe.pipe_classify()
    pipe.pipe_analyze()  # 确保使用正确的方法
    md_content = pipe.pipe_mk_markdown(image_dir, drop_mode="none")
    with open(f"{demo_name}.md", "w", encoding="utf-8") as f:
        f.write(md_content)
except Exception as e:
    logger.exception(e)
    print(e)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
model_json = [{"layout_dets": []}]
不要使用这种方式为model_json赋值
直接用model_json = []就可以了
