### ISSUE TITLE
Failed to build grpcio

### ISSUE THREAD

**Issue by leixinstar** [opendatalab/MinerU#178]
### Description of the bug | 错误描述

  distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build grpcio
ERROR: Could not build wheels for grpcio, which is required to install pyproject.toml-based projects

### How to reproduce the bug | 如何复现

  distutils.errors.CompileError: command '/usr/bin/clang' failed with exit code 1

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build grpcio
ERROR: Could not build wheels for grpcio, which is required to install pyproject.toml-based projects

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
grpcio应该不用编译安装吧，
```bash
pip install https://files.pythonhosted.org/packages/6f/ae/fd33f805d88bf5d9321d63d8d06b8e9c3d9d24753a6f7c1e611a5114870a/grpcio-1.65.1-cp310-cp310-macosx_12_0_universal2.whl
```
应该可以直接装预编译的
