### ISSUE TITLE
请问fast-langdetect文件夹的存放地址，是否改成magic-pdf.json里面一样的可配置地址吗？

### ISSUE THREAD

**Issue by SweeneyW** [opendatalab/MinerU#179]
1.离线部署首次运行，报错urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
首次运行需要在线下载一个小的语言检测模型，如果是离线部署需要手动下载该模型并放到指定目录。
参考：https://github.com/opendatalab/MinerU/issues/121

首次运行时，内部的一些模块可能需要联网环境以下载一些小模型资源，看了您的报错日志，是fast_langdetect需要下载一个语言检测用的模型文件，如您的机器不能联网，请将附件中压缩包内容解压到"/tmp"目录下
[fasttext-langdetect.zip](https://github.com/user-attachments/files/16082178/fasttext-langdetect.zip)
参考：
https://github.com/LlmKira/fast-langdetect

请问fast-langdetect文件夹的存放地址，是否改成magic-pdf.json里面一样的可配置地址吗？

**Comment by myhloli** [comment]
这个不可配置，是依赖库决定的，如果需要改位置需要自己重新编译这个库

**Comment by SweeneyW** [comment]
谢谢解答~
