### ISSUE TITLE
没有使用后gpu加速

### ISSUE THREAD

**Issue by fanzz1** [opendatalab/MinerU#180]
### Description of the bug | 错误描述

当我修改json文件中"device-mode":"cuda"
运行magic-pdf pdf-command --pdf "1.pdf" --inside_model true
仍然提示 magic_pdf.model.pdf_extract_kit:__init__:100 - using device: cpu

### How to reproduce the bug | 如何复现

1

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
把magic-pdf.json的完整内容发一下？

**Comment by fanzz1** [comment]
{
    "bucket_info":{
        "bucket-name-1":["ak", "sk", "endpoint"],
        "bucket-name-2":["ak", "sk", "endpoint"]
    },
    "output-dir":"/tmp",
    "models-dir":"E:\\MinerU-master\\tmp\\models\\MFD\\weights.pt",
    "device-mode":"cuda"
}

**Comment by myhloli** [comment]
> {
> 
>     "bucket_info":{
> 
>         "bucket-name-1":["ak", "sk", "endpoint"],
> 
>         "bucket-name-2":["ak", "sk", "endpoint"]
> 
>     },
> 
>     "output-dir":"/tmp",
> 
>     "models-dir":"E:\\MinerU-master\\tmp\\models\\MFD\\weights.pt",
> 
>     "device-mode":"cuda"
> 
> }

```json
{
"models-dir":"E:\\MinerU-master\\tmp\\models\\MFD\\weights.pt",
}
```
这个参数应该指向models目录而不是一个具体的模型文件，如果使用这个配置文件，程序应该无法正常运行，可以确认下修改了cuda的json配置文件是否在"~/"目录下

**Comment by SweeneyW** [comment]
> > {
> > ```
> > "bucket_info":{
> > 
> >     "bucket-name-1":["ak", "sk", "endpoint"],
> > 
> >     "bucket-name-2":["ak", "sk", "endpoint"]
> > 
> > },
> > 
> > "output-dir":"/tmp",
> > 
> > "models-dir":"E:\\MinerU-master\\tmp\\models\\MFD\\weights.pt",
> > 
> > "device-mode":"cuda"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> 
> ```json
> {
> "models-dir":"E:\\MinerU-master\\tmp\\models\\MFD\\weights.pt",
> }
> ```
> 
> 这个参数应该指向models目录而不是一个具体的模型文件，如果使用这个配置文件，程序应该无法正常运行，可以确认下修改了cuda的json配置文件是否在"~/"目录下



请问magic-pdf.json，如果要放在别的目录下，代码需要从那里修改呢？

**Comment by myhloli** [comment]
> > > {
> > > ```
> > > "bucket_info":{
> > > 
> > >     "bucket-name-1":["ak", "sk", "endpoint"],
> > > 
> > >     "bucket-name-2":["ak", "sk", "endpoint"]
> > > 
> > > },
> > > 
> > > "output-dir":"/tmp",
> > > 
> > > "models-dir":"E:\\MinerU-master\\tmp\\models\\MFD\\weights.pt",
> > > 
> > > "device-mode":"cuda"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }
> > 
> > 
> > ```json
> > {
> > "models-dir":"E:\\MinerU-master\\tmp\\models\\MFD\\weights.pt",
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个参数应该指向models目录而不是一个具体的模型文件，如果使用这个配置文件，程序应该无法正常运行，可以确认下修改了cuda的json配置文件是否在"~/"目录下
> 
> 请问magic-pdf.json，如果要放在别的目录下，代码需要从那里修改呢？

Placing the config file in the user directory facilitates better compatibility across different operating systems.
