### ISSUE TITLE
在demo文件中，如果我想要保存解析后的json文件，应该如何操作

### ISSUE THREAD

**Issue by fanzz1** [opendatalab/MinerU#183]
### Description of the bug | 错误描述

当我这样保存，返回的json文件是空值

### How to reproduce the bug | 如何复现

import os
import json
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'
from loguru import logger
from magic_pdf.model.pdf_extract_kit import CustomPEKModel

from magic_pdf.pipe.UNIPipe import UNIPipe
from magic_pdf.rw.DiskReaderWriter import DiskReaderWriter

import magic_pdf.model as model_config
model_config.__use_inside_model__ = True

# 设置模型目录和权重文件路径
current_script_dir = os.path.dirname(os.path.abspath(__file__))
model_dir = os.path.abspath(os.path.join(current_script_dir, '..', 'tmp', 'models', 'MFD'))
weight_path = os.path.join(model_dir, 'weights.pt')

# 打印路径确认
print(f"Model directory: {model_dir}")
print(f"Weight file path: {weight_path}")

# 确保权重文件存在
if not os.path.exists(weight_path):
    # 提示用户权重文件不存在
    print(f"Please ensure the weights file is available at: {weight_path}")
    raise FileNotFoundError(f"Model weights not found at {weight_path}")

# 初始化模型
custom_model = CustomPEKModel(
    ocr=True, show_log=True, models_dir=os.path.abspath(os.path.join(current_script_dir, '..', 'tmp', 'models')), device='cuda'
)
try:
    current_script_dir = os.path.dirname(os.path.abspath(__file__))
    demo_name = "3"
    pdf_path = os.path.join(current_script_dir, f"{demo_name}.pdf")
    model_path = os.path.join(current_script_dir, f"{demo_name}.json")
    pdf_bytes = open(pdf_path, "rb").read()
    # model_json = json.loads(open(model_path, "r", encoding="utf-8").read())
    model_json = []  # model_json传空list使用内置模型解析
    jso_useful_key = {"_pdf_type": "", "model_list": model_json}
    # 创建存放解析结果的文件夹，以PDF文件名命名
    output_folder = os.path.join(current_script_dir, demo_name)
    os.makedirs(output_folder, exist_ok=True)
    # 创建存放图片的子文件夹
    image_dir = os.path.join(output_folder, 'images')
    os.makedirs(image_dir, exist_ok=True)
    image_writer = DiskReaderWriter(image_dir)
    pipe = UNIPipe(pdf_bytes, jso_useful_key, image_writer)
    pipe.pipe_classify()
    """如果没有传入有效的模型数据，则使用内置model解析"""
    if len(model_json) == 0:
        if model_config.__use_inside_model__:
            pipe.pipe_analyze()
            # 保存模型 JSON 文件
            with open(os.path.join(output_folder, f"{demo_name}_model.json"), "w", encoding="utf-8") as f:
                json.dump(model_json, f, ensure_ascii=False, indent=4)
        else:
            logger.error("need model list input")
            exit(1)
    pipe.pipe_parse()
    md_content = pipe.pipe_mk_markdown('images', drop_mode="none")
    with open(os.path.join(output_folder, f"{demo_name}.md"), "w", encoding="utf-8") as f:
        f.write(md_content)
except Exception as e:
    logger.exception(e)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
@fanzz1 
```bash
orig_model_list = copy.deepcopy(pipe.model_list)
json.dumps(orig_model_list, ensure_ascii=False, indent=4)
```
