### ISSUE TITLE
下载模型后运行报错FileNotFoundError: [Errno 2] No such file or directory: '/tmp/models/MFD/weights.pt'

### ISSUE THREAD

**Issue by sssuperrrr** [opendatalab/MinerU#185]
### Description of the bug | 错误描述

在魔搭上下载模型wanderkid/PDF-Extract-Kit后上传至服务器，同时在magic-pdf.json中修改为"models-dir":"/tmp/models"，按照仓库步骤执行magic-pdf pdf-command --pdf "pdf_path" --inside_model true报错FileNotFoundError: [Errno 2] No such file or directory: '/tmp/models/MFD/weights.pt'

### How to reproduce the bug | 如何复现

![image](https://github.com/user-attachments/assets/9b8feb3a-417d-4485-b667-695045c8a7a2)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
可以尝试在服务器上
```bash
cd /tmp/models/MFD
ls -la
```
确认下模型文件又没有上传成功

**Comment by sssuperrrr** [comment]
> 可以尝试在服务器上
> 
> ```shell
> cd /tmp/models/MFD
> ls -la
> ```
> 
> 确认下模型文件又没有上传成功

![image](https://github.com/user-attachments/assets/9f17a6d8-8c6a-4e96-94f2-72bf4f7a4458)
这个位置有的

**Comment by myhloli** [comment]
> > 可以尝试在服务器上
> > ```shell
> > cd /tmp/models/MFD
> > ls -la
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 确认下模型文件又没有上传成功
> 
> ![image](https://private-user-images.githubusercontent.com/46615660/351552239-9f17a6d8-8c6a-4e96-94f2-72bf4f7a4458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3ODgwNzMsIm5iZiI6MTcyMTc4Nzc3MywicGF0aCI6Ii80NjYxNTY2MC8zNTE1NTIyMzktOWYxN2E2ZDgtOGM2YS00ZTk2LTk0ZjItNzJiZjRmN2E0NDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDAyMjI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NmFhNDg0Y2I5YTFkMTJjYTM3MThmNjJhNjMwNDFiNTQ5OGI3MGZjYTBkMjkxNWU0OGI3NTdhMGI1ZGM3NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5sF9MKsr-efvatF-8_zSP_kcpsk1wQxq2ZHS77uKU0c) 这个位置有的

这个是工程目录的tmp，你可以在这个目录下执行pwd，看一下真实的绝对路径，然后将这个绝对路径替换到magic-pdf.json中的模型路径参数里

**Comment by sssuperrrr** [comment]
> > > 可以尝试在服务器上
> > > ```shell
> > > cd /tmp/models/MFD
> > > ls -la
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 确认下模型文件又没有上传成功
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/46615660/351552239-9f17a6d8-8c6a-4e96-94f2-72bf4f7a4458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3ODgwNzMsIm5iZiI6MTcyMTc4Nzc3MywicGF0aCI6Ii80NjYxNTY2MC8zNTE1NTIyMzktOWYxN2E2ZDgtOGM2YS00ZTk2LTk0ZjItNzJiZjRmN2E0NDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDAyMjI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NmFhNDg0Y2I5YTFkMTJjYTM3MThmNjJhNjMwNDFiNTQ5OGI3MGZjYTBkMjkxNWU0OGI3NTdhMGI1ZGM3NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5sF9MKsr-efvatF-8_zSP_kcpsk1wQxq2ZHS77uKU0c) 这个位置有的
> 
> 这个是工程目录的tmp，你可以在这个目录下执行pwd，看一下真实的绝对路径，然后将这个绝对路径替换到magic-pdf.json中的模型路径参数里

仍然报错
![image](https://github.com/user-attachments/assets/0cbf0db6-103e-438f-87af-7206aa67430c)

**Comment by myhloli** [comment]
看起来是程序没找到magic-pdf.json或是没在magic-pdf.json中找到models-dir字段。不知道是不是和vscode的远程执行有关系。

**Comment by wangxinyu6666** [comment]
我本地也出现这种情况

**Comment by wangxinyu6666** [comment]
请问解决了吗？

**Comment by cvcuiwei** [comment]
> 我本地也出现这种情况

**你用的win系统吧,我也是win系统,遇到相同的问题
win系统magic-pdf.template.json要复制到的位置是系统用户名的根目录,正确的修改这个文件见以下说明**

############
cp magic-pdf.template.json ~/magic-pdf.json这条命令 ~/ 是指哪里
在这条命令中，~/是一个表示用户主目录的特殊字符。在Unix和类Unix系统（如Linux和macOS）中，用户主目录是用户登录后默认进入的目录。在Windows系统中，用户主目录通常位于C:\Users\<username>目录下，其中<username>是用户的用户名。

因此，~/magic-pdf.json表示用户主目录下的magic-pdf.json文件。这条命令的作用是将当前目录下的magic-pdf.template.json文件复制到用户主目录下，并将其重命名为magic-pdf.json。

这样做的目的是创建一个新的配置文件，该文件可以用于自定义magic-pdf工具的行为。通过将配置文件模板文件复制到用户主目录下，并将其重命名为magic-pdf.json，用户可以编辑该文件以自定义magic-pdf工具的行为。
############



**另外magic-pdf.json文件中在win系统的目录写法也不同,见倒数第2~3行是win系统的正确写法**

magic-pdf.json
{
    "bucket_info":{
        "bucket-name-1":["ak", "sk", "endpoint"],
        "bucket-name-2":["ak", "sk", "endpoint"]
    },
    "temp-output-dir":"D:\\BaiduSyncdisk\\Magic-PDF\\tmp",
    "models-dir":"D:\\BaiduSyncdisk\\Magic-PDF\\tmp\\models",
    "device-mode":"cpu"
}

**Comment by cvcuiwei** [comment]
> > 我本地也出现这种情况
> 
> **你用的win系统吧，我也是win系统，遇到同样的问题 win系统magic-pdf.template.json要复制到的位置是系统用户名的根目录，正确的修改这个文件见以下说明**
> 
> ############ cp magic-pdf.template.json ~/magic-pdf.json 这个命令~/ 是指 这条命令中的哪里，~/是一个表示用户主目录的特殊字符。在Unix和类Unix系统（如Linux和macOS）中，用户主目录是用户登录后默认进入的目录。在Windows系统中，用户主目录通常位于C:\ Users<用户名>目录下，其中是用户的用户名。
> 
> 因此，~/magic-pdf.json表示用户主目录下的magic-pdf.json文件。这条命令的作用相当于当前目录下的magic-pdf.template.json文件复制到用户主目录下，然后其重命名为magic-pdf.json。
> 
> 这样做的目的是创建一个新的配置文件，该文件可以用于自定义magic-pdf工具的行为。通过将配置文件模板文件复制到用户主目录下，并将其重命名为magic-pdf.json ，用户可以以自定义magic-pdf工具的行为编辑该文件。 ############
> 
> **另外magic-pdf.json文件中在win系统的目录写法也不同,见倒数第2~3行是win系统的正确写法**
> 
> magic-pdf.json { “bucket_info”：{ “bucket-name-1”：[“ak”， “sk”， “endpoint”], “bucket-name-2”：[“ak”， “sk”， “endpoint”] }, “temp-output-dir”：“D:\BaiduSyncdisk\Magic-PDF\tmp”, “models-dir”：“D:\BaiduSyncdisk\Magic-PDF\tmp\models”, “device-mode”：“cpu” }

我用上述方法,已经实现了识别,虽然有个小图没识别出来,但也算是流程跑通了,哈哈
<img width="1150" alt="sp240729_213934" src="https://github.com/user-attachments/assets/9a9ded48-0b0d-456c-a931-18e33b29a29d">

**Comment by Alan-zhong** [comment]
![image](https://github.com/user-attachments/assets/2a7d220a-5d85-4ae7-8745-175cc65d7fd0)
为什么我本地Windows系统不行啊？
