### ISSUE TITLE
pipeline支持传入图片和图片路径列表

### ISSUE THREAD

**Issue by randydl** [opendatalab/MinerU#187]
现在的pipeline可以传入pdf路径，比如：
magic-pdf pdf-command --pdf "pdf_path"

可不可以增加一个传入图片路径的方法（因为有很多书籍是扫描版，存的是图片），比如：
magic-pdf img-command --img "img_path"

虽然我把图片转成pdf也可以做到，但是我觉得这样太麻烦，而且我看咱们源代码里也是把pdf每一页转成图片。所以把图片转成pdf，然后pdf再转成图片的话，这样就很多余。

**Comment by myhloli** [comment]
这个功能已经在规划中了，敬请期待。

**Comment by myhloli** [comment]
这个功能开发过程中发现，整个流程中大量使用了基于pymupdf的doc对象和page对象，为了方便还是需要前置将图片转换为pdf再进行处理，https://github.com/opendatalab/MinerU/blob/8ee1da82a860556716a63578dba88d893def5dd9/projects/multi_gpu/server.py#L55
这个思路很棒，给了我们很多启发

**Comment by linchen111** [comment]
> 这个功能开发过程中发现，整个流程中大量使用了基于pymupdf的doc对象和page对象，为了方便还是需要前置将图片转换为pdf再进行处理，
> 
> [MinerU/projects/multi_gpu/server.py](https://github.com/opendatalab/MinerU/blob/8ee1da82a860556716a63578dba88d893def5dd9/projects/multi_gpu/server.py#L55)
> 
> Line 55 in [8ee1da8](/opendatalab/MinerU/commit/8ee1da82a860556716a63578dba88d893def5dd9)
> 
>  def to_pdf(self, file_base64): 
> 
> 这个思路很棒，给了我们很多启发

目前支持传入一本书的系列图片路径了吗

**Comment by tiptinker** [comment]
对，既然PDF都可以直接解析，那图片当然也可以啊。 
或者是否可以自动把word，ppt， 图片，这些转化成pdf，然后进入pipeline处理？
