### ISSUE TITLE
按照readme完全安装完成后无法运行

### ISSUE THREAD

**Issue by JiangRunzhi** [opendatalab/MinerU#190]
### Description of the bug | 错误描述

![1721704109614-ksj](https://github.com/user-attachments/assets/a0324200-86fa-46f4-bdb4-b9abd8a4d3be)
有一个warning: magic_pdf.cli.magicpdf:get_model_json:310 - not found json ../home/jiangrz/MinerU/test_3.json existed.
然后程序就卡这里不动了，无法跑出任何结果。
看了好半天才明白，这个对应pdf名字的json，是需要单独部署[PDF-Extract-Kit](https://github.com/opendatalab/PDF-Extract-Kit)运行得到的吗？

反正只按照MinerU的readme我没能跑出来。但是看有些人跑出来了，不知道是什么问题。求助。

### How to reproduce the bug | 如何复现

(py310torch) [root@server1 MinerU]# magic-pdf pdf-command --pdf "/home/jiangrz/MinerU/test_3.pdf" --inside_model true --model_mode full
2024-07-23 11:44:47.194 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:310 - not found json /home/jiangrz/MinerU/test_3.json existed
2024-07-23 11:44:47.194 | INFO     | magic_pdf.cli.magicpdf:do_parse:91 - local output dir is /home/jiangrz/MinerU/tmp/magic-pdf/test_3/auto

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
1.json找不到是个warning，没有json的情况下，应用会调用内置模型去生成json文件。
2.output目录log之后程序还在执行，如果没有异常报错的话，可以另起一个终端，使用top命令看一下cpu和内存占用情况，如果还有占用，就说明程序还在执行中，请耐心等待。

**Comment by JiangRunzhi** [comment]
> 1.json找不到是个warning，没有json的情况下，应用会调用内置模型去生成json文件。 2.output目录log之后程序还在执行，如果没有异常报错的话，可以另起一个终端，使用top命令看一下cpu和内存占用情况，如果还有占用，就说明程序还在执行中，请耐心等待。

top命令查看cpu和内存magic-pdf在输出这两行之后就没有占用了，而且等多久都跑不出来任何结果。

**Comment by myhloli** [comment]
> > 1.json找不到是个warning，没有json的情况下，应用会调用内置模型去生成json文件。 2.output目录log之后程序还在执行，如果没有异常报错的话，可以另起一个终端，使用top命令看一下cpu和内存占用情况，如果还有占用，就说明程序还在执行中，请耐心等待。
> 
> top命令查看cpu和内存magic-pdf在输出这两行之后就没有占用了，而且等多久都跑不出来任何结果。

可以试试在本地单机上试试能不能运行，服务器可能会由于共享资源导致程序获取不到足够资源继续运行而导致暂停或中断。

**Comment by JiangRunzhi** [comment]
谢谢！我发现应该是我的服务器有问题。
