### ISSUE TITLE
fail to install detectron2

### ISSUE THREAD

**Issue by bookandlover** [opendatalab/MinerU#199]
### Description of the bug | 错误描述

(.venv) peng@Mac-Studio magicpdf % pip install detectron2 --extra-index-url https://myhloli.github.io/wheels/
Looking in indexes: https://pypi.org/simple, https://myhloli.github.io/wheels/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /simple/detectron2/
ERROR: Could not find a version that satisfies the requirement detectron2 (from versions: none)
ERROR: No matching distribution found for detectron2

### How to reproduce the bug | 如何复现

(.venv) peng@Mac-Studio magicpdf % pip install detectron2 --extra-index-url https://myhloli.github.io/wheels/
Looking in indexes: https://pypi.org/simple, https://myhloli.github.io/wheels/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /simple/detectron2/
ERROR: Could not find a version that satisfies the requirement detectron2 (from versions: none)
ERROR: No matching distribution found for detectron2

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

mps

**Comment by myhloli** [comment]
>The full-feature package depends on detectron2, which requires a compilation installation.
If you need to compile it yourself, please refer to https://github.com/facebookresearch/detectron2/issues/5114
Alternatively, you can directly use our precompiled whl package (limited to Python 3.10)

your python version is 3.12, need compile it by yourself.
