### ISSUE TITLE
mac M2 未使用镜像源下载的版本是0.5.13

### ISSUE THREAD

**Issue by wiidi** [opendatalab/MinerU#200]
### Description of the bug | 错误描述

mac M2 未使用镜像源，下载的版本是0.5.13

### How to reproduce the bug | 如何复现

![WechatIMG170](https://github.com/user-attachments/assets/fa136a55-3a23-4996-93bb-6e986e106434)

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.5.x

### Device mode | 设备模式

mps

**Comment by wiidi** [comment]
pip install magic-pdf[full-cpu]

**Comment by myhloli** [comment]
安装结果看起来像是镜像源没更新的原因，可以查一下自己的pip是不是内置了镜像源，目前镜像源的话推荐使用清华源，可以试着用清华源重装一遍

**Comment by myhloli** [comment]
please try with it:
https://github.com/opendatalab/MinerU/issues/273#issuecomment-2261043221
