### ISSUE TITLE
已经安装了预编译的whl包还是报错显示没安装

### ISSUE THREAD

**Issue by WillingLau** [opendatalab/MinerU#202]
### Description of the bug | 错误描述

2024-07-24 14:38:40.920 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:24 - Required dependency not installed, please install by 
"pip install magic-pdf[full-cpu] detectron2 --extra-index-url https://myhloli.github.io/wheels/"
已经安装好了whl包，model权重也下载了，但是就是一直报这个错

### How to reproduce the bug | 如何复现

运行demo就报错

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
参考https://github.com/opendatalab/MinerU/issues/165#issuecomment-2235232877 这个再试下呢

**Comment by WillingLau** [comment]
> 参考[#165 (comment)](https://github.com/opendatalab/MinerU/issues/165#issuecomment-2235232877) 这个再试下呢

我自己手动编译了detectron2之后这个报错没了，但是又找不到一个叫fairscale的包了，删除重装之后还是一样

**Comment by WillingLau** [comment]
> 参考[#165 (comment)](https://github.com/opendatalab/MinerU/issues/165#issuecomment-2235232877) 这个再试下呢

然后extractedPDFkit那个项目也出现了同样的报错，找不到fairscale这个包

**Comment by myhloli** [comment]
We have updated to the [0.6.2b1 release](https://github.com/opendatalab/MinerU/releases/tag/magic_pdf-0.6.2b1-released), addressing and resolving the aforementioned issue.
