### ISSUE TITLE
安装detectron2时报错

### ISSUE THREAD

**Issue by yan32020** [opendatalab/MinerU#205]
### Description of the bug | 错误描述

![001](https://github.com/user-attachments/assets/3686d5f8-d8e9-4754-bcbd-90bf4ad662bc)

### How to reproduce the bug | 如何复现

环境使用conda创建的Python3.10 ，第二步报错无法进行

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
pip install https://github.com/myhloli/wheels/blob/main/assets/whl/detectron2/detectron2-0.6-cp310-cp310-win_amd64.whl

**Comment by yan32020** [comment]
> pip install https://github.com/myhloli/wheels/blob/main/assets/whl/detectron2/detectron2-0.6-cp310-cp310-win_amd64.whl
C:\Windows\system32>pip install https://github.com/myhloli/wheels/blob/main/assets/whl/detectron2/detectron2-0.6-cp310-cp310-win_amd64.whl
ERROR: detectron2-0.6-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.
好像还是不行

**Comment by myhloli** [comment]
你的windows是32位的吗？

**Comment by yan32020** [comment]
> 你的windows是32位的吗？

我知道怎么回事了，不知道为什么pycharm里我明明已经激活了创建的Python3.10，pip安装的时候却不是3.10，后面用命令行激活环境就可以正常安装了

**Comment by myhloli** [comment]
> > 你的windows是32位的吗？
> 
> 
> 
> 我知道怎么回事了，不知道为什么pycharm里我明明已经激活了创建的Python3.10，pip安装的时候却不是3.10，后面用命令行激活环境就可以正常安装了

好的
