### ISSUE TITLE
运行时2024-07-25 00:34:34.251 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:310 - not found json F:\Workspace\Magic-Doc\a.json existed报错

### ISSUE THREAD

**Issue by yan32020** [opendatalab/MinerU#206]
### Description of the bug | 错误描述

C:\Users\YAN>magic-pdf pdf-command --pdf "F:\Workspace\Magic-Doc\a.pdf" --inside_model true
2024-07-25 00:34:34.251 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:310 - not found json F:\Workspace\Magic-Doc\a.json existed

### How to reproduce the bug | 如何复现

![001](https://github.com/user-attachments/assets/325d19ee-b52f-45ca-85a2-9b08405241e8)
参数文件配置
![image](https://github.com/user-attachments/assets/d87d0f64-4605-4165-8c36-d4b92915f024)
pdf目录

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
这是个warning，不是报错

**Comment by yan32020** [comment]
但是现在根本没有运行，
![001](https://github.com/user-attachments/assets/93e8bc3c-144b-44b3-8815-1df524d6e885)
要怎么解决呢
