### ISSUE TITLE
运行error，need model list input

### ISSUE THREAD

**Issue by yan32020** [opendatalab/MinerU#210]
### Description of the bug | 错误描述

2024-07-25 10:02:33.886 | ERROR    | magic_pdf.cli.magicpdf:do_parse:114 - need model list input

### How to reproduce the bug | 如何复现

![image](https://github.com/user-attachments/assets/ce5a57be-216a-4831-bf39-78b1e001b9b6)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
命令行加参数 --inside_model true

**Comment by airtonix** [comment]
ticket needs to be repopened and the docs should be updated: 

```
> pdm run magic-pdf --help                              
Usage: magic-pdf [OPTIONS] COMMAND [ARGS]...

Options:
  -v, --version  显示版本信息
  -h, --help     显示帮助信息

Commands:
  json-command
  local-json-command
  pdf-command

x pdm run magic-pdf pdf-command --help                
Usage: magic-pdf pdf-command [OPTIONS]

Options:
  --pdf PATH               PDF文件的路径  [required]
  --model PATH             模型的路径
  --method [ocr|txt|auto]  指定解析方法。txt: 文本型 pdf 解析方法， ocr: 光学识别解析 pdf, auto:
                           程序智能选择解析方法
  --inside_model BOOLEAN   使用内置模型测试
  --model_mode TEXT        内置模型选择。lite: 快速解析，精度较低，full: 高精度解析，速度较慢
  --help                   Show this message and exit.
```

**Comment by myhloli** [comment]
> ticket needs to be repopened and the docs should be updated:
> 
> ```
> > pdm run magic-pdf --help                              
> Usage: magic-pdf [OPTIONS] COMMAND [ARGS]...
> 
> Options:
>   -v, --version  显示版本信息
>   -h, --help     显示帮助信息
> 
> Commands:
>   json-command
>   local-json-command
>   pdf-command
> 
> x pdm run magic-pdf pdf-command --help                
> Usage: magic-pdf pdf-command [OPTIONS]
> 
> Options:
>   --pdf PATH               PDF文件的路径  [required]
>   --model PATH             模型的路径
>   --method [ocr|txt|auto]  指定解析方法。txt: 文本型 pdf 解析方法， ocr: 光学识别解析 pdf, auto:
>                            程序智能选择解析方法
>   --inside_model BOOLEAN   使用内置模型测试
>   --model_mode TEXT        内置模型选择。lite: 快速解析，精度较低，full: 高精度解析，速度较慢
>   --help                   Show this message and exit.
> ```

magic-pdf -v 
it should be 0.7.1
