### ISSUE TITLE
运行demo报错

### ISSUE THREAD

**Issue by x19990416** [opendatalab/MinerU#211]
## 说明
我直接运行demo.py，
在windows10 下面的conda环境中根据说明文档一不一步执行，模型是根据glf下载的

## 运行日志
(MinerU) I:\900-归档-ocr-测试\MinerU\demo>python demo.py
2024-07-25 10:25:37.738 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 9, text_len: 31404, cid_chars_radio: 0.00028708133971291867
2024-07-25 10:25:50.212 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:92 - DocAnalysis init, this may take some times. apply_layout: True, apply_formula: True, apply_ocr: False
2024-07-25 10:25:50.213 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:100 - using device: cpu
2024-07-25 10:25:50.215 | ERROR    | __main__:<module>:38 - invalid load key, 'v'.
Traceback (most recent call last):

> File "I:\900-归档-ocr-测试\MinerU\demo\demo.py", line 29, in <module>
    pipe.pipe_analyze()
    │    └ <function UNIPipe.pipe_analyze at 0x00000208F0C79A20>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x00000208C8F0FF70>

  File "d:\miniconda3\envs\MinerU\lib\site-packages\magic_pdf\pipe\UNIPipe.py", line 29, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=False)
    │    │            │           │    └ b'%PDF-1.3\r%\xe2\xe3\xcf\xd3\r\n236 0 obj\r<< \r/Linearized 1 \r/O 242 \r/H [ 2994 878 ] \r/L 336919 \r/E 56128 \r/N 13 \r/T...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x00000208C8F0FF70>
    │    │            └ <function doc_analyze at 0x00000208DD0B7C70>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x00000208C8F0FF70>

  File "d:\miniconda3\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 69, in doc_analyze
    custom_model = CustomPEKModel(ocr=ocr, show_log=show_log, models_dir=local_models_dir, device=device)
                   │                  │             │                    │                        └ 'cpu'
                   │                  │             │                    └ 'I:/900-归档-ocr-测试/pdf/PDF-Extract-Kit/models'
                   │                  │             └ False
                   │                  └ False
                   └ <class 'magic_pdf.model.pdf_extract_kit.CustomPEKModel'>

  File "d:\miniconda3\envs\MinerU\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 106, in __init__
    self.mfd_model = mfd_model_init(str(os.path.join(models_dir, self.configs["weights"]["mfd"])))
    │                │                  │  │    │    │           │    └ {'config': {'device': 'cpu', 'layout': True, 'formula': True}, 'weights': {'layout': 'Layout/model_final.pth', 'mfd': 'MFD/we...
    │                │                  │  │    │    │           └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x00000208CCD05F60>
    │                │                  │  │    │    └ 'I:/900-归档-ocr-测试/pdf/PDF-Extract-Kit/models'
    │                │                  │  │    └ <function join at 0x00000208C8CA69E0>
    │                │                  │  └ <module 'ntpath' from 'd:\\miniconda3\\envs\\MinerU\\lib\\ntpath.py'>
    │                │                  └ <module 'os' from 'd:\\miniconda3\\envs\\MinerU\\lib\\os.py'>
    │                └ <function mfd_model_init at 0x00000208CD110E50>
    └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x00000208CCD05F60>

  File "d:\miniconda3\envs\MinerU\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 29, in mfd_model_init
    mfd_model = YOLO(weight)
                │    └ 'I:/900-归档-ocr-测试/pdf/PDF-Extract-Kit/models\\MFD/weights.pt'
                └ <class 'ultralytics.models.yolo.model.YOLO'>

  File "d:\miniconda3\envs\MinerU\lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
                           │           │             └ False
                           │           └ None
                           └ 'I:/900-归档-ocr-测试/pdf/PDF-Extract-Kit/models\\MFD/weights.pt'

  File "d:\miniconda3\envs\MinerU\lib\site-packages\ultralytics\engine\model.py", line 141, in __init__
    self._load(model, task=task)
    │    │     │           └ None
    │    │     └ 'I:/900-归档-ocr-测试/pdf/PDF-Extract-Kit/models\\MFD/weights.pt'
    │    └ <function Model._load at 0x0000020885F28940>
    └ YOLO()

  File "d:\miniconda3\envs\MinerU\lib\site-packages\ultralytics\engine\model.py", line 293, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
    │    │      │    │      │                       └ 'I:/900-归档-ocr-测试/pdf/PDF-Extract-Kit/models\\MFD/weights.pt'
    │    │      │    │      └ <function attempt_load_one_weight at 0x0000020885E94040>
    │    │      │    └ None
    │    │      └ YOLO()
    │    └ None
    └ YOLO()

  File "d:\miniconda3\envs\MinerU\lib\site-packages\ultralytics\nn\tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   │               └ 'I:/900-归档-ocr-测试/pdf/PDF-Extract-Kit/models\\MFD/weights.pt'
                   └ <function torch_safe_load at 0x0000020885E7BEB0>

  File "d:\miniconda3\envs\MinerU\lib\site-packages\ultralytics\nn\tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           │     │    └ 'I:\\900-归档-ocr-测试\\pdf\\PDF-Extract-Kit\\models\\MFD\\weights.pt'
           │     └ <function torch_load at 0x0000020885E11D80>
           └ <module 'torch' from 'd:\\miniconda3\\envs\\MinerU\\lib\\site-packages\\torch\\__init__.py'>

  File "d:\miniconda3\envs\MinerU\lib\site-packages\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
           │            │       └ {'map_location': 'cpu', 'weights_only': False}
           │            └ ('I:\\900-归档-ocr-测试\\pdf\\PDF-Extract-Kit\\models\\MFD\\weights.pt',)
           └ <function load at 0x00000208F2CC00D0>

  File "d:\miniconda3\envs\MinerU\lib\site-packages\torch\serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           │            │            │             │                └ {'encoding': 'utf-8'}
           │            │            │             └ <module 'pickle' from 'd:\\miniconda3\\envs\\MinerU\\lib\\pickle.py'>
           │            │            └ 'cpu'
           │            └ <_io.BufferedReader name='I:\\900-归档-ocr-测试\\pdf\\PDF-Extract-Kit\\models\\MFD\\weights.pt'>
           └ <function _legacy_load at 0x00000208F2CC0280>

  File "d:\miniconda3\envs\MinerU\lib\site-packages\torch\serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   │             │    │    └ {'encoding': 'utf-8'}
                   │             │    └ <_io.BufferedReader name='I:\\900-归档-ocr-测试\\pdf\\PDF-Extract-Kit\\models\\MFD\\weights.pt'>
                   │             └ <built-in function load>
                   └ <module 'pickle' from 'd:\\miniconda3\\envs\\MinerU\\lib\\pickle.py'>

_pickle.UnpicklingError: invalid load key, 'v'.

## 配置文件

{
    "bucket_info":{
        "bucket-name-1":["ak", "sk", "endpoint"],
        "bucket-name-2":["ak", "sk", "endpoint"]
    },
    "temp-output-dir":"./tmp",
    "models-dir":"I:/900-归档-ocr-测试/pdf/PDF-Extract-Kit/models",
    "device-mode":"cpu"
}

### How to reproduce the bug | 如何复现

运行demo

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
模型文件没下载完整，请检查下已下载的模型文件大小，或者校验下文件的SHA256和网页上是否一致。
