### ISSUE TITLE
你好，请问质检层相关的内容很感兴趣，你们有什么计划吗？

### ISSUE THREAD

**Issue by xuquankun** [opendatalab/MinerU#217]
![image](https://github.com/user-attachments/assets/13c20103-787b-4150-9d27-2c57905e2c18)

**Comment by drunkpig** [comment]
关于大批量混合PDF的数据质量质检我们是这么做的：
1. 人工从minerU中筛选出几个类别（论文、教材、试卷、研报等），不局限于这些，人工挑选出我们处理得好的页面，多样性越多越好
2. 页面转成图片
3. 这些图片被抽成特征库（ResNet50）
4. 当一个未知质量的pdf page被抽取时，利用这个page的截图从特征库查询出最相似的pdf面并记录下距离
5. 随着一批数据处理的结束，我们筛选出那些距离处于末尾N%的page，逐一分析用于改进我们的模型。

@xuquankun

**Comment by drunkpig** [comment]
Regarding the quality assurance of large-scale mixed PDFs, we proceed as follows:

1. Manually select several categories (such as papers, textbooks, exam papers, research reports, etc.) from PDF pages we have processed, not limited to these, and manually pick out the pages we have processed well. The more diversity, the better.
2. Convert these PDF pages into images.
3. These images are extracted into a feature library (using ResNet50).
4. When a PDF page of unknown quality is extracted, use the screenshot of this page to query the most similar PDF pages from the feature library and record the distance.
5. As a batch of Pdfs processing concludes, we filter out those pages whose distances are in the bottom N% and analyze them one by one to improve our model or drop these data.

@xuquankun

**Comment by xuquankun** [comment]
我理解了你们这块工作的流程，请问质检工具你们会开发开源吗？

**Comment by drunkpig** [comment]
@xuquankun This functionality relies on continuously data accumulating , and the tools are not fully developed. Some steps are completed by different team members  using various scripts, so it is not suitable for open sourcing

**Comment by xuquankun** [comment]
明白了，谢谢
