### ISSUE TITLE
paddleocr not installed, please install by "pip install magic-pdf[cpu]" or "pip install magic-pdf[gpu]"

### ISSUE THREAD

**Issue by forlifeproj** [opendatalab/MinerU#221]
### Description of the bug | 错误描述

已经安装magic-pdf[full-cpu]，依赖包也检查ok, 
**! magic-pdf pdf-command --pdf "../../data/pdf/我的第一本养猫书_20_22.pdf" --inside_model true** 还是报错：
paddleocr not installed, please install by "pip install magic-pdf[cpu]" or "pip install magic-pdf[gpu]"

**! pip show magic-pdf**
Name: magic-pdf
Version: 0.5.13
Summary: A practical tool for converting PDF to Markdown
Home-page: https://github.com/magicpdf/Magic-PDF
Author: 
Author-email: 
License: 
Location: [/Users/dengxiaolong/anaconda3/envs/MinerU/lib/python3.10/site-packages](https://file+.vscode-resource.vscode-cdn.net/Users/dengxiaolong/anaconda3/envs/MinerU/lib/python3.10/site-packages)
Requires: boto3, Brotli, click, fast-langdetect, loguru, numpy, numpy, pdfminer.six, PyMuPDF, scikit-learn, wordninja
Required-by:

**! pip list**
Package                 Version
----------------------- ------------------
opencv-contrib-python   4.10.0.84
opencv-python           4.10.0.84
opencv-python-headless  4.10.0.84
paddleocr               2.8.1
paddlepaddle            3.0.0b1
torch                   2.2.2
torchtext               0.17.2
torchvision             0.17.2

### How to reproduce the bug | 如何复现

! magic-pdf pdf-command --pdf "../../data/pdf/test.pdf" --inside_model true

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.5.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
intel mac要按这个方法装

https://github.com/opendatalab/MinerU/blob/master/docs/FAQ_zh_cn.md#3在intel-cpu-的mac上-安装最新版的完整功能包-magic-pdffull-cpu-06x-不成功

**Comment by zongzi531** [comment]
> intel mac要按这个方法装
> 
> [https://github.com/opendatalab/MinerU/blob/master/docs/FAQ_zh_cn.md#3在intel-cpu-的mac上-安装最新版的完整功能包-magic-pdffull-cpu-06x-不成功](https://github.com/opendatalab/MinerU/blob/master/docs/FAQ_zh_cn.md#3%E5%9C%A8intel-cpu-%E7%9A%84mac%E4%B8%8A-%E5%AE%89%E8%A3%85%E6%9C%80%E6%96%B0%E7%89%88%E7%9A%84%E5%AE%8C%E6%95%B4%E5%8A%9F%E8%83%BD%E5%8C%85-magic-pdffull-cpu-06x-%E4%B8%8D%E6%88%90%E5%8A%9F)

解决了我的问题，感谢！

**Comment by myhloli** [comment]
We have updated to the [0.6.2b1 release](https://github.com/opendatalab/MinerU/releases/tag/magic_pdf-0.6.2b1-released), addressing and resolving the aforementioned issue.
