### ISSUE TITLE
intel cpu无法安装detectron2

### ISSUE THREAD

**Issue by sanwacompany** [opendatalab/MinerU#222]
### Description of the bug | 错误描述

(venv) ~\PycharmProjects\Mineru
pip install detectron2 --extra-index-url https://myhloli.github.io/wheels/ 
Looking in indexes: https://pypi.org/simple, https://myhloli.github.io/wheels/
ERROR: Could not find a version that satisfies the requirement detectron2 (from versions: none)
ERROR: No matching distribution found for detectron2

### How to reproduce the bug | 如何复现

环境：intel MacBook pro， bootcamp安装64位windows 11，已经更新到最新。python版本3.12.4

在进行到“pip install detectron2 --extra-index-url https://myhloli.github.io/wheels/”这一步时，
错误提示“ERROR: Could not find a version that satisfies the requirement detectron2 (from versions: none)
ERROR: No matching distribution found for detectron2”

尝试重新安装paddlepaddle-gpu，但还是一样的问题。

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
The full-feature package depends on detectron2, which requires a compilation installation.
If you need to compile it yourself, please refer to https://github.com/facebookresearch/detectron2/issues/5114
Alternatively, you can directly use our precompiled whl package (limited to Python 3.10)

**Comment by sanwacompany** [comment]
> The full-feature package depends on detectron2, which requires a compilation installation. If you need to compile it yourself, please refer to [facebookresearch/detectron2#5114](https://github.com/facebookresearch/detectron2/issues/5114) Alternatively, you can directly use our precompiled whl package (limited to Python 3.10)

好吧非常感谢 我多去学一门技能
