### ISSUE TITLE
json.decoder.JSONDecodeError: Invalid \escape: line 7 column 21 (char 178)

### ISSUE THREAD

**Issue by huanjka119** [opendatalab/MinerU#223]
### Description of the bug | 错误描述

安装运行，出现如下报错：

(pdf) PS D:\Project\PDF\MinerU-master> magic-pdf pdf-command --pdf "D:\1.pdf" --inside_model true
2024-07-27 10:31:11.734 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:312 - not found json D:\1.json existed
2024-07-27 10:31:11.735 | ERROR    | magic_pdf.cli.magicpdf:parse_doc:338 - Invalid \escape: line 7 column 21 (char 178)
Traceback (most recent call last):

  File "\\?\D:\Python\miniconda3\envs\pdf\Scripts\magic-pdf-script.py", line 33, in <module>
    sys.exit(load_entry_point('magic-pdf==0.6.1', 'console_scripts', 'magic-pdf')())
    │   │    └ <function importlib_load_entry_point at 0x0000020CE5493D90>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "D:\Python\miniconda3\envs\pdf\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x0000020CE5F2C280>
           └ <Group cli>

  File "D:\Python\miniconda3\envs\pdf\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x0000020CE562BFD0>
         │    └ <function MultiCommand.invoke at 0x0000020CE5F2D240>
         └ <Group cli>

  File "D:\Python\miniconda3\envs\pdf\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x0000020CE5D75AE0>
           │               │       │       └ <function Command.invoke at 0x0000020CE5F2CD30>
           │               │       └ <Command pdf-command>
           │               └ <click.core.Context object at 0x0000020CE5D75AE0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x0000020CE58AEE60>

  File "D:\Python\miniconda3\envs\pdf\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'pdf': 'D:\\1.pdf', 'inside_model': True, 'model': None, 'method': 'auto', 'model_mode': 
'full'}
           │   │      │    │           └ <click.core.Context object at 0x0000020CE5D75AE0>
           │   │      │    └ <function pdf_command at 0x0000020C9D9743A0>
           │   │      └ <Command pdf-command>
           │   └ <function Context.invoke at 0x0000020CE5F17A30>
           └ <click.core.Context object at 0x0000020CE5D75AE0>

  File "D:\Python\miniconda3\envs\pdf\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'pdf': 'D:\\1.pdf', 'inside_model': True, 'model': None, 'method': 'auto', 'model_mode': 'full'}     
                       └ ()

  File "D:\Python\miniconda3\envs\pdf\lib\site-packages\magic_pdf-0.6.1-py3.10.egg\magic_pdf\cli\magicpdf.py", line 352, in pdf_command    parse_doc(pdf)
    │         └ 'D:\\1.pdf'
    └ <function pdf_command.<locals>.parse_doc at 0x0000020C9D95BF40>

> File "D:\Python\miniconda3\envs\pdf\lib\site-packages\magic_pdf-0.6.1-py3.10.egg\magic_pdf\cli\magicpdf.py", line 330, in parse_doc  
    do_parse(
    └ <function do_parse at 0x0000020C9D95BC70>

  File "D:\Python\miniconda3\envs\pdf\lib\site-packages\magic_pdf-0.6.1-py3.10.egg\magic_pdf\cli\magicpdf.py", line 91, in do_parse    
    local_image_dir, local_md_dir = prepare_env(pdf_file_name, parse_method)
                                    │           │              └ 'auto'
                                    │           └ '1'
                                    └ <function prepare_env at 0x0000020CE5D7CAF0>

  File "D:\Python\miniconda3\envs\pdf\lib\site-packages\magic_pdf-0.6.1-py3.10.egg\magic_pdf\cli\magicpdf.py", line 56, in prepare_env 
    local_parent_dir = os.path.join(get_local_dir(), "magic-pdf", pdf_file_name, method)
                       │  │    │    │                             │              └ 'auto'
                       │  │    │    │                             └ '1'
                       │  │    │    └ <function get_local_dir at 0x0000020CFFB89900>
                       │  │    └ <function join at 0x0000020CE55AAB90>
                       │  └ <module 'ntpath' from 'D:\\Python\\miniconda3\\envs\\pdf\\lib\\ntpath.py'>
                       └ <module 'os' from 'D:\\Python\\miniconda3\\envs\\pdf\\lib\\os.py'>

  File "D:\Python\miniconda3\envs\pdf\lib\site-packages\magic_pdf-0.6.1-py3.10.egg\magic_pdf\libs\config_reader.py", line 61, in get_local_dir
    config = read_config()
             └ <function read_config at 0x0000020CFFB89630>

  File "D:\Python\miniconda3\envs\pdf\lib\site-packages\magic_pdf-0.6.1-py3.10.egg\magic_pdf\libs\config_reader.py", line 26, in read_config
    config = json.load(f)
             │    │    └ <_io.TextIOWrapper name='C:\\Users\\jihui\\magic-pdf.json' mode='r' encoding='utf-8'>
             │    └ <function load at 0x0000020CE5D7D990>
             └ <module 'json' from 'D:\\Python\\miniconda3\\envs\\pdf\\lib\\json\\__init__.py'>

  File "D:\Python\miniconda3\envs\pdf\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           │     │  └ <method 'read' of '_io.TextIOWrapper' objects>
           │     └ <_io.TextIOWrapper name='C:\\Users\\jihui\\magic-pdf.json' mode='r' encoding='utf-8'>
           └ <function loads at 0x0000020CE5D7DA20>

  File "D:\Python\miniconda3\envs\pdf\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ '{\n    "bucket_info":{\n        "bucket-name-1":["ak", "sk", "endpoint"],\n        "bucket-name-2":["ak", "sk", "endpoint"]\...
           │                └ <function JSONDecoder.decode at 0x0000020CE5D7D360>
           └ <json.decoder.JSONDecoder object at 0x0000020CE5D76110>

  File "D:\Python\miniconda3\envs\pdf\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ '{\n    "bucket_info":{\n        "bucket-name-1":["ak", "sk", "endpoint"],\n        "bucket-name-2":["ak", "sk", "endpoint"]\...
               │    │          │      └ <built-in method match of re.Pattern object at 0x0000020CE591B2A0>
               │    │          └ '{\n    "bucket_info":{\n        "bucket-name-1":["ak", "sk", "endpoint"],\n        "bucket-name-2":["ak", "sk", "endpoint"]\...
               │    └ <function JSONDecoder.raw_decode at 0x0000020CE5D7D3F0>
               └ <json.decoder.JSONDecoder object at 0x0000020CE5D76110>

  File "D:\Python\miniconda3\envs\pdf\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               │    │         │  └ 0
               │    │         └ '{\n    "bucket_info":{\n        "bucket-name-1":["ak", "sk", "endpoint"],\n        "bucket-name-2":["ak", "sk", "endpoint"]\...
               │    └ <_json.Scanner object at 0x0000020CE5DA78E0>
               └ <json.decoder.JSONDecoder object at 0x0000020CE5D76110>

json.decoder.JSONDecodeError: Invalid \escape: line 7 column 21 (char 178)

请大佬指点！

### How to reproduce the bug | 如何复现

按照流程，下载源代码后，用python setup.py install 安装后，报错

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
check "magic-pdf.json" line 7 column 21 (char 178)

**Comment by huanjka119** [comment]
"models-dir":"D:\Project\PDF\PDF-Extract-Kit\models"
这样写对吗？
models安装要求下载了。

**Comment by Prudentist** [comment]
> "models-dir":"D:\Project\PDF\PDF-Extract-Kit\models" 这样写对吗？ models安装要求下载了。

得把斜线反过来写，像这样：
"models-dir":"D:/Project/PDF/PDF-Extract-Kit/models"

**Comment by myhloli** [comment]
> > "models-dir":"D:\Project\PDF\PDF-Extract-Kit\models" 这样写对吗？ models安装要求下载了。
> 
> 得把斜线反过来写，像这样： "models-dir":"D:/Project/PDF/PDF-Extract-Kit/models"

You must use "/" instead of "\\" on windows， this is right way.
