### ISSUE TITLE
demo.py下载demo1.json可以运行,但直接运行显示CustomVisionEncoderDecoderModel init后退出【已解决】

### ISSUE THREAD

**Issue by BYeHnb** [opendatalab/MinerU#228]
### Description of the bug | 错误描述

(MinerU) D:\app\MinerU>D:/Software/Anaconda/envs/MinerU/python.exe d:/app/MinerU/MinerU_main.py
2024-07-28 18:51:53.936 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 7, text_len: 31196, cid_chars_radio: 0.00022469024844321757
pipe.pipe_analyze() 1
2024-07-28 18:52:06.509 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:92 - DocAnalysis init, this may take some times. apply_layout: True, apply_formula: True, apply_ocr: False
2024-07-28 18:52:06.510 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:100 - using device: cpu
CustomVisionEncoderDecoderModel init

(MinerU) D:\app\MinerU>

### How to reproduce the bug | 如何复现

pipe.pipe_analyze()运行到这个就退出了.

### 已解决,是因为开了虚拟机,应该是CPU不太够用.把虚拟机关了就可以运行了 .

**Comment by myhloli** [comment]
please upload your code.

**Comment by BYeHnb** [comment]
import os
import json

from loguru import logger

from magic_pdf.pipe.UNIPipe import UNIPipe
from magic_pdf.rw.DiskReaderWriter import DiskReaderWriter

import magic_pdf.model as model_config 
model_config.__use_inside_model__ = True

try:
    current_script_dir = os.path.dirname(os.path.abspath(__file__))
    demo_name = "demo1"
    pdf_path = os.path.join(current_script_dir, f"{demo_name}.pdf")
    model_path = os.path.join(current_script_dir, f"{demo_name}.json")
    pdf_bytes = open(pdf_path, "rb").read()
    # model_json = json.loads(open(model_path, "r", encoding="utf-8").read())
    model_json = []  # model_json传空list使用内置模型解析
    jso_useful_key = {"_pdf_type": "", "model_list": model_json}
    local_image_dir = os.path.join(current_script_dir, 'images')
    image_dir = str(os.path.basename(local_image_dir))
    image_writer = DiskReaderWriter(local_image_dir)
    pipe = UNIPipe(pdf_bytes, jso_useful_key, image_writer)
    pipe.pipe_classify()
    """如果没有传入有效的模型数据，则使用内置model解析"""
    if len(model_json) == 0:
        if model_config.__use_inside_model__:
            print("pipe.pipe_analyze() 1")
            pipe.pipe_analyze()
            print("pipe.pipe_analyze() 2")
        else:
            logger.error("need model list input")
            exit(1)
    pipe.pipe_parse()
    md_content = pipe.pipe_mk_markdown(image_dir, drop_mode="none")
    with open(f"{demo_name}.md", "w", encoding="utf-8") as f:
        f.write(md_content)
except Exception as e:
    logger.error("An error occurred in function XYZ")
    logger.exception(e)


就加了
            print("pipe.pipe_analyze() 1")
            pipe.pipe_analyze()
            print("pipe.pipe_analyze() 2")

**Comment by myhloli** [comment]
thanks for your code. but i don't have enough information, is there any error information catched by try-except？

**Comment by BYeHnb** [comment]
在命令行可以成功输出.
demo.py打开model_json = json.loads(open(model_path, "r", encoding="utf-8").read())也可以输出demo1.md
但是model_json = []时就不行,没有更多的信息了.只知道问题在pipe.pipe_analyze().

**Comment by myhloli** [comment]
thanks for your report.
