### ISSUE TITLE
string indices must be integers

### ISSUE THREAD

**Issue by wangxinyu6666** [opendatalab/MinerU#229]
### Description of the bug | 错误描述

![recording](https://github.com/user-attachments/assets/1ad82f0f-3fbb-4bae-9d6a-39b654d2062a)

### How to reproduce the bug | 如何复现

运行出错

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
magic-pdf.json is a config json,you can't input it with model_json

**Comment by wangxinyu6666** [comment]
> magic-pdf.json is a config json,you can't input it with model_json↳

I know you said, but like blow, it doesn't work!

![image](https://github.com/user-attachments/assets/fabf0e97-9829-452f-8962-1ad8eb2e08fb)

**Comment by myhloli** [comment]
it's a interesting error,why the program use config_json to model json？ is there a json file named test.json？

**Comment by wangxinyu6666** [comment]
> it's a interesting error,why the program use config_json to model json？ is there a json file named test.json？↳

Yes, u r right. I have test all the possibilities about the config file name corresponding to the pdf file name. In order not to make mistakes, I manage to name pdf file with one same name config.json. Below is the project factory.
![image](https://github.com/user-attachments/assets/77b84316-fdc9-4a2a-9897-31c85ce63fee)

**Comment by myhloli** [comment]
if you haven't input model_json path, the program will found same name json in pdf path dir.now you can remove it and try again.

**Comment by wangxinyu6666** [comment]
same error! I decide to give it up, it's a waste of time and a rubbish project. (I think.)

**Comment by wangxinyu6666** [comment]
> if you haven't input model_json path, the program will found same name json in pdf path dir.now you can remove it and try again.↳

same error! I decide to give it up, it's a waste of time and a rubbish project. (I think.)

**Comment by myhloli** [comment]
only remove test.json,it will run.
if you can try again. please report your result.

**Comment by wangxinyu6666** [comment]
> only remove test.json,it will run. if you can try again. please report your result.↳

No, it also doesn't work.
