### ISSUE TITLE
如何在demo.py中加入可视化

### ISSUE THREAD

**Issue by ai1361720220000** [opendatalab/MinerU#235]
运行demo.py可以生成markdown结果，但是怎么在结果中添加像magic-pdf pdf-command结果出来的各种可视化结果和json文件。

**Comment by myhloli** [comment]
Maybe you can refer to this technique to enhance the demo method.
https://github.com/opendatalab/MinerU/blob/724db33dfee8ef6385aad58afe7d7f0d3ea55c29/magic_pdf/cli/magicpdf.py#L74
