### ISSUE TITLE
win10安装成功后运行命令没有报错也没看到输出文件

### ISSUE THREAD

**Issue by freedom1993** [opendatalab/MinerU#236]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/4d706483-dfd7-4415-9915-fdf7a8704f78)

### How to reproduce the bug | 如何复现

使用win10安装成功后运行命令

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
<img width="714" alt="image" src="https://github.com/user-attachments/assets/c8040c9c-f485-452a-b1cb-592d85bb517e">
can you found this dir？

**Comment by freedom1993** [comment]
no,/d/software/pdf/magic-pdf is my work dir
![image](https://github.com/user-attachments/assets/2b7e2712-e71c-49b6-a5b1-651abf67f0b8)

**Comment by freedom1993** [comment]
no
![image](https://github.com/user-attachments/assets/905f25a1-8bcf-4494-b305-de2fc51e017b)

**Comment by freedom1993** [comment]
how can i fix this problem

**Comment by myhloli** [comment]
maybe you have 2 question：
1.magic-pdf version is wrong
```bash
magic-pdf --version
```
if not 0.6.x, you need use a new clean env to install it.
2.output dir is wrong
you can mod magic-pdf.json
```json
{
"temp-output-dir":"D:/tmp",
}
```
when the program finished，you can find result in D:/tmp

**Comment by Jason-JP-Yang** [comment]
try find the absolute path? like D:/ or C:/
