### ISSUE TITLE
[QA]在线体验demo crash

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#237]
### Description of the bug | 错误描述

![img_v3_02d8_543f9817-8175-43bc-84c7-235474a63e3g](https://github.com/user-attachments/assets/64ac9d34-4b4d-42f0-beda-8f436b64a376)

### How to reproduce the bug | 如何复现

偶现
### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
fix
