### ISSUE TITLE
Degraded MPS performance

### ISSUE THREAD

**Issue by Kastakin** [opendatalab/MinerU#238]
### Description of the bug | 错误描述

MPS is much slower then CPU in extracting data from PDFs.

Is something that has been already observed and possibly related to the PYTORCH_ENABLE_MPS_FALLBACK=1 workaround also suggested in #194 ?

### How to reproduce the bug | 如何复现

1. Install MinerU
2. Run using device "cpu"
3. Run using device "mps" and using PYTORCH_ENABLE_MPS_FALLBACK=1 to allow execution
4. Observe differences in elapsed time

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

mps

**Comment by myhloli** [comment]
mps is not stable，we will remove mps support from main-line.maybe cuda is a nice way to use this project.

**Comment by Kastakin** [comment]
Unlucky but understandable. 

Is there something that can be done to improve its stability or is it purely an upstream problem?

**Comment by myhloli** [comment]
> Unlucky but understandable.
> 
> Is there something that can be done to improve its stability or is it purely an upstream problem?

Need pytorch support, we are powerless.
