### ISSUE TITLE
Ubuntu22.04相关依赖问题

### ISSUE THREAD

**Issue by newplay** [opendatalab/MinerU#242]
### Description of the bug | 错误描述

使用ubuntu22.04lts安装会有诸多依赖问题

### How to reproduce the bug | 如何复现

按照`readme.md`执行源码安装，很容易出现各种依赖问题，如paddle核心崩溃，torchtext出现`ValueError:"SP_DIR"`问题
目前测试的解决方案：
创建虚拟环境并进入创建好的虚拟环境
```bash
conda create -n MinerU python=3.10
conda activate MinerU
```
进到`MinerU`的根目录
```bash
cd /xxx/xxx/MinerU/
```
执行`setup.py`
```bash
python setup.py install
pip install detectron2 --extra-index-url https://myhloli.github.io/wheels/ 
```
### 这里可能会有一个`ImportError: libmupdf.so.24.8: cannot open shared object file: No such file or directory`的问题，找到`libmupdf.so.24.8`然后将路径放到$LD_LIBRARY_PATH即可。
```bash
find /xxx/anaconda3/envs/MinerU/ -name "libmupdf.so*"
export LD_LIBRARY_PATH=/xxx/anaconda3/envs/MinerU/lib/python3.10/site-packages/PyMuPDFb-1.24.9-py3.10-linux-x86_64.egg/pymupdf/:$LD_LIBRARY_PATH
```
接著conda install 需要的依赖：
```bash
conda install pytorch=2.3.0 torchvision=0.18.0 torchtext=0.18.0 torchaudio pytorch-cuda=11.8 cudatoolkit=11.8 cudnn paddlepaddle-gpu=3.0.0b1 paddlepaddle-cuda=11.8 -c paddle -c pytorch -c nvidia
conda install ultralytics -c conda-forge#yolo8需要安装这个

```
这里我改成pytorch=2.3.0，测试发现这个版本比较没有依赖的限制，若使用pytorch=2.3.1可能会碰到torchtext版本过低无法安装或者使用pip安装torchtext=0.18.0导致输出为`SP_DIR`而停止。
```bash
pip install paddleocr==2.7.3#需要使用pip安装，因为conda中的版本太低无法适配python3.10
pip install unimernet#执行完magic-pdf pdf-command --pdf后提示需要这个 需要使用pip安装
pip install ultralytics-thop#一样执行完后提示需要这个依赖，conda无法安装因此使用pip 安装
```
下载模型与magic-pdf.json的设置没有改变

以上是我解决Ubuntu22.04lts无法执行的方法，供大家参考

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
Thanks for your feedback. Conda is recommended for environment creation only. Try to install all dependencies using pip, which can significantly reduce version conflict issues.
Ubuntu 22.04 LTS is our mainline compatibility version. In subsequent compatibility releases, a single command will be supported to install the full package without encountering compatibility issues.

**Comment by newplay** [comment]
> Thanks for your feedback. Conda is recommended for environment creation only. Try to install all dependencies using pip, which can significantly reduce version conflict issues. Ubuntu 22.04 LTS is our mainline compatibility version. In subsequent compatibility releases, a single command will be supported to install the full package without encountering compatibility issues.

I agree with what you are saying, but I just wanted to share my solution for handling dependency issues. I encountered many problems and errors when using `pip install magic-pdf[full-cpu]`. Before the new version is released, I hope to provide a simpler workaround so that more people can try out this tool. I'm really looking forward to the new version and excited to see the improvements it will bring. 
Best Regards,
TzuChing

**Comment by myhloli** [comment]
@newplay Thank you once more for your sincere contribution，hope you have an awesome day！

**Comment by myhloli** [comment]
We update 0.6.2b1 release，solved this problem.
