### ISSUE TITLE
magic-pdf pdf-command --pdf "pdf_path" --inside_model true

### ISSUE THREAD

**Issue by beiluo** [opendatalab/MinerU#244]
### Description of the bug | 错误描述

Required dependency not installed, please install by
"pip install magic-pdf[full-cpu] detectron2 --extra-index-url https://myhloli.github.io/wheels/"

### How to reproduce the bug | 如何复现

Package                 Version
----------------------- ------------------
absl-py                 2.1.0
aiohttp                 3.9.5
aiosignal               1.3.1
albucore                0.0.12
albumentations          1.4.12
annotated-types         0.7.0
antlr4-python3-runtime  4.9.3
anyio                   4.4.0
astor                   0.8.1
async-timeout           4.0.3
attrdict                2.0.1
attrs                   23.2.0
Babel                   2.15.0
bce-python-sdk          0.9.17
beautifulsoup4          4.12.3
black                   24.4.2
blinker                 1.8.2
boto3                   1.34.150
botocore                1.34.150
braceexpand             0.1.7
Brotli                  1.1.0
cachetools              5.4.0
certifi                 2024.7.4
cffi                    1.16.0
charset-normalizer      3.3.2
click                   8.1.7
cloudpickle             3.0.0
colorama                0.4.6
coloredlogs             15.0.1
colorlog                6.8.2
contourpy               1.2.1
cryptography            43.0.0
cssselect               1.2.0
cssutils                2.11.1
cycler                  0.12.1
Cython                  3.0.10
datasets                2.20.0
decorator               5.1.1
detectron2              0.6
dill                    0.3.8
et-xmlfile              1.1.0
eva-decord              0.6.1
eval_type_backport      0.2.0
evaluate                0.4.2
exceptiongroup          1.2.2
fairscale               0.4.13
fast-langdetect         0.2.1
fasttext-wheel          0.9.2
filelock                3.15.4
fire                    0.6.0
Flask                   3.0.3
flask-babel             4.0.0
flatbuffers             24.3.25
fonttools               4.53.1
frozenlist              1.4.1
fsspec                  2024.5.0
ftfy                    6.2.0
future                  1.0.0
fvcore                  0.1.5.post20221221
grpcio                  1.65.1
h11                     0.14.0
httpcore                1.0.5
httpx                   0.27.0
huggingface-hub         0.24.3
humanfriendly           10.0
hydra-core              1.3.2
idna                    3.7
imageio                 2.34.2
imgaug                  0.4.0
intel-openmp            2021.4.0
iopath                  0.1.9
itsdangerous            2.2.0
Jinja2                  3.1.4
jmespath                1.0.1
joblib                  1.4.2
kiwisolver              1.4.5
lazy_loader             0.4
lmdb                    1.5.1
loguru                  0.7.2
lxml                    5.2.2
magic-pdf               0.6.1
Markdown                3.6
MarkupSafe              2.1.5
matplotlib              3.9.1
mkl                     2021.4.0
more-itertools          10.3.0
mpmath                  1.3.0
multidict               6.0.5
multiprocess            0.70.16
mypy-extensions         1.0.0
networkx                3.3
numpy                   1.26.4
omegaconf               2.3.0
onnxruntime             1.18.0
opencv-contrib-python   4.6.0.66
opencv-python           4.6.0.66
opencv-python-headless  4.10.0.84
openpyxl                3.1.5
opt-einsum              3.3.0
packaging               24.1
paddleocr               2.7.3
paddlepaddle            2.6.1
pandas                  2.2.2
pathspec                0.12.1
pdf2docx                0.5.8
pdfminer.six            20240706
pillow                  10.4.0
pip                     22.2.1
platformdirs            4.2.2
portalocker             2.10.1
premailer               3.10.0
protobuf                3.20.2
psutil                  6.0.0
py-cpuinfo              9.0.0
pyarrow                 17.0.0
pyarrow-hotfix          0.6
pybind11                2.13.1
pyclipper               1.3.0.post5
pycocotools             2.0.8
pycparser               2.22
pycryptodome            3.20.0
pydantic                2.8.2
pydantic_core           2.20.1
PyMuPDF                 1.24.9
PyMuPDFb                1.24.9
pyparsing               3.1.2
pyreadline3             3.4.1
python-dateutil         2.9.0.post0
python-docx             1.1.2
pytz                    2024.1
pywin32                 306
PyYAML                  6.0.1
rapidfuzz               3.9.5
rarfile                 4.2
regex                   2024.7.24
requests                2.32.3
robust-downloader       0.0.2
s3transfer              0.10.2
safetensors             0.4.3
scikit-image            0.24.0
scikit-learn            1.5.1
scipy                   1.14.0
seaborn                 0.13.2
setuptools              63.2.0
shapely                 2.0.5
six                     1.16.0
sniffio                 1.3.1
soupsieve               2.5
sympy                   1.13.1
tabulate                0.9.0
tbb                     2021.13.0
tensorboard             2.17.0
tensorboard-data-server 0.7.2
termcolor               2.4.0
threadpoolctl           3.5.0
tifffile                2024.7.24
timm                    0.9.16
tokenizers              0.19.1
tomli                   2.0.1
torch                   2.3.1
torchtext               0.18.0
torchvision             0.18.1
tqdm                    4.66.4
transformers            4.40.0
typing_extensions       4.12.2
tzdata                  2024.1
ultralytics             8.2.69
ultralytics-thop        2.0.0
unimernet               0.1.6
urllib3                 2.2.2
visualdl                2.5.3
Wand                    0.6.13
wcwidth                 0.2.13
webdataset              0.2.86
Werkzeug                3.0.3
win32-setctime          1.1.0
wordninja               2.0.0
xxhash                  3.4.1
yacs                    0.1.8
yarl                    1.9.4

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by beiluo** [comment]
目前看起来还是python版本的问题。
默认版本是3.11

**Comment by dev3py** [comment]
@beiluo  I am getting the same error how did u solve this issue?

**Comment by myhloli** [comment]
> @beiluo I am getting the same error how did u solve this issue?

```bash
pip install detectron2 --extra-index-url https://wheels.myhloli.com
pip install magic-pdf[full]==0.6.2b1
```
will help you solve this problem.

**Comment by yachty66** [comment]
no matches found: magic-pdf[full]==0.6.2b1
