### ISSUE TITLE
公式 的 中文字 不能识别

### ISSUE THREAD

**Issue by stoudjs01** [opendatalab/MinerU#247]
### Description of the bug | 错误描述

公式的中文字符会被记录为其他的不相关的英文字符。（行内公式）

![131722331953_ pic](https://github.com/user-attachments/assets/76c6e083-25e0-4d36-be93-d8964ea9ed33)
![141722332009_ pic](https://github.com/user-attachments/assets/d6588454-eab1-4eb4-b2c4-fa22b981e48b)
![151722332063_ pic](https://git
[ceshi_origin.pdf](https://github.com/user-attachments/files/16425561/ceshi_origin.pdf)
hub.com/user-attachments/assets/c75bcb7a-cc9f-4284-a59e-b0a60ad6d6c3)
[ceshi.md](https://github.com/user-attachments/files/16425563/ceshi.md)

### How to reproduce the bug | 如何复现

正常运行即可

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
@wangbinDL 公式解析的问题可以看一下。

**Comment by wangbinDL** [comment]
The formula recognition model does not support Chinese characters because the training data does not include any Chinese formulas. Please stay tuned for updates in future versions.
