### ISSUE TITLE
magic-pdf pdf-command --pdf "pdf_path" --inside_model true -> Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Invariant0502** [opendatalab/MinerU#252]
### Description of the bug | 错误描述

按流程复现
运行magic-pdf pdf-command --pdf "pdf_path" --inside_model true
报错如下：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   at::_ops::conv2d::call(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::SymInt)
1   at::native::conv2d_symint(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::SymInt)
2   at::_ops::convolution::call(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, bool, c10::ArrayRef<c10::SymInt>, c10::SymInt)
3   at::_ops::convolution::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, bool, c10::ArrayRef<c10::SymInt>, c10::SymInt)
4   at::native::convolution(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long)
5   at::_ops::_convolution::call(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, bool, c10::ArrayRef<c10::SymInt>, c10::SymInt, bool, bool, bool, bool)
6   at::native::_convolution(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool, bool)
7   at::_ops::cudnn_convolution::call(at::Tensor const&, at::Tensor const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::SymInt, bool, bool, bool)
8   at::native::cudnn_convolution(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1722363122 (unix time) try "date -d @1722363122" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x20000002ef4) received by PID 991495 (TID 0x7ffaa1cc54c0) from PID 12020 ***]

Segmentation fault (core dumped)

### How to reproduce the bug | 如何复现

按流程

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by drunkpig** [comment]
@Invariant0502 "pdf_path" in command line is a real path to a pdf file in your disk. 
For example :
```shell
magicpdf --pdf  /mnt/data/mybook.pdf  --inside_model true
```

**Comment by Invariant0502** [comment]
> @Invariant0502 "pdf_path" in command line is a real path to a pdf file in your disk. For example :
> 
> ```shell
> magicpdf --pdf  /mnt/data/mybook.pdf  --inside_model true
> ```

Of course, I did this, and it reported this error after running for a period of time.

**Comment by xzxjysgd** [comment]
我也是这样的：等待回复！！
[08/02 10:56:57 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from /home/yunke2024/MinerU/PDF-Extract-Kit/models/Layout/model_final.pth ...
[08/02 10:56:57 fvcore.common.checkpoint]: [Checkpointer] Loading from /home/yunke2024/MinerU/PDF-Extract-Kit/models/Layout/model_final.pth ...
2024-08-02 10:56:58.235 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:132 - DocAnalysis init done!
2024-08-02 10:56:58.235 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:custom_model_init:92 - model init cost: 33.7154860496521


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   at::_ops::conv2d::call(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::SymInt)
1   at::native::conv2d_symint(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::SymInt)
2   at::_ops::convolution::call(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, bool, c10::ArrayRef<c10::SymInt>, c10::SymInt)
3   at::_ops::convolution::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, bool, c10::ArrayRef<c10::SymInt>, c10::SymInt)
4   at::native::convolution(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long)
5   at::_ops::_convolution::call(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, bool, c10::ArrayRef<c10::SymInt>, c10::SymInt, bool, bool, bool, bool)
6   at::native::_convolution(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool, bool)
7   at::_ops::cudnn_convolution::call(at::Tensor const&, at::Tensor const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::SymInt, bool, bool, bool)
8   at::native::cudnn_convolution(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1722567420 (unix time) try "date -d @1722567420" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x20000002ef4) received by PID 1026855 (TID 0x7f1d7a435740) from PID 12020 ***]

Segmentation fault (core dumped)

**Comment by mynewstart** [comment]
我也是

**Comment by Invariant0502** [comment]
The issue was resolved after updating to version 6.1.2b1.

**Comment by mynewstart** [comment]
https://github.com/opendatalab/MinerU/releases/tag/magic_pdf-0.6.2b1-released is this version?

**Comment by mynewstart** [comment]
Solved this by updating toch2.3.1+cu118 to torch2.3.1+cu121

**Comment by GuokaiLiu** [comment]
> Solved this by updating toch2.3.1+cu118 to torch2.3.1+cu121

How to install torch2.3.1+cu121?
