### ISSUE TITLE
安装后版本是 0.6.1，日期 2024.7.30

### ISSUE THREAD

**Issue by GarrickLin** [opendatalab/MinerU#255]
### Description of the bug | 错误描述

使用的是清华源 https://pypi.tuna.tsinghua.edu.cn/simple
```
(pypdf) ➜  pdf_stuff pip show magic-pdf
Name: magic-pdf
Version: 0.6.1
Summary: A practical tool for converting PDF to Markdown
Home-page: https://github.com/opendatalab/MinerU
Author: 
Author-email: 
License: 
Location: /Users/garrick/anaconda3/envs/pypdf/lib/python3.10/site-packages
Requires: boto3, Brotli, click, fast-langdetect, loguru, numpy, pdfminer.six, PyMuPDF, scikit-learn, wordninja
Required-by: 
```

### How to reproduce the bug | 如何复现

pip install magic-pdf[full] -i https://pypi.tuna.tsinghua.edu.cn/simple 

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by GarrickLin** [comment]
readme 里面说版本理论上应该是 0.6.2

**Comment by myhloli** [comment]
> readme 里面说版本理论上应该是 0.6.2

full这个参数是为0.6.2设计的，目前0.6.2还没有release

**Comment by myhloli** [comment]
pip install magic-pdf[full]==0.6.2b1 -i https://mirrors.aliyun.com/pypi/simple/

0.6.2 has released.
