### ISSUE TITLE
执行pdf-command报错

### ISSUE THREAD

**Issue by antlaborli** [opendatalab/MinerU#256]
### Description of the bug | 错误描述

前期按要求安装了 pip install magic-pdf[full-cpu] detectron2 --extra-index-url https://myhloli.github.io/wheels/
执行 magic-pdf pdf-command --pdf "/home/xxx/uber_2021.pdf"  --inside_model 报错如下：
2024-07-31 13:27:50.498 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:310 - not found json /home/lihaijun/uber_2021.json existed
2024-07-31 13:27:50.499 | INFO     | magic_pdf.cli.magicpdf:do_parse:91 - local output dir is /tmp/magic-pdf/uber_2021/auto
2024-07-31 13:27:52.233 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 36572, cid_chars_radio: 0.0
2024-07-31 13:27:52.237 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:24 - Required dependency not installed, please install by
"pip install magic-pdf[full-cpu] detectron2 --extra-index-url https://myhloli.github.io/wheels/"

python 安装包如下：
Package                  Version
------------------------ ------------------
absl-py                  2.1.0
accelerate               0.30.1
aiohttp                  3.9.5
aiosignal                1.3.1
albucore                 0.0.13
albumentations           1.4.12
annotated-types          0.7.0
antlr4-python3-runtime   4.9.3
anyio                    4.4.0
astor                    0.8.1
async-timeout            4.0.3
attrdict                 2.0.1
attrs                    23.2.0
Babel                    2.15.0
bce-python-sdk           0.9.17
beautifulsoup4           4.12.3
bitsandbytes             0.43.1
black                    24.4.2
blinker                  1.8.2
boto3                    1.34.151
botocore                 1.34.151
braceexpand              0.1.7
Brotli                   1.1.0
cachetools               5.4.0
certifi                  2024.2.2
cffi                     1.16.0
charset-normalizer       3.3.2
click                    8.1.7
cloudpickle              3.0.0
colorlog                 6.8.2
contourpy                1.2.1
cryptography             43.0.0
cssselect                1.2.0
cssutils                 2.11.1
cycler                   0.12.1
Cython                   3.0.10
datasets                 2.19.1
decorator                5.1.1
deepspeed                0.14.0
detectron2               0.6
dill                     0.3.8
docstring_parser         0.16
environs                 9.5.0
et-xmlfile               1.1.0
eva-decord               0.6.1
eval_type_backport       0.2.0
evaluate                 0.4.2
exceptiongroup           1.2.2
fairscale                0.4.13
fast-langdetect          0.2.1
fasttext-wheel           0.9.2
filelock                 3.14.0
fire                     0.6.0
Flask                    3.0.3
flask-babel              4.0.0
fonttools                4.53.1
frozenlist               1.4.1
fsspec                   2024.3.1
ftfy                     6.2.0
future                   1.0.0
fvcore                   0.1.5.post20221221
grpcio                   1.63.0
h11                      0.14.0
hjson                    3.1.0
httpcore                 1.0.5
httpx                    0.27.0
huggingface-hub          0.23.1
hydra-core               1.3.2
idna                     3.7
imageio                  2.34.2
imgaug                   0.4.0
iopath                   0.1.9
itsdangerous             2.2.0
Jinja2                   3.1.4
jmespath                 1.0.1
joblib                   1.4.2
kiwisolver               1.4.5
lazy_loader              0.4
lmdb                     1.5.1
loguru                   0.7.2
lxml                     5.2.2
magic-pdf                0.6.1
Markdown                 3.6
markdown-it-py           3.0.0
MarkupSafe               2.1.5
marshmallow              3.21.3
matplotlib               3.9.1
mdurl                    0.1.2
milvus_cli               1.0.0
milvus-lite              2.4.8
more-itertools           10.3.0
mpmath                   1.3.0
multidict                6.0.5
multiprocess             0.70.16
mypy-extensions          1.0.0
networkx                 3.3
ninja                    1.11.1.1
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.5.40
nvidia-nvtx-cu12         12.1.105
omegaconf                2.3.0
opencv-contrib-python    4.6.0.66
opencv-python            4.6.0.66
opencv-python-headless   4.10.0.84
openpyxl                 3.1.5
opt-einsum               3.3.0
packaging                24.0
paddleocr                2.7.3
paddlepaddle             2.6.1
pandas                   2.2.2
pathspec                 0.12.1
pdf2docx                 0.5.8
pdfminer.six             20240706
peft                     0.11.1
pillow                   10.3.0
pip                      24.2
platformdirs             4.2.2
portalocker              2.10.1
premailer                3.10.0
protobuf                 4.25.4
psutil                   5.9.8
py-cpuinfo               9.0.0
pyarrow                  16.1.0
pyarrow-hotfix           0.6
pybind11                 2.13.1
pyclipper                1.3.0.post5
pycocotools              2.0.8
pycparser                2.22
pycryptodome             3.20.0
pydantic                 2.7.1
pydantic_core            2.18.2
Pygments                 2.18.0
pymilvus                 2.4.3
PyMuPDF                  1.24.9
PyMuPDFb                 1.24.9
pynvml                   11.5.0
pyparsing                3.1.2
python-dateutil          2.9.0.post0
python-docx              1.1.2
python-dotenv            1.0.1
pytz                     2024.1
PyYAML                   6.0.1
rapidfuzz                3.9.5
rarfile                  4.2
regex                    2024.5.15
requests                 2.31.0
rich                     13.7.1
robust-downloader        0.0.2
s3transfer               0.10.2
safetensors              0.4.3
scikit-image             0.24.0
scikit-learn             1.5.1
scipy                    1.14.0
seaborn                  0.13.2
setuptools               70.2.0
shapely                  2.0.5
shtab                    1.7.1
six                      1.16.0
sniffio                  1.3.1
soupsieve                2.5
sympy                    1.12
tabulate                 0.8.9
tensorboard              2.17.0
tensorboard-data-server  0.7.2
termcolor                2.4.0
threadpoolctl            3.5.0
tifffile                 2024.7.24
timm                     0.9.16
tokenizers               0.19.1
tomli                    2.0.1
torch                    2.3.0
torchaudio               2.3.0
torchtext                0.18.0
torchvision              0.18.0
tqdm                     4.66.4
transformers             4.40.0
triton                   2.3.0
trl                      0.8.6
typing_extensions        4.11.0
tyro                     0.8.4
tzdata                   2024.1
ujson                    5.10.0
ultralytics              8.2.70
ultralytics-thop         2.0.0
unimernet                0.1.6
urllib3                  2.2.1
visualdl                 2.5.3
Wand                     0.6.13
wcwidth                  0.2.13
webdataset               0.2.86
Werkzeug                 3.0.3
wheel                    0.43.0
wordninja                2.0.0
xxhash                   3.4.1
yacs                     0.1.8
yarl                     1.9.4

### How to reproduce the bug | 如何复现

每次执行magic-pdf pdf-command报错

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
依赖包整体是没有问题的，这个问题在0.6.2中会修复，请稍等最近就会release出来

**Comment by myhloli** [comment]
pip install magic-pdf[full]==0.6.2b1 -i https://mirrors.aliyun.com/pypi/simple/

0.6.2 has released.
