### ISSUE TITLE
为什么使用auto，先是没有使用ocr运行完后，没有生成md文件。又自动重新加载模型开始ocr

### ISSUE THREAD

**Issue by wumaotegan** [opendatalab/MinerU#267]
### Description of the bug | 错误描述

这是什么逻辑？

### How to reproduce the bug | 如何复现

![image](https://github.com/user-attachments/assets/67550e63-b496-46ca-81c1-f94364cf61a2)
![image](https://github.com/user-attachments/assets/37ae0f98-b07b-4bc4-ba54-7db3d8673412)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.9

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
parse_pdf_by_txt drop or error, switch to parse_pdf_by_ocr
