### ISSUE TITLE
AUTO模式的逻辑是什么？

### ISSUE THREAD

**Issue by wumaotegan** [opendatalab/MinerU#268]
### Description of the bug | 错误描述

为什么显示complicated_layout有20几页，但是为什么不是只对这20页进行ocr，而是全部文档？

### How to reproduce the bug | 如何复现

![image](https://github.com/user-attachments/assets/225ebc75-b9d0-4fbc-a48f-00e56c211407)
![image](https://github.com/user-attachments/assets/5f56db59-5d09-450d-9041-0db7050c588d)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.9

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
你这个是流程error了，切换到ocr是为了给数据生产兜底的，具体逻辑可以根据log提供的地址，自行查看源码

**Comment by drunkpig** [comment]
@wumaotegan complicated_layout tag  indicates that the layout of this page is complex and may have issues with text order. However, this tag does not determine whether OCR should be initiated.

**Comment by wumaotegan** [comment]
> 你这个是流程error了，切换到ocr是为了给数据生产兜底的，具体逻辑可以根据log提供的地址，自行查看源码

感谢您的回复，我发现即使是不太复杂的页面，布局识别仍不是很准。

**Comment by drunkpig** [comment]
@wumaotegan Can  you provide your pdfs to help us improve model.

**Comment by wumaotegan** [comment]
> @wumaotegan Can you provide your pdfs to help us improve model.

文档处理流程报错的原因是threadpoolctl的版本不对，安装 threadpoolctl==3.1.0后解决了。
pdf文档不太方便提供，类似下面的页面，识别错误概率很大。

![image](https://github.com/user-attachments/assets/0ee602dc-a957-416e-a20f-77f630c5d0a6)

![image](https://github.com/user-attachments/assets/76e3f3c1-d52d-4700-98d7-aaa2bb5bb3f6)

**Comment by wumaotegan** [comment]
> @wumaotegan Can you provide your pdfs to help us improve model.

![image](https://github.com/user-attachments/assets/46ff7e09-8e7f-4a75-8386-625131b85104)
