### ISSUE TITLE
希望修改输出文件的内容，请求帮助

### ISSUE THREAD

**Issue by lxc-hust** [opendatalab/MinerU#270]
希望修改运行后输出的json文件中包含的内容，例如输出文件中的一段{
        "type": "text",
        "text": "to be merged back to the base model parameters. However, LoRA’s superior performance in fine-tuning tasks has yet to reach a point that universally surpasses full parameter fine-tuning in all settings ( Ding et al. ,  2022 ; Dettmers et al. ,  2023 ). In particular, it has been observed that LoRA tends to falter on large-scale datasets during continual pre-training ( Lialin et al. ,  2023 ), which raises doubts about the effectiveness of LoRA under those circumstances. We attribute this to the much fewer trainable parameters of LoRA compared to the base model, which limits the representation power of LoRA training. "
    },中能否包含它所在的原PDF页码？谢谢！

**Comment by drunkpig** [comment]
@lxc-hust magic-pdf 0.6.2 [magic_pdf-0.6.2b1-released](https://github.com/opendatalab/MinerU/releases/tag/magic_pdf-0.6.2b1-released)  included this feature.

**Comment by lxc-hust** [comment]
已安装并获得理想的输出，非常感谢您的帮助！
