### ISSUE TITLE
生成的Markdown文档没有标题级别的区分

### ISSUE THREAD

**Issue by smdxdxd815** [opendatalab/MinerU#271]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/c168c332-3053-448c-b2d5-16b45f91a4d0)
例如上图的4与4.1,属于两个不同级别的标题，但是识别出来是同一级

### How to reproduce the bug | 如何复现

1.找了项目中demo1这个文档进行测试；
2.运行程序生成demo1.md文档

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
Currently, we will not be supporting the differentiation of multi-level directories.

**Comment by drunkpig** [comment]
We do not have a reliable method to distinguish the levels of headings, as the headings in documents come in various forms. Therefore, users need to complete this task based on the characteristics of their own documents. For example, using the height of the bounding box (bbox) of the heading as a criterion to differentiate the levels of headings. @smdxdxd815
