### ISSUE TITLE
实现文件夹内pdf批量识别

### ISSUE THREAD

**Issue by 1911xin** [opendatalab/MinerU#272]
像PDF—Extract-Kit一样实现批量识别

**Comment by myhloli** [comment]
0.6.2版本内置了一个简单的批处理功能，具体使用方法是先list出所有需要处理的pdf文件的绝对路径，写入到一个文本文件中，一行一个路径。将文本文件后缀改成.list，使用命令行pdf-command --pdf xxxx.list 程序就可以自动处理这个list文件内的所有pdf文件。

Version 0.6.2 has a simple batch processing function built in. The specific method of use is to list the absolute paths of all PDF files that need to be processed and write them into a text file, one path per line. Change the suffix of the text file to .list, and use the command line pdf-command --pdf xxxx.list. The program can automatically process all PDF files in this list file.
