### ISSUE TITLE
识别出错

### ISSUE THREAD

**Issue by ConleyKong** [opendatalab/MinerU#277]
### Description of the bug | 错误描述

CPU版本安装正常，模型下载正常，运行无报错，但是输出结果，而是出现了奇怪的提示：段错误(吐核)

### How to reproduce the bug | 如何复现

按照官方文档使用cpu安装0.6.1后识别word转换的pdf文件

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
可以试着更新到0.6.2b1版本再试试呢，这个一般是某些依赖库和系统不兼容导致的，后面调整了依赖环境，应该能解决一些

**Comment by ConleyKong** [comment]
> 可以试着更新到0.6.2b1版本再试试呢，这个一般是某些依赖库和系统不兼容导致的，后面调整了依赖环境，应该能解决一些

升级为GPU的最新版本了(cuda==12.1,pytroch==2.3.1,magic-pdf[full]==0.6.2b1)，这次给的提示比较明显了，但是不知道该怎么修复：


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1722495509 (unix time) try "date -d @1722495509" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0xa06986) received by PID 83368 (TID 0x7f182264d740) from PID 10512774 ***]

段错误(吐核)

**Comment by myhloli** [comment]
可以升级paddlepaddle到3.0.0b1解决该问题
```bash
pip install paddlepaddle==3.0.0b1
```

**Comment by ConleyKong** [comment]
> 可以升级paddlepaddle到3.0.0b1解决该问题
> 
> ```shell
> pip install paddlepaddle==3.0.0b1
> ```

重启机器后解决了，应该是服务器内存段错误，我把paddlepaddle降级到了2.4.2了也可以运行，应该不是这个paddlepaddle的事儿
