### ISSUE TITLE
建议将pipe.pipe_analyze()里面的模型初始化步骤独立出来

### ISSUE THREAD

**Issue by yqw1996** [opendatalab/MinerU#279]
建议将pipe.pipe_analyze()里面的模型初始化步骤独立出来
我将magic_pdf服务包装成一个web后端，如果提前加载好模型就可以节约每次调用时模型初始化的时间。
目前pipe.pipe_analyze()依赖于输入的pdf文件，而模型初始化并不需要输入文件

**Comment by myhloli** [comment]
包成后端之后，第一次调用的时候让程序初始化一次，后面再调用就不会初始化了，如果是做服务的话，不会在意首次初始化的时间吧

**Comment by yqw1996** [comment]
> 包成后端之后，第一次调用的时候让程序初始化一次，后面再调用就不会初始化了，如果是做服务的话，不会在意首次初始化的时间吧

这里说的初始化是哪个方法呢，我参考的demo.py，里面在pipe.pipe_analyze()初始化模型了，但是必须要在初始化UNIPipe的时候先传入pdf文件

**Comment by myhloli** [comment]
你做成服务，第一次解析的时候就有pdf传进去了，也就首次解析需要花30秒初始化模型，服务进程不死的话，第二次调用是没有模型初始化时间的

**Comment by myhloli** [comment]
unipipe是要传pdf初始化，analyse方法里面有个custommodel，那个做了单例的，你可以用多个pdf文件初始化多个unipipe，但是模型只加载一次

**Comment by yqw1996** [comment]
> unipipe是要传pdf初始化，analyse方法里面有个custommodel，那个做了单例的，你可以用多个pdf文件初始化多个unipipe，但是模型只加载一次

确实是这样，我之前第二次调用接口报错，升级后就好了，感谢答疑
