### ISSUE TITLE
在测试demo.py的时候，我用我的pdf文件出现问题

### ISSUE THREAD

**Issue by Lbaiall** [opendatalab/MinerU#289]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/8d5f5747-8511-4e1a-b4c7-9b9d96984e74)
![image](https://github.com/user-attachments/assets/e5b38dcc-2b4f-4783-a933-11820fcec9fb)
但是我在加载我的其他pdf文档的时候却又正常了

### How to reproduce the bug | 如何复现

我在安装完正常的依赖和步骤后，通过demo中的demo.py来测试，结果当我放置我的pdf文件的时候，然后取代掉我测试的代码中的时候，就出现这样的问题了

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
把图片中红色路径的.paddleocr文件夹删掉，让他重新下载一下模型就可以了，这个是上一次下载ocr模型的时候文件出错了

**Comment by Lbaiall** [comment]
感谢解决问题！！
这种问题又该怎么解决呀
![image](https://github.com/user-attachments/assets/29db3527-d933-4f5a-8116-afb13e776ded)

**Comment by myhloli** [comment]
> 感谢解决问题！！
> 
> 这种问题又该怎么解决呀
> 
> ![image](https://github.com/user-attachments/assets/29db3527-d933-4f5a-8116-afb13e776ded)
> 
> 
> 
> 

这不是没报错吗，只是个warning

**Comment by Lbaiall** [comment]
不是的，我按照你说的把那个文件删除了，它确实重新下载了，不过在这里出现需要config文件参数，
![image](https://github.com/user-attachments/assets/b9706236-6de4-464a-a138-f4313c044af3)
出现这个后
![image](https://github.com/user-attachments/assets/60a1f054-1e99-49f8-8ec5-95d2a833f775)
然后就又失败了
![image](https://github.com/user-attachments/assets/ba135c84-700c-47e3-90ed-7f98266d5114)

**Comment by myhloli** [comment]
看着是还有一个没下完，把.paddleocr删了，再把paddlepaddle卸载重装一遍试试

**Comment by Lbaiall** [comment]
我再试试，但是我做了一下对比
![image](https://github.com/user-attachments/assets/71473320-0f2e-486a-9687-ebcc2bd41784)
这个我的名字22的pdf可以处理，而且也保存了相应的图片和提取文字
![image](https://github.com/user-attachments/assets/07f48bbd-9e32-4cfb-9bc0-6b7b75488ce7)
而这个66的pdf却始终处理不了，我怀疑是不是有关我的66.pdf中包含一些特殊水印，类似于
![image](https://github.com/user-attachments/assets/cbda1cde-38c6-4826-90fa-0f4b97b21c0e)
我重新卸载了过后再重新下载再运行我的66.pdf的时候又出现了这个问题
![image](https://github.com/user-attachments/assets/dc90f343-3c77-46fc-98e6-a2738d9d7c94)

**Comment by myhloli** [comment]
因为第二篇66的文档需要ocr，ocr是个动态的开关，开启之后会调用paddleocr来处理，你的paddle模型没有下载完整，导致paddleocr初始化失败.
[inference.zip](https://github.com/user-attachments/files/16464397/inference.zip)
我本地提取了你缺失的文件，解压后，拷贝到
C:\Users\用户名\.paddleocr\whl\det\ch\ch_PP-OCRv4_det_infer
即可

**Comment by Lbaiall** [comment]
我感觉是个bug，我根据你的指示去看了一下源文件的ch_PP-OCRv4_det_infer内容，我发现是具备的inference.pdmodel，而且也是完整的大小（和你给我的文件大小一样），但是即使我替代了文件，也依然出现了这个问题
![image](https://github.com/user-attachments/assets/320a4817-abc0-4aaf-a339-d8068c9f4c03)

**Comment by myhloli** [comment]
我可以给出一个合理推测，因为你用户名是中文，导致paddle查找路径的时候出现了一些偏差，你可以更换成英文用户名再试一下啊

**Comment by Lbaiall** [comment]
感谢解答，可能是这个原因导致的，因为我当时使用Linux的时候确实没有遇到过这样的问题，但是我有一个小问题想知道，我可以通过修改路径去让paddle路径改为我自己的其他路径或者说，我该怎么改到其他位置，包括安装说明里面的config用户路径，这个是否能人为解决

**Comment by Lbaiall** [comment]
应为最终我想在colab中去测试

**Comment by myhloli** [comment]
> 感谢解答，可能是这个原因导致的，因为我当时使用Linux的时候确实没有遇到过这样的问题，但是我有一个小问题想知道，我可以通过修改路径去让paddle路径改为我自己的其他路径或者说，我该怎么改到其他位置，包括安装说明里面的config用户路径，这个是否能人为解决

paddleocr的逻辑我们没有通过代码进行干预，如果windows用户名不容易更改的话，也许你可以试试在wsl2中使用该项目

**Comment by sxk000** [comment]
@myhloli 你好，下载paddleocr模型时报错，可以把模型下载下来，然后通过设置配置参数指定模型所在的路径吗？这样的话会方便一点。

谢谢！

```
[Checkpointer] Loading from /apply/app/pdf/models/Layout/model_final.pth ...
download https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar to /root/.paddleocr/whl/det/ch/ch_PP-OCRv4_det_infer/ch_PP-OCRv4_det_infer.tar
Traceback (most recent call last):
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8f24213ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8f24213ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apply/app/pdf/demo.py", line 49, in <module>
    pdf_extract('data/新建文件夹')
  File "/apply/app/pdf/demo.py", line 38, in pdf_extract
    pipe.pipe_parse()
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 35, in pipe_parse
    self.pdf_mid_data = parse_union_pdf(self.pdf_bytes, self.model_list, self.image_writer,
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/magic_pdf/user_api.py", line 92, in parse_union_pdf
    pdf_models = doc_analyze(pdf_bytes, ocr=True)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 103, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 87, in custom_model_init
    custom_model = CustomPEKModel(ocr=ocr, show_log=show_log, models_dir=local_models_dir, device=device)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 130, in __init__
    self.ocr_model = ModifiedPaddleOCR(show_log=show_log)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 599, in __init__
    maybe_download(params.det_model_dir, det_url)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/paddleocr/ppocr/utils/network.py", line 55, in maybe_download
    download_with_progressbar(url, tmp_path)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/paddleocr/ppocr/utils/network.py", line 28, in download_with_progressbar
    response = requests.get(url, stream=True)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8f24213ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

**Comment by myhloli** [comment]
> @myhloli 你好，下载paddleocr模型时报错，可以把模型下载下来，然后通过设置配置参数指定模型所在的路径吗？这样的话会方便一点。
> 
> 
> 
> 谢谢！
> 
> 
> 
> ```
> 
> [Checkpointer] Loading from /apply/app/pdf/models/Layout/model_final.pth ...
> 
> download https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar to /root/.paddleocr/whl/det/ch/ch_PP-OCRv4_det_infer/ch_PP-OCRv4_det_infer.tar
> 
> Traceback (most recent call last):
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connection.py", line 196, in _new_conn
> 
>     sock = connection.create_connection(
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
> 
>     raise err
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
> 
>     sock.connect(sa)
> 
> OSError: [Errno 101] Network is unreachable
> 
> 
> 
> The above exception was the direct cause of the following exception:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
> 
>     response = self._make_request(
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
> 
>     raise new_e
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
> 
>     self._validate_conn(conn)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
> 
>     conn.connect()
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connection.py", line 615, in connect
> 
>     self.sock = sock = self._new_conn()
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connection.py", line 211, in _new_conn
> 
>     raise NewConnectionError(
> 
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8f24213ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable
> 
> 
> 
> The above exception was the direct cause of the following exception:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
> 
>     resp = conn.urlopen(
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
> 
>     retries = retries.increment(
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
> 
>     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
> 
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8f24213ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/apply/app/pdf/demo.py", line 49, in <module>
> 
>     pdf_extract('data/新建文件夹')
> 
>   File "/apply/app/pdf/demo.py", line 38, in pdf_extract
> 
>     pipe.pipe_parse()
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 35, in pipe_parse
> 
>     self.pdf_mid_data = parse_union_pdf(self.pdf_bytes, self.model_list, self.image_writer,
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/magic_pdf/user_api.py", line 92, in parse_union_pdf
> 
>     pdf_models = doc_analyze(pdf_bytes, ocr=True)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 103, in doc_analyze
> 
>     custom_model = model_manager.get_model(ocr, show_log)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 63, in get_model
> 
>     self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 87, in custom_model_init
> 
>     custom_model = CustomPEKModel(ocr=ocr, show_log=show_log, models_dir=local_models_dir, device=device)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 130, in __init__
> 
>     self.ocr_model = ModifiedPaddleOCR(show_log=show_log)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 599, in __init__
> 
>     maybe_download(params.det_model_dir, det_url)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/paddleocr/ppocr/utils/network.py", line 55, in maybe_download
> 
>     download_with_progressbar(url, tmp_path)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/paddleocr/ppocr/utils/network.py", line 28, in download_with_progressbar
> 
>     response = requests.get(url, stream=True)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/requests/api.py", line 73, in get
> 
>     return request("get", url, params=params, **kwargs)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/requests/api.py", line 59, in request
> 
>     return session.request(method=method, url=url, **kwargs)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
> 
>     resp = self.send(prep, **send_kwargs)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
> 
>     r = adapter.send(request, **kwargs)
> 
>   File "/apply/anaconda3/envs/p310pdf/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
> 
>     raise ConnectionError(e, request=request)
> 
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8f24213ca0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
> 
> ```

https://github.com/opendatalab/MinerU/issues/359
