### ISSUE TITLE
--method ocr参数的作用是啥？什么场景下需要加这个参数？加这个参数代码片段会被识别成1行，不加的话正常识别原始格式

### ISSUE THREAD

**Issue by freedom1993** [opendatalab/MinerU#290]
### Description of the bug | 错误描述

原始内容****
![image](https://github.com/user-attachments/assets/43a71626-db38-46c6-8f22-a354143024db)

加--method **ocr参数解析结果**
![image](https://github.com/user-attachments/assets/7696d47d-d78d-4767-b001-38e8c4df69f0)

不加--method **ocr参数解析结果**
![image](https://github.com/user-attachments/assets/f2eec121-6b31-40fc-a774-d5e11c16c591)

### How to reproduce the bug | 如何复现

 magic-pdf pdf-command --pdf agents.pdf --inside_model true --method ocr

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by drunkpig** [comment]
`--method ocr` means use paddle to get text from pdf, `--method text` means use pymuPDF  to get text from pdf.

The difference lies in that the bounding boxes obtained by pymupdf may expand irregularly in all directions, covering the surrounding text bounding boxes. This can lead to errors in position calculations. The text bounding boxes obtained through OCR are relatively reliable.

**Comment by drunkpig** [comment]
@freedom1993 We will document this phenomenon you reported as a bug and investigate the root cause.

**Comment by drunkpig** [comment]
@freedom1993 can you provide me this pdf?

**Comment by freedom1993** [comment]
sure
[A Behavior Language for Story-based Believable Agents.pdf](https://github.com/user-attachments/files/16465020/A.Behavior.Language.for.Story-based.Believable.Agents.pdf)
