### ISSUE TITLE
建议出一个去除公式检测的版本，从而可以使用Apache协议进行开源

### ISSUE THREAD

**Issue by ConleyKong** [opendatalab/MinerU#294]
当前项目的开源协议为agpl，但是我发现其实只有公式检测的YOLOv8模型为agpl导致当前项目被传染为了agpl协议，因此是否可以提供一版去除yolov8的版本，从而以Apache协议开源，这样受众会更广泛，大家用着也就没有过多的担忧了

**Comment by myhloli** [comment]
还有pymupdf，这个挺多实现要用到，暂时剥离不开

**Comment by ConleyKong** [comment]
> 还有pymupdf，这个挺多实现要用到，暂时剥离不开

好吧，这个的确是的，这个是核心部件了，剥离几乎是不可能的
