### ISSUE TITLE
如何获得每个字的坐标

### ISSUE THREAD

**Issue by 2257396011** [opendatalab/MinerU#296]
在使用ocr的时候我看获取到的坐标一般都是一句话的坐标位置，怎么能够改为ocr按字来识别，这样就能够在json文件中得到整个pdf中全部字的坐标了。

**Comment by myhloli** [comment]
ocr的最小识别单元是一行，也就是以line为单位，没办法精确到单字坐标定位

The minimum recognition unit for OCR is a line, meaning it operates on a line-by-line basis, and cannot precisely locate the coordinates of individual characters.

**Comment by 2257396011** [comment]
> ocr的最小识别单元是一行，能够清晰以线为单位，没有精确到单字坐标定位
> 
> OCR的最小识别单位是行，也就是说它是逐行进行操作的，无法精确定位单个字符的坐标。
那请问如何能够获取每个字的坐标呢，如果不适用ocr方式

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/293c9f25-e3f6-4c27-85f6-16080f9784d0)
使用pymupdf 获取页面文字信息，在char级别可以获取每个字符的坐标定位，具体的可以去看pymupdf的文档

**Comment by 2257396011** [comment]
> ![图像](https://private-user-images.githubusercontent.com/11393164/354441081-293c9f25-e3f6-4c27-85f6-16080f9784d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NjkwMzAsIm5iZiI6MTcyMjU2ODczMCwicGF0aCI6Ii8xMTM5MzE2NC8zNTQ0NDEwODEtMjkzYzlmMjUtZTNmNi00YzI3LTg1ZjYtMTYwODBmOTc4NGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDAzMTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNDUxYTFiZDg1N2IwZTg4YTE2MjkzYWFhMDM2ZGM3MzYwNzVjOGVhZDUxOWQyMTM0YTY5MWUyNDM1ZTIyOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ZUu1u1uo2W07JtL95cpiyW5W3imL87g93t_9KHx3jo) 使用pymupdf获取页面文字信息，在字符级别可以获取每个字符的坐标定位，具体的可以查看pymupdf的文档

请问项目中负责控制fitz库使用什么级别进行字符提取的位置在哪呀，没找到这部分内容

**Comment by myhloli** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/11393164/354441081-293c9f25-e3f6-4c27-85f6-16080f9784d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NjkwMzAsIm5iZiI6MTcyMjU2ODczMCwicGF0aCI6Ii8xMTM5MzE2NC8zNTQ0NDEwODEtMjkzYzlmMjUtZTNmNi00YzI3LTg1ZjYtMTYwODBmOTc4NGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDAzMTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNDUxYTFiZDg1N2IwZTg4YTE2MjkzYWFhMDM2ZGM3MzYwNzVjOGVhZDUxOWQyMTM0YTY5MWUyNDM1ZTIyOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ZUu1u1uo2W07JtL95cpiyW5W3imL87g93t_9KHx3jo) 使用pymupdf获取页面文字信息，在字符级别可以获取每个字符的坐标定位，具体的可以查看pymupdf的文档
> 
> 请问项目中负责控制fitz库使用什么级别进行字符提取的位置在哪呀，没找到这部分内容

https://github.com/opendatalab/MinerU/blob/37925f36d9f35d213c8217710e9ab12ace801a8b/magic_pdf/pdf_parse_union_core.py#L44
