### ISSUE TITLE
Error when  Paddle call for the OCR

### ISSUE THREAD

**Issue by qinyusen** [opendatalab/MinerU#298]
### Description of the bug | 错误描述

The content is consistent with the link below.
https://github.com/PaddlePaddle/PaddleOCR/issues/11631

### How to reproduce the bug | 如何复现

running with cpu, under ubuntu22.04, conda env is the same with the readme.

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
pip install paddlepaddle==3.0.0b1 

it will be work
