### ISSUE TITLE
使用cuda运行的时候报错，cpu正常

### ISSUE THREAD

**Issue by maohaodong** [opendatalab/MinerU#302]
### Description of the bug | 错误描述

安装文档的说明的依赖pip install --force-reinstall torch==2.3.1 torchvision==0.18.1 --index-url https://download.pytorch.org/whl/cu118
以及修改{
  "device-mode":"cuda"
}
按照命令启动magic-pdf pdf-command --pdf "pdf_path" --inside_model true
使用的cuda版本是11.8
且依赖安装正确
torchvision 是0.18.1
torch 是2.3.1
环境信息
 Environment info:
-------------------------------  ------------------------------------------------------------------------------------------------
sys.platform                     win32
Python                           3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)]
numpy                            1.26.4
detectron2                       0.6 @D:\develop\anaconda3\envs\MinerU\lib\site-packages\detectron2
Compiler                         MSVC 194033811
CUDA compiler                    not available
DETECTRON2_ENV_MODULE            <not set>
PyTorch                          2.3.1+cu118 @D:\develop\anaconda3\envs\MinerU\lib\site-packages\torch
PyTorch debug build              False
torch._C._GLIBCXX_USE_CXX11_ABI  False
GPU available                    Yes
GPU 0                            NVIDIA GeForce RTX 4090 D (arch=8.9)
Driver version                   555.85
CUDA_HOME                        C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
Pillow                           10.4.0
torchvision                      0.18.1+cpu @D:\develop\anaconda3\envs\MinerU\lib\site-packages\torchvision
torchvision arch flags           D:\develop\anaconda3\envs\MinerU\lib\site-packages\torchvision\_C.pyd; cannot find cuobjdump
fvcore                           0.1.5.post20221221
iopath                           0.1.9
cv2                              4.9.0

报这个错误
[08/02 13:26:22 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from D:/develop/anaconda3/envs/PDF-Extract-Kit/models\Layout/model_final.pth ...
[08/02 13:26:22 fvcore.common.checkpoint]: [Checkpointer] Loading from d:/develop/anaconda3/envs/PDF-Extract-Kit/models\Layout/model_final.pth ...
2024-08-02 13:26:23.483 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:132 - DocAnalysis init done!
2024-08-02 13:26:23.483 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:custom_model_init:92 - model init cost: 17.812323570251465
2024-08-02 13:26:24.745 | ERROR    | magic_pdf.cli.magicpdf:parse_doc:338 - Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, Meta, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
Meta: registered at /dev/null:467 [kernel]
QuantizedCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:154 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:497 [backend fallback]
Functionalize: registered at ..\aten\src\ATen\FunctionalizeFallbackKernel.cpp:324 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:18 [backend fallback]
ZeroTensor: registered at ..\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:53 [backend fallback]
AutogradCPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:57 [backend fallback]
AutogradCUDA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:65 [backend fallback]
AutogradXLA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:69 [backend fallback]
AutogradMPS: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:77 [backend fallback]
AutogradXPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:61 [backend fallback]
AutogradHPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:90 [backend fallback]
AutogradLazy: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:73 [backend fallback]
AutogradMeta: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:81 [backend fallback]
Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:297 [backend fallback]
AutocastCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\autocast\nms_kernel.cpp:34 [kernel]
AutocastCUDA: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\autocast\nms_kernel.cpp:27 [kernel]
FuncTorchBatched: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:731 [backend fallback]
BatchedNestedTensor: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:758 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ..\aten\src\ATen\functorch\VmapModeRegistrations.cpp:27 [backend fallback]
Batched: registered at ..\aten\src\ATen\LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ..\aten\src\ATen\functorch\TensorWrapper.cpp:202 [backend fallback]
PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:162 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:493 [backend fallback]
PreDispatch: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:166 [backend fallback]
PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:158 [backend fallback]

Traceback (most recent call last):

  File "D:\develop\anaconda3\envs\MinerU\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "D:\develop\anaconda3\envs\min...
           │         └ <code object <module> at 0x000001BE9DE83AA0, file "D:\develop\anaconda3\envs\mineru\Scripts\magic-pdf.exe\__main__.py", line 1>
           └ <function _run_code at 0x000001BE9DE6CCA0>

  File "D:\develop\anaconda3\envs\MinerU\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "D:\develop\anaconda3\envs\min...
         └ <code object <module> at 0x000001BE9DE83AA0, file "D:\develop\anaconda3\envs\mineru\Scripts\magic-pdf.exe\__main__.py", line 1>

  File "D:\develop\anaconda3\envs\mineru\Scripts\magic-pdf.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
    │   │    └ <Group cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x000001BE9E2D5C60>
           └ <Group cli>
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x000001BE9DED1060>
         │    └ <function MultiCommand.invoke at 0x000001BE9E2D6C20>
         └ <Group cli>
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x000001BEF4EE6B30>
           │               │       │       └ <function Command.invoke at 0x000001BE9E2D6710>
           │               │       └ <Command pdf-command>
           │               └ <click.core.Context object at 0x000001BEF4EE6B30>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x000001BE9DE5DA20>
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'pdf': 'C:\\Users\\admin\\Documents\\关于印发《宁波市海曙区科技创新产业政策专项资金管理办法》的通知.pdf', 'inside_model': True, 'model': None, 'method': 'a...
           │   │      │    │           └ <click.core.Context object at 0x000001BEF4EE6B30>
           │   │      │    └ <function pdf_command at 0x000001BEF4F08820>
           │   │      └ <Command pdf-command>
           │   └ <function Context.invoke at 0x000001BE9E2D5480>
           └ <click.core.Context object at 0x000001BEF4EE6B30>
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'pdf': 'C:\\Users\\admin\\Documents\\关于印发《宁波市海曙区科技创新产业政策专项资金管理办法》的通知.pdf', 'inside_model': True, 'model': None, 'method': 'a...
                       └ ()

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\cli\magicpdf.py", line 352, in pdf_command
    parse_doc(pdf)
    │         └ 'C:\\Users\\admin\\Documents\\关于印发《宁波市海曙区科技创新产业政策专项资金管理办法》的通知.pdf'
    └ <function pdf_command.<locals>.parse_doc at 0x000001BEF4F08550>

> File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\cli\magicpdf.py", line 330, in parse_doc
    do_parse(
    └ <function do_parse at 0x000001BEF4F08160>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\cli\magicpdf.py", line 111, in do_parse
    pipe.pipe_analyze()
    │    └ <function UNIPipe.pipe_analyze at 0x000001BEF4EFF130>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001BEF4EE66B0>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\pipe\UNIPipe.py", line 31, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True)
    │    │            │           │    └ b'%PDF-1.6\r%\xe2\xe3\xcf\xd3\r\n75 0 obj\r<</Linearized 1/L 2182181/O 77/E 156951/N 12/T 2181781/H [ 456 195]>>\rendobj\r   ...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001BEF4EE66B0>
    │    │            └ <function doc_analyze at 0x000001BEA0B2E200>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001BEF4EE66B0>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 113, in doc_analyze
    result = custom_model(img)
             │            └ array([[[255, 255, 255],
             │                      [255, 255, 255],
             │                      [255, 255, 255],
             │                      ...,
             │                      [255, 255, 255],
             │                      [255...
             └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x000001BEF4EE7A00>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 141, in __call__
    layout_res = self.layout_model(image, ignore_catids=[])
                 │    │            └ array([[[255, 255, 255],
                 │    │                      [255, 255, 255],
                 │    │                      [255, 255, 255],
                 │    │                      ...,
                 │    │                      [255, 255, 255],
                 │    │                      [255...
                 │    └ <magic_pdf.model.pek_sub_modules.layoutlmv3.model_init.Layoutlmv3_Predictor object at 0x000001BF0225FC70>
                 └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x000001BEF4EE7A00>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\model\pek_sub_modules\layoutlmv3\model_init.py", line 134, in __call__
    outputs = self.predictor(image)
              │    │         └ array([[[255, 255, 255],
              │    │                   [255, 255, 255],
              │    │                   [255, 255, 255],
              │    │                   ...,
              │    │                   [255, 255, 255],
              │    │                   [255...
              │    └ <detectron2.engine.defaults.DefaultPredictor object at 0x000001BF7FF9F220>
              └ <magic_pdf.model.pek_sub_modules.layoutlmv3.model_init.Layoutlmv3_Predictor object at 0x000001BF0225FC70>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\detectron2\engine\defaults.py", line 319, in __call__
    predictions = self.model([inputs])[0]
                  │    │      └ {'image': tensor([[[255., 255., 255.,  ..., 255., 255., 255.],
                  │    │                 [255., 255., 255.,  ..., 255., 255., 255.],
                  │    │                 ...
                  │    └ VLGeneralizedRCNN(
                  │        (backbone): FPN(
                  │          (fpn_lateral2): Conv2d(768, 256, kernel_size=(1, 1), stride=(1, 1))
                  │          (fpn_output...
                  └ <detectron2.engine.defaults.DefaultPredictor object at 0x000001BF7FF9F220>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {}
           │    │           └ ([{'image': tensor([[[255., 255., 255.,  ..., 255., 255., 255.],
           │    │                      [255., 255., 255.,  ..., 255., 255., 255.],
           │    │                    ...
           │    └ <function Module._call_impl at 0x000001BE8535AE60>
           └ VLGeneralizedRCNN(
               (backbone): FPN(
                 (fpn_lateral2): Conv2d(768, 256, kernel_size=(1, 1), stride=(1, 1))
                 (fpn_output...

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {}
           │             └ ([{'image': tensor([[[255., 255., 255.,  ..., 255., 255., 255.],
           │                        [255., 255., 255.,  ..., 255., 255., 255.],
           │                      ...
           └ <bound method VLGeneralizedRCNN.forward of VLGeneralizedRCNN(
               (backbone): FPN(
                 (fpn_lateral2): Conv2d(768, 256, kernel_...

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\model\pek_sub_modules\layoutlmv3\rcnn_vl.py", line 55, in forward
    return self.inference(batched_inputs)
           │    │         └ [{'image': tensor([[[255., 255., 255.,  ..., 255., 255., 255.],
           │    │                    [255., 255., 255.,  ..., 255., 255., 255.],
           │    │                   ...
           │    └ <function VLGeneralizedRCNN.inference at 0x000001BE992BADD0>
           └ VLGeneralizedRCNN(
               (backbone): FPN(
                 (fpn_lateral2): Conv2d(768, 256, kernel_size=(1, 1), stride=(1, 1))
                 (fpn_output...

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\model\pek_sub_modules\layoutlmv3\rcnn_vl.py", line 117, in inference
    proposals, _ = self.proposal_generator(images, features, None)
                   │                       │       └ {'p2': tensor([[[[-0.4419,  0.3926,  0.1177,  ...,  1.1292, -0.2004, -0.9965],
                   │                       │                   [-1.4375, -1.5375, -1.1382,  ..., -0...
                   │                       └ <detectron2.structures.image_list.ImageList object at 0x000001BF7FFA5510>
                   └ VLGeneralizedRCNN(
                       (backbone): FPN(
                         (fpn_lateral2): Conv2d(768, 256, kernel_size=(1, 1), stride=(1, 1))
                         (fpn_output...

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {}
           │    │           └ (<detectron2.structures.image_list.ImageList object at 0x000001BF7FFA5510>, {'p2': tensor([[[[-0.4419,  0.3926,  0.1177,  ......
           │    └ <function Module._call_impl at 0x000001BE8535AE60>
           └ RPN(
               (rpn_head): StandardRPNHead(
                 (conv): Conv2d(
                   256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
                ...

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {}
           │             └ (<detectron2.structures.image_list.ImageList object at 0x000001BF7FFA5510>, {'p2': tensor([[[[-0.4419,  0.3926,  0.1177,  ......
           └ <bound method RPN.forward of RPN(
               (rpn_head): StandardRPNHead(
                 (conv): Conv2d(
                   256, 256, kernel_size=(3, 3), stri...

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\detectron2\modeling\proposal_generator\rpn.py", line 477, in forward
    proposals = self.predict_proposals(
                │    └ <function RPN.predict_proposals at 0x000001BE99286290>
                └ RPN(
                    (rpn_head): StandardRPNHead(
                      (conv): Conv2d(
                        256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
                     ...

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\detectron2\modeling\proposal_generator\rpn.py", line 503, in predict_proposals
    return find_top_rpn_proposals(
           └ <function find_top_rpn_proposals at 0x000001BE992857E0>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\detectron2\modeling\proposal_generator\proposal_utils.py", line 121, in find_top_rpn_proposals
    keep = batched_nms(boxes.tensor, scores_per_img, lvl, nms_thresh)
           │           │     │       │               │    └ 0.7
           │           │     │       │               └ tensor([0, 0, 0,  ..., 4, 4, 4], device='cuda:0')
           │           │     │       └ tensor([ 12.2865,  11.0531,  10.9407,  ..., -25.9964, -26.6895, -27.1573], device='cuda:0')
           │           │     └ tensor([[ 374.4513, 1055.4813,  425.5862, 1070.9410],
           │           │               [ 375.1807, 1055.3943,  424.9715, 1070.4546],
           │           │               [ 377.779...
           │           └ Boxes(tensor([[ 374.4513, 1055.4813,  425.5862, 1070.9410],
           │                     [ 375.1807, 1055.3943,  424.9715, 1070.4546],
           │                     [ 3...
           └ <function batched_nms at 0x000001BE98F24D30>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\detectron2\layers\nms.py", line 22, in batched_nms
    return box_ops.batched_nms(boxes.float(), scores, idxs, iou_threshold)
           │       │           │     │        │       │     └ 0.7
           │       │           │     │        │       └ tensor([0, 0, 0,  ..., 4, 4, 4], device='cuda:0')
           │       │           │     │        └ tensor([ 12.2865,  11.0531,  10.9407,  ..., -25.9964, -26.6895, -27.1573], device='cuda:0')
           │       │           │     └ <method 'float' of 'torch._C.TensorBase' objects>
           │       │           └ tensor([[ 374.4513, 1055.4813,  425.5862, 1070.9410],
           │       │                     [ 375.1807, 1055.3943,  424.9715, 1070.4546],
           │       │                     [ 377.779...
           │       └ <function batched_nms at 0x000001BE8921ED40>
           └ <module 'torchvision.ops.boxes' from 'D:\\develop\\anaconda3\\envs\\MinerU\\lib\\site-packages\\torchvision\\ops\\boxes.py'>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\torchvision\ops\boxes.py", line 75, in batched_nms
    return _batched_nms_coordinate_trick(boxes, scores, idxs, iou_threshold)
           │                             │      │       │     └ 0.7
           │                             │      │       └ tensor([0, 0, 0,  ..., 4, 4, 4], device='cuda:0')
           │                             │      └ tensor([ 12.2865,  11.0531,  10.9407,  ..., -25.9964, -26.6895, -27.1573], device='cuda:0')
           │                             └ tensor([[ 374.4513, 1055.4813,  425.5862, 1070.9410],
           │                                       [ 375.1807, 1055.3943,  424.9715, 1070.4546],
           │                                       [ 377.779...
           └ <function _batched_nms_coordinate_trick at 0x000001BE8921EE60>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\torch\jit\_trace.py", line 1254, in wrapper
    return fn(*args, **kwargs)
           │   │       └ {}
           │   └ (tensor([[ 374.4513, 1055.4813,  425.5862, 1070.9410],
           │             [ 375.1807, 1055.3943,  424.9715, 1070.4546],
           │             [ 377.77...
           └ <function _batched_nms_coordinate_trick at 0x000001BE8921EDD0>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\torchvision\ops\boxes.py", line 94, in _batched_nms_coordinate_trick
    keep = nms(boxes_for_nms, scores, iou_threshold)
           │   │              │       └ 0.7
           │   │              └ tensor([ 12.2865,  11.0531,  10.9407,  ..., -25.9964, -26.6895, -27.1573], device='cuda:0')
           │   └ tensor([[ 374.4513, 1055.4813,  425.5862, 1070.9410],
           │             [ 375.1807, 1055.3943,  424.9715, 1070.4546],
           │             [ 377.779...
           └ <function nms at 0x000001BE8921E4D0>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\torchvision\ops\boxes.py", line 41, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           │     │   │           │   │      │       └ 0.7
           │     │   │           │   │      └ tensor([ 12.2865,  11.0531,  10.9407,  ..., -25.9964, -26.6895, -27.1573], device='cuda:0')
           │     │   │           │   └ tensor([[ 374.4513, 1055.4813,  425.5862, 1070.9410],
           │     │   │           │             [ 375.1807, 1055.3943,  424.9715, 1070.4546],
           │     │   │           │             [ 377.779...
           │     │   │           └ <OpOverloadPacket(op='torchvision.nms')>
           │     │   └ <module 'torch.ops.torchvision' from 'torch.ops'>
           │     └ <module 'torch.ops' from '_ops.py'>
           └ <module 'torch' from 'D:\\develop\\anaconda3\\envs\\MinerU\\lib\\site-packages\\torch\\__init__.py'>

  File "D:\develop\anaconda3\envs\MinerU\lib\site-packages\torch\_ops.py", line 854, in __call__
    return self_._op(*args, **(kwargs or {}))
           │     │    │        └ {}
           │     │    └ (tensor([[ 374.4513, 1055.4813,  425.5862, 1070.9410],
           │     │              [ 375.1807, 1055.3943,  424.9715, 1070.4546],
           │     │              [ 377.77...
           │     └ <built-in method nms of PyCapsule object at 0x000001BF7FFA46F0>
           └ <OpOverloadPacket(op='torchvision.nms')>

NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, Meta, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
Meta: registered at /dev/null:467 [kernel]
QuantizedCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:154 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:497 [backend fallback]
Functionalize: registered at ..\aten\src\ATen\FunctionalizeFallbackKernel.cpp:324 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:18 [backend fallback]
ZeroTensor: registered at ..\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:53 [backend fallback]
AutogradCPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:57 [backend fallback]
AutogradCUDA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:65 [backend fallback]
AutogradXLA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:69 [backend fallback]
AutogradMPS: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:77 [backend fallback]
AutogradXPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:61 [backend fallback]
AutogradHPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:90 [backend fallback]
AutogradLazy: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:73 [backend fallback]
AutogradMeta: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:81 [backend fallback]
Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:297 [backend fallback]
AutocastCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\autocast\nms_kernel.cpp:34 [kernel]
AutocastCUDA: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\autocast\nms_kernel.cpp:27 [kernel]
FuncTorchBatched: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:731 [backend fallback]
BatchedNestedTensor: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:758 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ..\aten\src\ATen\functorch\VmapModeRegistrations.cpp:27 [backend fallback]
Batched: registered at ..\aten\src\ATen\LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ..\aten\src\ATen\functorch\TensorWrapper.cpp:202 [backend fallback]
PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:162 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:493 [backend fallback]
PreDispatch: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:166 [backend fallback]
PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:158 [backend fallback]

### How to reproduce the bug | 如何复现

修改{
  "device-mode":"cuda"
}
按照命令启动magic-pdf pdf-command --pdf "pdf_path" --inside_model true

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
torchvision 0.18.1+cpu 这个版本应该不对，正确的版本应该跟torch一样以cu118结尾，可以试试卸了重装这个库
