### ISSUE TITLE
CSDN内容解析

### ISSUE THREAD

**Issue by StarDJJ2** [opendatalab/MinerU#312]
请问要如何进行CSDN博客中的内容提取呢？

**Comment by Ca1iber** [comment]
同问

**Comment by drunkpig** [comment]
try magic-html

**Comment by Ca1iber** [comment]
can u talk about it a lil more detailed? @drunkpig

**Comment by drunkpig** [comment]
> can u talk about it a lil more detailed? @drunkpig 

https://github.com/opendatalab/magic-html,this project is just you need.

**Comment by Ca1iber** [comment]
Appreciate it!! but doesn't MinerU include this function? I see the extract1 demonstration is what we talk about.

> > can u talk about it a lil more detailed? @drunkpig
> 
> https://github.com/opendatalab/magic-html,this project is just you need.

**Comment by drunkpig** [comment]
@Ca1iber we'll merge magic-html and magic-doc to minerU within the next month
