### ISSUE TITLE
官方出一份dockerfile? 根源解决文档和部署问题...

### ISSUE THREAD

**Issue by gowy222** [opendatalab/MinerU#318]
文档的部署有点繁琐,尤其是纯CPU和GPU双环境区分,

文档千言万语, 不如一份dockerfile.. 
官方dockerfile能直接部署成功, 文档就不需要过多解释, 
毕竟真正跨环境, 架构, 底层依赖各种疑难杂症, dockerfile见证一切...

**Comment by Liyu910228** [comment]
腾讯云服务器CPU部署测试正常：步骤拿去用
1.安装conda 
2.准备环境（python>3.9）
conda create -n MinerU python=3.10
conda activate MinerU
pip install detectron2 --extra-index-url https://wheels.myhloli.com/
pip install magic-pdf[full]==0.6.2b1
sudo apt-get install libgl1
3.下载模型
pip install modelscope
python
from modelscope import snapshot_download
model_dir = snapshot_download('wanderkid/PDF-Extract-Kit')
或者
git clone https://www.modelscope.cn/wanderkid/PDF-Extract-Kit.git
检查文件是否缺少
<img width="593" alt="9b990e1d746bd01054acce7e03a567d" src="https://github.com/user-attachments/assets/1e638619-fb8a-4fce-83b4-8638155c526a">
4.复制配置文件和配置设置
git clone https://github.com/opendatalab/MinerU.git
cd MinerU
cp magic-pdf.template.json ~/magic-pdf.json
在 magic-pdf.json 中，将 "models-dir" 配置为模型权重文件所在的目录。
cd ~/
magic-pdf pdf-command --pdf "/home/ubuntu/5.pdf" --inside_model true

**Comment by rockeodear** [comment]
> 腾讯云服务器CPU配置测试正常：步骤拿去用 1.安装conda 2.准备环境（python>3.9） conda create -n MinerU python=3.10 conda activate MinerU pip install detector2 --extra-index-url [https:// wheels.myhloli.com/](https://wheels.myhloli.com/) pip install magic-pdf[full]==0.6.2b1 sudo apt-get install libgl1 3.下载模型 pip install modelscope python from modelscope import snapshot_download model_dir = snapshot_download('wanderkid/PDF-Extract-Kit' ) 或者 git clone https://www.modelscope.cn/wanderkid/PDF-Extract-Kit.git 检查文件是否缺少 4.复制配置文件和配置设置 git clone https://github.com/opendatalab/MinerU.git cd MinerU cp magic-pdf.template.json ~/magic-pdf.json 在 magic-pdf.json 中，将 "models-dir" 配置为模型权重文件所在的目录。 cd ~/ magic-pdf pdf-command --pdf "/home/ubuntu/5.pdf" --inside_model true <img alt="9b990e1d746bd01054acce7e03a567d" width="593" src="https://private-user-images.githubusercontent.com/55588842/356109609-1e638619-fb8a-4fce-83b4-8638155c526a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDM3NTEsIm5iZiI6MTcyMzEwMzQ1MSwicGF0aCI6Ii81NTU4ODg0Mi8zNTYxMDk2MDktMWU2Mzg2MTktZmI4YS00ZmNlLTgzYjQtODYzODE1NWM1MjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA3NTA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZWYyOTAyY2MwYzlkYTY3ZTQ5YTY1NGMxNjZjNTE4OWZmMmViNDNiYTZiMzU2NDRlZDY0YzJiMmU1Yzg3ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F4wGtsJfAQM_M0wJDU2g2EhNIjZgUaaRMWUFwcJw_5I">[](https://github.com/opendatalab/MinerU.git)

six six six，thanks!

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/master/Dockerfile
