### ISSUE TITLE
F:\github代码\MinerU-master\magic_pdf\resources\fasttext-langdetect\lid.176.ftz cannot be opened for loading!

### ISSUE THREAD

**Issue by Alex-DeepL** [opendatalab/MinerU#320]
### Description of the bug | 错误描述

window遇到的问题.python=3.10

### How to reproduce the bug | 如何复现

F:\minionda\envs\MinerU\python.exe F:\github代码\MinerU-master\demo\demo.py 
Error loading model F:\github代码\MinerU-master\magic_pdf\resources\fasttext-langdetect\lid.176.ftz: F:\github代码\MinerU-master\magic_pdf\resources\fasttext-langdetect\lid.176.ftz cannot be opened for loading!
[2024-08-04 22:38:54,437][INFO] - File lid.176.ftz already downloaded
Error loading model F:\github代码\MinerU-master\magic_pdf\resources\fasttext-langdetect\lid.176.ftz: F:\github代码\MinerU-master\magic_pdf\resources\fasttext-langdetect\lid.176.ftz cannot be opened for loading!
[2024-08-04 22:38:56,000][INFO] - File lid.176.ftz already downloaded
2024-08-04 22:38:56.000 | ERROR    | __main__:<module>:38 - F:\github代码\MinerU-master\magic_pdf\resources\fasttext-langdetect\lid.176.ftz cannot be opened for loading!
Traceback (most recent call last):

  File "F:\github代码\MinerU-master\magic_pdf\libs\language.py", line 20, in detect_lang
    lang_upper = detect_language(text)
                 │               └ 'The response of ﬂow duration curves to afforestation\nPatrick N.J. Lanea,c,*, Alice E. Bestb,c,d, Klaus Hickelb,c, Lu Zhangb...
                 └ <function detect_language at 0x000001A7F5BCC0D0>

  File "F:\minionda\envs\MinerU\lib\site-packages\fast_langdetect\ft_detect\__init__.py", line 23, in detect_language
    lang_code = detect(sentence, low_memory=low_memory).get("lang").upper()
                │      │                    └ True
                │      └ 'The response of ﬂow duration curves to afforestation\nPatrick N.J. Lanea,c,*, Alice E. Bestb,c,d, Klaus Hickelb,c, Lu Zhangb...
                └ <function detect at 0x000001A7F5D6CE50>

  File "F:\minionda\envs\MinerU\lib\site-packages\fast_langdetect\ft_detect\infer.py", line 80, in detect
    model = get_model_loaded(low_memory=low_memory, download_proxy=model_download_proxy)
            │                           │                          └ None
            │                           └ True
            └ <function get_model_loaded at 0x000001A7F5D6CDC0>

  File "F:\minionda\envs\MinerU\lib\site-packages\fast_langdetect\ft_detect\infer.py", line 66, in get_model_loaded
    raise e

  File "F:\minionda\envs\MinerU\lib\site-packages\fast_langdetect\ft_detect\infer.py", line 61, in get_model_loaded
    loaded_model = fasttext.load_model(model_path)
                   │        │          └ 'F:\\github代码\\MinerU-master\\magic_pdf\\resources\\fasttext-langdetect\\lid.176.ftz'
                   │        └ <function load_model at 0x000001A7F5BCDB40>
                   └ <module 'fasttext' from 'F:\\minionda\\envs\\MinerU\\lib\\site-packages\\fasttext\\__init__.py'>

  File "F:\minionda\envs\MinerU\lib\site-packages\fasttext\FastText.py", line 436, in load_model
    return _FastText(model_path=path)
           │                    └ 'F:\\github代码\\MinerU-master\\magic_pdf\\resources\\fasttext-langdetect\\lid.176.ftz'
           └ <class 'fasttext.FastText._FastText'>

  File "F:\minionda\envs\MinerU\lib\site-packages\fasttext\FastText.py", line 94, in __init__
    self.f.loadModel(model_path)
    │    │ │         └ 'F:\\github代码\\MinerU-master\\magic_pdf\\resources\\fasttext-langdetect\\lid.176.ftz'
    │    │ └ <instancemethod loadModel at 0x000001A7F5BE3A60>
    │    └ <fasttext_pybind.fasttext object at 0x000001A7FF0316B0>
    └ <fasttext.FastText._FastText object at 0x000001A7F5BA2200>

ValueError: F:\github代码\MinerU-master\magic_pdf\resources\fasttext-langdetect\lid.176.ftz cannot be opened for loading!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

> File "F:\github代码\MinerU-master\demo\demo.py", line 25, in <module>
    pipe.pipe_classify()
    │    └ <function UNIPipe.pipe_classify at 0x000001A7FF4E5900>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001A7F461FF70>

  File "F:\github代码\MinerU-master\magic_pdf\pipe\UNIPipe.py", line 25, in pipe_classify
    self.pdf_type = AbsPipe.classify(self.pdf_bytes)
    │    │          │       │        │    └ b'%PDF-1.3\r%\xe2\xe3\xcf\xd3\r\n236 0 obj\r<< \r/Linearized 1 \r/O 242 \r/H [ 2994 878 ] \r/L 336919 \r/E 56128 \r/N 13 \r/T...
    │    │          │       │        └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001A7F461FF70>
    │    │          │       └ <staticmethod(<function AbsPipe.classify at 0x000001A7F81EBB50>)>
    │    │          └ <class 'magic_pdf.pipe.AbsPipe.AbsPipe'>
    │    └ ''
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001A7F461FF70>

  File "F:\github代码\MinerU-master\magic_pdf\pipe\AbsPipe.py", line 63, in classify
    pdf_meta = pdf_meta_scan(pdf_bytes)
               │             └ b'%PDF-1.3\r%\xe2\xe3\xcf\xd3\r\n236 0 obj\r<< \r/Linearized 1 \r/O 242 \r/H [ 2994 878 ] \r/L 336919 \r/E 56128 \r/N 13 \r/T...
               └ <function pdf_meta_scan at 0x000001A7F81EB010>

  File "F:\github代码\MinerU-master\magic_pdf\filter\pdf_meta_scan.py", line 337, in pdf_meta_scan
    text_language = get_language(doc)
                    │            └ Document('', <memory, doc# 1>)
                    └ <function get_language at 0x000001A7F81EAEF0>

  File "F:\github代码\MinerU-master\magic_pdf\filter\pdf_meta_scan.py", line 289, in get_language
    page_language = detect_lang(text_block)
                    │           └ 'The response of ﬂow duration curves to afforestation\nPatrick N.J. Lanea,c,*, Alice E. Bestb,c,d, Klaus Hickelb,c, Lu Zhangb...
                    └ <function detect_lang at 0x000001A7F5BBBC70>

  File "F:\github代码\MinerU-master\magic_pdf\libs\language.py", line 23, in detect_lang
    lang_upper = detect_language(html_no_ctrl_chars)
                 │               └ 'The response of ﬂow duration curves to afforestationPatrick N.J. Lanea,c,*, Alice E. Bestb,c,d, Klaus Hickelb,c, Lu Zhangb,c...
                 └ <function detect_language at 0x000001A7F5BCC0D0>

  File "F:\minionda\envs\MinerU\lib\site-packages\fast_langdetect\ft_detect\__init__.py", line 23, in detect_language
    lang_code = detect(sentence, low_memory=low_memory).get("lang").upper()
                │      │                    └ True
                │      └ 'The response of ﬂow duration curves to afforestationPatrick N.J. Lanea,c,*, Alice E. Bestb,c,d, Klaus Hickelb,c, Lu Zhangb,c...
                └ <function detect at 0x000001A7F5D6CE50>

  File "F:\minionda\envs\MinerU\lib\site-packages\fast_langdetect\ft_detect\infer.py", line 80, in detect
    model = get_model_loaded(low_memory=low_memory, download_proxy=model_download_proxy)
            │                           │                          └ None
            │                           └ True
            └ <function get_model_loaded at 0x000001A7F5D6CDC0>

  File "F:\minionda\envs\MinerU\lib\site-packages\fast_langdetect\ft_detect\infer.py", line 66, in get_model_loaded
    raise e

  File "F:\minionda\envs\MinerU\lib\site-packages\fast_langdetect\ft_detect\infer.py", line 61, in get_model_loaded
    loaded_model = fasttext.load_model(model_path)
                   │        │          └ 'F:\\github代码\\MinerU-master\\magic_pdf\\resources\\fasttext-langdetect\\lid.176.ftz'
                   │        └ <function load_model at 0x000001A7F5BCDB40>
                   └ <module 'fasttext' from 'F:\\minionda\\envs\\MinerU\\lib\\site-packages\\fasttext\\__init__.py'>

  File "F:\minionda\envs\MinerU\lib\site-packages\fasttext\FastText.py", line 436, in load_model
    return _FastText(model_path=path)
           │                    └ 'F:\\github代码\\MinerU-master\\magic_pdf\\resources\\fasttext-langdetect\\lid.176.ftz'
           └ <class 'fasttext.FastText._FastText'>

  File "F:\minionda\envs\MinerU\lib\site-packages\fasttext\FastText.py", line 94, in __init__
    self.f.loadModel(model_path)
    │    │ │         └ 'F:\\github代码\\MinerU-master\\magic_pdf\\resources\\fasttext-langdetect\\lid.176.ftz'
    │    │ └ <instancemethod loadModel at 0x000001A7F5BE3A60>
    │    └ <fasttext_pybind.fasttext object at 0x000001A7F5BE9030>
    └ <fasttext.FastText._FastText object at 0x000001A7DB394700>

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
check “lid.176.ftz” is really in F:\github代码\MinerU-master\magic_pdf\resources\fasttext-langdetect?
if not, please download from https://github.com/opendatalab/MinerU/tree/master/magic_pdf/resources/fasttext-langdetect

**Comment by Alex-DeepL** [comment]
lid.176.ftz文件在相应的目录中，还是报错

**Comment by li904775857** [comment]
最后怎么处理的呢

**Comment by Alex-DeepL** [comment]
可能是我环境的问题最终没搞定。推荐这个项目：https://github.com/VikParuchuri/surya




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月3日(星期二) 上午10:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [opendatalab/MinerU] F:\github代码\MinerU-master\magic_pdf\resources\fasttext-langdetect\lid.176.ftz cannot be opened for loading! (Issue #320)














 
最后怎么处理的呢

**Comment by li904775857** [comment]
好的，感谢

**Comment by li904775857** [comment]
fasttext路径不能有中文
