### ISSUE TITLE
求助：如何实现表格内容提取

### ISSUE THREAD

**Issue by JiangRunzhi** [opendatalab/MinerU#325]
求教一下我安装了0.6.2b1版本，为什么输出的markdown里面表格还是图片形式的呢？我修改magic-pdf.json中的"is_table_recog_enable": true, 也没作用。求助大佬

**Comment by UFOyyds** [comment]
我也提问了同样的问题，没注意您在我之前提问，不好意思啊，等待大佬回复

**Comment by myhloli** [comment]
表格解析能力目前还没有正式上线，0.6.x版本表格是作为图片直接保存到本地的，如果需要表格解析功能，需要等待0.7.x版本release。

**Comment by JiangRunzhi** [comment]
原来如此，谢谢老师

**Comment by JiangRunzhi** [comment]
> 我也提问了同样的问题，没注意您在我之前提问，不好意思啊，等待大佬回复

没关系，你太有礼貌了哈哈哈
