### ISSUE TITLE
cuda OUT OF MEMORY

### ISSUE THREAD

**Issue by rogerena09** [opendatalab/MinerU#331]
### Description of the bug | 错误描述

模式选择cuda，可以正常运行3-4个文件，然后就OOM了
算力环境8卡3090，只看到一卡在波动
请问有什么参数指定吗？

### How to reproduce the bug | 如何复现

运行  magic-pdf pdf-command --pdf "pdf_path" --inside_model true

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
目前没有适配多卡情况，应该只会占用卡1，如果你卡1上面还跑着别的吃显存的应用，可能就会oom，独享24G显存的话，通常情况下可以跑几百本维持在16～17G显存占用的。
如果需要在多机多卡的设备上运行，需要自己写调度逻辑。
