### ISSUE TITLE
'magic-pdf' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by RGthx** [opendatalab/MinerU#333]
### Description of the bug | 错误描述

虽然我按教程部署了虚拟环境以及下载了对应的模型文件等并配置好
但是命令行操作模式并不可用；也无法使用magic-pdf --version等命令查看；然而我运行示例demo.py文件是可以正常运行并输出预期md文件的
是我需要对环境变量等什么修改吗？

### How to reproduce the bug | 如何复现

(MinerU) C:\Users\rgthx\Downloads\MinerU-master\MinerU-master\demo>python demo.py
2024-08-06 00:07:26.246 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 -
 cid_count: 9, text_len: 33962, cid_chars_radio: 0.00026542408871062874
INFO:datasets:PyTorch version 2.3.1 available.
2024-08-06 00:07:35.988 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:99 - DocAnalysis init, this may take some times. apply_layout: True, apply_formula: True, apply_ocr: False
2024-08-06 00:07:35.989 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:107 - using device: cpu
2024-08-06 00:07:35.989 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:109 - using models_dir: D:/Anaconda/envs/MinerU/models
CustomVisionEncoderDecoderModel init
CustomMBartForCausalLM init
CustomMBartDecoder init
[08/06 00:07:45 detectron2]: Rank of current process: 0. World size: 1
[08/06 00:07:45 detectron2]: Environment info:
-------------------------------  ------------------------------------------------------------------------------------------------
sys.platform                     win32
Python                           3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)]
numpy                            1.26.4
detectron2                       0.6 @C:\Users\rgthx\AppData\Roaming\Python\Python310\site-packages\detectron2
Compiler                         MSVC 194033811
CUDA compiler                    not available
DETECTRON2_ENV_MODULE            <not set>
PyTorch                          2.3.1+cpu @C:\Users\rgthx\AppData\Roaming\Python\Python310\site-packages\torch
PyTorch debug build              False
torch._C._GLIBCXX_USE_CXX11_ABI  False
GPU available                    No: torch.cuda.is_available() == False
Pillow                           10.4.0
torchvision                      0.18.1+cpu @C:\Users\rgthx\AppData\Roaming\Python\Python310\site-packages\torchvision
fvcore                           0.1.5.post20221221
iopath                           0.1.9
cv2                              4.6.0
-------------------------------  ------------------------------------------------------------------------------------------------
PyTorch built with:
  - C++ Version: 201703
  - MSVC 192930154
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /bigobj /FS /utf-8 -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.1, USE_CUDA=0, USE_CUDNN=OFF, USE_CUSPARSELT=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

[08/06 00:07:45 detectron2]: Command line arguments: {'config_file': 'C:\\Users\\rgthx\\AppData\\Roaming\\Python\\Python310\\site-packages\\magic_pdf\\resources\\model_config\\layoutlmv3\\layoutlmv3_base_inference.yaml', 'resume': False, 'eval_only': False, 'num_gpus': 1, 'num_machines': 1, 'machine_rank': 0, 'dist_url': 'tcp://127.0.0.1:57823', 'opts': ['MODEL.WEIGHTS', 'D:/Anaconda/envs/MinerU/models\\Layout/model_final.pth']}
[08/06 00:07:45 detectron2]: Contents of args.config_file=C:\Users\rgthx\AppData\Roaming\Python\Python310\site-packages\magic_pdf\resources\model_config\layoutlmv3\layoutlmv3_base_inference.yaml:
AUG:
  DETR: true
CACHE_DIR: ~/cache/huggingface
CUDNN_BENCHMARK: false
DATALOADER:
  ASPECT_RATIO_GROUPING: true
  FILTER_EMPTY_ANNOTATIONS: false
  NUM_WORKERS: 4
  REPEAT_THRESHOLD: 0.0
  SAMPLER_TRAIN: TrainingSampler
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: []
  PROPOSAL_FILES_TRAIN: []
  TEST:
  - scihub_train
  TRAIN:
  - scihub_train
GLOBAL:
  HACK: 1.0
ICDAR_DATA_DIR_TEST: ''
ICDAR_DATA_DIR_TRAIN: ''
INPUT:
  CROP:
    ENABLED: true
    SIZE:
    - 384
    - 600
    TYPE: absolute_range
  FORMAT: RGB
  MASK_FORMAT: polygon
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN:
  - 480
  - 512
  - 544
  - 576
  - 608
  - 640
  - 672
  - 704
  - 736
  - 768
  - 800
  MIN_SIZE_TRAIN_SAMPLING: choice
  RANDOM_FLIP: horizontal
MODEL:
  ANCHOR_GENERATOR:
    ANGLES:
    - - -90
      - 0
      - 90
    ASPECT_RATIOS:
    - - 0.5
      - 1.0
      - 2.0
    NAME: DefaultAnchorGenerator
    OFFSET: 0.0
    SIZES:
    - - 32
    - - 64
    - - 128
    - - 256
    - - 512
  BACKBONE:
    FREEZE_AT: 2
    NAME: build_vit_fpn_backbone
  CONFIG_PATH: ''
  DEVICE: cuda
  FPN:
    FUSE_TYPE: sum
    IN_FEATURES:
    - layer3
    - layer5
    - layer7
    - layer11
    NORM: ''
    OUT_CHANNELS: 256
  IMAGE_ONLY: true
  KEYPOINT_ON: false
  LOAD_PROPOSALS: false
  MASK_ON: true
  META_ARCHITECTURE: VLGeneralizedRCNN
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: true
      INSTANCES_CONFIDENCE_THRESH: 0.5
      OVERLAP_THRESH: 0.5
      STUFF_AREA_LIMIT: 4096
    INSTANCE_LOSS_WEIGHT: 1.0
  PIXEL_MEAN:
  - 127.5
  - 127.5
  - 127.5
  PIXEL_STD:
  - 127.5
  - 127.5
  - 127.5
  PROPOSAL_GENERATOR:
    MIN_SIZE: 0
    NAME: RPN
  RESNETS:
    DEFORM_MODULATED: false
    DEFORM_NUM_GROUPS: 1
    DEFORM_ON_PER_STAGE:
    - false
    - false
    - false
    - false
    DEPTH: 50
    NORM: FrozenBN
    NUM_GROUPS: 1
    OUT_FEATURES:
    - res4
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: true
    WIDTH_PER_GROUP: 64
  RETINANET:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_WEIGHTS:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    IN_FEATURES:
    - p3
    - p4
    - p5
    - p6
    - p7
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.4
    - 0.5
    NMS_THRESH_TEST: 0.5
    NORM: ''
    NUM_CLASSES: 10
    NUM_CONVS: 4
    PRIOR_PROB: 0.01
    SCORE_THRESH_TEST: 0.05
    SMOOTH_L1_LOSS_BETA: 0.1
    TOPK_CANDIDATES_TEST: 1000
  ROI_BOX_CASCADE_HEAD:
    BBOX_REG_WEIGHTS:
    - - 10.0
      - 10.0
      - 5.0
      - 5.0
    - - 20.0
      - 20.0
      - 10.0
      - 10.0
    - - 30.0
      - 30.0
      - 15.0
      - 15.0
    IOUS:
    - 0.5
    - 0.6
    - 0.7
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS:
    - 10.0
    - 10.0
    - 5.0
    - 5.0
    CLS_AGNOSTIC_BBOX_REG: true
    CONV_DIM: 256
    FC_DIM: 1024
    NAME: FastRCNNConvFCHead
    NORM: ''
    NUM_CONV: 0
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
    SMOOTH_L1_BETA: 0.0
    TRAIN_ON_PRED_BOXES: false
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    IN_FEATURES:
    - p2
    - p3
    - p4
    - p5
    IOU_LABELS:
    - 0
    - 1
    IOU_THRESHOLDS:
    - 0.5
    NAME: CascadeROIHeads
    NMS_THRESH_TEST: 0.5
    NUM_CLASSES: 10
    POSITIVE_FRACTION: 0.25
    PROPOSAL_APPEND_GT: true
    SCORE_THRESH_TEST: 0.05
  ROI_KEYPOINT_HEAD:
    CONV_DIMS:
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    LOSS_WEIGHT: 1.0
    MIN_KEYPOINTS_PER_IMAGE: 1
    NAME: KRCNNConvDeconvUpsampleHead
    NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: true
    NUM_KEYPOINTS: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: false
    CONV_DIM: 256
    NAME: MaskRCNNConvUpsampleHead
    NORM: ''
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: ROIAlignV2
  RPN:
    BATCH_SIZE_PER_IMAGE: 256
    BBOX_REG_LOSS_TYPE: smooth_l1
    BBOX_REG_LOSS_WEIGHT: 1.0
    BBOX_REG_WEIGHTS:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    BOUNDARY_THRESH: -1
    CONV_DIMS:
    - -1
    HEAD_NAME: StandardRPNHead
    IN_FEATURES:
    - p2
    - p3
    - p4
    - p5
    - p6
    IOU_LABELS:
    - 0
    - -1
    - 1
    IOU_THRESHOLDS:
    - 0.3
    - 0.7
    LOSS_WEIGHT: 1.0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    PRE_NMS_TOPK_TRAIN: 2000
    SMOOTH_L1_BETA: 0.0
  SEM_SEG_HEAD:
    COMMON_STRIDE: 4
    CONVS_DIM: 128
    IGNORE_VALUE: 255
    IN_FEATURES:
    - p2
    - p3
    - p4
    - p5
    LOSS_WEIGHT: 1.0
    NAME: SemSegFPNHead
    NORM: GN
    NUM_CLASSES: 10
  VIT:
    DROP_PATH: 0.1
    IMG_SIZE:
    - 224
    - 224
    NAME: layoutlmv3_base
    OUT_FEATURES:
    - layer3
    - layer5
    - layer7
    - layer11
    POS_TYPE: abs
  WEIGHTS:
OUTPUT_DIR:
SCIHUB_DATA_DIR_TRAIN: ~/publaynet/layout_scihub/train
SEED: 42
SOLVER:
  AMP:
    ENABLED: true
  BACKBONE_MULTIPLIER: 1.0
  BASE_LR: 0.0002
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 2000
  CLIP_GRADIENTS:
    CLIP_TYPE: full_model
    CLIP_VALUE: 1.0
    ENABLED: true
    NORM_TYPE: 2.0
  GAMMA: 0.1
  GRADIENT_ACCUMULATION_STEPS: 1
  IMS_PER_BATCH: 32
  LR_SCHEDULER_NAME: WarmupCosineLR
  MAX_ITER: 20000
  MOMENTUM: 0.9
  NESTEROV: false
  OPTIMIZER: ADAMW
  REFERENCE_WORLD_SIZE: 0
  STEPS:
  - 10000
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 333
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: null
  WEIGHT_DECAY_NORM: 0.0
TEST:
  AUG:
    ENABLED: false
    FLIP: true
    MAX_SIZE: 4000
    MIN_SIZES:
    - 400
    - 500
    - 600
    - 700
    - 800
    - 900
    - 1000
    - 1100
    - 1200
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 1000
  EXPECTED_RESULTS: []
  KEYPOINT_OKS_SIGMAS: []
  PRECISE_BN:
    ENABLED: false
    NUM_ITER: 200
VERSION: 2
VIS_PERIOD: 0

[08/06 00:07:46 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from D:/Anaconda/envs/MinerU/models\Layout/model_final.pth ...
[08/06 00:07:46 fvcore.common.checkpoint]: [Checkpointer] Loading from d:/Anaconda/envs/MinerU/models\Layout/model_final.pth ...
2024-08-06 00:07:47.665 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:132 - DocAnalysis init done!
2024-08-06 00:07:47.666 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:custom_model_init:92 - model init cost: 21.418904542922974
2024-08-06 00:08:02.520 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 14.49

0: 1888x1408 7 embeddings, 5043.3ms
Speed: 27.0ms preprocess, 5043.3ms inference, 1.0ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:08:14.034 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 7, mfr time: 4.14
2024-08-06 00:08:35.911 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 21.88

0: 1888x1408 3 embeddings, 6740.8ms
Speed: 28.5ms preprocess, 6740.8ms inference, 1.0ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:08:46.955 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 3, mfr time: 4.25
2024-08-06 00:09:16.613 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 29.66

0: 1888x1408 18 embeddings, 2 isolateds, 6887.6ms
Speed: 26.2ms preprocess, 6887.6ms inference, 1.0ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:09:34.476 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 20, mfr time: 10.83
2024-08-06 00:09:49.655 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 15.18

0: 1888x1408 32 embeddings, 4 isolateds, 3605.5ms
Speed: 24.7ms preprocess, 3605.5ms inference, 1.0ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:10:25.533 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 36, mfr time: 32.08
2024-08-06 00:10:53.225 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 27.69

0: 1888x1408 7 embeddings, 1 isolated, 5715.7ms
Speed: 30.6ms preprocess, 5715.7ms inference, 1.0ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:11:11.822 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 8, mfr time: 12.79
2024-08-06 00:11:39.676 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 27.85

0: 1888x1408 6 embeddings, 5515.7ms
Speed: 26.1ms preprocess, 5515.7ms inference, 2.0ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:11:50.873 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 6, mfr time: 5.62
2024-08-06 00:12:18.559 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 27.69

0: 1888x1408 20 embeddings, 5642.8ms
Speed: 27.1ms preprocess, 5642.8ms inference, 2.0ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:12:41.888 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 20, mfr time: 17.55
2024-08-06 00:12:57.379 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 15.49

0: 1888x1408 7 embeddings, 4560.2ms
Speed: 15.2ms preprocess, 4560.2ms inference, 2.2ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:13:05.562 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 7, mfr time: 3.57
2024-08-06 00:13:22.253 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 16.69

0: 1888x1408 15 embeddings, 4624.4ms
Speed: 26.3ms preprocess, 4624.4ms inference, 1.0ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:13:34.929 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 15, mfr time: 7.94
2024-08-06 00:13:51.540 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 16.61

0: 1888x1408 1 embedding, 6940.7ms
Speed: 25.4ms preprocess, 6940.7ms inference, 2.0ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:14:00.052 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 1, mfr time: 1.54
2024-08-06 00:14:27.619 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 27.57

0: 1888x1408 4 embeddings, 5760.3ms
Speed: 29.9ms preprocess, 5760.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:14:38.158 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 4, mfr time: 4.72
2024-08-06 00:15:04.580 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 26.42

0: 1888x1408 1 embedding, 3774.9ms
Speed: 25.6ms preprocess, 3774.9ms inference, 0.0ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:15:09.153 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 1, mfr time: 0.77
2024-08-06 00:15:24.270 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:143 - layout detection cost: 15.12

0: 1888x1408 (no detections), 5563.2ms
Speed: 26.3ms preprocess, 5563.2ms inference, 1.3ms postprocess per image at shape (1, 3, 1888, 1408)
2024-08-06 00:15:29.863 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 0, mfr time: 0.0
2024-08-06 00:15:29.865 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:118 - doc analyze cost: 461.83641028404236
2024-08-06 00:15:33.156 | INFO     | magic_pdf.pipe.UNIPipe:pipe_mk_markdown:48 - uni_pipe mk mm_markdown finished

(MinerU) C:\Users\rgthx\Downloads\MinerU-master\MinerU-master\demo>magic-pdf --help
'magic-pdf' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
pip list看看有没有安装magic-pdf的包？

**Comment by RGthx** [comment]
使用pip list列出的列表如下图，里面是有magic-pdf的包的（不然demo.py也跑不起来）
`
C:\Users\rgthx>conda activate MinerU

(MinerU) C:\Users\rgthx>pip list
Package                 Version
----------------------- ------------------
absl-py                 2.1.0
aiohappyeyeballs        2.3.4
aiohttp                 3.10.1
aiosignal               1.3.1
albucore                0.0.13
albumentations          1.4.12
annotated-types         0.7.0
antlr4-python3-runtime  4.9.3
anyio                   4.4.0
astor                   0.8.1
async-timeout           4.0.3
attrdict                2.0.1
attrs                   24.1.0
Babel                   2.15.0
bce-python-sdk          0.9.19
beautifulsoup4          4.12.3
black                   24.8.0
blinker                 1.8.2
boto3                   1.34.153
botocore                1.34.153
braceexpand             0.1.7
Brotli                  1.1.0
cachetools              5.4.0
certifi                 2024.7.4
cffi                    1.16.0
charset-normalizer      3.3.2
click                   8.1.7
cloudpickle             3.0.0
colorama                0.4.6
colorlog                6.8.2
contourpy               1.2.1
cryptography            43.0.0
cssselect               1.2.0
cssutils                2.11.1
cycler                  0.12.1
Cython                  3.0.11
datasets                2.20.0
decorator               5.1.1
detectron2              0.6
dill                    0.3.8
et-xmlfile              1.1.0
eva-decord              0.6.1
eval_type_backport      0.2.0
evaluate                0.4.2
exceptiongroup          1.2.2
fairscale               0.4.13
fast-langdetect         0.2.0
fasttext-wheel          0.9.2
filelock                3.15.4
fire                    0.6.0
Flask                   3.0.3
flask-babel             4.0.0
fonttools               4.53.1
frozenlist              1.4.1
fsspec                  2024.5.0
ftfy                    6.2.0
future                  1.0.0
fvcore                  0.1.5.post20221221
grpcio                  1.65.4
h11                     0.14.0
httpcore                1.0.5
httpx                   0.27.0
huggingface-hub         0.24.5
hydra-core              1.3.2
idna                    3.7
imageio                 2.34.2
imgaug                  0.4.0
intel-openmp            2021.4.0
iopath                  0.1.9
itsdangerous            2.2.0
Jinja2                  3.1.4
jmespath                1.0.1
joblib                  1.4.2
kiwisolver              1.4.5
langdetect              1.0.9
lazy_loader             0.4
lmdb                    1.5.1
loguru                  0.7.2
lxml                    5.2.2
magic-pdf               0.6.2b1
Markdown                3.6
MarkupSafe              2.1.5
matplotlib              3.9.0
mkl                     2021.4.0
more-itertools          10.3.0
mpmath                  1.3.0
multidict               6.0.5
multiprocess            0.70.16
mypy-extensions         1.0.0
networkx                3.3
numpy                   1.26.4
omegaconf               2.3.0
opencv-contrib-python   4.6.0.66
opencv-python           4.6.0.66
opencv-python-headless  4.10.0.84
openpyxl                3.1.5
opt-einsum              3.3.0
packaging               24.1
paddleocr               2.7.3
paddlepaddle            2.6.1
pandas                  2.2.2
pathspec                0.12.1
pdf2docx                0.5.8
pdfminer.six            20231228
pillow                  10.4.0
pip                     24.0
platformdirs            4.2.2
portalocker             2.10.1
premailer               3.10.0
protobuf                3.20.2
psutil                  6.0.0
py-cpuinfo              9.0.0
pyarrow                 17.0.0
pyarrow-hotfix          0.6
pybind11                2.13.1
pyclipper               1.3.0.post5
pycocotools             2.0.8
pycparser               2.22
pycryptodome            3.20.0
pydantic                2.8.2
pydantic_core           2.20.1
PyMuPDF                 1.24.9
PyMuPDFb                1.24.9
pyparsing               3.1.2
python-dateutil         2.9.0.post0
python-docx             1.1.2
pytz                    2024.1
pywin32                 306
PyYAML                  6.0.1
rapidfuzz               3.9.5
rarfile                 4.2
regex                   2024.7.24
requests                2.32.3
robust-downloader       0.0.2
s3transfer              0.10.2
safetensors             0.4.4
scikit-image            0.24.0
scikit-learn            1.5.1
scipy                   1.14.0
seaborn                 0.13.2
setuptools              72.1.0
shapely                 2.0.5
six                     1.16.0
sniffio                 1.3.1
soupsieve               2.5
sympy                   1.13.1
tabulate                0.9.0
tbb                     2021.13.0
tensorboard             2.17.0
tensorboard-data-server 0.7.2
termcolor               2.4.0
threadpoolctl           3.5.0
tifffile                2024.7.24
timm                    0.9.16
tokenizers              0.19.1
tomli                   2.0.1
torch                   2.3.1
torchtext               0.18.0
torchvision             0.18.1
tqdm                    4.66.5
transformers            4.40.0
typing_extensions       4.12.2
tzdata                  2024.1
ultralytics             8.2.73
ultralytics-thop        2.0.0
unimernet               0.1.6
urllib3                 2.2.2
visualdl                2.5.3
Wand                    0.6.13
wcwidth                 0.2.13
webdataset              0.2.86
Werkzeug                3.0.3
wheel                   0.43.0
win32-setctime          1.1.0
wordninja               2.0.0
xxhash                  3.4.1
yacs                    0.1.8
yarl                    1.9.4

(MinerU) C:\Users\rgthx>magic-pdf -v
'magic-pdf' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

(MinerU) C:\Users\rgthx>
`

**Comment by RGthx** [comment]
抱歉，解决了
解决方法是在管理员权限下的Anaconda prompt内激活对应虚拟环境并配置
我之前是直接终端内激活的环境；pip默认下载到了c盘里
参考：https://blog.csdn.net/m0_65634471/article/details/130297467
