### ISSUE TITLE
Can `pdf_res_path` be set to configurable?

### ISSUE THREAD

**Issue by naiij** [opendatalab/MinerU#334]
**Is your feature request related to a problem? Please describe.**
每次都去 `/tmp` 目录复制粘贴出来有点不方便

**Describe the solution you'd like**
可以在`magic-pdf.json` 中被配置，另外是否有可能指定 `magic-pdf.json`的位置，比如我想放在`~/.config/magic-pdf.json`

另外，很好用的工具，支持作者❤️

**Comment by myhloli** [comment]
在magic-pdf.json的根层级添加
"temp-output-dir":"/tmp",
其中"/tmp"可以自定义成你要输出的目录。

Add to the root level of `magic-pdf.json`:
```json
"temp-output-dir": "/tmp",
```
where `"/tmp"` can be customized to the directory where you want to output the files.
