### ISSUE TITLE
有些表格解析了但是没有输出结果

### ISSUE THREAD

**Issue by 2257396011** [opendatalab/MinerU#335]
### Description of the bug | 错误描述

从这里可以看出来应该识别到了6个表格，输出应该有6个表格的结果。但是其中第二个表格还是图片形式的，没有替换为表格，按理说只要识别到了应该就能转换成功呀，这是为什么。
![屏幕截图 2024-08-06 101023](https://github.com/user-attachments/assets/f29c609f-8ec1-4471-91e3-423c6c1fa416)
[1.md](https://github.com/user-attachments/files/16504409/1.md)
[1.pdf](https://github.com/user-attachments/files/16504410/1.pdf)

### How to reproduce the bug | 如何复现

运行magic_pdf_parse_main.py

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
表格解析超时了，程序认为这张表格转换失败，所以使用了图片输出代替。  
如果可以等待更长时间以获得完整表格输出，请修改magic-pdf.json中的max_time项

**Comment by 2257396011** [comment]
> 表格解析超时了，程序认为这张表格转换失败，所以使用了图片输出代替。 如果可以等待更长时间以获得完整表格输出，请修改magic-pdf.json中的max_time项

明白了，感谢
