### ISSUE TITLE
报错：ModuleNotFoundError: No module named 'struct_eqtable'

### ISSUE THREAD

**Issue by CocoaML** [opendatalab/MinerU#336]
### Description of the bug | 错误描述

更新最新代码后，报错：ModuleNotFoundError: No module named 'struct_eqtable'

### How to reproduce the bug | 如何复现

~/MinerU/magic_pdf/model/pek_sub_modules/structeqtable/StructTableModel.py", line 1, in <module>
    from struct_eqtable.model import StructTable

ModuleNotFoundError: No module named 'struct_eqtable'

magic-pdf --version
magic-pdf, version 0.6.2b1

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
pip install struct-eqtable

**Comment by CocoaML** [comment]
> pip install struct-eqtable

感谢您的回复。

请问如何激活表格识别呢？
magic-pdf pdf-command --pdf "~/mypdf/a1.pdf" --inside_model true

如何修改这个命令使用ocr模式呢？

期待您的回复。

**Comment by CocoaML** [comment]
> pip install struct-eqtable

谢谢，感谢你的回复。

**Comment by WangJianQ-0118** [comment]
ModuleNotFoundError: No module named 'struct_eqtable.model' 这是什么报错

**Comment by myhloli** [comment]
> ModuleNotFoundError: No module named 'struct_eqtable.model' 这是什么报错

看了下是这个库更新了，没有对应的模块了，临时解决需要
`pip install struct-eqtable==0.1.0`
