### ISSUE TITLE
所有表格解析的结果都是图片

### ISSUE THREAD

**Issue by jujulovesstudying** [opendatalab/MinerU#338]
### Description of the bug | 错误描述

上传的pdf中有两个表格：但是全部以图片形式输出，也看不出识别为table的过程，不知道怎么调整，求助
![1](https://github.com/user-attachments/assets/1cbc8b90-0974-4193-b33a-6f87ca6bbecd)
已更新为0.6.2版本

### How to reproduce the bug | 如何复现

已设置：
"device-mode": "cuda",
    "table-config": {
        "is_table_recog_enable": true,
        "max_time": 1000
    }
}

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
0.6.2不支持表格识别，目前表格识别只在master分支中进行测试，如果需要使用，需要源码安装或者等待0.7.x版本release

**Comment by JiangRunzhi** [comment]
> 0.6.2不支持表格识别，目前表格识别只在master分支中进行测试，如果需要使用，需要源码安装或者等待0.7.x版本release

老师，0.7.x版本这周会有吗

**Comment by myhloli** [comment]
> > 0.6.2不支持表格识别，目前表格识别只在master分支中进行测试，如果需要使用，需要源码安装或者等待0.7.x版本release
> 
> 
> 
> 老师，0.7.x版本这周会有吗

今天在打包了，后续要看QA的测试反馈
