### ISSUE TITLE
magic-pdf -p

### ISSUE THREAD

**Issue by ywm108** [opendatalab/MinerU#340]
### Description of the bug | 错误描述

Error: No such option: -p

### How to reproduce the bug | 如何复现

magic-pdf -p
Usage: magic-pdf [OPTIONS] COMMAND [ARGS]...

Error: No such option: -p

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
-p is for 0.7.x
0.6.x need use cli by https://github.com/opendatalab/MinerU#1usage-via-command-line

**Comment by sandyw-nvidia** [comment]
@myhloli 你的文件裡面的 cli 還是有 -p，0.6 還是用不了
我後來升版之後解決了
pip unintall magic-pdf
pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/
