### ISSUE TITLE
腾讯云的轻量化服务器能否部署？

### ISSUE THREAD

**Issue by samqin123** [opendatalab/MinerU#345]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
对存在的问题进行清晰且简洁的描述。例如：我一直很困扰的是 [...]
【sam】我们构建了一个RAG应用(https://github.com/PancrePal-xiaoyibao/PancrePal-xiaoyibao), 一直没有很好的解决知识库图文混编，以及RAG知识库内容的质量提升，MinerU是个不错的尝试。

本地化测试情况顺利，现在想在2c4g的轻量化服务器上部署，便于和同样环境部署的fastgpt配合导入以及应用图片链接。这是很重要的原因。

**Describe the solution you'd like**
**描述您期望的解决方案**

【sam】能够支持轻量化服务器部署和应用。既然支持cpu，无非就是慢一点，但是对于量少，计算压力不大的，应该可以有轻量化的版本可能性吧。

清晰且简洁地描述您希望实现的内容。
【sam】能够支持2c4g的部署和应用，完成对pdf和网页（html类型的知识库）进行转化就可以。最好能够和fastgpt结合测试，导入部分现在看会被切割，还有md文件的图片链接，使用相对地址的测试没有完全通过。

**Describe alternatives you've considered**
**描述您已考虑的替代方案**

清晰且简洁地描述您已经考虑过的任何替代解决方案。

**Additional context**
**提供更多细节**
请附上任何相关截图、链接或文件，以帮助我们更好地理解您的请求。

**Comment by myhloli** [comment]
项目运行需要至少16g内存空间，2c4g明显达不到运行的最低要求。
