### ISSUE TITLE
Mac M1使用mps报错

### ISSUE THREAD

**Issue by samqin123** [opendatalab/MinerU#346]
### Description of the bug | 错误描述

2024-08-07 07:43:27.974 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:173 - formula nums: 3, mfr time: 8.61
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG13XFamilyCommandBuffer: 0x35bc5d8a0>
    label = <none> 
    device = <AGXG13XDevice: 0x31fb40800>
        name = Apple M1 Pro 
    commandQueue = <AGXG13XFamilyCommandQueue: 0x31fbe5600>
        label = <none> 
        device = <AGXG13XDevice: 0x31fb40800>
            name = Apple M1 Pro 
    retainedReferences = 1
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG13XFamilyCommandBuffer: 0x335ba02d0>
    label = <none> 
    device = <AGXG13XDevice: 0x31fb40800>
        name = Apple M1 Pro 
    commandQueue = <AGXG13XFamilyCommandQueue: 0x31fbe5600>
        label = <none> 
        device = <AGXG13XDevice: 0x31fb40800>
            name = Apple M1 Pro 
    retainedReferences = 1
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG13XFamilyCommandBuffer: 0x357fc44b0>
    label = <none> 
    device = <AGXG13XDevice: 0x31fb40800>
        name = Apple M1 Pro 
    commandQueue = <AGXG13XFamilyCommandQueue: 0x31fbe5600>
        label = <none> 
        device = <AGXG13XDevice: 0x31fb40800>
            name = Apple M1 Pro 
    retainedReferences = 1
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG13XFamilyCommandBuffer: 0x35e0e71b0>
    label = <none> 
    device = <AGXG13XDevice: 0x31fb40800>
        name = Apple M1 Pro 
    commandQueue = <AGXG13XFamilyCommandQueue: 0x31fbe5600>
        label = <none> 
        device = <AGXG13XDevice: 0x31fb40800>
            name = Apple M1 Pro 
    retainedReferences = 1
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG13XFamilyCommandBuffer: 0x35bca7a60>
    label = <none> 
    device = <AGXG13XDevice: 0x31fb40800>
        name = Apple M1 Pro 
    commandQueue = <AGXG13XFamilyCommandQueue: 0x31fbe5600>
        label = <none> 
        device = <AGXG13XDevice: 0x31fb40800>
            name = Apple M1 Pro 
    retainedReferences = 1
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG13XFamilyCommandBuffer: 0x35bcaa170>
    label = <none> 
    device = <AGXG13XDevice: 0x31fb40800>
        name = Apple M1 Pro 
    commandQueue = <AGXG13XFamilyCommandQueue: 0x31fbe5600>
        label = <none> 
        device = <AGXG13XDevice: 0x31fb40800>
            name = Apple M1 Pro 
    retainedReferences = 1
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG13XFamilyCommandBuffer: 0x35bcaab40>
    label = <none> 
    device = <AGXG13XDevice: 0x31fb40800>
        name = Apple M1 Pro 
    commandQueue = <AGXG13XFamilyCommandQueue: 0x31fbe5600>
        label = <none> 
        device = <AGXG13XDevice: 0x31fb40800>
            name = Apple M1 Pro 
    retainedReferences = 1
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG13XFamilyCommandBuffer: 0x35e139930>
    label = <none> 
    device = <AGXG13XDevice: 0x31fb40800>
        name = Apple M1 Pro 
    commandQueue = <AGXG13XFamilyCommandQueue: 0x31fbe5600>
        label = <none> 
        device = <AGXG13XDevice: 0x31fb40800>
            name = Apple M1 Pro 
    retainedReferences = 1
Error: command buffer exited with error status.
        The Metal Performance Shaders operations encoded on it may not have completed.
        Error: 
        (null)
        Internal Error (0000000e:Internal Error)
        <AGXG13XFamilyCommandBuffer: 0x35e0e6af0>
    label = <none> 
    device = <AGXG13XDevice: 0x31fb40800>
        name = Apple M1 Pro 
    commandQueue = <AGXG13XFamilyCommandQueue: 0x31fbe5600>
        label = <none> 
        device = <AGXG13XDevice: 0x31fb40800>
            name = Apple M1 Pro 
    retainedReferences = 1

### How to reproduce the bug | 如何复现

<img width="375" alt="image" src="https://github.com/user-attachments/assets/854a56c5-d62e-4019-9089-c5dfaa6200fb">

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

mps

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/issues/238#issuecomment-2256390257
