### ISSUE TITLE
【文档refine】说明模型下载的模型文件的目录等于magic-pdf.json里model_dir

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#348]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/25ccef84-950e-432b-bef0-303610e19b94)

### How to reproduce the bug | 如何复现

无需复现

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
fixed
