### ISSUE TITLE
magic-pdf, version 0.6.2b1的--help结果还是和老版本一样，没有readmev2里的效果

### ISSUE THREAD

**Issue by WillingLau** [opendatalab/MinerU#352]
### Description of the bug | 错误描述

magic-pdf, version 0.6.2b1的--help结果还是和老版本一样，没有readmev2里展示的效果，参数列表和老版本不一样

### How to reproduce the bug | 如何复现

magic-pdf --help
Usage: magic-pdf [OPTIONS] COMMAND [ARGS]...

Options:
  -v, --version  显示版本信息
  -h, --help     显示帮助信息

Commands:
  json-command
  local-json-command
  pdf-command

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by drunkpig** [comment]
@WillingLau this document_v2 for version 0.7.0 only.
