### ISSUE TITLE
【文档】文档里"额外步骤"建议修改

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#353]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/ce86a523-ab68-487c-91f0-df31053fbeb5)
这个步骤从使用层面是和前面1、2连接起来的，建议修改为步骤三、四 这样

### How to reproduce the bug | 如何复现

无需复现

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
fixed
