### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by THEONEBUKE** [opendatalab/MinerU#356]
### Description of the bug | 错误描述

https://github.com/opendatalab/MinerU/issues/252#issue-2438426546 和这一样

### How to reproduce the bug | 如何复现

成功部署了模型并成功解析PDF后，准备再测试ocr开启cuda加速时出现了该问题：
`python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/`
然后
`magic-pdf pdf-command --pdf "pdf_path" `

我实际使用的是大概38MB，180页的pdf，怀疑是文件太大，页数过多的问题，换了demo中的small_ocr.pdf也还是一样的报错
怀疑是paddlepaddle-gpu包的问题，但卸载重装了还是一样的报错
查了下issue根据 https://github.com/opendatalab/MinerU/issues/277#issuecomment-2262278736 重启了机器也还是一样

解决办法：
卸载所有第三方库：
`pip freeze >requirements.txt`
`pip uninstall -r requirements.txt -y`

再重新安装：
`pip install magic-pdf[full]==0.6.2b1 detectron2 --extra-index-url https://wheels.myhloli.com -i https://pypi.tuna.tsinghua.edu.cn/simple`

之后没有进行`python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/`，便能正常运行，至于 
 https://github.com/opendatalab/MinerU/issues/252#issuecomment-2271283898 提到的解决办法还没有进行测试

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
ubuntu下torch和paddle同时使用加速的基础是torch使用12.1的cuda，而paddle使用11.8的，我自己测试同时用11.x或者同时用12.x都会有冲突问题，可能你之前装过cu118的torch，后面装paddle的时候冲突了，后面通过卸载依赖再重装带进来的torch应该是cu121版本，就解决了冲突。

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/issues/252#issuecomment-2271283898
可能直接按这个操作就ok了？

**Comment by THEONEBUKE** [comment]
是不是执行`python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/`，会导致torch安装为cu11x版本的，得再把torch版本还原为cu12x版本的

**Comment by myhloli** [comment]
> 是不是执行`python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/`，会导致torch安装为cu11x版本的，得再把torch版本还原为cu12x版本的

ubuntu下torch和paddle都可以用自己独立的cuda环境，前提是两个cuda的大版本不相同。如果torch之前装了cu12的，再装paddlecu11是不影响的，但是如果之前装过cu11的torch就会冲突

**Comment by THEONEBUKE** [comment]
> > 是不是执行`python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/`，会导致torch安装为cu11x版本的，得再把torch版本还原为cu12x版本的
> 
> ubuntu下torch和paddle都可以用自己独立的cuda环境，前提是两个cuda的大版本不相同。如果torch之前装了cu12的，再装paddlecu11是不影响的，但是如果之前装过cu11的torch就会冲突

好的，感谢解答 0^v^0
