### ISSUE TITLE
Customize request

### ISSUE THREAD

**Issue by Ly-Lynn** [opendatalab/MinerU#357]
Hello, first of all, thank you for this great project!!

I am interested in PDF parser and coincidently found your work, and I love it.
However, I cannot customize the code of this repo due to a lack of dependencies. I was trying to install packages from requirement.txt, requirement-qa.txt, and setup.py but it was not enough.
Could you please update the requirements of env 🥹 . That would be great!
![image](https://github.com/user-attachments/assets/0bc195e4-5975-4d07-b5ef-eef694e631ec)
Thank you a lot ><

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/master/docs/README_Windows_CUDA_Acceleration_en_US.md

create a new clean conda env, install through this doc can help you.
