### ISSUE TITLE
pdf小标题所在行的普通文字未被识别

### ISSUE THREAD

**Issue by yushengliao** [opendatalab/MinerU#358]
### Description of the bug | 错误描述

如下图，是执行后的spans.pdf文件，红色方框以外的内容未被写入到markdown中
![image](https://github.com/user-attachments/assets/4578cc77-097b-4614-aff3-80769f90a73c)
![image](https://github.com/user-attachments/assets/016326a2-7a50-46bc-b7f3-69da4603a802)

### How to reproduce the bug | 如何复现

正确的情况应该是保留该行的内容

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
pdf文件能上传一下吗

**Comment by yushengliao** [comment]
[xssc_37.pdf](https://github.com/user-attachments/files/16578764/xssc_37.pdf)
@myhloli   您好已上传一页，供参考

**Comment by myhloli** [comment]
> [xssc_37.pdf](https://github.com/user-attachments/files/16578764/xssc_37.pdf) @myhloli 您好已上传一页，供参考

测试样本这一页，发现缺失的行其实是图片，可以尝试在浏览器中打开该pdf，缺失的这几行复制不出任何文本。
这种属于pdf本身文件存在文本缺失，使用auto时，自动选择的文本模式提取就会丢失没有文本信息的行。
这种情况可以在命令行增加`--method ocr`手动强制开启ocr开关进行提取。
付本次ocr解析结果：
[ocr.zip](https://github.com/user-attachments/files/16580329/ocr.zip)

**Comment by myhloli** [comment]
fixed in 0.10.x
