### ISSUE TITLE
load remote model ch_PP_OCR_v4

### ISSUE THREAD

**Issue by Thirty502** [opendatalab/MinerU#359]
### Description of the bug | 错误描述

我已经在下载好了模型权重文件，并使用文字版pdf进行正常的测试。
当我使用一个扫描版pdf进行测试时，系统在总向网络端请求PP_OCR模型，然而我的环境是一个完全离线的环境。

### How to reproduce the bug | 如何复现

使用扫描版pdf，通过命令行进行测试

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
paddle的模型是要在线下载的，或者你可以找一台联网的机器，下载好paddle的模型再拷贝到你离线部署的那台机器里

**Comment by Thirty502** [comment]
我离线下载了提示对应的包，我应该把放在哪里才能生效，我尝试将他直接放在提示的路径下，他仍然会去联网下载

**Comment by Thirty502** [comment]
> paddle的模型是要在线下载的，或者你可以找一台联网的机器，下载好paddle的模型再拷贝到你离线部署的那台机器里

我下载的对应的包，并尝试将他放在提示的路径下，但系统仍然会联网进行下载，请问我该将他放在哪里才会生效

**Comment by myhloli** [comment]
一般是用户目录的.paddleocr目录下
另外可能需要在/lib/python3.10/site-packages/paddleocr/tools/infer/utility.py:158 中根据这个方法中需要的路径在paddleocr初始化的时候传一下模型路径的参数

**Comment by Thirty502** [comment]
> 一般是用户目录的.paddleocr目录下 另外可能需要在/lib/python3.10/site-packages/paddleocr/tools/infer/utility.py:158 中根据这个方法中需要的路径在paddleocr初始化的时候传一下模型路径的参数
![1e4ffb73dcda9644b3cd67638cfa01c1](https://github.com/user-attachments/assets/bd70eef0-df26-47c0-a982-06ebf1285da6)
我的错误如上图，我将提示的包下载并放置在了对应的位置中，但他仍然会报上图一样的问题

**Comment by myhloli** [comment]
> 另外可能需要在/lib/python3.10/site-packages/paddleocr/tools/infer/utility.py:158 中根据这个方法中需要的路径在paddleocr初始化的时候传一下模型路径的参数

可能需要在paddleocr初始化的时候指定一下本地模型路径

**Comment by Thirty502** [comment]
> > 另外可能需要在/lib/python3.10/site-packages/paddleocr/tools/infer/utility.py:158 中根据这个方法中需要的路径在paddleocr初始化的时候传一下模型路径的参数
> 
> 可能需要在paddleocr初始化的时候指定一下本地模型路径

请问该如何去指定，我使用的是命令行调用的方式

**Comment by myhloli** [comment]
需要修改代码中的
https://github.com/opendatalab/MinerU/blob/c0ee70d52505535f0dac3b16b5924d5d19f1f48a/magic_pdf/model/pdf_extract_kit.py#L142
来指定模型路径，命令行不支持这个操作。

**Comment by Thirty502** [comment]
> 需要修改代码中的
> 
> https://github.com/opendatalab/MinerU/blob/c0ee70d52505535f0dac3b16b5924d5d19f1f48a/magic_pdf/model/pdf_extract_kit.py#L142
> 
> 
> 来指定模型路径，命令行不支持这个操作。

那在离线环境下，我该如何来实现对扫描版pdf的处理

**Comment by albin3** [comment]
@myhloli 什么情况下会触发下载这个模型呢？我解析纯英文的pdf好像也会触发

**Comment by myhloli** [comment]
> @myhloli 什么情况下会触发下载这个模型呢？我解析纯英文的pdf好像也会触发

处理的这篇文档是扫描版的情况下。

**Comment by albin3** [comment]
@myhloli 我本地做上load from cache了会报这个错。。

![image](https://github.com/user-attachments/assets/37f9406f-5096-4c86-948a-654108f9727b)

![image](https://github.com/user-attachments/assets/30500e6b-7c17-421f-a03c-06136f07d16c)

**Comment by myhloli** [comment]
> @myhloli 我本地做上load from cache了会报这个错。。
> 
> ![image](https://private-user-images.githubusercontent.com/6190670/356124897-37f9406f-5096-4c86-948a-654108f9727b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDI2MjQsIm5iZiI6MTcyMzEwMjMyNCwicGF0aCI6Ii82MTkwNjcwLzM1NjEyNDg5Ny0zN2Y5NDA2Zi01MDk2LTRjODYtOTQ4YS02NTQxMDhmOTcyN2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDczMjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzMyNTc4NTcxZjIxNjc4OWVlODkyNTM3MjYxMDJmMWQzZDI5MjRlYmQ0YzAzYmU4YjcxOWFiMjQ1N2UwMGRiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Cdmgahi-TtX8GDLctzC4uLBmCtubZqKQK2aj1U2HVHI)
> 
> ![image](https://private-user-images.githubusercontent.com/6190670/356124514-30500e6b-7c17-421f-a03c-06136f07d16c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDI2MjQsIm5iZiI6MTcyMzEwMjMyNCwicGF0aCI6Ii82MTkwNjcwLzM1NjEyNDUxNC0zMDUwMGU2Yi03YzE3LTQyMWYtYTAzYy0wNjEzNmYwN2QxNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDczMjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ3YWRmNDliOGEyZTY5MWU3YjY3N2ZmM2RmZjY1MjkxYTQyY2U4MjUxYzI4Y2Y1MjdmOTY5MzhjYjJlODc3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RMWZhWYU2IlmU2YakHQKIO2RcvRcHVKiv8Kr3PEi6SM)

tar包应该解压？onnx这个参数是必须的？

**Comment by Thirty502** [comment]
> @myhloli 我本地做上load from cache了会报这个错。。
> 
> ![image](https://private-user-images.githubusercontent.com/6190670/356124897-37f9406f-5096-4c86-948a-654108f9727b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDI2MDcsIm5iZiI6MTcyMzEwMjMwNywicGF0aCI6Ii82MTkwNjcwLzM1NjEyNDg5Ny0zN2Y5NDA2Zi01MDk2LTRjODYtOTQ4YS02NTQxMDhmOTcyN2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDczMTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTA1OWFhYjg1YThjNTliMTk5ODQyNGMxYWFlNzg2OWMxZWExNDBjODFmMTliODc0NGRiNDllMTQ2Njk4ZmNmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WWYkD4OoJrjCpdrJzkUO3MOu54LfGU2UC2dTYrpYpD4)
> 
> ![image](https://private-user-images.githubusercontent.com/6190670/356124514-30500e6b-7c17-421f-a03c-06136f07d16c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDI2MDcsIm5iZiI6MTcyMzEwMjMwNywicGF0aCI6Ii82MTkwNjcwLzM1NjEyNDUxNC0zMDUwMGU2Yi03YzE3LTQyMWYtYTAzYy0wNjEzNmYwN2QxNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDczMTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTI3OWY0MDk3OTE4MzYzY2JlMDIzMGFkMDVmZTY2MTFmYzRkNTcxZTk4MTYyYzBmMGFjMzVkOTIzMDM5ZTlkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2mkwqp_nPgDTjhi0NVysTG-T2oJuRihJub1B3EjxGcc)

你这个报错似乎是缺失了oonxruntime这个依赖包，你是否有安装？

**Comment by albin3** [comment]
@myhloli 确实需要把这个true去掉

magic_pdf/model/pdf_extract_kit.py

![image](https://github.com/user-attachments/assets/fb1ded6a-d7cd-48e9-8ff8-0e34fd48c8bc)

@Thirty502 看下maybe_download的实现，应该可以解决。我加了54han行跑起来了

paddleocr/ppocr/utils/network.py

![image](https://github.com/user-attachments/assets/db04d9f0-34ad-4c3f-855b-59fccd0b6a0b)

但是跑得卡住了，这个问题应该解决了

**Comment by albin3** [comment]
@myhloli  运行卡住了，红框里的内容需要显式在代码里加开关么？

![image](https://github.com/user-attachments/assets/efeac062-a50f-49b5-88c7-e57c0bb15175)

卡这十几分钟了：

![image](https://github.com/user-attachments/assets/c15ef1b8-9e55-4eb1-86ec-8cd219291243)

**Comment by myhloli** [comment]
> @myhloli 运行卡住了，红框里的内容需要显式在代码里加开关么？
> 
> ![image](https://private-user-images.githubusercontent.com/6190670/356143761-efeac062-a50f-49b5-88c7-e57c0bb15175.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDY3MzYsIm5iZiI6MTcyMzEwNjQzNiwicGF0aCI6Ii82MTkwNjcwLzM1NjE0Mzc2MS1lZmVhYzA2Mi1hNTBmLTQ5YjUtODhjNy1lNTdjMGJiMTUxNzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDg0MDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWIwOTg4ZjQ2OGNlYTJjNDY2YWRkZjRiOWExMWZmMDU0OWM5YWEyMDFhZGUwMTc2NWQxYjQxNTJhODc0NTFjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B8Lm4aLHHUg0sxVobCD7pganovhr4ccMylNWL0K1Sjg)
> 
> 卡这十几分钟了：
> 
> ![image](https://private-user-images.githubusercontent.com/6190670/356144095-c15ef1b8-9e55-4eb1-86ec-8cd219291243.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDY3MzYsIm5iZiI6MTcyMzEwNjQzNiwicGF0aCI6Ii82MTkwNjcwLzM1NjE0NDA5NS1jMTVlZjFiOC05ZTU1LTRlYjEtODZlYy04Y2QyMTkyOTEyNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDg0MDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTNlMzM5MTM1Y2ZhZjkyMDRhMDc0Nzc0NzFiOWFhYjQ2ZmVkMjczNTI2MGM2Yzc0NTQxNTU1OWIwOGJkMDFjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5c4hnEAnIe-5EXiNcP7ietDUIf3M4dxw4dgiVd6R5Nk)

https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_zh_CN.md

按教程来，不需要显式开关，paddle-gpu装好之后自动开启ocr加速的

你这个卡住的话和ocr加速应该关系不大，可能是初始化的地方改的不太对导致的。

**Comment by Thirty502** [comment]
经过测试，将对应的模型下载后，需要解压在相应的位置，系统仍然能够较好的运行

**Comment by myhloli** [comment]
> 经过测试，将对应的模型下载后，需要解压在相应的位置，系统仍然能够较好的运行

看来还是需要解压，直接复制tar包是不行的
