### ISSUE TITLE
提取PDF中表格的其他方案（间接）

### ISSUE THREAD

**Issue by beiluo** [opendatalab/MinerU#360]
因为0.6版本不支持提取PDF中的表格，0.7版本的提取表格功能暂时不可用（巨慢）。所以参考Issues中其他人给出的方案，自己实现了一个版本

首先需要按照模块
```bash
pip install rapidocr_onnxruntime
pip install rapid_table
```

代码main.py
```python
import json
import re
import os
import sys
from typing import Dict, List

from rapidocr_onnxruntime import RapidOCR
from rapid_table import RapidTable

table_engine = RapidTable()
ocr_engine = RapidOCR()

def read_markdown_file(file_path: str) -> str:
    with open(file_path, 'r', encoding='utf-8') as file:
        return file.read()

def write_markdown_file(file_path: str, content: str):
    with open(file_path, 'w', encoding='utf-8') as file:
        file.write(content)

def read_json_file(file_path: str) -> List[Dict]:
    with open(file_path, 'r', encoding='utf-8') as file:
        return json.load(file)

def perform_ocr(img_path: str) -> str:
    ocr_result, _ = ocr_engine(img_path)
    table_html_str, table_cell_bboxes, elapse = table_engine(img_path, ocr_result)
    return table_html_str

def replace_image_with_ocr_content(markdown_content: str, image_path: str, ocr_content: str) -> str:
    # 这里假设图片在Markdown中的格式是 ![alt text](image_path)
    image_pattern = f"!\\[.*?\\]\\({re.escape(image_path)}\\)"
    return re.sub(image_pattern, ocr_content, markdown_content)

def find_markdown_file(base_path: str) -> str:
    auto_folder = os.path.join(base_path, 'auto')
    for file in os.listdir(auto_folder):
        if file.endswith('.md'):
            return os.path.join(auto_folder, file)
    return None

def main(base_path: str):
    # 查找Markdown文件
    markdown_file_path = find_markdown_file(base_path)
    if not markdown_file_path:
        print(f"错误：在 {os.path.join(base_path, 'auto')} 中未找到 Markdown 文件")
        return

    # 构建JSON文件路径
    markdown_filename = os.path.basename(markdown_file_path)
    json_filename = f"{os.path.splitext(markdown_filename)[0]}_content_list.json"
    json_file_path = os.path.join(base_path, "auto", json_filename)

    # 检查文件是否存在
    if not os.path.exists(json_file_path):
        print(f"错误：无法找到JSON文件: {json_file_path}")
        return

    # 读取Markdown文件
    markdown_content = read_markdown_file(markdown_file_path)

    # 读取JSON文件
    json_data = read_json_file(json_file_path)

    # 计算需要OCR处理的项目数量
    total_items = sum(1 for item in json_data if item['type'] == 'table' and 'img_path' in item)

    # 处理JSON数据
    ocr_count = 0

    # 处理JSON数据
    for item in json_data:
        if item['type'] == 'table' and 'img_path' in item:
            img_path = os.path.join(base_path, 'auto', item['img_path'])
            if os.path.exists(img_path):
                ocr_count += 1
                ocr_content = perform_ocr(img_path)
                markdown_content = replace_image_with_ocr_content(markdown_content, item['img_path'], ocr_content)
                print(f"OCR 进度: {ocr_count}/{total_items}")
            else:
                print(f"警告：图片文件不存在 {img_path}")

    # 保存更改后的Markdown文件
    write_markdown_file(markdown_file_path, markdown_content)
    print(f"处理完成，已更新 {markdown_file_path} 文件。")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("用法: python tt.py <base_path>")
        sys.exit(1)
    
    base_path = sys.argv[1]
    main(base_path)
```

使用方式
```bash
python main.py {magic-pdf输出路径}
```
路径示例
```
E:\mineru\output\magic-pdf\companies-list
```
需要读取的文件（支持<0.7版本）
```
E:\mineru\output\magic-pdf\companies-list\auto\companies-list.md
E:\mineru\output\magic-pdf\companies-list\auto\companies-list_content_list.json
```
目前速度还可以，在笔记本RTX4060上基本上1S以内一张图

期待0.7更好的支持表格提取，这只是一个可用的临时方案。

**Comment by beiluo** [comment]
代码绝大部分是通过ClaudeAI生成的，RapidTable的内容是从https://github.com/RapidAI/RapidTable找的。
RapidTable方案是其他Issues里边推荐的，测试下来整体效率比较好，准备度也比较高。

**Comment by drunkpig** [comment]
@beiluo We will test this solution.

**Comment by hahhforest** [comment]
> 代码绝大部分是通过ClaudeAI生成的，RapidTable的内容是从[https://github.com/RapidAI/RapidTable找的。](https://github.com/RapidAI/RapidTable%E6%89%BE%E7%9A%84%E3%80%82) RapidTable方案是其他Issues里边推荐的，测试下来整体效率比较好，准备度也比较高。

hello 我还没测试0.7版本，问一问0.7版本的表格解析现在有多慢

**Comment by beiluo** [comment]
> > 代码绝大部分是通过ClaudeAI生成的，RapidTable的内容是从[https://github.com/RapidAI/RapidTable找的。](https://github.com/RapidAI/RapidTable%E6%89%BE%E7%9A%84%E3%80%82) RapidTable方案是其他Issues里边推荐的，测试下来整体效率比较好，准备度也比较高。
> 
> hello 我还没测试0.7版本，问一问0.7版本的表格解析现在有多慢

一个表格最少2分钟起步，RTX 4060

**Comment by 2257396011** [comment]
我试了一下速度确实挺快的，效果也不错

**Comment by sky-fly97** [comment]
Struct-EqTable速度这块我们支持了[Tensorrt-LLM加速](https://github.com/UniModal4Reasoning/StructEqTable-Deploy/blob/main/docs/GETTING_STARTED.md)，提速效果非常明显，感兴趣的同学可以提前测试一下~效果方面我们也在持续迭代优化中

**Comment by hahhforest** [comment]
> Struct-EqTable速度这块我们支持了[Tensorrt-LLM加速](https://github.com/UniModal4Reasoning/StructEqTable-Deploy/blob/main/docs/GETTING_STARTED.md)，提速效果非常明显，感兴趣的同学可以提前测试一下~效果方面我们也在持续迭代优化中

hello，请问下如何测试

**Comment by sky-fly97** [comment]
> > Struct-EqTable速度这块我们支持了[Tensorrt-LLM加速](https://github.com/UniModal4Reasoning/StructEqTable-Deploy/blob/main/docs/GETTING_STARTED.md)，提速效果非常明显，感兴趣的同学可以提前测试一下~效果方面我们也在持续迭代优化中
> 
> hello，请问下如何测试

需要[点进去](https://github.com/UniModal4Reasoning/StructEqTable-Deploy/blob/main/docs/GETTING_STARTED.md)配一下环境，然后按教程走就行

**Comment by Kyrie666** [comment]
我在0.7.1版本输出没有这个后缀 _content_list.json的文件

**Comment by myhloli** [comment]
> 我在0.7.1版本输出没有这个后缀 _content_list.json的文件


由于优化cli，这个文件不提供输出了。

**Comment by Kyrie666** [comment]
> > 我在0.7.1版本输出没有这个后缀 _content_list.json的文件
> 
> 由于优化cli，这个文件不提供输出了。
ok，那只能期待新的版本，非常优秀的工作，感谢。

**Comment by Juan-hwt** [comment]
请教一下，大部分的pdf和报表，都有合并单元格和斜线，然而md天然不支持合并表头，这些可能会怎么处理？

**Comment by beiluo** [comment]
> 请教一下，大部分的pdf和报表，都有合并单元格和斜线，然而md天然不支持合并表头，这些可能会怎么处理？

使用html的table组件来进行实现

**Comment by Alan-zhong** [comment]
请问json文件哪里来的，我只有md文件

**Comment by beiluo** [comment]
> 请问json文件哪里来的，我只有md文件

注意看版本，0.6是有的，0.7是没有的。

**Comment by cz9510** [comment]
您好，请问下支持gpu加速么

**Comment by beiluo** [comment]
> 您好，请问下支持gpu加速么

支持的

**Comment by cz9510** [comment]
请问具体如何使用cuda加速呢

**Comment by beiluo** [comment]
> ```python
> rapidocr_onnxruntime 
> ```

看下代码吧，代码里使用的是rapidocr_onnxruntime ，是支持CUDA的

**Comment by RwandanMtGorilla** [comment]
0.7版本的写法: 
```py

import json
import re
import os
import sys
from typing import Dict, List

from rapidocr_onnxruntime import RapidOCR
from rapid_table import RapidTable

from typing import Any, List, Tuple


table_engine = RapidTable()
ocr_engine = RapidOCR()

def read_markdown_file(file_path: str) -> str:
    with open(file_path, 'r', encoding='utf-8') as file:
        return file.read()

def write_markdown_file(file_path: str, content: str):
    with open(file_path, 'w', encoding='utf-8') as file:
        file.write(content)

# def read_json_file(file_path: str) -> List[Dict]:
#     with open(file_path, 'r', encoding='utf-8') as file:
#         return json.load(file)

def perform_ocr(img_path: str) -> str:
    ocr_result, _ = ocr_engine(img_path)
    table_html_str, table_cell_bboxes, elapse = table_engine(img_path, ocr_result)
    return table_html_str

def replace_image_with_ocr_content(markdown_content: str, image_path: str, ocr_content: str) -> str:
    # 这里假设图片在Markdown中的格式是 ![alt text](image_path)
    image_pattern = f"!\\[.*?\\]\\({re.escape(image_path)}\\)"
    return re.sub(image_pattern, ocr_content, markdown_content)

def find_markdown_file(base_path: str) -> str:
    auto_folder = os.path.join(base_path, 'auto')
    for file in os.listdir(auto_folder):
        if file.endswith('.md'):
            return os.path.join(auto_folder, file)
    return None

def read_json_file(file_path: str) -> Any:
    """读取JSON文件并返回其内容"""
    with open(file_path, 'r', encoding='utf-8') as file:
        return json.load(file)

def find_image_paths(data: Any, paths: List[Tuple[str, str]] = None) -> List[Tuple[str, str]]:
    """
    递归查找JSON数据中的'image_path'和对应的'type'，当'type' == 'table'时保存。
    
    :param data: 当前的JSON数据，可以是字典、列表或其他类型
    :param paths: 用于存储找到的(type, image_path)元组
    :return: 包含符合条件的(type, image_path)的列表
    """
    if paths is None:
        paths = []

    if isinstance(data, dict):
        # 如果当前数据是字典，检查其中是否有 'image_path' 和 'type'
        image_path = data.get('image_path')
        item_type = data.get('type')
        # 当 'type' 为 'table' 且有 'image_path' 时，保存该路径
        if item_type == 'table' and image_path:
            paths.append((item_type, image_path))
        
        # 递归遍历字典中的所有子项
        for key, value in data.items():
            find_image_paths(value, paths)

    elif isinstance(data, list):
        # 如果当前数据是列表，遍历列表中的每一项
        for item in data:
            find_image_paths(item, paths)

    return paths

def main(base_path: str):
    # 查找Markdown文件
    markdown_file_path = find_markdown_file(base_path)
    if not markdown_file_path:
        print(f"错误：在 {os.path.join(base_path, 'auto')} 中未找到 Markdown 文件")
        return

    # 构建JSON文件路径
    markdown_filename = os.path.basename(markdown_file_path)
    json_filename = "middle.json"# f"{os.path.splitext(markdown_filename)[0]}_content_list.json"
    json_file_path = os.path.join(base_path, "auto", json_filename)

    # 检查文件是否存在
    if not os.path.exists(json_file_path):
        print(f"错误：无法找到JSON文件: {json_file_path}")
        return

    # 读取Markdown文件
    markdown_content = read_markdown_file(markdown_file_path)

    # 读取JSON文件
    json_data = read_json_file(json_file_path)

    # 查找所有符合条件的(image_path, type)
    image_paths = find_image_paths(json_data)

    # 计算需要OCR处理的项目数量
    total_items = len(image_paths)
    ocr_count = 0

    # 处理JSON数据
    for item_type, img_path in image_paths:
        img_full_path = os.path.join(base_path, 'auto\\images', img_path)
        if os.path.exists(img_full_path):
            ocr_count += 1
            ocr_content = perform_ocr(img_full_path)
            markdown_content = replace_image_with_ocr_content(markdown_content, img_path, ocr_content)
            print(f"OCR 进度: {ocr_count}/{total_items}")
        else:
            print(f"警告：图片文件不存在 {img_full_path}")

    # 保存更改后的Markdown文件
    write_markdown_file(markdown_file_path, markdown_content)
    print(f"处理完成，已更新 {markdown_file_path} 文件。")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("用法: python TableOCR.py <base_path>")
        sys.exit(1)
    
    base_path = sys.argv[1]
    main(base_path)


```
0.8版本修改一下   json_filename =

**Comment by Sherlockqhs** [comment]
好像还是提取不了表格哦，表格依然是以图片的形式嵌入在md文件中

**Comment by ghost** [comment]
请问 0.8.x版本的修改json_filenam成什么呢

**Comment by jianxinxie** [comment]
> 请问 0.8.x版本的修改json_filenam成什么呢

0.8 的变成 xxx_middle.json 了, xxx 是不带后缀的文件名，可以参考

```
import json
import os
import re
import sys
from typing import Any, Dict, List, Tuple

from rapid_table import RapidTable
from rapidocr_onnxruntime import RapidOCR

table_engine = RapidTable()
ocr_engine = RapidOCR()


def read_markdown_file(file_path: str) -> str:
    with open(file_path, "r", encoding="utf-8") as file:
        return file.read()


def write_markdown_file(file_path: str, content: str):
    with open(file_path, "w", encoding="utf-8") as file:
        file.write(content)


# def read_json_file(file_path: str) -> List[Dict]:
#     with open(file_path, 'r', encoding='utf-8') as file:
#         return json.load(file)


def perform_ocr(img_path: str) -> str:
    ocr_result, _ = ocr_engine(img_path)
    table_html_str, table_cell_bboxes, elapse = table_engine(img_path, ocr_result)
    return table_html_str


def replace_image_with_ocr_content(markdown_content: str, image_path: str, ocr_content: str) -> str:
    # 这里假设图片在Markdown中的格式是 ![alt text](image_path)
    image_pattern = f"!\\[.*?\\]\\({re.escape(image_path)}\\)"
    return re.sub(image_pattern, ocr_content, markdown_content)


def find_markdown_file(base_path: str) -> str:
    auto_folder = os.path.join(base_path, "auto")
    for file in os.listdir(auto_folder):
        if file.endswith(".md"):
            return os.path.join(auto_folder, file)
    return None


def read_json_file(file_path: str) -> Any:
    """读取JSON文件并返回其内容"""
    with open(file_path, "r", encoding="utf-8") as file:
        return json.load(file)


def find_image_paths(data: Any, paths: List[Tuple[str, str]] = None) -> List[Tuple[str, str]]:
    """
    递归查找JSON数据中的'image_path'和对应的'type'，当'type' == 'table'时保存。

    :param data: 当前的JSON数据，可以是字典、列表或其他类型
    :param paths: 用于存储找到的(type, image_path)元组
    :return: 包含符合条件的(type, image_path)的列表
    """
    if paths is None:
        paths = []

    if isinstance(data, dict):
        # 如果当前数据是字典，检查其中是否有 'image_path' 和 'type'
        image_path = data.get("image_path")
        item_type = data.get("type")
        # 当 'type' 为 'table' 且有 'image_path' 时，保存该路径
        if item_type == "table" and image_path:
            paths.append((item_type, image_path))

        # 递归遍历字典中的所有子项
        for key, value in data.items():
            find_image_paths(value, paths)

    elif isinstance(data, list):
        # 如果当前数据是列表，遍历列表中的每一项
        for item in data:
            find_image_paths(item, paths)

    return paths


def main(base_path: str):
    # 查找Markdown文件
    markdown_file_path = find_markdown_file(base_path)
    if not markdown_file_path:
        print(f"错误：在 {os.path.join(base_path, 'auto')} 中未找到 Markdown 文件")
        return

    # 构建JSON文件路径
    markdown_filename = os.path.basename(markdown_file_path)
    pdf_filename = os.path.splitext(os.path.basename(markdown_filename))[0]
    json_filename = (
        pdf_filename + "_middle.json"
    )  # f"{os.path.splitext(markdown_filename)[0]}_content_list.json"
    json_file_path = os.path.join(base_path, "auto", json_filename)

    # 检查文件是否存在
    if not os.path.exists(json_file_path):
        print(f"错误：无法找到JSON文件: {json_file_path}")
        return

    # 读取Markdown文件
    markdown_content = read_markdown_file(markdown_file_path)

    # 读取JSON文件
    json_data = read_json_file(json_file_path)

    # 查找所有符合条件的(image_path, type)
    image_paths = find_image_paths(json_data)

    # 计算需要OCR处理的项目数量
    total_items = len(image_paths)
    ocr_count = 0

    # 处理JSON数据
    for item_type, img_path in image_paths:
        img_full_path = os.path.join(base_path, "auto/images", img_path)
        if os.path.exists(img_full_path):
            ocr_count += 1
            ocr_content = perform_ocr(img_full_path)
            markdown_content = replace_image_with_ocr_content(markdown_content, img_path, ocr_content)
            print(f"OCR 进度: {ocr_count}/{total_items}")
        else:
            print(f"警告：图片文件不存在 {img_full_path}")

    # 保存更改后的Markdown文件
    write_markdown_file(markdown_file_path, markdown_content)
    print(f"处理完成，已更新 {markdown_file_path} 文件。")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("用法: python TableOCR.py <base_path>")
        sys.exit(1)

    base_path = sys.argv[1]
    main(base_path)
```

**Comment by tongshiyuan** [comment]
这个方法对横版的表格还是一地稀碎

**Comment by EvanSong77** [comment]
> > 请问 0.8.x版本的修改json_filenam成什么呢
> 
> 0.8 的变成 xxx_middle.json 了, xxx 是不带后缀的文件名，可以参考
> 
> ```
> import json
> import os
> import re
> import sys
> from typing import Any, Dict, List, Tuple
> 
> from rapid_table import RapidTable
> from rapidocr_onnxruntime import RapidOCR
> 
> table_engine = RapidTable()
> ocr_engine = RapidOCR()
> 
> 
> def read_markdown_file(file_path: str) -> str:
>     with open(file_path, "r", encoding="utf-8") as file:
>         return file.read()
> 
> 
> def write_markdown_file(file_path: str, content: str):
>     with open(file_path, "w", encoding="utf-8") as file:
>         file.write(content)
> 
> 
> # def read_json_file(file_path: str) -> List[Dict]:
> #     with open(file_path, 'r', encoding='utf-8') as file:
> #         return json.load(file)
> 
> 
> def perform_ocr(img_path: str) -> str:
>     ocr_result, _ = ocr_engine(img_path)
>     table_html_str, table_cell_bboxes, elapse = table_engine(img_path, ocr_result)
>     return table_html_str
> 
> 
> def replace_image_with_ocr_content(markdown_content: str, image_path: str, ocr_content: str) -> str:
>     # 这里假设图片在Markdown中的格式是 ![alt text](image_path)
>     image_pattern = f"!\\[.*?\\]\\({re.escape(image_path)}\\)"
>     return re.sub(image_pattern, ocr_content, markdown_content)
> 
> 
> def find_markdown_file(base_path: str) -> str:
>     auto_folder = os.path.join(base_path, "auto")
>     for file in os.listdir(auto_folder):
>         if file.endswith(".md"):
>             return os.path.join(auto_folder, file)
>     return None
> 
> 
> def read_json_file(file_path: str) -> Any:
>     """读取JSON文件并返回其内容"""
>     with open(file_path, "r", encoding="utf-8") as file:
>         return json.load(file)
> 
> 
> def find_image_paths(data: Any, paths: List[Tuple[str, str]] = None) -> List[Tuple[str, str]]:
>     """
>     递归查找JSON数据中的'image_path'和对应的'type'，当'type' == 'table'时保存。
> 
>     :param data: 当前的JSON数据，可以是字典、列表或其他类型
>     :param paths: 用于存储找到的(type, image_path)元组
>     :return: 包含符合条件的(type, image_path)的列表
>     """
>     if paths is None:
>         paths = []
> 
>     if isinstance(data, dict):
>         # 如果当前数据是字典，检查其中是否有 'image_path' 和 'type'
>         image_path = data.get("image_path")
>         item_type = data.get("type")
>         # 当 'type' 为 'table' 且有 'image_path' 时，保存该路径
>         if item_type == "table" and image_path:
>             paths.append((item_type, image_path))
> 
>         # 递归遍历字典中的所有子项
>         for key, value in data.items():
>             find_image_paths(value, paths)
> 
>     elif isinstance(data, list):
>         # 如果当前数据是列表，遍历列表中的每一项
>         for item in data:
>             find_image_paths(item, paths)
> 
>     return paths
> 
> 
> def main(base_path: str):
>     # 查找Markdown文件
>     markdown_file_path = find_markdown_file(base_path)
>     if not markdown_file_path:
>         print(f"错误：在 {os.path.join(base_path, 'auto')} 中未找到 Markdown 文件")
>         return
> 
>     # 构建JSON文件路径
>     markdown_filename = os.path.basename(markdown_file_path)
>     pdf_filename = os.path.splitext(os.path.basename(markdown_filename))[0]
>     json_filename = (
>         pdf_filename + "_middle.json"
>     )  # f"{os.path.splitext(markdown_filename)[0]}_content_list.json"
>     json_file_path = os.path.join(base_path, "auto", json_filename)
> 
>     # 检查文件是否存在
>     if not os.path.exists(json_file_path):
>         print(f"错误：无法找到JSON文件: {json_file_path}")
>         return
> 
>     # 读取Markdown文件
>     markdown_content = read_markdown_file(markdown_file_path)
> 
>     # 读取JSON文件
>     json_data = read_json_file(json_file_path)
> 
>     # 查找所有符合条件的(image_path, type)
>     image_paths = find_image_paths(json_data)
> 
>     # 计算需要OCR处理的项目数量
>     total_items = len(image_paths)
>     ocr_count = 0
> 
>     # 处理JSON数据
>     for item_type, img_path in image_paths:
>         img_full_path = os.path.join(base_path, "auto/images", img_path)
>         if os.path.exists(img_full_path):
>             ocr_count += 1
>             ocr_content = perform_ocr(img_full_path)
>             markdown_content = replace_image_with_ocr_content(markdown_content, img_path, ocr_content)
>             print(f"OCR 进度: {ocr_count}/{total_items}")
>         else:
>             print(f"警告：图片文件不存在 {img_full_path}")
> 
>     # 保存更改后的Markdown文件
>     write_markdown_file(markdown_file_path, markdown_content)
>     print(f"处理完成，已更新 {markdown_file_path} 文件。")
> 
> 
> if __name__ == "__main__":
>     if len(sys.argv) != 2:
>         print("用法: python TableOCR.py <base_path>")
>         sys.exit(1)
> 
>     base_path = sys.argv[1]
>     main(base_path)
> ```

执行完了还是没有将图片形式的表格转过去。。

**Comment by beiluo** [comment]
> 这个方法对横版的表格还是一地稀碎

可以发下你的横版的表格看下。
我测试正常的表格效果是很好的。

**Comment by myhloli** [comment]
将会在0.9.3版本集成rapidtable
