### ISSUE TITLE
耗时问题

### ISSUE THREAD

**Issue by 1greatday** [opendatalab/MinerU#361]
### Description of the bug | 错误描述

在gpu上做推理，发现cpu利用率很高，这正常吗？而且ocr部分cost大概在5s左右

### How to reproduce the bug | 如何复现

按照步骤安装，用源码运行+cuda加速

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
早期发布的版本没解决好torch和paddle同时使用cuda的冲突问题，因此paddle默认是使用cpu推理的，在0.6.2b1版本中解决了兼容问题之后才更新了ocr加速的教程。
可以参考
https://github.com/opendatalab/MinerU/blob/master/README_zh-CN_v2.md#%E4%BD%BF%E7%94%A8gpu
中的内容，根据自己的系统选择教程，开启ocr加速。
如果之前在linux上装过cu118的torch，请按教程新建一个conda环境再重新装一遍环境，以解决torch和paddle的冲突问题。

**Comment by 1greatday** [comment]
<img width="569" alt="image" src="https://github.com/user-attachments/assets/97f49523-62c5-46a4-8aa0-29c95a7d181b">

**Comment by 1greatday** [comment]
我的显卡cuda信息是
<img width="580" alt="image" src="https://github.com/user-attachments/assets/371fd42d-5166-464a-8f70-ab789754637d">
torch版本是
<img width="439" alt="image" src="https://github.com/user-attachments/assets/edf7e96b-b9fa-4c70-8b26-75aa7bbb8589">
paddle版本是
<img width="352" alt="image" src="https://github.com/user-attachments/assets/e3650e7f-47d4-49b8-9e4b-e54564ae1960">
问题是：
<img width="762" alt="image" src="https://github.com/user-attachments/assets/ae92c4b5-5fb7-4065-93c4-cb6bad1ed383">
ocr耗时还是很高，是拉取MinerU-magic_pdf-0.7.0a1-released版本重新安装的环境，这个是什么原因呢

**Comment by myhloli** [comment]
paddleocr-gpu装了吗

**Comment by myhloli** [comment]
> 我的显卡cuda信息是 <img alt="image" width="580" src="https://private-user-images.githubusercontent.com/50477496/356127902-371fd42d-5166-464a-8f70-ab789754637d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDMzNzIsIm5iZiI6MTcyMzEwMzA3MiwicGF0aCI6Ii81MDQ3NzQ5Ni8zNTYxMjc5MDItMzcxZmQ0MmQtNTE2Ni00NjRhLThmNzAtYWI3ODk3NTQ2MzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA3NDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMmQ2MmYzMTU4YTNjMDM0ODg1MTQyYzRiODNiMWJkN2Y4ZGIzNDAxYTU3Yjk3MjVjMWFiMTMzYzY0MTZjNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bi1oj5AEOyTpKRKAaLM1vFWOcjZzv3F3gtLDlRF7U9E"> torch版本是 <img alt="image" width="439" src="https://private-user-images.githubusercontent.com/50477496/356128054-edf7e96b-b9fa-4c70-8b26-75aa7bbb8589.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDMzNzIsIm5iZiI6MTcyMzEwMzA3MiwicGF0aCI6Ii81MDQ3NzQ5Ni8zNTYxMjgwNTQtZWRmN2U5NmItYjlmYS00YzcwLThiMjYtNzVhYTdiYmI4NTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA3NDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3N2JjZjhiMmYzY2JlNDRmMzU2YzBkMTE0ZjE0MjY4ZjgzMWY2MmY1MThjNWVjMjgyMWVmMGViZThmYTIzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VByCALaoMUfZh7DUdjwtEb1lMQEpxKIIALmSXNr-7E"> paddle版本是 <img alt="image" width="352" src="https://private-user-images.githubusercontent.com/50477496/356128231-e3650e7f-47d4-49b8-9e4b-e54564ae1960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDMzNzIsIm5iZiI6MTcyMzEwMzA3MiwicGF0aCI6Ii81MDQ3NzQ5Ni8zNTYxMjgyMzEtZTM2NTBlN2YtNDdkNC00OWI4LTllNGItZTU0NTY0YWUxOTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA3NDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxODA2YTY3M2Q5NGVkMTNjNzY0NDQ3Nzg4MGY3Nzg1YmNlNTYzYzdjMGJjYzAyYzliYmY4ODFkMmFjN2MwYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bk7AEQOdDvlCdUwmejlV_MtxzJA7GraItEQXIxgrUSU"> 问题是： <img alt="image" width="762" src="https://private-user-images.githubusercontent.com/50477496/356128467-ae92c4b5-5fb7-4065-93c4-cb6bad1ed383.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDMzNzIsIm5iZiI6MTcyMzEwMzA3MiwicGF0aCI6Ii81MDQ3NzQ5Ni8zNTYxMjg0NjctYWU5MmM0YjUtNWZiNy00MDY1LTkzYzQtY2I2YmFkMWVkMzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA3NDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNjhiMWYxMWZkMTUwYjA2MDNlNDBlNDczM2JjYzA2ZjY1MjdlYmRjZjk4MjlkOWEzNjFjNTIwZjUzM2FmYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8pqCSTQASvl6gp9U0Loxy4i5WwEeyNDj6018rglFX-A"> ocr耗时还是很高，是拉取MinerU-magic_pdf-0.7.0a1-released版本重新安装的环境，这个是什么原因呢

是根据https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_zh_CN.md 这个教程重装的环境吗，我看paddlepaddle的版本和教程并不一致，教程中linux应该安装3.0.0b1版本的paddle和paddle-gpu

**Comment by 1greatday** [comment]
好的，这个已经解决了，想问一下这个支持在npu上部署吗？我再npu上部署的时候，同样遇到cpu利用率很高的问题

**Comment by myhloli** [comment]
> 好的，这个已经解决了，想问一下这个支持在npu上部署吗？我再npu上部署的时候，同样遇到cpu利用率很高的问题

目前只保证在主线支持平台上的加速可用性，对于其他的加速配置，需要自行尝试。
关于主线平台支持的详情可以参考https://github.com/opendatalab/MinerU/blob/master/README_zh-CN_v2.md 中
【⚠️安装前必看——软硬件环境支持说明】一节
