### ISSUE TITLE
将标题识别成了页眉

### ISSUE THREAD

**Issue by lygiants** [opendatalab/MinerU#363]
### Description of the bug | 错误描述

将标题识别成了页眉, 请问这个是在哪个代码中判断的呢, 我看看能自己改一改已满足我的需求

### How to reproduce the bug | 如何复现

[2407.01449v2_origin.pdf](https://github.com/user-attachments/files/16539682/2407.01449v2_origin.pdf)
![image](https://github.com/user-attachments/assets/09bef58b-6d67-4082-b5cd-9ca2cc3626bd)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by lygiants** [comment]
json文件中显示是 title
![image](https://github.com/user-attachments/assets/83912d19-1152-4dd7-9912-a7449dbd53e6)

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/d40dd3cc-3f44-45fb-ae69-f86da96329a9)
你的输出结果和标准输出不一致，请检查自己是否使用>=0.6.2b1版本运行的该程序

**Comment by lygiants** [comment]
好的谢谢您, 我这边是0.6.1的版本, 但是我注意到会出现两种情况, 我升级0.6.2版本再测试一下
