### ISSUE TITLE
ocr之后的pdf在那里？

### ISSUE THREAD

**Issue by ytcpub** [opendatalab/MinerU#370]
### Description of the bug | 错误描述

处理后的目录只看到spans.pdf layout.pdf origion.pdf, 有什么配置项可以让它输出ocr之后的pdf吗？谢谢

### How to reproduce the bug | 如何复现

conda run -n MinerU magic-pdf pdf-command --pdf ocr.pdf --inside_model true --model_mode full --method=ocr

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
什么是ocr后的pdf？

**Comment by ytcpub** [comment]
类似ocrmypdf 工具， 将原pdf 转成一个同样内容的pdf，新pdf中文字可拷贝  后续的处理过程就跟正常pdf比较类似了

**Comment by myhloli** [comment]
> 类似ocrmypdf 工具， 将原pdf 转成一个同样内容的pdf，新pdf中文字可拷贝 后续的处理过程就跟正常pdf比较类似了

目前没有这种功能
