### ISSUE TITLE
MinerU和pdf-extract-kit的关联是什么

### ISSUE THREAD

**Issue by Ur0512** [opendatalab/MinerU#372]
我想要实现的功能是把pdf中的某一个表格提取出来，请问大佬，我们的项目可以实现这个功能吗？
以及MinerU和pdf-extract-kit的关联是什么，MinerU是在pdf-extract-kit的基础上继续实现某种功能吗？

**Comment by drunkpig** [comment]
The pdf-extract-kit is a foundational library for PDF processing that includes layout analysis, formula and table detection, and recognition capabilities. minerU utilizes the basic functions of the pdf-extract-kit and is an end-to-end solution for parsing PDFs. Similarly, while pdf-extract-kit is like a QT interface library, minerU is an application tool developed using QT.

**Comment by Ur0512** [comment]
好的，感谢。也就是说他们并非是一种先后关系，并不是先使用pdf-extract-kit再使用mineru，而是mineru在pdf-extract-kit的基础上开发而来的？是我理解的这样吗

**Comment by drunkpig** [comment]
@Ur0512 yes
