### ISSUE TITLE
关闭表格识别功能-import 表格依赖报错

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#376]
### Description of the bug | 错误描述

![img_v3_02dj_5a184883-65fa-40d2-a508-7a159b8eaf6g](https://github.com/user-attachments/assets/1f56c9db-27c7-4464-b910-fc14604d5c3e)

### How to reproduce the bug | 如何复现

关闭表格识别开关  
magic-pdf命令行

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
测试的whl包问题，线上master无此问题。
