### ISSUE TITLE
请问如何设置cpu多线程运行?

### ISSUE THREAD

**Issue by meng0423** [opendatalab/MinerU#377]
在服务器上运行很慢
![image](https://github.com/user-attachments/assets/9ed06420-dd1c-4076-9bdf-9bdc1faab701)
同时cpu占用很低，请问如何设置多线程提速？
![image](https://github.com/user-attachments/assets/e82b757a-683e-4cb2-b201-288b3f7c045a)

**Comment by myhloli** [comment]
默认就是支持多线程运行的，正常情况下，纯cpu模式下可以把全部cpu核心吃满。因为cpu多线程支持是由底层的torch和paddlepaddle支持的，如果效果不理想，可以排查下是否设备对这两个库的支持不够完善。

**Comment by meng0423** [comment]
> 默认就是支持多线程运行的，正常情况下，纯cpu模式下可以把全部cpu核心吃满。因为cpu多线程支持是由底层的torch和paddlepaddle支持的，如果效果不理想，可以排查下是否设备对这两个库的支持不够完善。

谢谢解答，我是arm的linux服务器，torch版本是2.4.0和推荐的2.3.1不一样，会不会是这个有影响呀？

**Comment by myhloli** [comment]
arm可能不支持mkl库导致cpu并行处理效果不佳

**Comment by meng0423** [comment]
> arm可能不支持mkl库导致cpu并行处理效果不佳

谢谢，我刚才检查了一下，发现没有安装这个库，我去编译一下试试。
