### ISSUE TITLE
报错RuntimeError: CUDA error: an illegal memory access was encountered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by 2257396011** [opendatalab/MinerU#378]
### Description of the bug | 错误描述

2024-08-09 07:19:19.929 | ERROR    | __main__:pdf_parse_main:135 - CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):

  File "/home/founder/MinerU-master/MinerU-master/demo/magic_pdf_parse_main.py", line 224, in <module>
    pdf_parse_main(pdf_path)
    │              └ '/home/founder/MinerU-master/pdf/1.pdf'
    └ <function pdf_parse_main at 0x7fbc0f665e10>

> File "/home/founder/MinerU-master/MinerU-master/demo/magic_pdf_parse_main.py", line 117, in pdf_parse_main
    pipe.pipe_analyze()  # 解析
    │    └ <function OCRPipe.pipe_analyze at 0x7fbc0f6657e0>
    └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7fbc01a5a680>

  File "/home/founder/env/lib/python3.10/site-packages/magic_pdf/pipe/OCRPipe.py", line 19, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True)
    │    │            │           │    └ b'%PDF-1.7\r%\xe2\xe3\xcf\xd3\r\n308 0 obj\r<</Linearized 1/L 643506/O 310/E 111574/N 6/T 642787/H [ 660 557]>>\rendobj\r    ...
    │    │            │           └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7fbc01a5a680>
    │    │            └ <function doc_analyze at 0x7fbca469e290>
    │    └ []
    └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7fbc01a5a680>
  File "/home/founder/env/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 113, in doc_analyze
    result = custom_model(img)
             │            └ array([[[101, 205, 244],
             │                      [101, 205, 244],
             │                      [101, 205, 244],
             │                      ...,
             │                      [101, 205, 244],
             │                      [101...
             └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x7fbc01a5a530>
  File "/home/founder/env/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 141, in __call__
    layout_res = self.layout_model(image, ignore_catids=[])
                 │    │            └ array([[[101, 205, 244],
                 │    │                      [101, 205, 244],
                 │    │                      [101, 205, 244],
                 │    │                      ...,
                 │    │                      [101, 205, 244],
                 │    │                      [101...
                 │    └ <magic_pdf.model.pek_sub_modules.layoutlmv3.model_init.Layoutlmv3_Predictor object at 0x7fb99382b940>
                 └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x7fbc01a5a530>
  File "/home/founder/env/lib/python3.10/site-packages/magic_pdf/model/pek_sub_modules/layoutlmv3/model_init.py", line 134, in __call__
    outputs = self.predictor(image)
              │    │         └ array([[[101, 205, 244],
              │    │                   [101, 205, 244],
              │    │                   [101, 205, 244],
              │    │                   ...,
              │    │                   [101, 205, 244],
              │    │                   [101...
              │    └ <detectron2.engine.defaults.DefaultPredictor object at 0x7fba6a1fe770>
              └ <magic_pdf.model.pek_sub_modules.layoutlmv3.model_init.Layoutlmv3_Predictor object at 0x7fb99382b940>
  File "/home/founder/env/lib/python3.10/site-packages/detectron2/engine/defaults.py", line 319, in __call__
    predictions = self.model([inputs])[0]
                  │    │      └ {'image': tensor([[[241., 241., 241.,  ..., 241., 241., 243.],
                  │    │                 [239., 239., 239.,  ..., 239., 239., 241.],
                  │    │                 ...
                  │    └ VLGeneralizedRCNN(
                  │        (backbone): FPN(
                  │          (fpn_lateral2): Conv2d(768, 256, kernel_size=(1, 1), stride=(1, 1))
                  │          (fpn_output...
                  └ <detectron2.engine.defaults.DefaultPredictor object at 0x7fba6a1fe770>
  File "/home/founder/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {}
           │    │           └ ([{'image': tensor([[[241., 241., 241.,  ..., 241., 241., 243.],
           │    │                      [239., 239., 239.,  ..., 239., 239., 241.],
           │    │                    ...
           │    └ <function Module._call_impl at 0x7fbbdc2edea0>
           └ VLGeneralizedRCNN(
               (backbone): FPN(
                 (fpn_lateral2): Conv2d(768, 256, kernel_size=(1, 1), stride=(1, 1))
                 (fpn_output...
  File "/home/founder/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {}
           │             └ ([{'image': tensor([[[241., 241., 241.,  ..., 241., 241., 243.],
           │                        [239., 239., 239.,  ..., 239., 239., 241.],
           │                      ...
           └ <bound method VLGeneralizedRCNN.forward of VLGeneralizedRCNN(
               (backbone): FPN(
                 (fpn_lateral2): Conv2d(768, 256, kernel_...
  File "/home/founder/env/lib/python3.10/site-packages/magic_pdf/model/pek_sub_modules/layoutlmv3/rcnn_vl.py", line 55, in forward
    return self.inference(batched_inputs)
           │    │         └ [{'image': tensor([[[241., 241., 241.,  ..., 241., 241., 243.],
           │    │                    [239., 239., 239.,  ..., 239., 239., 241.],
           │    │                   ...
           │    └ <function VLGeneralizedRCNN.inference at 0x7fbaa19879a0>
           └ VLGeneralizedRCNN(
               (backbone): FPN(
                 (fpn_lateral2): Conv2d(768, 256, kernel_size=(1, 1), stride=(1, 1))
                 (fpn_output...
  File "/home/founder/env/lib/python3.10/site-packages/magic_pdf/model/pek_sub_modules/layoutlmv3/rcnn_vl.py", line 117, in inference
    proposals, _ = self.proposal_generator(images, features, None)
                   │                       │       └ <unprintable dict object>
                   │                       └ <detectron2.structures.image_list.ImageList object at 0x7fba61f29900>
                   └ VLGeneralizedRCNN(
                       (backbone): FPN(
                         (fpn_lateral2): Conv2d(768, 256, kernel_size=(1, 1), stride=(1, 1))
                         (fpn_output...
  File "/home/founder/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           │    │           │       └ {}
           │    │           └ <unprintable tuple object>
           │    └ <function Module._call_impl at 0x7fbbdc2edea0>
           └ RPN(
               (rpn_head): StandardRPNHead(
                 (conv): Conv2d(
                   256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
                ...
  File "/home/founder/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           │             │       └ {}
           │             └ <unprintable tuple object>
           └ <bound method RPN.forward of RPN(
               (rpn_head): StandardRPNHead(
                 (conv): Conv2d(
                   256, 256, kernel_size=(3, 3), stri...
  File "/home/founder/env/lib/python3.10/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 477, in forward
    proposals = self.predict_proposals(
                │    └ <function RPN.predict_proposals at 0x7fbaa197dc60>
                └ RPN(
                    (rpn_head): StandardRPNHead(
                      (conv): Conv2d(
                        256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
                     ...
  File "/home/founder/env/lib/python3.10/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 502, in predict_proposals
    pred_proposals = self._decode_proposals(anchors, pred_anchor_deltas)
                     │    │                 │        └ <unprintable list object>
                     │    │                 └ <unprintable list object>
                     │    └ <function RPN._decode_proposals at 0x7fbaa197dcf0>
                     └ RPN(
                         (rpn_head): StandardRPNHead(
                           (conv): Conv2d(
                             256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
                          ...
  File "/home/founder/env/lib/python3.10/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 530, in _decode_proposals
    proposals_i = self.box2box_transform.apply_deltas(pred_anchor_deltas_i, anchors_i)
                  │    │                 │            │                     └ <unprintable Tensor object>
                  │    │                 │            └ <unprintable Tensor object>
                  │    │                 └ <function Box2BoxTransform.apply_deltas at 0x7fbaa19469e0>
                  │    └ <detectron2.modeling.box_regression.Box2BoxTransform object at 0x7fba6a1ab4f0>
                  └ RPN(
                      (rpn_head): StandardRPNHead(
                        (conv): Conv2d(
                          256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
                       ...
  File "/home/founder/env/lib/python3.10/site-packages/detectron2/modeling/box_regression.py", line 108, in apply_deltas
    pred_w = torch.exp(dw) * widths[:, None]
             │     │   │     └ <unprintable Tensor object>
             │     │   └ <unprintable Tensor object>
             │     └ <built-in method exp of type object at 0x7fbb64de3760>
             └ <module 'torch' from '/home/founder/env/lib/python3.10/site-packages/torch/__init__.py'>

RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### How to reproduce the bug | 如何复现

运行magic_pdf_parse_main.py

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
可能是你的cuda版本与torch不兼容，可以尝试下载适配自己cuda版本的torch看看能不能解决。

**Comment by 2257396011** [comment]
> 可能是你的cuda版本与torch不兼容，可以尝试下载适配自己cuda版本的torch看看能不能解决。

好的，谢谢
