### ISSUE TITLE
求助：源码哪里读取magic-pdf.json？

### ISSUE THREAD

**Issue by JiangRunzhi** [opendatalab/MinerU#380]
我的服务器是多GPU的，希望能多开几个窗口，用不同的GPU并行跑MinerU。

但因为magic-pdf.json的位置的文件名都是规定好的，所以不同窗口运行MinerU输出md的路径只能是同一个文件夹。

我希望能为不同的窗口指定单独的文件夹来输出运行结果，因此希望在源码中能修改配置文件magic-pdf.json的名字，比如改成magic-pdf1.json，这样我可以为不同的运行指定不同的输出目录。

请问怎么做到呢？如果不能，有别的解决方案吗？

**Comment by myhloli** [comment]
0.7.x版本支持通过命令行指定output目录，并不再支持从magic-pdf.json获取输出路径，可以看看https://github.com/opendatalab/MinerU/blob/master/README_zh-CN_v2.md#命令行

**Comment by JiangRunzhi** [comment]
> 0.7.x版本支持通过命令行指定output目录，并不再支持从magic-pdf.json获取输出路径，可以看看[https://github.com/opendatalab/MinerU/blob/master/README_zh-CN_v2.md#命令行](https://github.com/opendatalab/MinerU/blob/master/README_zh-CN_v2.md#%E5%91%BD%E4%BB%A4%E8%A1%8C)

诶诶！老师，这个版本是刚刚刚刚发布的吗？那0.6.2b1有没有解决办法呢？

**Comment by myhloli** [comment]
> > 0.7.x版本支持通过命令行指定output目录，并不再支持从magic-pdf.json获取输出路径，可以看看[https://github.com/opendatalab/MinerU/blob/master/README_zh-CN_v2.md#命令行](https://github.com/opendatalab/MinerU/blob/master/README_zh-CN_v2.md#%E5%91%BD%E4%BB%A4%E8%A1%8C)
> 
> 诶诶！老师，这个版本是刚刚刚刚发布的吗？那0.6.2b1有没有解决办法呢？

https://github.com/opendatalab/MinerU/blob/fc6a7c30da53ea5eccd980c4dafe2a61ef3334e2/magic_pdf/libs/config_reader.py#L14

**Comment by JiangRunzhi** [comment]
> > > 0.7.x版本支持通过命令行指定output目录，并不再支持从magic-pdf.json获取输出路径，可以看看[https://github.com/opendatalab/MinerU/blob/master/README_zh-CN_v2.md#命令行](https://github.com/opendatalab/MinerU/blob/master/README_zh-CN_v2.md#%E5%91%BD%E4%BB%A4%E8%A1%8C)
> > 
> > 
> > 诶诶！老师，这个版本是刚刚刚刚发布的吗？那0.6.2b1有没有解决办法呢？
> 
> https://github.com/opendatalab/MinerU/blob/fc6a7c30da53ea5eccd980c4dafe2a61ef3334e2/magic_pdf/libs/config_reader.py#L14

谢谢老师
