### ISSUE TITLE
286页的扫描版PDF文档识别报错

### ISSUE THREAD

**Issue by lceCre4m** [opendatalab/MinerU#383]
### Description of the bug | 错误描述

对100页的PDF进行解析成功，但286页报错，部分错误信息如下：
2024-08-09 17:40:54.590 | ERROR    | __main__:parse_doc:365 - string index out of range
Traceback (most recent call last):
  File "/home/hisense/forAI/zth/llm_core/rag/loader_splitter/MinerU/magic_pdf/cli/magicpdf.py", line 386, in <module>
    cli()
    └ <Group cli>
286页已经识别完毕，但出现报错，最后的正常信息如下：
(正常)
2024-08-09 17:40:54.482 | INFO     | magic_pdf.pdf_parse_union_core:pdf_parse_union:219 - page_id: 286, last_page_cost_time: 0.0
2024-08-09 17:40:54.564 | INFO     | magic_pdf.para.para_split_v2:__detect_list_lines:140 - 发现了列表，列表
2024-08-09 17:40:54.565 | INFO     | magic_pdf.para.para_split_v2:__detect_list_lines:153 - 列表行的第2到第3行是列表
...
(报错)
2024-08-09 17:40:54.590 | ERROR    | __main__:parse_doc:365 - string index out of range
Traceback (most recent call last):
  File "/home/hisense/forAI/zth/llm_core/rag/loader_splitter/MinerU/magic_pdf/cli/magicpdf.py", line 386, in <module>
    cli()
    └ <Group cli>

### How to reproduce the bug | 如何复现

麻烦看一下问题，谢谢

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
把后面的堆栈信息完整发一下？

**Comment by lceCre4m** [comment]
> 把后面的堆栈信息完整发一下？

麻烦看一下：

2024-08-09 17:40:54.590 | ERROR    | __main__:parse_doc:365 - string index out of range
Traceback (most recent call last):

  File "/MinerU/magic_pdf/cli/magicpdf.py", line 386, in <module>
    cli()
    └ <Group cli>

  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f8d42da9870>
           └ <Group cli>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f8c05b626e0>
         │    └ <function MultiCommand.invoke at 0x7f8d42daa830>
         └ <Group cli>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f8c05b62980>
           │               │       │       └ <function Command.invoke at 0x7f8d42daa320>
           │               │       └ <Command pdf-command>
           │               └ <click.core.Context object at 0x7f8c05b62980>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f8c05b88940>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'pdf': '/MinerU/docs/test12.pdf', 'inside_model': True, 'model': None, '...    
           │   │      │    │           └ <click.core.Context object at 0x7f8c05b62980>
           │   │      │    └ <function pdf_command at 0x7f8c05b88f70>
           │   │      └ <Command pdf-command>
           │   └ <function Context.invoke at 0x7f8d42da9090>
           └ <click.core.Context object at 0x7f8c05b62980>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'pdf': '/MinerU/docs/test12.pdf', 'inside_model': True, 'model': None, '...
                       └ ()

  File "/MinerU/magic_pdf/cli/magicpdf.py", line 379, in pdf_command
    parse_doc(pdf)
    │         └ '/MinerU/docs/test12.pdf'
    └ <function pdf_command.<locals>.parse_doc at 0x7f8c05b88d30>

> File "/MinerU/magic_pdf/cli/magicpdf.py", line 357, in parse_doc
    do_parse(
    └ <function do_parse at 0x7f8c05b888b0>

  File "/MinerU/magic_pdf/cli/magicpdf.py", line 142, in do_parse
    pipe.pipe_parse()
    │    └ <function UNIPipe.pipe_parse at 0x7f8c05b17520>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f8c05b635b0>

  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 38, in pipe_parse
    self.pdf_mid_data = parse_ocr_pdf(self.pdf_bytes, self.model_list, self.image_writer,
    │    │              │             │    │          │    │           │    └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x7f8c05b63040>
    │    │              │             │    │          │    │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f8c05b635b0>
    │    │              │             │    │          │    └ [{'layout_dets': [{'category_id': 1, 'poly': [655.239501953125, 990.4547119140625, 991.644775390625, 990.45471191406
25, 991.6...
    │    │              │             │    │          └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f8c05b635b0>
    │    │              │             │    └ b'%PDF-1.6\r%\xe2\xe3\xcf\xd3\r\n3551 0 obj\r<</Linearized 1/L 9774209/O 3553/E 24087/N 287/T 9765834/H [ 855 1715]>>\rendobj...    
    │    │              │             └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f8c05b635b0>
    │    │              └ <function parse_ocr_pdf at 0x7f8c05b17250>
    │    └ None
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f8c05b635b0>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/user_api.py", line 53, in parse_ocr_pdf
    pdf_info_dict = parse_pdf_by_ocr(
                    └ <function parse_pdf_by_ocr at 0x7f8c076b9870>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/pdf_parse_by_ocr.py", line 11, in parse_pdf_by_ocr
    return pdf_parse_union(pdf_bytes,
           │               └ b'%PDF-1.6\r%\xe2\xe3\xcf\xd3\r\n3551 0 obj\r<</Linearized 1/L 9774209/O 3553/E 24087/N 287/T 9765834/H [ 855 1715]>>\rendobj...
           └ <function pdf_parse_union at 0x7f8c05b17010>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core.py", line 229, in pdf_parse_union
    para_split(pdf_info_dict, debug_mode=debug_mode)
    │          │                         └ True
    │          └ {'page_0': {'preproc_blocks': [{'type': 'title', 'bbox': [208, 162, 383, 181], 'lines': [{'bbox': [209, 163, 381, 180], 'span...
    └ <function para_split at 0x7f8c05b14280>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/para/para_split_v2.py", line 746, in para_split
    splited_blocks, page_list_info = __do_split_page(blocks, layout_bboxes, new_layout_bbox, page_num, lang)
    │                                │               │       │              │                │         └ 'en'
    │                                │               │       │              │                └ 'page_13'
    │                                │               │       │              └ [[90, 77, 227, 183]]
    │                                │               │       └ [{'layout_bbox': [0, 0, 595.0, 821.0], 'layout_label': 'V', 'sub_layout': []}]
    │                                │               └ [{'type': 'text', 'bbox': [90, 77, 227, 183], 'lines': [{'bbox': [90, 77, 191, 95], 'spans': [{'bbox': [91, 77, 191, 95], 
'sc...
    │                                └ <function __do_split_page at 0x7f8c05b141f0>
    └ [[{'type': 'text', 'bbox': [78, 79, 280, 93], 'lines': [{'bbox': [78, 79, 280, 93], 'spans': [{'bbox': [78, 79, 276, 93], 'sc...
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/para/para_split_v2.py", line 728, in __do_split_page
    layout_list_info = __split_para_in_layoutbox(blocks_group, new_layout_bbox, lang)  # layout内分段
                       │                         │             │                └ 'en'
                       │                         │             └ [[90, 77, 227, 183]]
                       │                         └ [[{'type': 'text', 'bbox': [90, 77, 227, 183], 'lines': [{'bbox': [90, 77, 191, 95], 'spans': [{'bbox': [91, 77, 191, 95], 's.
..
                       └ <function __split_para_in_layoutbox at 0x7f8c05b33be0>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/para/para_split_v2.py", line 356, in __split_para_in_layoutbox
    text_segments, list_start_line = __detect_list_lines(lines, new_layout_bbox, lang)
                                     │                   │      │                └ 'en'
                                     │                   │      └ [[90, 77, 227, 183]]
                                     │                   └ [{'bbox': [90, 77, 191, 95], 'spans': [{'bbox': [91, 77, 191, 95], 'score': 0.98, 'content': 'R—人行道宽度;', 'type': 
'text'}]}, {...
                                     └ <function __detect_list_lines at 0x7f8c0752d870>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/para/para_split_v2.py", line 117, in __detect_list_lines
    first_char = span_text[0]
                 └ ''

IndexError: string index out of range

**Comment by myhloli** [comment]
@papayalove 看一下分段的问题

**Comment by lceCre4m** [comment]
十分感谢！

**Comment by lceCre4m** [comment]
> @papayalove 看一下分段的问题

此外用另外一篇PDF文档测试，出现如下问题：

2024-08-12 10:05:43.842 | ERROR    | __main__:parse_doc:365 - Dataset 'scihub_train' is already registered!
Traceback (most recent call last):

  File "/MinerU/magic_pdf/cli/magicpdf.py", line 386, in <module>
    cli()
    └ <Group cli>

  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f7a6b131870>
           └ <Group cli>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f791def2500>
         │    └ <function MultiCommand.invoke at 0x7f7a6b132830>
         └ <Group cli>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f791def27a0>
           │               │       │       └ <function Command.invoke at 0x7f7a6b132320>
           │               │       └ <Command pdf-command>
           │               └ <click.core.Context object at 0x7f791def27a0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f791df1c940>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'pdf': '/MinerU/docs/test11.pdf', 'inside_model': True, 'model': None, '...    
           │   │      │    │           └ <click.core.Context object at 0x7f791def27a0>
           │   │      │    └ <function pdf_command at 0x7f791df1cf70>
           │   │      └ <Command pdf-command>
           │   └ <function Context.invoke at 0x7f7a6b131090>
           └ <click.core.Context object at 0x7f791def27a0>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'pdf': '/MinerU/docs/test11.pdf', 'inside_model': True, 'model': None, '...
                       └ ()

  File "/MinerU/magic_pdf/cli/magicpdf.py", line 379, in pdf_command
    parse_doc(pdf)
    │         └ '/MinerU/docs/test11.pdf'
    └ <function pdf_command.<locals>.parse_doc at 0x7f791df1cd30>

> File "/MinerU/magic_pdf/cli/magicpdf.py", line 357, in parse_doc
    do_parse(
    └ <function do_parse at 0x7f791df1c8b0>

  File "/MinerU/magic_pdf/cli/magicpdf.py", line 142, in do_parse
    pipe.pipe_parse()
    │    └ <function UNIPipe.pipe_parse at 0x7f791dea7520>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f791def33d0>

  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 35, in pipe_parse
    self.pdf_mid_data = parse_union_pdf(self.pdf_bytes, self.model_list, self.image_writer,
    │    │              │               │    │          │    │           │    └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x7f791def2f80>
    │    │              │               │    │          │    │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f791def33d0>
    │    │              │               │    │          │    └ [{'layout_dets': [{'category_id': 0, 'poly': [461.81683349609375, 480.4631652832031, 1192.2999267578125, 480.46316
52832031, 1...
    │    │              │               │    │          └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f791def33d0>
    │    │              │               │    └ b'%PDF-1.5\n%\xa1\xb3\xc5\xd7\n1 0 obj\r\n<</Contents 2 0 R /CropBox[ 0 0 595.22 842]/MediaBox[ 0 0 595.22 842]/Parent 1487 0...  
    │    │              │               └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f791def33d0>
    │    │              └ <function parse_union_pdf at 0x7f791dea72e0>
    │    └ None
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f791def33d0>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/user_api.py", line 92, in parse_union_pdf
    pdf_models = doc_analyze(pdf_bytes, ocr=True)
                 │           └ b'%PDF-1.5\n%\xa1\xb3\xc5\xd7\n1 0 obj\r\n<</Contents 2 0 R /CropBox[ 0 0 595.22 842]/MediaBox[ 0 0 595.22 842]/Parent 1487 0...
                 └ <function doc_analyze at 0x7f7a5ac73400>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 69, in doc_analyze
    custom_model = CustomPEKModel(ocr=ocr, show_log=show_log, models_dir=local_models_dir, device=device)
                   │                  │             │                    │                        └ 'cuda'
                   │                  │             │                    └ '/PDF-Extract-Kit/models'
                   │                  │             └ False
                   │                  └ True
                   └ <class 'magic_pdf.model.pdf_extract_kit.CustomPEKModel'>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 109, in __init__
    self.layout_model = Layoutlmv3_Predictor(
    │                   └ <class 'magic_pdf.model.pek_sub_modules.layoutlmv3.model_init.Layoutlmv3_Predictor'>
    └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x7f7871b14d60>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/model/pek_sub_modules/layoutlmv3/model_init.py", line 122, in __init__
    cfg = setup(layout_args, device)
          │     │            └ 'cuda'
          │     └ {'config_file': '/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/resources/model_config/layoutlmv3...
          └ <function setup at 0x7f7872ff7be0>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/model/pek_sub_modules/layoutlmv3/model_init.py", line 82, in setup
    register_coco_instances(
    └ <function register_coco_instances at 0x7f787471add0>
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/detectron2/data/datasets/coco.py", line 510, in register_coco_instances
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
    │              │        │             │              │          │           └ 'scihub_train'
    │              │        │             │              │          └ '/mnt/petrelfs/share_data/zhaozhiyuan/publaynet/layout_scihub/train'
    │              │        │             │              └ '/mnt/petrelfs/share_data/zhaozhiyuan/publaynet/layout_scihub/train.json'
    │              │        │             └ <function load_coco_json at 0x7f787471a4d0>
    │              │        └ 'scihub_train'
    │              └ <function _DatasetCatalog.register at 0x7f7874bf5ea0>
    └ DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_t...
  File "/anaconda3/envs/paddle/lib/python3.10/site-packages/detectron2/data/catalog.py", line 37, in register
    assert name not in self, "Dataset '{}' is already registered!".format(name)
           │           │                                                  └ 'scihub_train'
           │           └ DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_t...
           └ 'scihub_train'

AssertionError: Dataset 'scihub_train' is already registered!

**Comment by myhloli** [comment]
> > @papayalove 看一下分段的问题
> 
> 此外用另外一篇PDF文档测试，出现如下问题：
> 
> 2024-08-12 10:05:43.842 | ERROR | **main**:parse_doc:365 - Dataset 'scihub_train' is already registered! Traceback (most recent call last):
> 
> File "/MinerU/magic_pdf/cli/magicpdf.py", line 386, in cli() └
> 
> File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 1157, in **call** return self.main(*args, **kwargs) │ │ │ └ {} │ │ └ () │ └ <function BaseCommand.main at 0x7f7a6b131870> └ File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 1078, in main rv = self.invoke(ctx) │ │ └ <click.core.Context object at 0x7f791def2500> │ └ <function MultiCommand.invoke at 0x7f7a6b132830> └ File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) │ │ │ │ └ <click.core.Context object at 0x7f791def27a0> │ │ │ └ <function Command.invoke at 0x7f7a6b132320> │ │ └ │ └ <click.core.Context object at 0x7f791def27a0> └ <function MultiCommand.invoke.._process_result at 0x7f791df1c940> File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) │ │ │ │ │ └ {'pdf': '/MinerU/docs/test11.pdf', 'inside_model': True, 'model': None, '... │ │ │ │ └ <click.core.Context object at 0x7f791def27a0> │ │ │ └ <function pdf_command at 0x7f791df1cf70> │ │ └ │ └ <function Context.invoke at 0x7f7a6b131090> └ <click.core.Context object at 0x7f791def27a0> File "/anaconda3/envs/paddle/lib/python3.10/site-packages/click/core.py", line 783, in invoke return __callback(*args, **kwargs) │ └ {'pdf': '/MinerU/docs/test11.pdf', 'inside_model': True, 'model': None, '... └ ()
> 
> File "/MinerU/magic_pdf/cli/magicpdf.py", line 379, in pdf_command parse_doc(pdf) │ └ '/MinerU/docs/test11.pdf' └ <function pdf_command..parse_doc at 0x7f791df1cd30>
> 
> > File "/MinerU/magic_pdf/cli/magicpdf.py", line 357, in parse_doc
> > do_parse(
> > └ <function do_parse at 0x7f791df1c8b0>
> 
> File "/MinerU/magic_pdf/cli/magicpdf.py", line 142, in do_parse pipe.pipe_parse() │ └ <function UNIPipe.pipe_parse at 0x7f791dea7520> └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f791def33d0>
> 
> File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 35, in pipe_parse self.pdf_mid_data = parse_union_pdf(self.pdf_bytes, self.model_list, self.image_writer, │ │ │ │ │ │ │ │ └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x7f791def2f80> │ │ │ │ │ │ │ └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f791def33d0> │ │ │ │ │ │ └ [{'layout_dets': [{'category_id': 0, 'poly': [461.81683349609375, 480.4631652832031, 1192.2999267578125, 480.46316 52832031, 1... │ │ │ │ │ └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f791def33d0> │ │ │ │ └ b'%PDF-1.5\n%\xa1\xb3\xc5\xd7\n1 0 obj\r\n<</Contents 2 0 R /CropBox[ 0 0 595.22 842]/MediaBox[ 0 0 595.22 842]/Parent 1487 0... │ │ │ └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f791def33d0> │ │ └ <function parse_union_pdf at 0x7f791dea72e0> │ └ None └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f791def33d0> File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/user_api.py", line 92, in parse_union_pdf pdf_models = doc_analyze(pdf_bytes, ocr=True) │ └ b'%PDF-1.5\n%\xa1\xb3\xc5\xd7\n1 0 obj\r\n<</Contents 2 0 R /CropBox[ 0 0 595.22 842]/MediaBox[ 0 0 595.22 842]/Parent 1487 0... └ <function doc_analyze at 0x7f7a5ac73400> File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 69, in doc_analyze custom_model = CustomPEKModel(ocr=ocr, show_log=show_log, models_dir=local_models_dir, device=device) │ │ │ │ └ 'cuda' │ │ │ └ '/PDF-Extract-Kit/models' │ │ └ False │ └ True └ <class 'magic_pdf.model.pdf_extract_kit.CustomPEKModel'> File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 109, in **init** self.layout_model = Layoutlmv3_Predictor( │ └ <class 'magic_pdf.model.pek_sub_modules.layoutlmv3.model_init.Layoutlmv3_Predictor'> └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x7f7871b14d60> File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/model/pek_sub_modules/layoutlmv3/model_init.py", line 122, in **init** cfg = setup(layout_args, device) │ │ └ 'cuda' │ └ {'config_file': '/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/resources/model_config/layoutlmv3... └ <function setup at 0x7f7872ff7be0> File "/anaconda3/envs/paddle/lib/python3.10/site-packages/magic_pdf/model/pek_sub_modules/layoutlmv3/model_init.py", line 82, in setup register_coco_instances( └ <function register_coco_instances at 0x7f787471add0> File "/anaconda3/envs/paddle/lib/python3.10/site-packages/detectron2/data/datasets/coco.py", line 510, in register_coco_instances DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name)) │ │ │ │ │ │ └ 'scihub_train' │ │ │ │ │ └ '/mnt/petrelfs/share_data/zhaozhiyuan/publaynet/layout_scihub/train' │ │ │ │ └ '/mnt/petrelfs/share_data/zhaozhiyuan/publaynet/layout_scihub/train.json' │ │ │ └ <function load_coco_json at 0x7f787471a4d0> │ │ └ 'scihub_train' │ └ <function _DatasetCatalog.register at 0x7f7874bf5ea0> └ DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_t... File "/anaconda3/envs/paddle/lib/python3.10/site-packages/detectron2/data/catalog.py", line 37, in register assert name not in self, "Dataset '{}' is already registered!".format(name) │ │ └ 'scihub_train' │ └ DatasetCatalog(registered datasets: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_valminusminival, coco_2017_t... └ 'scihub_train'
> 
> AssertionError: Dataset 'scihub_train' is already registered!

这个在最新版本已经修复，可以通过升级解决。

**Comment by papayalove** [comment]
文件可以发给我测试一下

**Comment by lceCre4m** [comment]
> 文件可以发给我测试一下

[test12.pdf](https://github.com/user-attachments/files/16578525/test12.pdf)

**Comment by lceCre4m** [comment]
> > 文件可以发给我测试一下
> 
> [test12.pdf](https://github.com/user-attachments/files/16578525/test12.pdf)

请问测试有什么结论吗？

**Comment by lceCre4m** [comment]
> > > 文件可以发给我测试一下
> > 
> > 
> > [test12.pdf](https://github.com/user-attachments/files/16578525/test12.pdf)
> 
> 请问测试有什么结论吗？

在多篇100页以内PDF文档中均出现此问题，因此与页数无关，有的PDF会出现，有的则不会。

**Comment by lceCre4m** [comment]
> 文件可以发给我测试一下

你好，请问这个测试有结果了吗

**Comment by myhloli** [comment]
> > 文件可以发给我测试一下
> 
> 
> 
> 你好，请问这个测试有结果了吗

应该已经在dev分支修复了，等待下一次release推送到正式版

**Comment by lceCre4m** [comment]
> > > 文件可以发给我测试一下
> > 
> > 
> > 你好，请问这个测试有结果了吗
> 
> 应该已经在dev分支修复了，等待下一次release推送到正式版

谢谢，期待！

**Comment by lceCre4m** [comment]
> > > 文件可以发给我测试一下
> > 
> > 
> > 你好，请问这个测试有结果了吗
> 
> 应该已经在dev分支修复了，等待下一次release推送到正式版

您好，非常感谢MinerU的工作，请问最新的release版本什么时候发版呢。

**Comment by lceCre4m** [comment]
> 文件可以发给我测试一下

您好，非常感谢您的工作。由于新版本没有发布，但我又急于使用MinerU，因此想问一下这个问题是如何解决的，能简单说一下吗？我是否可以自己修改？

**Comment by papayalove** [comment]
https://github.com/opendatalab/MinerU/compare/master...papayalove:Magic-PDF:bug-fix-383
