### ISSUE TITLE
关闭公式解析

### ISSUE THREAD

**Issue by yuzj1002** [opendatalab/MinerU#394]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**请问可以关闭公式解析功能吗？

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/7cdf88c668f90c7a97821d5f26f10340dd8f5000/magic_pdf/model/doc_analyze_by_custom_model.py#L88
在这个字典结构的末尾增加一条`"apply_formula": False`即可

**Comment by lceCre4m** [comment]
> https://github.com/opendatalab/MinerU/blob/7cdf88c668f90c7a97821d5f26f10340dd8f5000/magic_pdf/model/doc_analyze_by_custom_model.py#L88
> 
> 
> 在这个字典结构的末尾增加一条`"apply_formula": False`即可

请问这样的话公式是怎么识别呢，是用OCR吗？还是说这样就不再识别公式了呢？

**Comment by myhloli** [comment]
> > https://github.com/opendatalab/MinerU/blob/7cdf88c668f90c7a97821d5f26f10340dd8f5000/magic_pdf/model/doc_analyze_by_custom_model.py#L88
> > 
> > 在这个字典结构的末尾增加一条`"apply_formula": False`即可
> 
> 请问这样的话公式是怎么识别呢，是用OCR吗？还是说这样就不再识别公式了呢？

这样处理之后就不识别公式了
