### ISSUE TITLE
支持自动将图片上传到s3

### ISSUE THREAD

**Issue by liqiankun1111** [opendatalab/MinerU#395]
是否可以支持用户配置s3 url sk sk，进而自动将解析的图片上传到s3上，markdown 中的image标签自动引用s3 地址？

**Comment by myhloli** [comment]
是支持这个功能的，可以参考readme中的
https://github.com/opendatalab/MinerU/tree/master#api

```python
image_dir = "s3://img_bucket/"
s3image_cli = S3ReaderWriter(img_ak, img_sk, img_endpoint, parent_path=image_dir)
...
pipe = UNIPipe(pdf_bytes, jso_useful_key, s3image_cli)
```

这样解析的图片会自动上传到`s3://img_bucket/` 中，生成的markdown中image标签也会是拼装好的s3路径。

**Comment by liyunhan** [comment]
@myhloli 我使用magic-pdf 1.2.2，readme中没找到您提到这段代码，用官方api的示例markdown中的Image标签不会拼装好endpoint路径

**Comment by myhloli** [comment]
> @myhloli 我使用magic-pdf 1.2.2，readme中没找到您提到这段代码，用官方api的示例markdown中的Image标签不会拼装好endpoint路径

是不会拼接endpoint和bucket路径的，因为我们经常有桶迁移的需求，要用的时候自己拼一下就行
