### ISSUE TITLE
能否更新一下工程化相关的内容，一个类似fastapi的后端接口，dockerfile就能拉起来的

### ISSUE THREAD

**Issue by Hammer-888** [opendatalab/MinerU#402]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
对存在的问题进行清晰且简洁的描述。例如：我一直很困扰的是 [...]

**Describe the solution you'd like**
**描述您期望的解决方案**
清晰且简洁地描述您希望实现的内容。

**Describe alternatives you've considered**
**描述您已考虑的替代方案**
清晰且简洁地描述您已经考虑过的任何替代解决方案。

**Additional context**
**提供更多细节**
请附上任何相关截图、链接或文件，以帮助我们更好地理解您的请求。

**Comment by weihanfeng** [comment]
同求

**Comment by Kyrie666** [comment]
hammer哥，我帮你写一个吧。

**Comment by drunkpig** [comment]
@weihanfeng Take a look at this project : https://github.com/magicyuan876/mineru-server

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/tree/dev/web_api
