### ISSUE TITLE
输出的markdown中，很多单词没有分隔，连在一起了

### ISSUE THREAD

**Issue by wzl0329** [opendatalab/MinerU#408]
### Description of the bug | 错误描述

原文（公司环境上传不了文件，只能粘贴出来）：
This innovative approach bypasses the interaction with cumbersome structured text, empowering SeeClick to universally adapt to various GUI platforms. Building such visual agents presents a foundational challenge: GUI grounding - the capacity to accurately locate screen elements based on instructions, which is absent in current LVLMs.To tackle this challenge, SeeClick enhances LVLM with a GUI grounding pre-training strategy. We devise a method to automate the curation of web grounding data and adapt public mobile UI datasets to obtain mobile grounding data. SeeClick employs the above-curated dataset for continual pre-training of the LVLM, enabling it to accurately locate elements such as text, widgets, and icons in various GUI environments.

识别的markdown：
 This innovative approach bypasses the inter- action with cumbersome structured text, empower ing See Click to universally adapt **tovariousGUl** platforms.**Buildingsuchvisualagentspresentsa** foundational challenge: GUI grounding - the capac- ity to accurately locate screen elements based on instructions,which is absent in current LVLMs.To tackle this challenge,SeeClick enhances LVLM with a GUI grounding pre-training strategy. We **deviseamethodtoautomatethecurationofweb** grounding data and adapt public mobile UI datasets to obtain mobile grounding data. SeeClick employs the above-curated dataset for continual pre-training of the LVLM,enabling it to accurately locate ele- ments such as text, widgets, and icons in various **GUIenvironments**.  

### How to reproduce the bug | 如何复现

使用的pdf：SeeClick: Harnessing GUI Grounding for Advanced Visual GUI Agents，是一篇论文
https://arxiv.org/pdf/2401.10935

版本：magic-pdf, version 0.7.0b1
运行参数：magic-pdf -p "xxx" -o "xxx" -m ocr
启动了ocr功能

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.0b1

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
测试了一下这篇文档，用auto模式生产的markdown效果较好，这种文本类型且默认解析效果较好的pdf不需要手动指定ocr模式处理。ocr模式下是会出现部分单词粘连的情况，我们已经通过一些方案对粘连单词做了分词处理，但是不能保证每个粘连的单词都能准确识别并处理。后期我们也会继续优化粘连单词的处理方案。

**Comment by wzl0329** [comment]
> 测试本文这篇文档，用auto模式生成的markdown效果较好，文本类型且默认解析效果较好的pdf这种不需要手动指定ocr模式处理。ocr模式下面是会出现部分单词粘连的情况，我们已经通过一些方案对粘连单词做了分词处理，但不能保证每个粘连单词都能准确识别并处理。后期我们还继续优化粘连单词的处理方案。

我试了auto模式，确实效果很好。请问一下auto模式对扫描件pdf可以正确使用ocr提取吗，如果可以的话，是不是对大部分pdf文档，只用保持auto模式就可以了

**Comment by myhloli** [comment]
> > 测试本文这篇文档，用auto模式生成的markdown效果较好，文本类型且默认解析效果较好的pdf这种不需要手动指定ocr模式处理。ocr模式下面是会出现部分单词粘连的情况，我们已经通过一些方案对粘连单词做了分词处理，但不能保证每个粘连单词都能准确识别并处理。后期我们还继续优化粘连单词的处理方案。
> 
> 
> 
> 我试了auto模式，确实效果很好。请问一下auto模式对扫描件pdf可以正确使用ocr提取吗，如果可以的话，是不是对大部分pdf文档，只用保持auto模式就可以了

是的，auto模式可以适配绝大多数文档，包括扫描版pdf也可以自动选择ocr模式，一般直接默认的auto即可。

**Comment by wzl0329** [comment]
> > > 测试本文这篇文档，用auto模式生成的markdown效果较好，文本类型且默认解析效果较好的pdf这种不需要手动指定ocr模式处理。ocr模式下面是会出现部分单词粘连的情况，我们已经通过一些方案对粘连单词做了分词处理，但不能保证每个粘连单词都能准确识别并处理。后期我们还继续优化粘连单词的处理方案。
> > 
> > 
> > 我试了auto模式，确实效果很好。请问一下auto模式对扫描件pdf可以正确使用ocr提取吗，如果可以的话，是不是对大部分pdf文档，只用保持auto模式就可以了
> 
> 是的，auto模式可以适配绝大多数文档，包括扫描版pdf也可以自动选择ocr模式，一般直接默认的auto即可。

好的，非常感谢~
