### ISSUE TITLE
相关依赖已安装但提示错误为所需依赖未安装

### ISSUE THREAD

**Issue by Putin0922** [opendatalab/MinerU#411]
### Description of the bug | 错误描述

已根据Readme步骤完成Magic-PDF的CPU体验版安装，在运行测试时出现错误，提示缺少fairscale模块，如图所示，然后按其给出的指示重新用pip install进行安装，显示所有需要的依赖已经安装，然而仍然出现同样错误，请各位帮忙查找原因，软件版本为0.7.0b1。
![屏幕截图 2024-08-13 160607](https://github.com/user-attachments/assets/30d5d1bc-0d7f-451f-a90e-3b722fd5eb2d)

### How to reproduce the bug | 如何复现

如错误描述所示

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
```bash
pip uninstall fairscale
pip install fairscale
```
卸了再装一下这个模块

**Comment by Putin0922** [comment]
好的感谢，该问题已解决

**Comment by QuintinTao** [comment]
我这边 0.7.1 卸载了，再安装还是不行啊
![image](https://github.com/user-attachments/assets/6efc250b-e455-42ac-bfe6-344a092c847a) @myhloli

**Comment by myhloli** [comment]
> 我这边 0.7.1 卸载了，再安装还是不行啊 ![image](https://private-user-images.githubusercontent.com/72123724/365580813-6efc250b-e455-42ac-bfe6-344a092c847a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NzIyMDAsIm5iZiI6MTcyNTg3MTkwMCwicGF0aCI6Ii83MjEyMzcyNC8zNjU1ODA4MTMtNmVmYzI1MGItZTQ1NS00MmFjLWJmZTYtMzQ0YTA5MmM4NDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA4NTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmOTkwZTIxODA0MzZhNzgxMTZlZTA3MmViMjQxNjNiZGU1MzYwOTllOTA2ZjhhN2VkMDEwYjM2MjVlNzM4YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s-sgtAS__qkAXK7LDVlwPRtTd8hKQYIjFfxJdffnP1w) @myhloli

不需要卸载magic-pdf，只需要执行：
pip uninstall fairscale
pip install fairscale
重装这个模块即可
