### ISSUE TITLE
zsh: no matches found: magic-pdf[full]==0.7.0b1

### ISSUE THREAD

**Issue by Kyrie666** [opendatalab/MinerU#412]
### Description of the bug | 错误描述

pip install magic-pdf[full]==0.7.0b1 --extra-index-url https://wheels.myhloli.com -i https://pypi.tuna.tsinghua.edu.cn/simple 时出现这个问题

### How to reproduce the bug | 如何复现

安装时即可复现

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
zsh问题，参考FAQ可以解决
https://github.com/opendatalab/MinerU/blob/master/docs/FAQ_zh_cn.md#1在较新版本的mac上使用命令安装pip-install-magic-pdffull-zsh-no-matches-found-magic-pdffull

**Comment by Schumpeterx** [comment]
`pip install "magic-pdf[full]==0.7.0b1" --extra-index-url https://wheels.myhloli.com -i https://pypi.tuna.tsinghua.edu.cn/simple`
我在zsh里用引号把有方括号的部分包起来可以解决

**Comment by kwangsuklee** [comment]
ERROR: No matching distribution found for detectron2; extra == "full"  
  
\---  
OS. Mac M1 Pro. 14.5.   
Python ver. 3.12.3.   
  
\> pip install "magic-pdf\[full\]==0.7.0b1" --extra-index-url https://wheels.myhloli.com -i https://pypi.tuna.tsinghua.edu.cn/simple

\> pip install "magic-pdf\[full\]==0.7.0b1" --extra-index-url [https://wheels.myhloli.com](https://wheels.myhloli.com)  
...  
...   
ERROR: Ignored the following versions that require a different python version: 8.0.10 Requires-Python >=3.7,\<=3.11; 8.0.11 Requires-Python >=3.7,\<=3.11; 8.0.12 Requires-Python >=3.7,\<=3.11; 8.0.13 Requires-Python >=3.7,\<=3.11; 8.0.14 Requires-Python >=3.7,\<=3.11; 8.0.15 Requires-Python >=3.7,\<=3.11; 8.0.16 Requires-Python >=3.7,\<=3.11; 8.0.17 Requires-Python >=3.7,\<=3.11; 8.0.18 Requires-Python >=3.7,\<=3.11; 8.0.19 Requires-Python >=3.7,\<=3.11; 8.0.20 Requires-Python >=3.7,\<=3.11; 8.0.21 Requires-Python >=3.7,\<=3.11; 8.0.22 Requires-Python >=3.7,\<=3.11; 8.0.23 Requires-Python >=3.7,\<=3.11; 8.0.24 Requires-Python >=3.7,\<=3.11; 8.0.25 Requires-Python >=3.7,\<=3.11; 8.0.26 Requires-Python >=3.7,\<=3.11; 8.0.27 Requires-Python >=3.7,\<=3.11; 8.0.28 Requires-Python >=3.7,\<=3.11; 8.0.29 Requires-Python >=3.7,\<=3.11; 8.0.30 Requires-Python >=3.7,\<=3.11; 8.0.31 Requires-Python >=3.7,\<=3.11; 8.0.32 Requires-Python >=3.7,\<=3.11; 8.0.33 Requires-Python >=3.7,\<=3.11; 8.0.34 Requires-Python >=3.7,\<=3.11; 8.0.7 Requires-Python >=3.7,\<=3.11; 8.0.8 Requires-Python >=3.7,\<=3.11; 8.0.9 Requires-Python >=3.7,\<=3.11  
ERROR: Could not find a version that satisfies the requirement detectron2; extra == "full" (from magic-pdf\[full\]) (from versions: none)  
ERROR: No matching distribution found for detectron2; extra == "full"

**Comment by myhloli** [comment]
> ERROR: No matching distribution found for detectron2; extra == "full"  
> 
>   
> 
> \---  
> 
> OS. Mac M1 Pro. 14.5.   
> 
> Python ver. 3.12.3.   
> 
>   
> 
> \> pip install "magic-pdf\[full\]==0.7.0b1" --extra-index-url https://wheels.myhloli.com -i https://pypi.tuna.tsinghua.edu.cn/simple
> 
> 
> 
> \> pip install "magic-pdf\[full\]==0.7.0b1" --extra-index-url [https://wheels.myhloli.com](https://wheels.myhloli.com)  
> 
> ...  
> 
> ...   
> 
> ERROR: Ignored the following versions that require a different python version: 8.0.10 Requires-Python >=3.7,\<=3.11; 8.0.11 Requires-Python >=3.7,\<=3.11; 8.0.12 Requires-Python >=3.7,\<=3.11; 8.0.13 Requires-Python >=3.7,\<=3.11; 8.0.14 Requires-Python >=3.7,\<=3.11; 8.0.15 Requires-Python >=3.7,\<=3.11; 8.0.16 Requires-Python >=3.7,\<=3.11; 8.0.17 Requires-Python >=3.7,\<=3.11; 8.0.18 Requires-Python >=3.7,\<=3.11; 8.0.19 Requires-Python >=3.7,\<=3.11; 8.0.20 Requires-Python >=3.7,\<=3.11; 8.0.21 Requires-Python >=3.7,\<=3.11; 8.0.22 Requires-Python >=3.7,\<=3.11; 8.0.23 Requires-Python >=3.7,\<=3.11; 8.0.24 Requires-Python >=3.7,\<=3.11; 8.0.25 Requires-Python >=3.7,\<=3.11; 8.0.26 Requires-Python >=3.7,\<=3.11; 8.0.27 Requires-Python >=3.7,\<=3.11; 8.0.28 Requires-Python >=3.7,\<=3.11; 8.0.29 Requires-Python >=3.7,\<=3.11; 8.0.30 Requires-Python >=3.7,\<=3.11; 8.0.31 Requires-Python >=3.7,\<=3.11; 8.0.32 Requires-Python >=3.7,\<=3.11; 8.0.33 Requires-Python >=3.7,\<=3.11; 8.0.34 Requires-Python >=3.7,\<=3.11; 8.0.7 Requires-Python >=3.7,\<=3.11; 8.0.8 Requires-Python >=3.7,\<=3.11; 8.0.9 Requires-Python >=3.7,\<=3.11  
> 
> ERROR: Could not find a version that satisfies the requirement detectron2; extra == "full" (from magic-pdf\[full\]) (from versions: none)  
> 
> ERROR: No matching distribution found for detectron2; extra == "full"

please use python3.10

**Comment by kwangsuklee** [comment]
please use python3.10  
  
Thank you for attention.
