### ISSUE TITLE
如何对layout模型进行微调

### ISSUE THREAD

**Issue by dengtianmin** [opendatalab/MinerU#416]
有些pdf分块有一点问题，如何使用私有数据进行微调
![image](https://github.com/user-attachments/assets/a94426fb-033d-4b2d-bb9d-74a900c84b37)
正确分块如下：
![image](https://github.com/user-attachments/assets/96f7e2c1-37f0-438e-b975-bb493c866db7)

**Comment by myhloli** [comment]
layout识别看着没问题，这个是后处理算法问题，如果有能力二次开发的话直接对算法部分进行修改就行。
layout核心算法是这个
https://github.com/opendatalab/MinerU/blob/4983bc1df668b80fa3481fa657eb509b448bb082/magic_pdf/pdf_parse_union_core.py#L152
能解决这种多栏排版的话也欢迎提pr。

**Comment by drunkpig** [comment]
@dengtianmin Due to copyright issues with the training data, it cannot be made public. If needed, you can contact the Opendatalab assistant in the WeChat group for cooperation.
