### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by chaobian** [opendatalab/MinerU#421]
### Description of the bug | 错误描述

pip install magic-pdf[full]==0.7.0b1 --extra-index-url https://wheels.myhloli.com

zsh: no matches found: magic-pdf[full]==0.7.0b1

### How to reproduce the bug | 如何复现

pip install magic-pdf[full]==0.7.0b1 --extra-index-url https://wheels.myhloli.com

zsh: no matches found: magic-pdf[full]==0.7.0b1

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.5.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
请阅读FAQ第一条
