### ISSUE TITLE
RuntimeError: CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by 2257396011** [opendatalab/MinerU#426]
### Description of the bug | 错误描述

2024-08-14 05:45:39.030 | ERROR    | __main__:pdf_parse_main:135 - CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):

  File "/home/founder/New/MinerU-master/demo/magic_pdf_parse_main.py", line 224, in <module>
    pdf_parse_main(pdf_path)
    │              └ '/home/founder/New/pdf/paper_1.pdf'
    └ <function pdf_parse_main at 0x7fc2be1ba5f0>

> File "/home/founder/New/MinerU-master/demo/magic_pdf_parse_main.py", line 117, in pdf_parse_main
    pipe.pipe_analyze()  # 解析
    │    └ <function TXTPipe.pipe_analyze at 0x7fc2be1ba170>
    └ <magic_pdf.pipe.TXTPipe.TXTPipe object at 0x7fc2b05f0910>

  File "/home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/TXTPipe.py", line 20, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=False)
    │    │            │           │    └ b'%PDF-1.3\n%\xe2\xe3\xcf\xd3\n1 0 obj\n<<\n/Type /Pages\n/Count 1\n/Kids [ 4 0 R ]\n>>\nendobj\n2 0 obj\n<<\n/Producer (PyPD...
    │    │            │           └ <magic_pdf.pipe.TXTPipe.TXTPipe object at 0x7fc2b05f0910>
    │    │            └ <function doc_analyze at 0x7fc3532de9e0>
    │    └ []
    └ <magic_pdf.pipe.TXTPipe.TXTPipe object at 0x7fc2b05f0910>
  File "/home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 119, in doc_analyze
    result = custom_model(img)
             │            └ array([[[255, 255, 255],
             │                      [255, 255, 255],
             │                      [255, 255, 255],
             │                      ...,
             │                      [255, 255, 255],
             │                      [255...
             └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x7fc2b05f07c0>
  File "/home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 184, in __call__
    output = self.mfr_model.generate({'image': mf_img})
             │    │         │                  └ <unprintable Tensor object>
             │    │         └ <function UniMERModel.generate at 0x7fc14d689ea0>
             │    └ UniMERModel(
             │        (model): DonutEncoderDecoder(
             │          (model): CustomVisionEncoderDecoderModel(
             │            (encoder): DonutSwinModel(
             │       ...
             └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x7fc2b05f07c0>
  File "/home/founder/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ <unprintable tuple object>
           └ <function UniMERModel.generate at 0x7fc14d689e10>
  File "/home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages/unimernet/models/unimernet/unimernet.py", line 80, in generate
    outputs = self.model.generate(
              └ UniMERModel(
                  (model): DonutEncoderDecoder(
                    (model): CustomVisionEncoderDecoderModel(
                      (encoder): DonutSwinModel(
                 ...
  File "/home/founder/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           │     │       └ <unprintable dict object>
           │     └ (DonutEncoderDecoder(
           │         (model): CustomVisionEncoderDecoderModel(
           │           (encoder): DonutSwinModel(
           │             (embeddings): DonutSwi...
           └ <function DonutEncoderDecoder.generate at 0x7fc14d6897e0>
  File "/home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages/unimernet/models/unimernet/encoder_decoder.py", line 746, in generate
    outputs = self.model.generate(
              └ DonutEncoderDecoder(
                  (model): CustomVisionEncoderDecoderModel(
                    (encoder): DonutSwinModel(
                      (embeddings): DonutSwin...
  File "/home/founder/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           │     │       └ <unprintable dict object>
           │     └ (CustomVisionEncoderDecoderModel(
           │         (encoder): DonutSwinModel(
           │           (embeddings): DonutSwinEmbeddings(
           │             (patch_embeddings...
           └ <function GenerationMixin.generate at 0x7fc14d96f370>
  File "/home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages/transformers/generation/utils.py", line 1576, in generate
    result = self._greedy_search(
             │    └ <function GenerationMixin._greedy_search at 0x7fc14d96f760>
             └ CustomVisionEncoderDecoderModel(
                 (encoder): DonutSwinModel(
                   (embeddings): DonutSwinEmbeddings(
                     (patch_embeddings)...
  File "/home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages/transformers/generation/utils.py", line 2548, in _greedy_search
    unfinished_sequences = unfinished_sequences & ~stopping_criteria(input_ids, scores)
                           │                       │                 │          └ None
                           │                       │                 └ <unprintable Tensor object>
                           │                       └ [<transformers.generation.stopping_criteria.MaxLengthCriteria object at 0x7fc081fcdc60>, <transformers.generation.stopping_cr...
                           └ <unprintable Tensor object>
  File "/home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages/transformers/generation/stopping_criteria.py", line 158, in __call__
    is_done = is_done | criteria(input_ids, scores, **kwargs)
              │         │        │          │         └ {}
              │         │        │          └ None
              │         │        └ <unprintable Tensor object>
              │         └ <transformers.generation.stopping_criteria.EosTokenCriteria object at 0x7fc081fcd720>
              └ <unprintable Tensor object>
  File "/home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages/transformers/generation/stopping_criteria.py", line 149, in __call__
    is_done = torch.isin(input_ids[:, -1], self.eos_token_id.to(input_ids.device))
              │     │    │                 │    │            │  │         └ <attribute 'device' of 'torch._C.TensorBase' objects>
              │     │    │                 │    │            │  └ <unprintable Tensor object>
              │     │    │                 │    │            └ <method 'to' of 'torch._C.TensorBase' objects>
              │     │    │                 │    └ tensor([2])
              │     │    │                 └ <transformers.generation.stopping_criteria.EosTokenCriteria object at 0x7fc081fcd720>
              │     │    └ <unprintable Tensor object>
              │     └ <built-in method isin of type object at 0x7fc213a81760>
              └ <module 'torch' from '/home/founder/.local/lib/python3.10/site-packages/torch/__init__.py'>

RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### How to reproduce the bug | 如何复现

magic_pdf_parse_main.py

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by 2257396011** [comment]
报这个错之后显卡也会无法使用，必须重启服务器之后才可以重新使用显卡。

**Comment by myhloli** [comment]
看着像显卡硬件问题，显存不足导致的？

**Comment by 2257396011** [comment]
> 看着像显卡硬件问题，显存不足导致的？

显存11G，感觉按理来说不应该这样

**Comment by myhloli** [comment]
> > 看着像显卡硬件问题，显存不足导致的？
> 
> 
> 
> 显存11G，感觉按理来说不应该这样

开ocr加速了吗

**Comment by 2257396011** [comment]
> > > 看着像显卡硬件问题，显存不足导致的？
> > 
> > 
> > 显存11G，感觉按理来说不应该这样
> 
> 开ocr加速了吗

我都是在默认配置下跑的

**Comment by 2257396011** [comment]
> > > 看着像显卡硬件问题，显存不足导致的？
> > 
> > 
> > 显存11G，感觉按理来说不应该这样
> 
> 开ocr加速了吗

抱歉好像是显卡坏了

**Comment by myhloli** [comment]
> > > > 看着像显卡硬件问题，显存不足导致的？
> 
> > > 
> 
> > > 
> 
> > > 显存11G，感觉按理来说不应该这样
> 
> > 
> 
> > 开ocr加速了吗
> 
> 
> 
> 我都是在默认配置下跑的

默认是？

**Comment by 2257396011** [comment]
> > > > > 看着像显卡硬件问题，明显存在不足导致的？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 显存11G，感觉按理来说不应该这样
> > 
> > 
> > > 
> > 
> > 
> > > 开启ocr加速了吗
> > 
> > 
> > 我都是在默认配置下跑的
> 
> 默认是？

没有开启ocr加速的，看了下我这个好像是显卡问题

**Comment by myhloli** [comment]
我也从网上查了一下，这个可能和显卡硬件状态或者一些配置有关，应该和本项目是无关的。

**Comment by 2257396011** [comment]
> 我也从网上查了一下，这个可能和显卡硬件状态或者一些配置有关，应该和本项目是相关的。

好的，我这边再排查下

**Comment by 2257396011** [comment]
> 我也从网上查了一下，这个可能和显卡硬件状态或者一些配置有关，应该和本项目是相关的。

换了张显卡没问题了，换的型号和之前一样的，应该就是显卡出问题了。
