### ISSUE TITLE
category_id 

### ISSUE THREAD

**Issue by Note-Liu** [opendatalab/MinerU#427]
In the magic_model.py file, there is the following code:

for layout_det in layout_dets:
    category_id = layout_det["category_id"]
    if category_id in allow_category_id_list:
        span = {"bbox": layout_det["bbox"], "score": layout_det["score"]}
        if category_id == 3:
            span["type"] = ContentType.Image
        elif category_id == 5:
            span["type"] = ContentType.Table
        elif category_id == 13:
            span["content"] = layout_det["latex"]
            span["type"] = ContentType.InlineEquation
        elif category_id == 14:
            span["content"] = layout_det["latex"]
            span["type"] = ContentType.InterlineEquation
        elif category_id == 15:
            span["content"] = layout_det["text"]
            span["type"] = ContentType.Text
        all_spans.append(span)
return remove_duplicate_spans(all_spans)                     

Does category 15 represent text? Shouldn't it be category 1?

**Comment by Note-Liu** [comment]
If using Layoutlmv3_Predictor, with the formula type set as 'isolate_formula', what is its relationship with 'InterlineEquation' and 'InlineEquation'?

**Comment by myhloli** [comment]
15是ocr出来的文本，或许你可以参考这个
```
{0: 'title',              # Title
 1: 'plain text',         # Text
 2: 'abandon',            # Includes headers, footers, page numbers, and page annotations
 3: 'figure',             # Image
 4: 'figure_caption',     # Image caption
 5: 'table',              # Table
 6: 'table_caption',      # Table caption
 7: 'table_footnote',     # Table footnote
 8: 'isolate_formula',    # Display formula (this is a layout display formula, lower priority than 14)
 9: 'formula_caption',    # Display formula label

 13: 'inline_formula',    # Inline formula
 14: 'isolated_formula',  # Display formula
 15: 'ocr_text'}          # OCR result
```

**Comment by Note-Liu** [comment]
> 15是ocr出来的文本，或许你可以参考这个
> 
> ```
> {0: 'title',              # Title
>  1: 'plain text',         # Text
>  2: 'abandon',            # Includes headers, footers, page numbers, and page annotations
>  3: 'figure',             # Image
>  4: 'figure_caption',     # Image caption
>  5: 'table',              # Table
>  6: 'table_caption',      # Table caption
>  7: 'table_footnote',     # Table footnote
>  8: 'isolate_formula',    # Display formula (this is a layout display formula, lower priority than 14)
>  9: 'formula_caption',    # Display formula label
> 
>  13: 'inline_formula',    # Inline formula
>  14: 'isolated_formula',  # Display formula
>  15: 'ocr_text'}          # OCR result
> ```

Got it, thank you for the explanation!
