### ISSUE TITLE
0.7版本表格识别全都是图片

### ISSUE THREAD

**Issue by ynywna** [opendatalab/MinerU#431]
不是说0.7有识别表格的能力吗，为什么还是会将所有表格都变成图片

**Comment by TianCai19** [comment]
同样遇到了这个问题
![image](https://github.com/user-attachments/assets/6159489c-a6eb-4367-9d46-58351110699f)

**Comment by riku7032** [comment]
把配置文件里的"is_table_recog_enable": false， 改成true，就可以开启识别功能了，文档里写着默认关闭。但是识别后是表格那部分是latex格式，md无法渲染。

**Comment by TianCai19** [comment]
> 把配置文件里的"is_table_recog_enable": false， 改成true，就可以开启识别功能了，文档里写着默认关闭。但是识别后是表格那部分是latex格式，md无法渲染。

好的 谢谢解答 我还没有在本地部署 我是用的GitHub里的线上demo的那个网站
