### ISSUE TITLE
有一个需要联网下载

### ISSUE THREAD

**Issue by 1greatday** [opendatalab/MinerU#432]
### Description of the bug | 错误描述

<img width="748" alt="image" src="https://github.com/user-attachments/assets/d1131753-54e8-4548-939c-0f3239e5c624">
想问下，这个xu'yao'l需要联网的地方在哪，不联网的怎么解决呢

### How to reproduce the bug | 如何复现

    不联网会出现这个问题

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by drunkpig** [comment]
@1greatday you should disable ultralytics auto update.  set env  `NO_ALBUMENTATIONS_UPDATE=1` will solve this problem.

**Comment by 1greatday** [comment]
在代码中有办法解决吗

**Comment by drunkpig** [comment]
@1greatday 
```python
import os

# set env
os.environ['MY_ENV_VAR'] = 'some_value'

```

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/295df3293c02cf8077be1ceb1a4ebd8e86bacfbe/magic_pdf/model/pdf_extract_kit.py#L7
在>=0.6.2b1版本已经修复这个问题了，直接升级到新版本即可
