### ISSUE TITLE
关于LayoutLMv3模型

### ISSUE THREAD

**Issue by Jamly7** [opendatalab/MinerU#437]
目前我是用MinerU指定的LayoutLMv3模型效果并不理想，通过查阅资料发现LayoutLMv3官方有3个不同的预训练模型，我如何在MinerU中替换模型呐？需要进行代码的修改吗？目前的模型地址是这样的：/opt/PDF-Extract-Kit/models/Layout/model_final.pth，模型同级目录有个config.json。

**Comment by myhloli** [comment]
我们的模型字典与原版不兼容，而且后处理模块也不支持原版模型字典，因此不支持自行替换layout模型

**Comment by shellyfung** [comment]
> 我们的模型字典与原版不兼容，而且后处理模块也不支持原版模型字典，因此不支持自行替换layout模型

大佬您好，请问你们是对layoutlmv3做了微调或者是预训练吗
