### ISSUE TITLE
torchvision报错

### ISSUE THREAD

**Issue by 1greatday** [opendatalab/MinerU#438]
### Description of the bug | 错误描述

<img width="710" alt="image" src="https://github.com/user-attachments/assets/d07e2be9-b260-43d6-8d36-d9aecd1fd5f3">
走ocr的pdf正常，走txt的pdf报这个问题，是torchvision版本问题吗？

### How to reproduce the bug | 如何复现

 <img width="710" alt="image" src="https://github.com/user-attachments/assets/d07e2be9-b260-43d6-8d36-d9aecd1fd5f3">
走ocr的pdf正常，走txt的pdf报这个问题，是torchvision版本问题吗？

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
没理由ocr正常txt不正常的，如果torchvision有问题是不管什么模式都运行不了的
