### ISSUE TITLE
I want to convert to a docx file from pdf. What can i do for it .

### ISSUE THREAD

**Issue by zuanzuanshao** [opendatalab/MinerU#442]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
通过mineru提取pdf文档后，想将md格式的文件转成word格式

**Describe the solution you'd like**
**描述您期望的解决方案**
能否支持将提取出来的格式化的markdown文件再转成其他格式，比如word

**Describe alternatives you've considered**
**描述您已考虑的替代方案**
目前通过pandoc将md转成word，但是结果不理想。通过pdf2doc工具直接转成word，效果也不理想。

**Additional context**
**提供更多细节**
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/fe736d2f-c733-4a69-95e8-18484d033ee0">
<img width="1178" alt="image" src="https://github.com/user-attachments/assets/85f826c9-4319-4920-9f70-1c3f55894f4e">
目前使用最新的0.7.b版本转换，有出现乱码或者页面识别问题。

**Comment by drunkpig** [comment]
@zuanzuanshao use parameters `-m ocr` can solve you problem.  You can try pandoc  to convert markdown to docx

**Comment by zuanzuanshao** [comment]
ok, i'll try it.

**Comment by zuanzuanshao** [comment]
@drunkpig 还是有乱码的情况，这个是因为什么呢
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/9a73885f-bbdf-4a28-b57e-75a6b89c65b2">

**Comment by wlevene** [comment]
pdf2document.com - No loss of pdf layout
30 free page conversions daily for all users.
