### ISSUE TITLE
ocr加速包下载的时候nvidia-nccl-cu11会与原库有冲突

### ISSUE THREAD

**Issue by 2257396011** [opendatalab/MinerU#446]
### Description of the bug | 错误描述

(MinerU) founder@founder:~/MinerU/MinerU-master$ python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/
Looking in indexes: https://www.paddlepaddle.org.cn/packages/stable/cu118/
Collecting paddlepaddle-gpu==3.0.0b1
  Downloading https://paddle-whl.bj.bcebos.com/stable/cu118/paddlepaddle-gpu/paddlepaddle_gpu-3.0.0b1-cp310-cp310-linux_x86_64.whl (845.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 845.8/845.8 MB 1.5 MB/s eta 0:00:00
Requirement already satisfied: httpx in /home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (0.27.0)
Requirement already satisfied: numpy<2.0,>=1.13 in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (1.26.3)
Requirement already satisfied: protobuf>=3.20.2 in /home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (4.25.4)
Requirement already satisfied: Pillow in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (10.2.0)
Requirement already satisfied: decorator in /home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (5.1.1)
Requirement already satisfied: astor in /home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (0.8.1)
Requirement already satisfied: opt-einsum==3.3.0 in /home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (3.3.0)
Requirement already satisfied: networkx in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (3.2.1)
Requirement already satisfied: typing-extensions in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (4.9.0)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (11.8.89)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (11.8.87)
Requirement already satisfied: nvidia-cudnn-cu11==8.7.0.84 in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (8.7.0.84)
Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (11.11.3.6)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (10.3.0.86)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (11.4.1.48)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (11.7.5.86)
Collecting nvidia-nccl-cu11==2.19.3 (from paddlepaddle-gpu==3.0.0b1)
  Downloading https://paddle-whl.bj.bcebos.com/stable/cu118/nvidia-nccl-cu11/nvidia_nccl_cu11-2.19.3-py3-none-manylinux1_x86_64.whl (135.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.3/135.3 MB 1.7 MB/s eta 0:00:00
Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (11.8.86)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in /home/founder/.local/lib/python3.10/site-packages (from paddlepaddle-gpu==3.0.0b1) (11.8.89)
Requirement already satisfied: anyio in /home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages (from httpx->paddlepaddle-gpu==3.0.0b1) (4.4.0)
Requirement already satisfied: certifi in /home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages (from httpx->paddlepaddle-gpu==3.0.0b1) (2024.7.4)
Requirement already satisfied: httpcore==1.* in /home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages (from httpx->paddlepaddle-gpu==3.0.0b1) (1.0.5)
Requirement already satisfied: idna in /home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages (from httpx->paddlepaddle-gpu==3.0.0b1) (3.7)
Requirement already satisfied: sniffio in /home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages (from httpx->paddlepaddle-gpu==3.0.0b1) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages (from httpcore==1.*->httpx->paddlepaddle-gpu==3.0.0b1) (0.14.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /home/founder/anaconda3/envs/MinerU/lib/python3.10/site-packages (from anyio->httpx->paddlepaddle-gpu==3.0.0b1) (1.2.2)
Installing collected packages: nvidia-nccl-cu11, paddlepaddle-gpu
  Attempting uninstall: nvidia-nccl-cu11
    Found existing installation: nvidia-nccl-cu11 2.20.5
    Uninstalling nvidia-nccl-cu11-2.20.5:
      Successfully uninstalled nvidia-nccl-cu11-2.20.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.3.1+cu118 requires nvidia-nccl-cu11==2.20.5; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nccl-cu11 2.19.3 which is incompatible.

### How to reproduce the bug | 如何复现

python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
按教程来一遍，torch在教程里装的是cu121的版本，和cu118的paddle可以共存

**Comment by 2257396011** [comment]
> 按教程来一遍，torch在教程里装的是cu121的版本，和cu118的paddle可以共存

好的

**Comment by 2257396011** [comment]
> 另外，火炬在教程里安装cu121的版本，和cu118的桨可以共存

请问ocr启用gpu加速后能比原来快大概多少呢？

**Comment by myhloli** [comment]
> > 另外，火炬在教程里安装cu121的版本，和cu118的桨可以共存
> 
> 
> 
> 请问ocr启用gpu加速后能比原来快大概多少呢？

一般会快10倍以上

**Comment by 2257396011** [comment]
> > > 另外，火炬在教程里安装cu121的版本，和cu118的桨可以共存
> > 
> > 
> > 请问ocr启用gpu加速后能比原来快大概多少呢？
> 
> 一般会快10倍以上

好的，谢谢
