### ISSUE TITLE
希望可以添加一个选项，只产生markdown文件

### ISSUE THREAD

**Issue by ywh-my** [opendatalab/MinerU#451]

**Comment by myhloli** [comment]
你可以参考这个demo的代码，调用本项目的接口并只生成md文件：

https://github.com/opendatalab/MinerU/blob/master/demo/demo.py

**Comment by ywh-my** [comment]
感谢您的迅速回复，但是我之前研究demo.py的时候发现模型的初始化 似乎很难从api里面分离出来。 因此单纯修改那个可能没用。现在我倾向于修改 tools/common.py ，将那些设置为True的改成false试试（例如产生.json和orgin.pdf，设为false）

**Comment by ywh-my** [comment]
之所以想“模型的初始化  和 数据的提取分离”是希望能进行快速地批量提取。 不需要每次有新的pdf都加载模型。

**Comment by myhloli** [comment]
模型初始化的地方是做了单例的，不论是修改demo.py还是修改tools/common.py,他们在加载模型的地方是没有区别的，都是只会在处理第一篇文档的时候开始初始化。

**Comment by ywh-my** [comment]
感谢，已经解决。

**Comment by HaoRenkk123** [comment]
哈喽，请问最后你怎么做的批量处理呢

**Comment by dltraveler** [comment]
@ywh-my 
你好，想请教下怎么解决的，tools/common.py中设置False好像不行，还是有其他文件产生，如果只产生md文件，速度会快很多吗？

**Comment by majestichou** [comment]
@ywh-my 请问您是怎么解决的，有公开博客细节吗？
