### ISSUE TITLE
标题消失问题

### ISSUE THREAD

**Issue by cskkx1** [opendatalab/MinerU#452]
### Description of the bug | 错误描述

解析完之后的标题为空，只有序号
<img width="219" alt="1724033963512" src="https://github.com/user-attachments/assets/24f87468-a7e7-400d-a481-99a551bc72ea">

<img width="215" alt="1724034237623" src="https://github.com/user-attachments/assets/df92cfc4-d26f-4e3b-89eb-fc4b91f7a264">

[轮胎设计_制造技术和法规进展及民族轮胎企业技术创新战略_危银涛.pdf](https://github.com/user-attachments/files/16654753/_._.pdf)

[我国子午线轮胎技术概况_王锋.pdf](https://github.com/user-attachments/files/16654748/_.pdf)

### How to reproduce the bug | 如何复现

magic-pdf -p test.pdf

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
span在样本pdf中的分布和排版比较怪异，部分文本的span框超出了对应的layout边界，导致无法fill进result.
对于这种pdf，可以在命令行中添加`-m ocr`强制开启ocr模式，对应的标题文本就不会缺失。

**Comment by cskkx1** [comment]
<img width="215" alt="1724038099942" src="https://github.com/user-attachments/assets/d7bb2817-4775-45f6-a869-d28830430619">
<img width="220" alt="1724038282437" src="https://github.com/user-attachments/assets/03e00c64-d55e-4c00-9618-e997b20b7f22">
谢谢大佬，标题文本有了
