### ISSUE TITLE
关于model.json文件

### ISSUE THREAD

**Issue by 2257396011** [opendatalab/MinerU#454]
请问model.json中的poly坐标和bbox坐标两者之间有什么区别么，感觉bbox像是那种相对坐标，如果想要获取绝对坐标的话是得需要poly和bbox一起计算还是怎么样

**Comment by myhloli** [comment]
参考文档：https://github.com/opendatalab/MinerU/blob/master/docs/output_file_zh_cn.md#modeljson

**Comment by bygzyz** [comment]
还是没太懂这两者的区别，bbox 坐标代表的是框的左上角和右下角的位置吗

```
{
                "category_id": 1,
                "poly": [
                    343.77142333984375,
                    969.0945434570312,
                    2839.352783203125,
                    969.0945434570312,
                    2839.352783203125,
                    1523.2757568359375,
                    343.77142333984375,
                    1523.2757568359375
                ],
                "score": 0.999995231628418,
                "bbox": [
                    123,
                    348,
                    1022,
                    548
                ]
            }
```
            
     没太懂 bbox 中内容的含义以及它是如何表示坐标的

**Comment by myhloli** [comment]
> 还是没太懂这两者的区别，bbox 坐标代表的是框的左上角和右下角的位置吗
> 
> ```
> {
>                 "category_id": 1,
>                 "poly": [
>                     343.77142333984375,
>                     969.0945434570312,
>                     2839.352783203125,
>                     969.0945434570312,
>                     2839.352783203125,
>                     1523.2757568359375,
>                     343.77142333984375,
>                     1523.2757568359375
>                 ],
>                 "score": 0.999995231628418,
>                 "bbox": [
>                     123,
>                     348,
>                     1022,
>                     548
>                 ]
>             }
> ```
> 
> ```
>  没太懂 bbox 中内容的含义以及它是如何表示坐标的
> ```

新版本中不会再出现poly和bbox同时出现的情况，poly是模型分析的四点坐标，左上-右上-右下-左下，分辨率一般是200dpi
bbox是pipeline后处理统一使用的两点坐标，左上，右下，分辨率一般是72dpi
