### ISSUE TITLE
PDF文字识别错误

### ISSUE THREAD

**Issue by josh1707** [opendatalab/MinerU#455]
### Description of the bug | 错误描述

PDF是图片型的PDF。是否自动调用OCR识别。结果准确度不高：

例如简历中
2015-09-2019.06 东莞理工学院 人力资源管理
输出的md结果为：
019.06车京里工之院原管里不料

### How to reproduce the bug | 如何复现

执行的命令：
magic-pdf pdf-command --pdf /data/resume/aa.pdf --inside_model true

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
pdf样本上传一下

**Comment by josh1707** [comment]
> pdf样本上传一下

PDF涉及隐私，不方便上传。是否有其他方式进行反馈

**Comment by myhloli** [comment]
> > pdf样本上传一下
> 
> PDF涉及隐私，不方便上传。是否有其他方式进行反馈

从readme置顶链接进微信群加我好友，私发
