### ISSUE TITLE
使用ocr模式运行一段时间后卡住

### ISSUE THREAD

**Issue by zuanzuanshao** [opendatalab/MinerU#457]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/fe2adaec-b9e9-4dac-b340-8a4712f6c9ce)
图片上面是具体的运行信息，请问是因为内存不够才卡住吗？

### How to reproduce the bug | 如何复现

magic-pdf -p 奥迪Q5混合动力技术培训.pdf -m ocr

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
截图能看到显存没满，内存32g的满了？

**Comment by zuanzuanshao** [comment]
@myhloli 这个是运行时的数据，我是在wsl里面的Ubuntu跑的。
![image](https://github.com/user-attachments/assets/c575f86f-9c10-4828-a61f-8b5ead215837)

**Comment by myhloli** [comment]
wsl的内存策略和物理机不同？

**Comment by zuanzuanshao** [comment]
刚查了下，没有物理机直接，多了一层。

**Comment by myhloli** [comment]
要不试下直接在win上跑呢，程序对windows兼容其实还不错的。

**Comment by drunkpig** [comment]
@zuanzuanshao 不建议wsl参与大规模提取，wsl无论做任何事情卡死是常态。

**Comment by zuanzuanshao** [comment]
@myhloli @drunkpig 好的，我试试直接Windows看看。

**Comment by ZXH-hu** [comment]
> 要不试下直接在win上跑呢，程序对windows兼容其实还不错的。
我就是在window下使用conda构建服务，模型下载到本地，调用api解析文件时就一直卡住，没有日志显示，按CTRL+C后又显示进程了，这种情况经常卡住，使用gpu模式加速也是一样。该怎么优化？还是使用docker来部署会好些？
