### ISSUE TITLE
怎么指定模型呢，那个demo 写的奇奇怪怪

### ISSUE THREAD

**Issue by huangguifeng** [opendatalab/MinerU#461]
### Description of the bug | 错误描述

运行demo 

### How to reproduce the bug | 如何复现

运行demo

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cpu

**Comment by drunkpig** [comment]
config model path in `~/magic-pdf.json`
