### ISSUE TITLE
本地部署完成后，运行命令，出现：非法指令  的提示

### ISSUE THREAD

**Issue by wxzheng88** [opendatalab/MinerU#464]
### Description of the bug | 错误描述

![Screenshot 2024-08-20 151520](https://github.com/user-attachments/assets/200e10a3-aa5c-4a26-9684-11a5f9fadde2)
本地部署完成后，运行命令，出现：非法指令  的提示。不知道是哪里出了问题

### How to reproduce the bug | 如何复现

本地部署

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
没有更多详细报错信息了吗？

**Comment by wxzheng88** [comment]
没了，就这么一句报错，不知道是哪里有问题

**Comment by myhloli** [comment]
> 没了，就这么一句报错，不知道是哪里有问题

那就不好排查了，有没有试过用我们推荐的环境呢？ubuntu22.04+python3.10

**Comment by wxzheng88** [comment]
我是ubuntu24.04+python3.10

**Comment by myhloli** [comment]
> 我是ubuntu24.04+python3.10

我们目前的兼容性测试仅在ubuntu22上完成，
目前不清楚ubuntu24和22有哪些差异，如果ubuntu24跑不起来可以等下我们的官方docker

**Comment by wxzheng88** [comment]
请问是否有交流群呢

**Comment by myhloli** [comment]
> 请问是否有交流群呢

readme置顶有微信群二维码链接
