### ISSUE TITLE
离线环境下部署，报错：Failed to resolve 'paddleocr.bj.bcebos.com'

### ISSUE THREAD

**Issue by zhagnzhenfei** [opendatalab/MinerU#466]
看日志是要从这个地址下载一个tar包，但是我是离线环境，我已经下载好了tar包放在对应的位置，怎么让它不在发送这个请求

**Comment by myhloli** [comment]
参考这个issue，应该是需要解压并放在指定位置。
https://github.com/opendatalab/MinerU/issues/359
