### ISSUE TITLE
Zh: 建立一个微信交流群，可以方便大家交流  En: A Discord community group 

### ISSUE THREAD

**Issue by chmod777john** [opendatalab/MinerU#476]
En: A Discord community group for people to discuss issues and PRs.

https://discord.gg/3rZfvz3xqH

中： 可以建立一个微信交流群，方便大家讨论 issue Pr 相关的问题。非引流，如果官方要求的话，我可以转让管理员权限
若链接失效，可联系微信 dreamingforhope 

![image](https://github.com/user-attachments/assets/6351a1dd-60c6-4559-86c2-48184e3e2c15)

**Comment by lygiants** [comment]
您好, 官方readme文档顶部有微信交流群~我已经进群了

**Comment by drunkpig** [comment]
Official WeChat group QR code: https://cdn.vansin.top/internlm/mineru.jpg

Discord link: https://discord.gg/Tdedn9GTXq
