### ISSUE TITLE
能不能转化doc成md啊？还是只能pdf转md

### ISSUE THREAD

**Issue by Alan-zhong** [opendatalab/MinerU#491]
能不能转化doc成md啊？还是只能pdf转md
能不能转化doc成md啊？还是只能pdf转md
能不能转化doc成md啊？还是只能pdf转md

**Comment by drunkpig** [comment]
@Alan-zhong  使用libreoffice命令行，转换office格式到pdf,,然后处理 

```shell
soffice --headless --convert-to pdf path/to/your/file.docx
```

**Comment by laulguo** [comment]
DOC转PDF还不简单吗。。

**Comment by minervazz** [comment]
doc转md直接解压处理xml就行了，不用这么复杂

**Comment by Barmaid1076** [comment]
> doc转md直接解压处理xml就行了，不用这么复杂

应该怎么做呢？

**Comment by minervazz** [comment]
这个你去csdn搜一下就行，python-docx可以直接解压出xml文件，你可以自己再写一些代码转化为json
