### ISSUE TITLE
pdf识别不出图片

### ISSUE THREAD

**Issue by Ceceliachenen** [opendatalab/MinerU#497]
### Description of the bug | 错误描述

识别这页pdf的时候，无法识别出图片。

### How to reproduce the bug | 如何复现

用auto模式解析这个pdf
[机器学习怎么获取到eascmd客户连接配置的ak.pdf](https://github.com/user-attachments/files/16774885/eascmd.ak.pdf)

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
网页截图与文本样式过于接近了，图像的边界感不强，确实难以识别
