### ISSUE TITLE
Library not loaded: @loader_path/libjxl.0.6.1.dylib

### ISSUE THREAD

**Issue by audio-github-2020** [opendatalab/MinerU#504]
### Description of the bug | 错误描述

ImportError: dlopen(/opt/anaconda3/envs/MinerU/lib/python3.10/site-packages/cv2/cv2.abi3.so, 2): Library not loaded: @loader_path/libjxl.0.6.1.dylib
  Referenced from: /opt/anaconda3/envs/MinerU/lib/python3.10/site-packages/cv2/.dylibs/libavcodec.58.134.100.dylib
  Reason: no suitable image found.  Did find:
	/opt/anaconda3/envs/MinerU/lib/python3.10/site-packages/cv2/.dylibs/libjxl.0.6.1.dylib: file too short
	/opt/anaconda3/envs/MinerU/lib/python3.10/site-packages/cv2/.dylibs/libjxl.0.6.1.dylib: file too short
2024-08-29 11:33:11.312 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:28 - Required dependency not installed, please install by
"pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/&#34;

环境：macOs 10.15.7

重新安装也还是不行，根据目录找到对应的文件只有0字节
![Snipaste_2024-08-29_13-43-53](https://github.com/user-attachments/assets/466df9c6-6f5e-4720-8178-dd6bdbab95b0)

### How to reproduce the bug | 如何复现

根据wiki要求完成安装，执行命令进行pdf解析时报错

magic-pdf -p {some_pdf} -o {some_output_dir} -m auto

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
```bash
pip uninstall opencv-python
pip install opencv-python
```
重新安装opencv库试试

**Comment by audio-github-2020** [comment]
已解决，直接从国外的源下载就没问题。从国内源下载、重新安装依赖包等方式都没解决。
