### ISSUE TITLE
使用small_ocr.pdf实验，解析结果为空

### ISSUE THREAD

**Issue by huhk-sysu** [opendatalab/MinerU#509]
### Description of the bug | 错误描述

使用 [/docs/README_Ubuntu_CUDA_Acceleration_zh_CN.md](/docs/README_Ubuntu_CUDA_Acceleration_zh_CN.md) 中提到的文件实验解析，推理正常进行，但输出md文件为空文件，layout.pdf和spans.pdf和原pdf一致。

### How to reproduce the bug | 如何复现

按照上述文档中4-8步执行。已正确在`magic-pdf.json`中配置模型位置。由于是离线环境，下载并解压了所需paddleOCR对应模型文件到指定位置。
此后执行命令
```
magic-pdf -p small_ocr.pdf -o output/test
```
输出如下：
![image](https://github.com/user-attachments/assets/45d21d00-cc85-4432-8ff8-fad69cae08bf)
![image](https://github.com/user-attachments/assets/6dec03ff-3bce-4a1f-96b6-21598ac46b62)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
看了下日志，应该是你layout检测过程没有正确识别页面上的各种block，可以看下输出目录的model.json,里面是不是空的

**Comment by huhk-sysu** [comment]
感谢回复。model.json里不全是空的，有layout_dets、page_info等字段。个别layout_dets是空的，其它有一些符号。
这个原因已查明，是比较罕见的情况，传输模型`Layout/model_final.pth`至服务器时内容不知为何修改了，但大小没变化也没报错，查md5查出来了，重新上传后正常运行了。
