### ISSUE TITLE
latex识别错误

### ISSUE THREAD

**Issue by Barmaid1076** [opendatalab/MinerU#515]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/505f748f-f048-4e0d-bd28-7a2d2af2b8ad)

经常会出现这样子的latex识别错误, 请问是bug吗，有什么办法修复吗

### How to reproduce the bug | 如何复现

latex识别错误

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by drunkpig** [comment]
pls provide this pdf document for debug

**Comment by Barmaid1076** [comment]
The error cannot be reproduced when parsing that specific page of that pdf file. The modal seems to have a better performance when processing small pdf files individually instead of one file that combines them together
