### ISSUE TITLE
magic_pdf_parse_main.py的最佳配置

### ISSUE THREAD

**Issue by HaoRenkk123** [opendatalab/MinerU#516]
谢谢分享这么棒的pdf2md方案，我想用python脚本入口来进行pdf的提取，而不是用命令行方式，并且本地下载好了models，请问最佳的配置是什么呢，gpu的设置以及是否可以设置多线程，ocr加速，请问在哪里设置呢

**Comment by drunkpig** [comment]
请参考readme文档上，使用GPU加速一节。[win10](https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_en_US.md), [ubuntu](https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_en_US.md)

**Comment by fanshuaiyao** [comment]
> 请参考readme文档上，使用GPU加速一节。[Win10](https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_en_US.md)、[Ubuntu](https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_en_US.md)

这一节也是用得命令行啊

**Comment by myhloli** [comment]
> > 请参考readme文档上，使用GPU加速一节。[Win10](https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_en_US.md)、[Ubuntu](https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_en_US.md)
> 
> 这一节也是用得命令行啊

https://github.com/opendatalab/MinerU/blob/dev/projects/gradio_app/README_zh-CN.md

参考这个文档，可以运行gradio前端

**Comment by bwnjnOEI** [comment]
请问下[parse_method](https://github.com/opendatalab/MinerU/blob/85ed25875e0e59e214fa496b2c8427c9795cac07/demo/magic_pdf_parse_main.py#L61) 三种参数有具体描述吗？还有不同table模型的描述，我没在repo的文档中找到详细描述。

**Comment by myhloli** [comment]
> 请问下[parse_method](https://github.com/opendatalab/MinerU/blob/85ed25875e0e59e214fa496b2c8427c9795cac07/demo/magic_pdf_parse_main.py#L61) 三种参数有具体描述吗？还有不同table模型的描述，我没在repo的文档中找到详细描述。

auto适合90%以上的文档解析，再少部分使用auto解析效果不好的文档可以使用ocr模式提高解析效果
