### ISSUE TITLE
求帮助：识别时输出kill，然后识别中断

### ISSUE THREAD

**Issue by meng0423** [opendatalab/MinerU#525]
### Description of the bug | 错误描述

识别时输出kill，然后识别中断
![image](https://github.com/user-attachments/assets/4fe0eefb-b081-4520-b72f-112a484fb01f)

### How to reproduce the bug | 如何复现

正常识别

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
一般是内存不足

**Comment by meng0423** [comment]
> 一般是内存不足

谢谢您，切割文档后解决了！
