### ISSUE TITLE
 ModuleNotFoundError: No module named 'pycocotools'

### ISSUE THREAD

**Issue by yangtutuaka** [opendatalab/MinerU#530]
### Description of the bug | 错误描述

(MinerU) C:\Users\ChenRui.Yang>magic-pdf pdf-command --pdf ""C:\Users\ChenRui.Yang\Downloads\基于深度学习的盾构掘进噪声...模态面波数据处理与成像方法_王清扬.pdf"" --inside_model true --model_mode full
2024-09-02 21:34:47.452 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:312 - not found json C:\Users\ChenRui.Yang\Downloads\基于深度学习的盾构掘进噪声...模态面波数据处理与成像方法_王清扬.json existed
2024-09-02 21:34:47.453 | WARNING  | magic_pdf.libs.config_reader:get_local_dir:64 - 'temp-output-dir' not found in magic-pdf.json, use '/tmp' as default
2024-09-02 21:34:53.570 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 20365, cid_chars_radio: 0.0
2024-09-02 21:34:53.576 | WARNING  | magic_pdf.filter.pdf_classify_by_type:classify:334 - pdf is not classified by area and text_len, by_image_area: False, by_text: True, by_avg_words: True, by_img_num: True, by_text_layout: True, by_img_narrow_strips: True, by_invalid_chars: True
2024-09-02 21:34:59.508 | ERROR    | magic_pdf.cli.magicpdf:parse_doc:338 - No module named 'pycocotools'
Traceback (most recent call last):

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\ChenRui.Yang\.conda\...
           │         └ <code object <module> at 0x0000018CAF42BEC0, file "C:\Users\ChenRui.Yang\.conda\envs\MinerU\Scripts\magic-pdf.exe\__main__.py...
           └ <function _run_code at 0x0000018CAF411D80>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\ChenRui.Yang\.conda\...
         └ <code object <module> at 0x0000018CAF42BEC0, file "C:\Users\ChenRui.Yang\.conda\envs\MinerU\Scripts\magic-pdf.exe\__main__.py...

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\Scripts\magic-pdf.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
    │   │    └ <Group cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x0000018CAF87B1C0>
           └ <Group cli>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x0000018CAF478F10>
         │    └ <function MultiCommand.invoke at 0x0000018CAF8881F0>
         └ <Group cli>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x0000018CFF19FBE0>
           │               │       │       └ <function Command.invoke at 0x0000018CAF87BC70>
           │               │       └ <Command pdf-command>
           │               └ <click.core.Context object at 0x0000018CFF19FBE0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x0000018CAF187520>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'pdf': 'C:\\Users\\ChenRui.Yang\\Downloads\\基于深度学习的盾构掘进噪声... 模态面波数据处理与成像方法_王清扬.pdf', 'inside_model': True, 'model_mode': 'ful...
           │   │      │    │           └ <click.core.Context object at 0x0000018CFF19FBE0>
           │   │      │    └ <function pdf_command at 0x0000018CFF1CA170>
           │   │      └ <Command pdf-command>
           │   └ <function Context.invoke at 0x0000018CAF87A9E0>
           └ <click.core.Context object at 0x0000018CFF19FBE0>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'pdf': 'C:\\Users\\ChenRui.Yang\\Downloads\\基于深度学习的盾构掘进噪声...模态面波数据 处理与成像方法_王清扬.pdf', 'inside_model': True, 'model_mode': 'ful...
                       └ ()

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\cli\magicpdf.py", line 352, in pdf_command
    parse_doc(pdf)
    │         └ 'C:\\Users\\ChenRui.Yang\\Downloads\\基于深度学习的盾构掘进噪声...模态面波数据处理与成像方法_王清扬.pdf'
    └ <function pdf_command.<locals>.parse_doc at 0x0000018CFF1C9EA0>

> File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\cli\magicpdf.py", line 330, in parse_doc
    do_parse(
    └ <function do_parse at 0x0000018CFF1C9AB0>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\cli\magicpdf.py", line 111, in do_parse
    pipe.pipe_analyze()
    │    └ <function UNIPipe.pipe_analyze at 0x0000018CFF1C8940>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x0000018CFF19FD30>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\pipe\UNIPipe.py", line 31, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True)
    │    │            │           │    └ b'%PDF-1.6\r%\xe5\xbf\x8f\xe5\xab\x8c\r\n4 0 obj\n<<\n/Type /XObject\n/Subtype /Image\n/Name /I0\n/Width 2360\n/Height 3428\n...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x0000018CFF19FD30>
    │    │            └ <function doc_analyze at 0x0000018CB1FD56C0>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x0000018CFF19FD30>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line
 103, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
                   │             │         │    └ False
                   │             │         └ True
                   │             └ <function ModelSingleton.get_model at 0x0000018CB1FD5630>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x0000018C8A5C8220>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line
 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
    │    │       │      │                     │             └ False
    │    │       │      │                     └ True
    │    │       │      └ <function custom_model_init at 0x0000018CB1FD5510>
    │    │       └ (True, False)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x0000018C8A5C8220>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line
 83, in custom_model_init
    from magic_pdf.model.pdf_extract_kit import CustomPEKModel

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 30, in <module>
    from magic_pdf.model.pek_sub_modules.layoutlmv3.model_init import Layoutlmv3_Predictor

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\pek_sub_modules\layoutlmv3\model_init.py", line 1, in <module>
    from .visualizer import Visualizer

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\pek_sub_modules\layoutlmv3\visualizer.py", line 11, in <module>
    import pycocotools.mask as mask_util

ModuleNotFoundError: No module named 'pycocotools'

### How to reproduce the bug | 如何复现

  这是我的版本![图片](https://github.com/user-attachments/assets/5da00f8b-27fb-4486-9851-5e7e0f4fca17)
这是环境列表(MinerU) C:\Users\ChenRui.Yang>magic-pdf -v
magic-pdf, version 0.6.2b1
                               conda list
# packages in environment at C:\Users\ChenRui.Yang\.conda\envs\MinerU:
#
# Name                    Version                   Build  Channel
aiohappyeyeballs          2.4.0                    pypi_0    pypi
aiohttp                   3.10.5                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
albucore                  0.0.14                   pypi_0    pypi
albumentations            1.4.14                   pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.4.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrdict                  2.0.1                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
babel                     2.16.0                   pypi_0    pypi
bce-python-sdk            0.9.19                   pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
blinker                   1.8.2                    pypi_0    pypi
boto3                     1.35.10                  pypi_0    pypi
botocore                  1.35.10                  pypi_0    pypi
braceexpand               0.1.7                    pypi_0    pypi
brotli                    1.1.0                    pypi_0    pypi
bzip2                     1.0.8                h2466b09_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2024.8.30            h56e8100_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cachetools                5.5.0                    pypi_0    pypi
certifi                   2024.8.30                pypi_0    pypi
cffi                      1.17.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
colorlog                  6.8.2                    pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
cryptography              43.0.0                   pypi_0    pypi
cssselect                 1.2.0                    pypi_0    pypi
cssutils                  2.11.1                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cython                    3.0.11                   pypi_0    pypi
datasets                  2.21.0                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
eva-decord                0.6.1                    pypi_0    pypi
eval-type-backport        0.2.0                    pypi_0    pypi
evaluate                  0.4.2                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
fairscale                 0.4.13                   pypi_0    pypi
fast-langdetect           0.2.0                    pypi_0    pypi
fasttext-wheel            0.9.2                    pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
fire                      0.6.0                    pypi_0    pypi
flask                     3.0.3                    pypi_0    pypi
flask-babel               4.0.0                    pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
ftfy                      6.2.3                    pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.5                    pypi_0    pypi
httpx                     0.27.2                   pypi_0    pypi
huggingface-hub           0.24.6                   pypi_0    pypi
idna                      3.8                      pypi_0    pypi
imageio                   2.35.1                   pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
intel-openmp              2021.4.0                 pypi_0    pypi
iopath                    0.1.10                   pypi_0    pypi
itsdangerous              2.2.0                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
langdetect                1.0.9                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
libffi                    3.4.2                h8ffe710_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libsqlite                 3.46.0               h2466b09_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.3.1                h2466b09_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lmdb                      1.5.1                    pypi_0    pypi
loguru                    0.7.2                    pypi_0    pypi
lxml                      5.3.0                    pypi_0    pypi
magic-pdf                 0.6.2b1                  pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
mkl                       2021.4.0                 pypi_0    pypi
modelscope                1.17.1                   pypi_0    pypi
more-itertools            10.4.0                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
networkx                  3.3                      pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
opencv-contrib-python     4.6.0.66                 pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openpyxl                  3.1.5                    pypi_0    pypi
openssl                   3.3.1                h2466b09_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
paddleocr                 2.7.3                    pypi_0    pypi
paddlepaddle              2.6.1                    pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pdf2docx                  0.5.8                    pypi_0    pypi
pdfminer-six              20231228                 pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2               pyh8b19718_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
portalocker               2.10.1                   pypi_0    pypi
premailer                 3.10.0                   pypi_0    pypi
protobuf                  3.20.2                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   17.0.0                   pypi_0    pypi
pybind11                  2.13.5                   pypi_0    pypi
pyclipper                 1.3.0.post5              pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pydantic                  2.8.2                    pypi_0    pypi
pydantic-core             2.20.1                   pypi_0    pypi
pymupdf                   1.24.9                   pypi_0    pypi
pymupdfb                  1.24.9                   pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
python                    3.10.14         h4de0772_0_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python-docx               1.1.2                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
rapidfuzz                 3.9.6                    pypi_0    pypi
rarfile                   4.2                      pypi_0    pypi
regex                     2024.7.24                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
robust-downloader         0.0.2                    pypi_0    pypi
s3transfer                0.10.2                   pypi_0    pypi
safetensors               0.4.4                    pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scikit-learn              1.5.1                    pypi_0    pypi
scipy                     1.14.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
setuptools                72.2.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
shapely                   2.0.6                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
sympy                     1.13.2                   pypi_0    pypi
tbb                       2021.13.1                pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.8.30                pypi_0    pypi
timm                      0.9.16                   pypi_0    pypi
tk                        8.6.13               h5226925_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tokenizers                0.19.1                   pypi_0    pypi
torch                     2.3.1                    pypi_0    pypi
torchtext                 0.18.0                   pypi_0    pypi
torchvision               0.18.1                   pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
transformers              4.40.0                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ultralytics               8.2.86                   pypi_0    pypi
ultralytics-thop          2.0.6                    pypi_0    pypi
unimernet                 0.1.6                    pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
vc                        14.3                h8a93ad2_20    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vc14_runtime              14.40.33810         hcc2c482_20    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
visualdl                  2.5.3                    pypi_0    pypi
vs2015_runtime            14.40.33810         h3bf8584_20    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wand                      0.6.13                   pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webdataset                0.2.100                  pypi_0    pypi
werkzeug                  3.0.4                    pypi_0    pypi
wheel                     0.44.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
win32-setctime            1.1.0                    pypi_0    pypi
wordninja                 2.0.0                    pypi_0    pypi
xxhash                    3.5.0                    pypi_0    pypi
xz                        5.2.6                h8d14728_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yarl                      1.9.7                    pypi_0    pypi

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by yangtutuaka** [comment]
大神们棒棒忙，这是怎么了，谢谢大家

**Comment by myhloli** [comment]
这是d2的依赖，这个在0.6.x上需要单独安装，你按照我们的readme安装一下0.7.0b1版本，就可以处理好环境

**Comment by yangtutuaka** [comment]
> 这是d2的依赖，这个在0.6.x上需要单独安装，你按照我们的readme安装一下0.7.0b1版本，就可以处理好环境
大佬 按照要求安装了 还是报错
(MinerU) C:\Users\ChenRui.Yang>magic-pdf -p C:\Users\ChenRui.Yang\Desktop\=技术报告\二、项目进展及任务完成情况.pdf -o C:\Users\ChenRui.Yang\Desktop\=技术报告\ -m auto
2024-09-03 10:52:47.149 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 5600, cid_chars_radio: 0.0
2024-09-03 10:52:59.142 | ERROR    | magic_pdf.tools.cli:parse_doc:69 - No module named 'pycocotools'
Traceback (most recent call last):

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\ChenRui.Yang\.conda\...
           │         └ <code object <module> at 0x000001A2C269BEC0, file "C:\Users\ChenRui.Yang\.conda\envs\MinerU\Scripts\magic-pdf.exe\__main__.py...
           └ <function _run_code at 0x000001A2C267DD80>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\ChenRui.Yang\.conda\...
         └ <code object <module> at 0x000001A2C269BEC0, file "C:\Users\ChenRui.Yang\.conda\envs\MinerU\Scripts\magic-pdf.exe\__main__.py...

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\Scripts\magic-pdf.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
    │   │    └ <Command cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x000001A2C4267D00>
           └ <Command cli>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x000001A2C26E89A0>
         │    └ <function Command.invoke at 0x000001A2C427C820>
         └ <Command cli>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'C:\\Users\\ChenRui.Yang\\Desktop\\=技术报告\\二、项目进展及任务完成情况.pdf', 'output_dir': 'C:\\Users\\ChenRui.Yang\\Desktop\\=技术报告...
           │   │      │    │           └ <click.core.Context object at 0x000001A2C26E89A0>
           │   │      │    └ <function cli at 0x000001A2994A9630>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x000001A2C4267520>
           └ <click.core.Context object at 0x000001A2C26E89A0>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'path': 'C:\\Users\\ChenRui.Yang\\Desktop\\=技术报告\\二、项目进展及任务完成情况.pdf', 'output_dir': 'C:\\Users\\ChenRui.Yang\\Desktop\\=技术报告...
                       └ ()

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\tools\cli.py", line 75, in cli
    parse_doc(path)
    │         └ 'C:\\Users\\ChenRui.Yang\\Desktop\\=技术报告\\二、项目进展及任务完成情况.pdf'
    └ <function cli.<locals>.parse_doc at 0x000001A2C23F7520>

> File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\tools\cli.py", line 60, in parse_doc
    do_parse(
    └ <function do_parse at 0x000001A2C4ACAB00>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\tools\common.py", line 65, in do_parse
    pipe.pipe_analyze()
    │    └ <function UNIPipe.pipe_analyze at 0x000001A2994A8940>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001A299483610>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\pipe\UNIPipe.py", line 29, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=False)
    │    │            │           │    └ b'%PDF-1.7\n%\xc2\xb3\xc7\xd8\r\n3 0 obj\r<</Author (WPS_1177005309) /Comments () /Company () /CreationDate (D:20240811100840...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001A299483610>
    │    │            └ <function doc_analyze at 0x000001A2C523FF40>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000001A299483610>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 109, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
                   │             │         │    └ False
                   │             │         └ False
                   │             └ <function ModelSingleton.get_model at 0x000001A2C523FEB0>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x000001A2994F2F80>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
    │    │       │      │                     │             └ False
    │    │       │      │                     └ False
    │    │       │      └ <function custom_model_init at 0x000001A2C523FD90>
    │    │       └ (False, False)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x000001A2994F2F80>

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 83, in custom_model_init
    from magic_pdf.model.pdf_extract_kit import CustomPEKModel

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 33, in <module>
    from magic_pdf.model.pek_sub_modules.layoutlmv3.model_init import Layoutlmv3_Predictor

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\pek_sub_modules\layoutlmv3\model_init.py", line 1, in <module>
    from .visualizer import Visualizer

  File "C:\Users\ChenRui.Yang\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\pek_sub_modules\layoutlmv3\visualizer.py", line 11, in <module>
    import pycocotools.mask as mask_util

ModuleNotFoundError: No module named 'pycocotools'

(MinerU) C:\Users\ChenRui.Yang>magic-pdf -v
magic-pdf, version 0.7.0b1

(MinerU) C:\Users\ChenRui.Yang>

**Comment by myhloli** [comment]
试试这个
pip install -U magic-pdf[full]==0.7.1 --extra-index-url https://wheels.myhloli.com -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by yangtutuaka** [comment]
> 试试这个 pip install -U magic-pdf[full]==0.7.1 --extra-index-url https://wheels.myhloli.com -i https://pypi.tuna.tsinghua.edu.cn/simple

重新启动，并且使用这个，成功跑通了，谢谢大佬，
