### ISSUE TITLE
pdf中的表格识别，怎么将表格解析为纯文本而不是图片的形式存放在pdf解析生成的md文件中？

### ISSUE THREAD

**Issue by SuperDZ** [opendatalab/MinerU#531]
### Description of the bug | 错误描述

使用magic_pdf的文本识别或者ocr识别解析pdf中的表格，最终生成的md文件中 表格是以图片的形式呈现，需求是将表格中的数据解析为文本并存放在pdf解析生成的md文件中表格的对应位置，有无好的解决办法？

### How to reproduce the bug | 如何复现

使用magic_pdf的文本识别或者ocr识别解析pdf中的表格，最终生成的md文件中 表格是以图片的形式呈现，需求是将表格中的数据解析为文本并存放在pdf解析生成的md文件中表格的对应位置，有无好的解决办法？

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by MeVeryHandsome** [comment]
![image](https://github.com/user-attachments/assets/ebdffc5a-7d1b-4453-bac0-9f115b74df6b)
把magic-pdf.json的is_table_recog_enable改成true试试

**Comment by SuperDZ** [comment]
根据官方给的说明配置并将is_table_recog_enable字段改为true，测试解析带有表格的pdf文档报错了
![image](https://github.com/user-attachments/assets/17b978a2-05d0-4d0f-bc41-2d394674a5c6)
报错信息如下，如何解决这个问题？

2024-09-03 18:27:31.178 | ERROR    | __main__:pdf_parse_main:194 - Expecting property name enclosed in double quotes: line 10 column 27 (char 304)
Traceback (most recent call last):

  File "/usr/local/bin/python3.11/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fb7ffa9cea0>
    └ <Thread(Thread-1 (process_request_thread), started daemon 140422673655552)>
  File "/usr/local/bin/python3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fb7ffa9cb80>
    └ <Thread(Thread-1 (process_request_thread), started daemon 140422673655552)>
  File "/usr/local/bin/python3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-1 (process_request_thread), started daemon 140422673655552)>
    │    │        │    └ (<socket.socket fd=4, family=2, type=1, proto=0, laddr=('192.168.1.153', 7861), raddr=('192.1.113.3', 10159)>, ('192.1.113.3'...
    │    │        └ <Thread(Thread-1 (process_request_thread), started daemon 140422673655552)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x7fb6b5259890>>
    └ <Thread(Thread-1 (process_request_thread), started daemon 140422673655552)>
  File "/usr/local/bin/python3.11/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('192.1.113.3', 10159)
    │    │              └ <socket.socket fd=4, family=2, type=1, proto=0, laddr=('192.168.1.153', 7861), raddr=('192.1.113.3', 10159)>
    │    └ <function BaseServer.finish_request at 0x7fb6b3d0a520>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7fb6b5259890>
  File "/usr/local/bin/python3.11/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x7fb6b5259890>
    │    │                   │        └ ('192.1.113.3', 10159)
    │    │                   └ <socket.socket fd=4, family=2, type=1, proto=0, laddr=('192.168.1.153', 7861), raddr=('192.1.113.3', 10159)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7fb6b5259890>
  File "/usr/local/bin/python3.11/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fb6b3d9fb00>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x7fb6b3a28f50>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/local/bin/python3.11/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x7fb6b3d20860>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x7fb6b3a28f50>
  File "/usr/local/bin/python3.11/lib/python3.11/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x7fb6b3a28f50>>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <Flask 'main'>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7fb6b5259890>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x7fb6b3a28f50>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x7fb6b3a3ca40>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/werkzeug/serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7fb6b3a3c9a0>
                       │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=4>, 'wsgi.errors': <_io.TextIOWrap...
                       └ <Flask 'main'>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7fb6b3a3c9a0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=4>, 'wsgi.errors': <_io.TextIOWrap...
           │    └ <function Flask.wsgi_app at 0x7fb6b3a12980>
           └ <Flask 'main'>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x7fb6b3a120c0>
               └ <Flask 'main'>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x7fb6b3a12020>
         └ <Flask 'main'>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'pdf_to_md'
           │    │           │    │              └ <Rule '/pdf_to_md' (OPTIONS, POST) -> pdf_to_md>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x7fb6b3d08680>, 'pdf_to_md': <function pdf_to_md at 0x7fb6b3a209a0>...
           │    │           └ <Flask 'main'>
           │    └ <function Flask.ensure_sync at 0x7fb6b3a122a0>
           └ <Flask 'main'>

  File "/app/MinerU/main.py", line 30, in pdf_to_md
    md_content = pdf_parse_main(pdf_path=data["pdf_path"], output_dir=data['output_dir'])
                 │                       │                            └ {'pdf_path': '/app/MinerU/tmp/magic-pdf/test_table_in_PDF/带合并单元格的表格pdf_test3.pdf', 'output_dir': '/app/MinerU/tmp/magic-pdf/t...
                 │                       └ {'pdf_path': '/app/MinerU/tmp/magic-pdf/test_table_in_PDF/带合并单元格的表格pdf_test3.pdf', 'output_dir': '/app/MinerU/tmp/magic-pdf/t...
                 └ <function pdf_parse_main at 0x7fb6b3a20ae0>

> File "/app/MinerU/main.py", line 174, in pdf_parse_main
    pipe.pipe_analyze()  # 解析
    │    └ <function UNIPipe.pipe_analyze at 0x7fb6b3cbbc40>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fb6b3a35cd0>

  File "/app/MinerU/magic_pdf/pipe/UNIPipe.py", line 29, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=False)
    │    │            │           │    └ b'%PDF-1.5\r\n%\xb5\xb5\xb5\xb5\r\n1 0 obj\r\n<</Type/Catalog/Pages 2 0 R/Lang(zh-CN) /StructTreeRoot 37 0 R/MarkInfo<</Marke...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fb6b3a35cd0>
    │    │            └ <function doc_analyze at 0x7fb75a656840>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fb6b3a35cd0>

  File "/app/MinerU/magic_pdf/model/doc_analyze_by_custom_model.py", line 109, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
                   │             │         │    └ False
                   │             │         └ False
                   │             └ <function ModelSingleton.get_model at 0x7fb75a6567a0>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7fb6b3971810>

  File "/app/MinerU/magic_pdf/model/doc_analyze_by_custom_model.py", line 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
    │    │       │      │                     │             └ False
    │    │       │      │                     └ False
    │    │       │      └ <function custom_model_init at 0x7fb75a656660>
    │    │       └ (False, False)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7fb6b3971810>

  File "/app/MinerU/magic_pdf/model/doc_analyze_by_custom_model.py", line 85, in custom_model_init
    local_models_dir = get_local_models_dir()
                       └ <function get_local_models_dir at 0x7fb75a6563e0>

  File "/app/MinerU/magic_pdf/libs/config_reader.py", line 61, in get_local_models_dir
    config = read_config()
             └ <function read_config at 0x7fb7ff1cd3a0>

  File "/app/MinerU/magic_pdf/libs/config_reader.py", line 26, in read_config
    config = json.load(f)
             │    │    └ <_io.TextIOWrapper name='/root/magic-pdf.json' mode='r' encoding='utf-8'>
             │    └ <function load at 0x7fb7ffc16c00>
             └ <module 'json' from '/usr/local/bin/python3.11/lib/python3.11/json/__init__.py'>

  File "/usr/local/bin/python3.11/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           │     │  └ <method 'read' of '_io.TextIOWrapper' objects>
           │     └ <_io.TextIOWrapper name='/root/magic-pdf.json' mode='r' encoding='utf-8'>
           └ <function loads at 0x7fb7ffc16ca0>
  File "/usr/local/bin/python3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ '{\n    "bucket_info":{\n        "bucket-name-1":["ak", "sk", "endpoint"],\n        "bucket-name-2":["ak", "sk", "endpoint"]\...
           │                └ <function JSONDecoder.decode at 0x7fb7ffc16660>
           └ <json.decoder.JSONDecoder object at 0x7fb7ffb93bd0>
  File "/usr/local/bin/python3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ '{\n    "bucket_info":{\n        "bucket-name-1":["ak", "sk", "endpoint"],\n        "bucket-name-2":["ak", "sk", "endpoint"]\...
               │    │          │      └ <built-in method match of re.Pattern object at 0x7fb7ffbab510>
               │    │          └ '{\n    "bucket_info":{\n        "bucket-name-1":["ak", "sk", "endpoint"],\n        "bucket-name-2":["ak", "sk", "endpoint"]\...
               │    └ <function JSONDecoder.raw_decode at 0x7fb7ffc16700>
               └ <json.decoder.JSONDecoder object at 0x7fb7ffb93bd0>
  File "/usr/local/bin/python3.11/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               │    │         │  └ 0
               │    │         └ '{\n    "bucket_info":{\n        "bucket-name-1":["ak", "sk", "endpoint"],\n        "bucket-name-2":["ak", "sk", "endpoint"]\...
               │    └ <_json.Scanner object at 0x7fb7ffbcdf60>
               └ <json.decoder.JSONDecoder object at 0x7fb7ffb93bd0>

json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 10 column 27 (char 304)

**Comment by Carkham** [comment]
@SuperDZ 
Hi，这个问题是因为json不支持注释导致的。你可以尝试去掉"//"后的内容，这对我来说是可行的。

**Comment by sapipoZZZ** [comment]
请教下，
已经将is_table_recog_enable=true，
我的pdf中的表格都是可选的文字，但是最终输出的很多汉字不正确。

目前0.8的版本中，是否是因为调用外部表格识别模型时，内部调用传的图片导致的吗？是否能直接原文解析，而不是OCR再绕一次？

**Comment by myhloli** [comment]
> 请教下， 已经将is_table_recog_enable=true， 我的pdf中的表格都是可选的文字，但是最终输出的很多汉字不正确。
> 
> 目前0.8的版本中，是否是因为调用外部表格识别模型时，内部调用传的图片导致的吗？是否能直接原文解析，而不是OCR再绕一次？

目前表格识别用的ppocr是v3的，精度会略低，后面会升级v4，文本准确率会高一些
