### ISSUE TITLE
'fairscale'模块不存在

### ISSUE THREAD

**Issue by yang123456he** [opendatalab/MinerU#535]
### Description of the bug | 错误描述

ModuleNotFoundError: No module named 'fairscale'
2024-09-03 15:47:29.277 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:28 - Required dependency not installed, please install by 
"pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/"
我已经下载了模块，干净的环境运行 magic-pdf -p .\PDF\input\test.pdf -o .\PDF\output\ -m auto
报错

### How to reproduce the bug | 如何复现

 magic-pdf -p .\PDF\input\test.pdf -o .\PDF\output\ -m auto
ModuleNotFoundError: No module named 'fairscale'
2024-09-03 15:47:29.277 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:28 - Required dependency not installed, please install by 
"pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/"

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
把fairscale卸载再重装一下

**Comment by yang123456he** [comment]
卸载重装还是会报错



---原始邮件---
发件人: "Xiaomeng ***@***.***&gt;
发送时间: 2024年9月3日(周二) 下午3:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [opendatalab/MinerU] 'fairscale'模块不存在 (Issue #535)




 
把fairscale卸载再重装一下

**Comment by zhangmain666** [comment]
用了虚拟环境没有，可以试试新起个虚拟环境再装一遍依赖

**Comment by yang123456he** [comment]
按照这三步搞好了，我也重新配环境了，还是有报错，3.10python



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月3日(周二) 下午4:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [opendatalab/MinerU] 'fairscale'模块不存在 (Issue #535)




 
用了虚拟环境没有，可以试试新起个虚拟环境再装一遍依赖

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/master/docs/FAQ_zh_cn.md#5%E9%81%87%E5%88%B0%E6%8A%A5%E9%94%99-modulenotfounderror--nomodulenamed-fairscale
