### ISSUE TITLE
英文部分检测乱码

### ISSUE THREAD

**Issue by clareliu1234** [opendatalab/MinerU#538]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/07821523-bb7e-4c1e-bb7a-1079aa4ba295)

### How to reproduce the bug | 如何复现

[f076073b120019e83ec5d2877.pdf](https://github.com/user-attachments/files/16845937/f076073b120019e83ec5d2877.pdf)
这个是pdf文件

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cpu

**Comment by drunkpig** [comment]
这种文件出于 某种保护机制，修改/删除了pdf内的字符映射表。因此可以正常显示，但是无法正常复制。mineru内置了乱码检测，但是这个文件没有检测出来，因此出现了乱码。可以强制开启ocr模式可解决。

乱码检测我们会再研究下。

**Comment by clareliu1234** [comment]
是的，强制开启ocr之后能识别出来了，感谢回复
