### ISSUE TITLE
在线体验端pdf识别结果问题

### ISSUE THREAD

**Issue by X17exe** [opendatalab/MinerU#545]
附示例pdf和识别结果截图，问题：识别结果中图片占比过大，其中内容没有OCR输出
![image](https://github.com/user-attachments/assets/68235914-cc4b-4d5a-bfb6-feb8348437f7)
[889884检测报告.pdf](https://github.com/user-attachments/files/16866453/889884.pdf)

**Comment by myhloli** [comment]
线上demo没有开启表格解析功能，表格解析需要自己在本地部署并测试
