### ISSUE TITLE
MinerU和marker解析pdf能力对比

### ISSUE THREAD

**Issue by Sakura4036** [opendatalab/MinerU#551]
请问有没有人测试过MinerU和[marker](https://github.com/VikParuchuri/marker)解析pdf能力对比：准确率、格式、速度、OCR等方面？

**Comment by chloejooo123** [comment]
只是读论文的话nougat的base model比marker的解析能力强
minerU就不清楚了

**Comment by Sakura4036** [comment]
> 只是读论文的话nougat的base model比marker的解析能力强
> 
> minerU就不清楚了
> 
> 

我没用过nougat，那marker仓库的readme中的比较是虚假的吗？

**Comment by gemini-mouse** [comment]
我幫你比較完了，可直接選用MinerU。

Latex - 
MinerU的解析能力比較好，marker的Latex解析沒有那麼好，太複雜的會無法解析，但MinerU連一些超複雜的公式都能完美解讀，這真的超強。

文字表格 - 
marker預設會以文字表格的方式解析，優點是文字可複製，但排版有時候會跑掉。
MinerU預設會以圖表的方式解析，我覺得比較方便閱讀，反正真有需要文字複製，再找原檔即可，至少方便閱讀不跑版。

BTW，這議題非issue，應該貼在discussion才對~

**Comment by Sakura4036** [comment]
好的，十分感谢！ 我主要需求是提取文字，图片暂时不在考虑范围内，marker表格排版经常乱的确实很头痛。

发在这看的人比较多hhh

**Comment by star20245** [comment]
启用表格识别不就行了吗，这样不就得到文本了吗
