### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by CloudAndMist** [opendatalab/MinerU#553]
### Description of the bug | 错误描述

After finishing the first example pdf extraction, the second running failed. And then all runnings failed like this:
![issue](https://github.com/user-attachments/assets/f11b897c-33bb-4ed0-b8a6-8845f2db0521)

Is there something wrong with the second file? -> '1.2.1--0.2_课程内容导学.pdf' 
[1.2.1--0.2_课程内容导学.pdf](https://github.com/user-attachments/files/16883657/1.2.1.--0.2_.pdf)

Or is this a env issue?

### How to reproduce the bug | 如何复现

Running in command line:
`magic-pdf -p 1.2.1--0.2_课程内容导学.pdf -o output -m auto`

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
是不是设备内存不足，可以把设备的基础配置贴上来吗

**Comment by CloudAndMist** [comment]
> 是不是设备内存不足，可以把设备的基础配置贴上来吗
 
内存和显存应该是够的，也没有其它进程在跑。第一次跑测试pdf跑成功了，然后安装了一下paddlepaddle-gpu，下一次用-m auto跑上面的1.2.1--0.2_课程内容导学.pdf文件，开始卡了一阵子没反应，然后就报错了。之后无论拿什么文件跑都Bus error (core dumped) 了。
![1](https://github.com/user-attachments/assets/fe4d491e-29b1-45ab-98b7-0640f5e02b14)
![2](https://github.com/user-attachments/assets/e3df3bcd-bc59-4e8f-8672-f198a29ed954)
![3](https://github.com/user-attachments/assets/e89c98a8-f199-47e6-ad96-e0c328a51b78)

**Comment by myhloli** [comment]
系统是ubuntu吗，paddlepaddlegpu是用的3.0.0b1？

**Comment by CloudAndMist** [comment]
是Ubuntu 20.04.6 LTS，paddlepaddlegpu是用的3.0.0b1

**Comment by myhloli** [comment]
> 是Ubuntu 20.04.6 LTS，paddlepaddlegpu是用的3.0.0b1

试试把paddlepaddle和paddlepaddle-gpu都卸了，然后装paddlepaddle-gpu==2.6.1

**Comment by myhloli** [comment]
或者可以试试我们的docker，应该能解决一些兼容问题
https://github.com/opendatalab/MinerU/blob/dev/Dockerfile

**Comment by CloudAndMist** [comment]
感谢！更换了paddlepaddle-gpu版本后可以运行-m txt了，请问如果我的应用场景仅需使用-m txt是不是就不需要ocr的GPU加速呢？
使用-m ocr时报错如下：
![4](https://github.com/user-attachments/assets/abffb477-53f4-47e9-af14-51abc7326596)
![5](https://github.com/user-attachments/assets/56fa1f54-6366-4052-a800-5ecd3db1e9c8)

**Comment by myhloli** [comment]
只需要-m txt是不需要ocr的gpu加速的，看报错应该是2.6.1的paddle要求的cudnn和你目前的环境不兼容

**Comment by CloudAndMist** [comment]
好的，感谢！
