### ISSUE TITLE
ocr解析pdf，部分pdf会出现乱码问题

### ISSUE THREAD

**Issue by stormchen-cell** [opendatalab/MinerU#558]
### Description of the bug | 错误描述

![微信图片_20240906110217](https://github.com/user-attachments/assets/1d17d739-6481-47ef-9f11-3e2bab11c32d)
![微信图片_20240906110328](https://github.com/user-attachments/assets/3fda561d-b2e3-4ca8-9e4e-cfbafee68706)
![微信图片_20240906110340](https://github.com/user-attachments/assets/da5aca96-fbe9-48de-9669-3e648466d7ab)
基础镜像 /cuda-12.1.1-cudnn-8-python-3.10-ubuntu-22.04-coocaa

### How to reproduce the bug | 如何复现

![微信图片_20240906110217](https://github.com/user-attachments/assets/1d17d739-6481-47ef-9f11-3e2bab11c32d)
![微信图片_20240906110328](https://github.com/user-attachments/assets/3fda561d-b2e3-4ca8-9e4e-cfbafee68706)
![微信图片_20240906110340](https://github.com/user-attachments/assets/da5aca96-fbe9-48de-9669-3e648466d7ab)
基础镜像 /cuda-12.1.1-cudnn-8-python-3.10-ubuntu-22.04-coocaa
尝试过换成 /cuda-11.8.0-cudnn-8-python-3.10-ubuntu-22.04-coocaa还是乱码
使用cpu进行解析的话不会出现乱码

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by stormchen-cell** [comment]
我这边乱码的pdf，在官方demo调用不会出现乱码

**Comment by myhloli** [comment]
看这个症状，应该是paddle框架和显卡不兼容导致的，可以去paddleocr仓库提一下issue

**Comment by stormchen-cell** [comment]
pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu123/
把paddlepaddle-gpu 118升级成123就好了

**Comment by myhloli** [comment]
已添加该案例到FAQ

**Comment by ChenZiHong-Gavin** [comment]
> pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu123/ 把paddlepaddle-gpu 118升级成123就好了

pytorch无法兼容cu123，所有paddlepaddle-gpu cu123版本总是安装失败，有遇到类似的情况吗？

**Comment by qdushuaicao** [comment]
把paddlepaddle-gpu 118升级成123  后 处理速度慢了一倍，是什么原因？
