### ISSUE TITLE
对于整个页面大部分为空白，只有几个字符的PDF页面， 无法识别

### ISSUE THREAD

**Issue by coocoocooee** [opendatalab/MinerU#559]
### Description of the bug | 错误描述

对于整个页面大部分为空白，只有几个字符的PDF页面， 无法识别。请问是否对pdf的尺寸有什么要求？ 

### How to reproduce the bug | 如何复现

[1.pdf](https://github.com/user-attachments/files/16902496/1.pdf)
[2.pdf](https://github.com/user-attachments/files/16902501/2.pdf)
运行命令  magic-pdf -p ./2.pdf -m ocr  得到的md文件为0字节

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/3bf67f3e-be0c-4634-87ec-eec4aa71e128)
版面分析模型认为这是一个需要被移除的区块，可能因为这个页面结构确实不太合理，没有正文，且你的内容在页面的边角部分

**Comment by coocoocooee** [comment]
> ![image](https://private-user-images.githubusercontent.com/11393164/365026860-3bf67f3e-be0c-4634-87ec-eec4aa71e128.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTU0MzcsIm5iZiI6MTcyNTU5NTEzNywicGF0aCI6Ii8xMTM5MzE2NC8zNjUwMjY4NjAtM2JmNjdmM2UtYmUwYy00NjM0LTg3ZWMtZWVjNGFhNzFlMTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAzNTg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNDVkODc3ZThjYzI4Mjg0MzI1M2U4YmIyMGZjZDdkMjU2YWNmOTk3YTc2ZGRjZTUxNjIyMjJiNzJlNGY4MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PMJxvlezQizhUuPAedsPeW9s09XH4X7uPGerA5sQJiI) 版面分析模型认为这是一个需要被移除的区块，可能因为这个页面结构确实不太合理，没有正文，且你的内容在页面的边角部分

感谢回复！ 请问有什么办法处理没？ 背景是这样的，由于现在MinerU似乎还不支持复杂表格的识别（有复杂单元格的行列合并）， 所以我使用img2table 这个工具， 将每个单元格单独裁剪出来给mineru识别。 试过将图片按原始大小生成pdf， 或按A4尺寸居中或左上角顶格生成pdf，经常都是无法识别（有些单元格能识别， 字越少的识别概率越低）

**Comment by myhloli** [comment]
你需要的可能只是普通的ocr？直接用paddleocr就可以了吧

**Comment by coocoocooee** [comment]
> 你需要的可能只是普通的ocr？直接用paddleocr就可以了吧

不知道为什么，我用paddleocr总是对公式的识别很差（我的这些图片很多是公式）， 谢谢，我从pp的方向也再去试试看

**Comment by myhloli** [comment]
> > 你需要的可能只是普通的ocr？直接用paddleocr就可以了吧
> 
> 
> 
> 不知道为什么，我用paddleocr总是对公式的识别很差（我的这些图片很多是公式）， 谢谢，我从pp的方向也再去试试看

paddleocr本身就不支持公式，你有独立的公式识别需求可以试试unimernet

**Comment by coocoocooee** [comment]
> > > 你需要的可能只是普通的ocr？直接用paddleocr就可以了吧
> > 
> > 
> > 不知道为什么，我用paddleocr总是对公式的识别很差（我的这些图片很多是公式）， 谢谢，我从pp的方向也再去试试看
> 
> paddleocr本身就不支持公式，你有独立的公式识别需求可以试试unimernet

感谢，我去研究下
