### ISSUE TITLE
推理显存占用很高

### ISSUE THREAD

**Issue by pandaominggz** [opendatalab/MinerU#561]
### Description of the bug | 错误描述

for loop 对文件夹内pdf 进行推理，每个pdf 页数不超过50页。在for loop 过程中，显存占用从8221MB逐渐上升到17969MB, 设备是单张4090显卡。

### How to reproduce the bug | 如何复现

import os
import json
import shutil
import pandas as pd
from loguru import logger

from rapidocr_onnxruntime import RapidOCR
from rapid_table import RapidTable

from magic_pdf.pipe.UNIPipe import UNIPipe
from magic_pdf.rw.DiskReaderWriter import DiskReaderWriter

import magic_pdf.model as model_config 
model_config.__use_inside_model__ = True

pdf_root_path = './pdf'
for pdf_file in os.listdir(pdf_root_path):
    if pdf_file.endswith('.pdf'):
        # 按照demo.py 读取pdf 文件，设置路径
        pdf_bytes = open(os.path.join(pdf_root_path, pdf_file), "rb").read()
        jso_useful_key = {"_pdf_type": "", "model_list": []}
        output_dir = os.path.join(pdf_root_path, pdf_file[:-4])
        os.makedirs(output_dir, exist_ok=True)
        local_image_dir = os.path.join(output_dir, 'images')
        image_writer = DiskReaderWriter(local_image_dir)
        pipe = UNIPipe(pdf_bytes, jso_useful_key, image_writer)
        pipe.pipe_classify()
        pipe.pipe_analyze()
        pipe.pipe_parse()
        # 保存结果
        with open(os.path.join(output_dir, 'middle.json'), 'w', encoding="utf-8") as f:  
            json.dump(pipe.pdf_mid_data, f)
        md_content = pipe.pipe_mk_markdown(str(os.path.basename(local_image_dir)), drop_mode="none")
        with open(f"{pdf_file[:-4]}.md", "w", encoding="utf-8") as f:
            f.write(md_content)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by clareliu1234** [comment]
我也是这样的问题，楼主有解决方案吗？

**Comment by myhloli** [comment]
@clareliu1234 @pandaominggz 已修复显存占用过高问题，目前单进程运行峰值占用不超过10G，服务端空闲时占用约4G。
![image](https://github.com/user-attachments/assets/64f73e55-2baf-4690-9815-49d529360545)
修复代码预计在0.9.x实装。
