### ISSUE TITLE
解析PDF得到的content_list中标题只有一级

### ISSUE THREAD

**Issue by littlexiaoyou** [opendatalab/MinerU#562]
### Description of the bug | 错误描述

通过 demo/magic_pdf_parse_main.py 去跑 pdf_parse_main(pdf_path) 得到
content_list.json文件中 标题的 text_level 只有 1

我看 magic_pdf\dict2md\ocr_mkcontent.py 中
para_to_standard_format_v2 方法里 'text_level': 1 是写死的

### How to reproduce the bug | 如何复现

任意的pdf都是一样的，去执行这个
demo/magic_pdf_parse_main.py

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
这个level确实是写死的1，我们只是预留了扩展方案，目前并没有实现标题分级。
