### ISSUE TITLE
报错torch版本和cuda版本不匹配

### ISSUE THREAD

**Issue by ynzm233** [opendatalab/MinerU#563]
### Description of the bug | 错误描述

![cuda、torch](https://github.com/user-attachments/assets/a12b9e7e-79f1-4610-af8f-4ef3ae105276)
d
![报错](https://github.com/user-attachments/assets/d9d12cd6-76bd-42b1-b266-698f652eaaa5)
您好想请问一下，我按照流程安装了cuda11.8和torch2.3.1，并且在python中检查可用，但运行示例的pdf文件ocr后却会报错

### How to reproduce the bug | 如何复现

按教程部署gpu加速

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
第一张图是在系统环境的python检测的，第二张图是在conda的虚拟环境里

**Comment by ynzm233** [comment]
> 第一张图是在系统环境的python检测的，第二张图是在conda的虚拟环境里

！！！好的！我在conda环境里重新安装了torch已经可以正常使用了！！谢谢大佬
