### ISSUE TITLE
内网离线运行总是提示发送request失败，里面是有什么依赖要手动下载吗？

### ISSUE THREAD

**Issue by DreamTeamWangbowen** [opendatalab/MinerU#565]
### Description of the bug | 错误描述

2024-09-06 22:05:44.569 | ERROR    | __main__:pdf_parse_main:162 - <urlopen error [Errno 104] Connection reset by peer>
Traceback (most recent call last):

  File "/root/anaconda3/envs/wbw/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
    │ │       │   │             │   │         │   │     └ {'Host': 'dl.fbaipublicfiles.com', 'Method': 'HEAD', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebK...
    │ │       │   │             │   │         │   └ <property object at 0x7f0623542930>
    │ │       │   │             │   │         └ <urllib.request.Request object at 0x7f04d60577d0>
    │ │       │   │             │   └ '/fasttext/supervised-models/lid.176.ftz'
    │ │       │   │             └ <urllib.request.Request object at 0x7f04d60577d0>
    │ │       │   └ <function Request.get_method at 0x7f06235ca5c0>
    │ │       └ <urllib.request.Request object at 0x7f04d60577d0>
    │ └ <function HTTPConnection.request at 0x7f0623e005e0>
    └ <http.client.HTTPSConnection object at 0x7f04d635fb10>
  File "/root/anaconda3/envs/wbw/lib/python3.11/http/client.py", line 1303, in request
    self._send_request(method, url, body, headers, encode_chunked)
    │    │             │       │    │     │        └ False
    │    │             │       │    │     └ {'Host': 'dl.fbaipublicfiles.com', 'Method': 'HEAD', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebK...
    │    │             │       │    └ None
    │    │             │       └ '/fasttext/supervised-models/lid.176.ftz'
    │    │             └ 'GET'
    │    └ <function HTTPConnection._send_request at 0x7f0623e00680>
    └ <http.client.HTTPSConnection object at 0x7f04d635fb10>
  File "/root/anaconda3/envs/wbw/lib/python3.11/http/client.py", line 1349, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
    │    │          │                    └ False
    │    │          └ None
    │    └ <function HTTPConnection.endheaders at 0x7f0623e00540>
    └ <http.client.HTTPSConnection object at 0x7f04d635fb10>
  File "/root/anaconda3/envs/wbw/lib/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    │    │            │                            └ False
    │    │            └ None
    │    └ <function HTTPConnection._send_output at 0x7f0623e000e0>
    └ <http.client.HTTPSConnection object at 0x7f04d635fb10>
  File "/root/anaconda3/envs/wbw/lib/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
    │    │    └ b'GET /fasttext/supervised-models/lid.176.ftz HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: dl.fbaipublicfiles.com\r\nMethod...
    │    └ <function HTTPConnection.send at 0x7f0623dffec0>
    └ <http.client.HTTPSConnection object at 0x7f04d635fb10>
  File "/root/anaconda3/envs/wbw/lib/python3.11/http/client.py", line 996, in send
    self.connect()
    │    └ <function HTTPSConnection.connect at 0x7f062372dbc0>
    └ <http.client.HTTPSConnection object at 0x7f04d635fb10>
  File "/root/anaconda3/envs/wbw/lib/python3.11/http/client.py", line 1475, in connect
    self.sock = self._context.wrap_socket(self.sock,
    │    │      │    │        │           │    └ None
    │    │      │    │        │           └ <http.client.HTTPSConnection object at 0x7f04d635fb10>
    │    │      │    │        └ <function SSLContext.wrap_socket at 0x7f0623e01f80>
    │    │      │    └ <ssl.SSLContext object at 0x7f04d47a5640>
    │    │      └ <http.client.HTTPSConnection object at 0x7f04d635fb10>
    │    └ None
    └ <http.client.HTTPSConnection object at 0x7f04d635fb10>
  File "/root/anaconda3/envs/wbw/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod(<function SSLSocket._create at 0x7f0623e03ec0>)>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7f04d47a5640>
  File "/root/anaconda3/envs/wb

### How to reproduce the bug | 如何复现

通过demo中的调用方法

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by yetao2023** [comment]
你好，最后怎么解决的？
