### ISSUE TITLE
模型预加载参数错误，大佬救命🆘🆘🆘

### ISSUE THREAD

**Issue by FHhui** [opendatalab/MinerU#571]
### Description of the bug | 错误描述

<img width="1009" alt="mmexport1725846334462" src="https://github.com/user-attachments/assets/00bba0b6-ba3e-42a8-b063-851d854c7fed">

### How to reproduce the bug | 如何复现

模型加载参数报错。
<img width="1009" alt="mmexport1725846334462" src="https://github.com/user-attachments/assets/7ada6c46-777f-42b6-81a1-d5a6e9b5c835">

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by FHhui** [comment]
解决了
pip install unimernet=0.1.6

**Comment by myhloli** [comment]
mineru的依赖版本是写死的0.1.6，应该不会有这个问题

**Comment by FHhui** [comment]
好的，重新装一下这个依赖就解决了，可能是我当时装的有问题
