### ISSUE TITLE
pdf解析时报“pymupdf.mupdf.FzErrorSyntax: code=8: syntax error in object (58 0 R)”

### ISSUE THREAD

**Issue by liy-a** [opendatalab/MinerU#572]
### Description of the bug | 错误描述

在以命令 magic-pdf -p 12352684.pdf -o out_re  解析pdf时报错如下：
  File "/home/chenzixiang785/.conda/envs/mineru/lib/python3.10/site-packages/magic_pdf/libs/draw_bbox.py", line 143, in draw_layout_bbox
    pdf_docs.save(f"{out_path}/layout.pdf")
    │        └ <function Document.save at 0x7f2db359dea0>
    └ Document('', <memory, doc# 6>)
  File "/home/chenzixiang785/.conda/envs/mineru/lib/python3.10/site-packages/pymupdf/__init__.py", line 5452, in save
    mupdf.pdf_save_document(pdf, filename, opts)
    │     │                 │    │         └ (do_incremental=0 do_pretty=0 do_ascii=0 do_compress=0 do_compress_images=0 do_compress_fonts=0 do_decompress=0 do_garbage=0 ...
    │     │                 │    └ 'out_re/12352684/auto/layout.pdf'
    │     │                 └ <pymupdf.mupdf.PdfDocument; proxy of <Swig Object of type 'mupdf::PdfDocument *' at 0x7f2d5e3c56b0> >
    │     └ <function pdf_save_document at 0x7f2db34d3c70>
    └ <module 'pymupdf.mupdf' from '/home/chenzixiang785/.conda/envs/mineru/lib/python3.10/site-packages/pymupdf/mupdf.py'>
  File "/home/chenzixiang785/.conda/envs/mineru/lib/python3.10/site-packages/pymupdf/mupdf.py", line 50692, in pdf_save_document
    return _mupdf.pdf_save_document(doc, filename, opts)
           │      │                 │    │         └ (do_incremental=0 do_pretty=0 do_ascii=0 do_compress=0 do_compress_images=0 do_compress_fonts=0 do_decompress=0 do_garbage=0 ...
           │      │                 │    └ 'out_re/12352684/auto/layout.pdf'
           │      │                 └ <pymupdf.mupdf.PdfDocument; proxy of <Swig Object of type 'mupdf::PdfDocument *' at 0x7f2d5e3c56b0> >
           │      └ <built-in function pdf_save_document>
           └ <module 'pymupdf._mupdf' from '/home/chenzixiang785/.conda/envs/mineru/lib/python3.10/site-packages/pymupdf/_mupdf.so'

### How to reproduce the bug | 如何复现

1.上传pdf 12352684.pdf
2. 运行命令 magic-pdf -p 12352684.pdf -o out_re 
[12352684.pdf](https://github.com/user-attachments/files/16925066/12352684.pdf)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
文档本身损坏了，导致最后画框之后保存不了，可以通过浏览器重打印一遍，我这边测试可以正常执行的。
![image](https://github.com/user-attachments/assets/9b6d3c97-324d-4573-b58c-1a1dadcd7da0)

**Comment by liy-a** [comment]
好的，谢谢您的回复～，我这边试一下。

**Comment by liy-a** [comment]
这边尝试过了，问题解决了，太感谢您了～

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/pull/957 fixed
