### ISSUE TITLE
求助docker相关

### ISSUE THREAD

**Issue by meng0423** [opendatalab/MinerU#575]
目前物理机上的cuda版本是10.2，请问我直接用官方的dockerfile可以成功部署嘛？需不需要在docker中安装cuda11.8，谢谢！

**Comment by myhloli** [comment]
docker中的cuda与物理机中的互不影响，只需要保证物理机的driver支持的最高版本的cuda大于等于12.1即可

**Comment by meng0423** [comment]
谢谢您的回答！

**Comment by aantior** [comment]
使用官方docker部署出来的网页没有上传按钮
