### ISSUE TITLE
Unable to handle large files

### ISSUE THREAD

**Issue by Sg4Dylan** [opendatalab/MinerU#576]
### Description of the bug | 错误描述

PyMuPDF throws a segment error when processing large bytes of input.

### How to reproduce the bug | 如何复现

```shell
>>> import fitz
>>> pdf_bytes = open("test.pdf", "rb").read()
>>> len(pdf_bytes)
2800084663
>>> doc = fitz.open("pdf", pdf_bytes)
[1]    779680 segmentation fault (core dumped)  python
```

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
。。。2800m的单pdf文档，这个我们没有测试过，而且这个问题我们也没法解决，可以提issue到pymupdf的仓库

**Comment by Sg4Dylan** [comment]
https://github.com/opendatalab/MinerU/blob/magic_pdf-0.7.1-released/magic_pdf/pdf_parse_union_core.py#L202
I mean using `pdf_docs = fitz.open(doc_path)` instead of `doc = fitz.open("pdf", pdf_bytes)` could fix it.

我的意思是使用 `pdf_docs = fitz.open(doc_path)` 而不是 `doc = fitz.open("pdf", pdf_bytes)` 可以解决这个问题。

**Comment by myhloli** [comment]
> https://github.com/opendatalab/MinerU/blob/magic_pdf-0.7.1-released/magic_pdf/pdf_parse_union_core.py#L202 I mean using `pdf_docs = fitz.open(doc_path)` instead of `doc = fitz.open("pdf", pdf_bytes)` could fix it.
> 
> 我的意思是使用 `pdf_docs = fitz.open(doc_path)` 而不是 `doc = fitz.open("pdf", pdf_bytes)` 可以解决这个问题。

使用bytes作为输入是有原因的，api接口在被调用时，使用bytes输入便于接口对s3环境和本地环境的统一适配，doc_path的读取方式并不能很好适应远程调用接口的情况。
