### ISSUE TITLE
能提供远程IP地址+API key使用的功能吗？

### ISSUE THREAD

**Issue by llity** [opendatalab/MinerU#585]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
移动笔记本性能很弱，希望能在服务器安装，通过远程api key的方法发送PDF和接收结果。

**Describe the solution you'd like**
**描述您期望的解决方案**
在linux服务器中安装，用过IP地址和api key互联使用

**Comment by myhloli** [comment]
可以试试这个https://github.com/opendatalab/MinerU/tree/dev/web_api

**Comment by llity** [comment]
主要想集成到其他软件里面调用API。发送API，返回多种格式的结果文件。

**Comment by Tendo33** [comment]
> 可以试试这个https://github.com/opendatalab/MinerU/tree/dev/web_api

这样部署模型支持并发吗

**Comment by liu-kan** [comment]
试下这个 https://github.com/liu-kan/pdf2othersAPI
