### ISSUE TITLE
layout.pdf结果和layout模型结果不一致

### ISSUE THREAD

**Issue by Schumpeterx** [opendatalab/MinerU#590]
### Description of the bug | 错误描述

使用`magic-pdf -m auto`命令得到的layout.pdf长这样：
<img width="1077" alt="image" src="https://github.com/user-attachments/assets/3c8d65f4-a722-4b47-9bc2-c5abdf9f7fb4">
上图中4.1.10这一句话被处理成了表格的一部分，后续不会出现在md文件中。
`锂电池/超级电容状态检测设备及系统清单 表4.1.10`也不会出现在md文件中。
这显然是错误的。

----------------------------------------------------------------

而直接调用layout模型获取的输出长这样（在label studio中显示。 红色框为text，绿色框为表格， 蓝色框为表格标题）：
分类的置信度都为1.0
<img width="450" alt="image" src="https://github.com/user-attachments/assets/ce686951-7489-44ad-bb70-1f984a599ec8">

可以看出，layout模型对页面元素的分类是正确的。

----------------------------------------------------------------

生成的md文件：表格的标题、表与表直接的正文都丢失了
<img width="797" alt="image" src="https://github.com/user-attachments/assets/f6b9dff6-764d-4d61-a60a-da836c09f1a7">

----------------------------------------------------------------

结论：layout模型的输出是正确的，后续处理时出现了错误。
除此之外， 表格标题存在同样的问题：layout模型可以识别出上图中的表格标题的两个部分，比如`锂电池/超级电容状态检测设备及系统清单 表4.1.10`， 但是后续处理时，只保留其中的一部分，有时是`锂电池/超级电容状态检测设备及系统清单 `, 有时是`表4.1.10`

### How to reproduce the bug | 如何复现

[origin-页面-2 (1).pdf](https://github.com/user-attachments/files/16957199/origin-.-2.1.pdf)
注：我对layout模型进行过微调，可能和原layout模型的输出不一样。

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/02a036d1-1e3a-4f09-9302-f302cdffe85c)
后续处理应该没有问题，可以升级0.8.0再试下

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/34bc5399-f838-4ca6-960f-e66bf099af29)
你这个是0.7的问题，0.8已经修了

**Comment by Schumpeterx** [comment]
> ![image](https://private-user-images.githubusercontent.com/11393164/366280930-02a036d1-1e3a-4f09-9302-f302cdffe85c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzMxNTAsIm5iZiI6MTcyNjAzMjg1MCwicGF0aCI6Ii8xMTM5MzE2NC8zNjYyODA5MzAtMDJhMDM2ZDEtMWUzYS00ZjA5LTkzMDItZjMwMmNkZmZlODVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA1MzQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMDlkODZmZjRlMWFhMTZkYjNlMzY4OWJiMTI4MTNlMDVhNzkxNmE2MDJmNDRkMGFmOTU2YjA2YTU4OTZlNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.33fQzvrf9TTAwUOxlRLAvzfeiCEpc7c-jYO6yuXaU_k) 后续处理应该没有问题，可以升级0.8.0再试下

升级完4.1.10这块确实可以了。 但是其他地方还有问题：
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/51bc061d-af30-4688-a20a-bbe030b2c796">
<img width="1107" alt="image" src="https://github.com/user-attachments/assets/8774cbd8-4f15-49dd-822d-61b0f2984318">
4.1.8这块文本layout识别出来是对的
<img width="563" alt="image" src="https://github.com/user-attachments/assets/1bbbd610-153a-4c1c-b26e-f742a461e536">

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/515f5afc-8bbd-4945-b178-c88e3e5f251e)
上面是模型识别结果，红框是textblock
![image](https://github.com/user-attachments/assets/5449f7fc-2314-4bd1-b28e-9fc3286fb5e7)
这个是pipeline处理完的结果，看上去下表的caption被上面的表合并了，而且新生成的table block覆盖了三块红色区域的textblock。
@icecraft 麻烦看一下好修复吗

**Comment by icecraft** [comment]
@Schumpeterx @myhloli 原因确实是 下表的 caption 被上面的表合并了。将在下个 release 予以修复。

**Comment by myhloli** [comment]
0.8.1已修复
