### ISSUE TITLE
magic-pdf -p demo1.pdf Illegal instruction | 执行magic-pdf提示指令非法

### ISSUE THREAD

**Issue by Joyouspeng** [opendatalab/MinerU#591]
### Description of the bug | 错误描述

执行magic-pdf -p demo1.pdf后，打印
```
2024-09-11 12:26:07.581 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 1, text_len: 35537, cid_chars_radio: 2.8144437251977146e-05
Illegal instruction
```

### How to reproduce the bug | 如何复现

1. wget -U NoSuchBrowser/1.0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-2024.06-1-Linux-x86_64.sh
2. bash Anaconda3-2024.06-1-Linux-x86_64.sh （在这里指定了conda的安装目录、后续编辑了~/.bashrc的内容“export PATH=$PATH:/data/minerU/anaconda3/bin”）
3. conda create -n MinerU python=3.10
4. pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com 这个超时（在下载这个paddlepaddle包的时候）了，采用下面的命令执行
pip install -U magic-pdf[full]==0.7.1 --extra-index-url https://wheels.myhloli.com -i https://pypi.tuna.tsinghua.edu.cn/simple

5. 安装模型pip install modelscope -i https://pypi.tuna.tsinghua.edu.cn/simple 并创建py脚本执行snapshot_download方法
6. 第一次运行前配置，配置完 报错：“ImportError: libGL.so.1: cannot open shared object file: No such file or directory”
wget https://gitee.com/myhloli/MinerU/raw/master/magic-pdf.template.json
cp magic-pdf.template.json ~/magic-pdf.json
根据报错 安装
yum install mesa-libGL-devel mesa-libGL

7. 执行测试
wget https://gitee.com/myhloli/MinerU/raw/master/demo/small_ocr.pdf
magic-pdf -p small_ocr.pdf
报错：
“2024-09-11 12:26:07.581 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 1, text_len: 35537, cid_chars_radio: 2.8144437251977146e-05
Illegal instruction”

模型文件核对过了
![image](https://github.com/user-attachments/assets/0d61afe8-4f7c-450c-947f-5e7fd62dd881)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
看上去像是cpu指令集不兼容，这个除了换服务器配置无解

**Comment by Joyouspeng** [comment]
![Snipaste_2024-09-11_14-33-36](https://github.com/user-attachments/assets/128392ac-4de6-4965-aec1-d868f183c691)

这个是开发环境的cpu配置 如何检视硬件条件呢？

**Comment by myhloli** [comment]
理论上没有什么特殊要求，看之前其他人的反馈应该是需要AVX或者AVX2指令集支持，你这个金至强看上去时不支持的？
![image](https://github.com/user-attachments/assets/bc210431-341f-4360-9a37-7820fac7f80d)

**Comment by tanhaipeng** [comment]
> 理论上没有什么特殊要求，看之前其他人的反馈应该是需要AVX或者AVX2指令集支持，你这个金至强看上去时不支持的？ ![image](https://github.com/user-attachments/assets/bc210431-341f-4360-9a37-7820fac7f80d)

旧版magic_pdf没这个问题，升级到1.0出现的，能兼容下么

**Comment by myhloli** [comment]
> > 理论上没有什么特殊要求，看之前其他人的反馈应该是需要AVX或者AVX2指令集支持，你这个金至强看上去时不支持的？ ![image](https://github.com/user-attachments/assets/bc210431-341f-4360-9a37-7820fac7f80d)
> 
> 旧版magic_pdf没这个问题，升级到1.0出现的，能兼容下么

你说的旧版是哪个版本，0.9，0.10能正常使用吗
