### ISSUE TITLE
解析信息丢失

### ISSUE THREAD

**Issue by JackMacs** [opendatalab/MinerU#592]
### Description of the bug | 错误描述

使用线上接口解析pdf时，部分pdf信息会丢失。

### How to reproduce the bug | 如何复现

上传pdf即可

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
需要提供可以复现的样本
