### ISSUE TITLE
请问华为昇腾卡可否用来运行MinerU推理加速呢

### ISSUE THREAD

**Issue by JiangRunzhi** [opendatalab/MinerU#593]
有一些昇腾卡，不是CUDA，是CANN，求教可否运行MinerU，如果可以如何配置呢？

**Comment by myhloli** [comment]
需要自行在你的设备上跑通pytorch 2.3.1和paddlepaddle 3.0.0b1的加速，然后把项目中初始化模型的地方修改成你跑通的配置

**Comment by lrybbbccc** [comment]
MinerU在华为显卡上的适配效果如何？期待新的结论
