### ISSUE TITLE
文件转换

### ISSUE THREAD

**Issue by sabibi12** [opendatalab/MinerU#594]
请问有什么办法可以将md与对应的图片资源转换为pdf或者word一类的文档呢，mineru非常好用，但是我看了一下输出的几个文件，没有适合我使用的。希望可以增加一个参数设置，工作的时候可以导出md那样的pdf或者word文件。
如果有相关办法的话，请留言，不胜感激

**Comment by myhloli** [comment]
试试pandoc呢

**Comment by sabibi12** [comment]
好的，感谢，我去尝试一下
