### ISSUE TITLE
按轮次处理文件，一轮只使用一个模型，减少对最大显存的需求。

### ISSUE THREAD

**Issue by hwf1324** [opendatalab/MinerU#596]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**

我显卡的显存只有 8 G，但看 OCR 对显存的需求也没那么大，想也用 GPU 加速 OCR。
而且看处理输出，现在似乎是每次对单页进行多个模型的处理，一会显卡占用一会 CPU 占用的。
直觉上每个模型处理的部分应该是分离的，所以有一次使用单模型处理所有内容后在交给下一个模型处理的设想。
这样就可以同时加速了。

**Describe the solution you'd like**
**描述您期望的解决方案**

改变处理流程，每轮只使用单个处理步骤处理所有内容后，多轮处理。
交替轮次时卸载/加载模型。

**Describe alternatives you've considered**
**描述您已考虑的替代方案**

这也许对长期运行的 API 服务的场景不太适用，除非同时只处理一个文件。

**Additional context**
**提供更多细节**

None

**Comment by myhloli** [comment]
在处理过程中增加了显存回收代码，测试有效，可以在

https://huggingface.co/spaces/opendatalab/MinerU

通过实时资源占用情况确认自己的样本解析时的显存占用情况，我这边测试目前峰值不会超过10g，在本地一块8g的3060ti上也运行良好。

修复代码会在下一个版本中合并到release中。
