### ISSUE TITLE
未来能考虑增加arm架构的支持吗

### ISSUE THREAD

**Issue by MeVeryHandsome** [opendatalab/MinerU#598]
我们在arm机器上运行pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com 时，下载回来的版本默认是0.6.1，当指定最新0.8.0时，对于eva-decord、torchtext等依赖会出现版本过低无法满足要求的问题，所以想问一下未来可以考虑增加arm架构的支持吗😭

**Comment by myhloli** [comment]
only support arm64 on macOS.
