### ISSUE TITLE
How can I use all GPUs to accelarate?

### ISSUE THREAD

**Issue by wahahaer** [opendatalab/MinerU#606]
I have 4 GPUs (2080), and when I use **_magic-pdf cli_** to deal with the pdf files in a folder, I found only **_GPU:0_** is used (by `nvidia-smi`). How can I assign GPU index in command line to use all the GPUs?

`magic-pdf -p /folder/path`

thanks

**Comment by myhloli** [comment]
Please refer this project: https://github.com/opendatalab/MinerU/tree/master/projects/multi_gpu
