### ISSUE TITLE
图片描述和图片并排时图片描述丢失的问题。

### ISSUE THREAD

**Issue by L9qmzn** [opendatalab/MinerU#610]
### Description of the bug | 错误描述

![下载 (1)](https://github.com/user-attachments/assets/d0b2ebf2-42e5-4ff6-9982-6d4ef1443780)

### How to reproduce the bug | 如何复现

[2405.07987v1_3.pdf](https://github.com/user-attachments/files/16981409/2405.07987v1_3.pdf)

上面是测试使用的pdf文件。

在魔搭的demo中和本地部署中，都遇到了这个问题。

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
这张图存在下方和右侧两个caption，在预处理过程中有一步是将图片和对应的caption合并到同一个block中，在这个例子中一张图在两个方向有两个caption，算法会将最近的那个caption与图片合并。
目前我们为了不影响上下文语义的连贯性，不能简单的将无主的caption当做普通文本块合并到文档中，对于这种一图多caption的案例需要内部讨论下如何保留。

**Comment by myhloli** [comment]
已修复
https://github.com/opendatalab/MinerU/pull/785

![image](https://github.com/user-attachments/assets/e31eceb4-8042-4b22-b9d9-4e0fd6786d43)
