### ISSUE TITLE
部份PDF解析过程会卡住

### ISSUE THREAD

**Issue by Ajax-Yi** [opendatalab/MinerU#612]
### Description of the bug | 错误描述

参数："device-mode":"cuda",
    "table-config": {
        "model": "TableMaster",
        "is_table_recog_enable": false,
        "max_time": 400
    }
运行命令：magic-pdf -p 8a950bf3d8ebe453368c9ce2e61d5968.pdf -o test
文档解析到26页就卡住了。（第27页图标较多）
<img width="1296" alt="image" src="https://github.com/user-attachments/assets/f909b73a-5b6a-4b75-96ef-1e344dadc02f">

### How to reproduce the bug | 如何复现

[8a950bf3d8ebe453368c9ce2e61d5968 (1).pdf](https://github.com/user-attachments/files/16991358/8a950bf3d8ebe453368c9ce2e61d5968.1.pdf)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
这页有太多看不到的隐藏文字，导致在一个循环去重的地方速度比较慢
和之前某些论文的表现形式比较类似，矢量图是由细小的文字组成的
![image](https://github.com/user-attachments/assets/f1fc552e-211e-4032-bac5-8680435eb8cb)
![image](https://github.com/user-attachments/assets/90c2bef7-d39f-46d3-a748-8afc7d395d61)
这种情况没有什么好的办法，要么等，要么使用ocr全局处理，要么通过剪裁把这页删除掉再处理

**Comment by Ajax-Yi** [comment]
> 这页有太多看不到的隐藏文字，导致在一个循环去重的地方速度比较慢 和之前某些论文的表现形式比较类似，矢量图是由细小的文字组成的 ![image](https://private-user-images.githubusercontent.com/11393164/367231425-f1fc552e-211e-4032-bac5-8680435eb8cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTk5NTQsIm5iZiI6MTcyNjIxOTY1NCwicGF0aCI6Ii8xMTM5MzE2NC8zNjcyMzE0MjUtZjFmYzU1MmUtMjExZS00MDMyLWJhYzUtODY4MDQzNWViOGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA5MjczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmM2NkZjVlYWZhZGVkMDM2MzhhN2VlMTNiM2M3MzFjNWQwYmQ1ODNjNTg4MzM5ZjRmMDljNDI5Y2NlNjU5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mlrl9YSqKUyjeh-jaiPvR6RYWgVjDVHObZsyBg1X2Mw) ![image](https://private-user-images.githubusercontent.com/11393164/367231838-90c2bef7-d39f-46d3-a748-8afc7d395d61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTk5NTQsIm5iZiI6MTcyNjIxOTY1NCwicGF0aCI6Ii8xMTM5MzE2NC8zNjcyMzE4MzgtOTBjMmJlZjctZDM5Zi00NmQzLWE3NDgtOGFmYzdkMzk1ZDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA5MjczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MzFhNDg0MjYyNjhlOWRlNDZlMjQ5ZDA1OGEzNzQ0YTI1MGY5NTc1NjczMjk4MDAwZDcxNmI4YWYxNTNhNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eJQPJElAGSlZWVA8PdbOt0cYDbEdQf1wTOAMPEcJwjs) 这种情况没有什么好的办法，要么等，要么使用ocr全局处理，要么通过剪裁把这页删除掉再处理

线上版处理的速度还挺快。是有什么区别吗。https://opendatalab.com/OpenSourceTools/Extractor/

**Comment by myhloli** [comment]
因为线上版没处理到这一页吧，默认只会处理前10页

**Comment by Ajax-Yi** [comment]
> 因为线上版没处理到这一页吧，默认只会处理前10页

我裁剪了，处理的后10页。
[8a950bf3d8ebe453368c9ce2e61d5968-10.pdf](https://github.com/user-attachments/files/16992003/8a950bf3d8ebe453368c9ce2e61d5968-10.pdf)

**Comment by myhloli** [comment]
线上做了缓存吧，你上次提交的时候他后台跑完就缓存了，下次再跑的时候直接给你读的缓存

**Comment by Ajax-Yi** [comment]
> 线上做了缓存吧，你上次提交的时候他后台跑完就缓存了，下次再跑的时候直接给你读的缓存

线上只提交了一次，很快就出结果了。而且我本地的卡了3小时还没结果。

**Comment by myhloli** [comment]
> > 线上做了缓存吧，你上次提交的时候他后台跑完就缓存了，下次再跑的时候直接给你读的缓存
> 
> 线上只提交了一次，很快就出结果了。而且我本地的卡了3小时还没结果。

有没有可能你勾了ocr，ocr是不会卡在这的
线上有个逻辑bug，你首次上传勾了ocr，第二次不勾也会读首次ocr的缓存

**Comment by Ajax-Yi** [comment]
> > > 线上做了缓存吧，你上次提交的时候他后台跑完就缓存了，下次再跑的时候直接给你读的缓存
> > 
> > 
> > 线上只提交了一次，很快就出结果了。而且我本地的卡了3小时还没结果。
> 
> 有没有可能你勾了ocr，ocr是不会卡在这的 线上有个逻辑bug，你首次上传勾了ocr，第二次不勾也会读首次ocr的缓存

确实是勾选了OCR

**Comment by myhloli** [comment]
> > > > 线上做了缓存吧，你上次提交的时候他后台跑完就缓存了，下次再跑的时候直接给你读的缓存
> > > 
> > > 
> > > 线上只提交了一次，很快就出结果了。而且我本地的卡了3小时还没结果。
> > 
> > 
> > 有没有可能你勾了ocr，ocr是不会卡在这的 线上有个逻辑bug，你首次上传勾了ocr，第二次不勾也会读首次ocr的缓存
> 
> 确实是勾选了OCR

那就对了
