### ISSUE TITLE
你好，能否配置文件中增加对paddleoc检测和识别模型文件存储位置的配置，方便训练模型的配置使用，谢谢

### ISSUE THREAD

**Issue by cabbage18** [opendatalab/MinerU#614]
你好，能否在magic-pdf.json配置文件中增加对paddleoc检测和识别模型文件存储位置的配置，方便训练模型的配置使用，谢谢！

**Comment by myhloli** [comment]
paddle模型极小，可以参考官方放置位置，放在用户目录即可
