### ISSUE TITLE
更新改本后部分内容会丢失

### ISSUE THREAD

**Issue by Maple0709** [opendatalab/MinerU#617]
### Description of the bug | 错误描述

使用老版本可以正确的解析的正文内容，在0.8的版本中内容丢失了

### How to reproduce the bug | 如何复现

使用老版本可以正确的解析的正文内容，在0.8的版本中内容丢失了。

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by dehua6666666** [comment]
我更新到最新8.1版本，下载新的模型文件以后也是，之前很好识别的文件现在效果很不好

**Comment by myhloli** [comment]
@Maple0709 @dehua6666666 可以上传一下解析效果有差异的pdf文档吗

**Comment by myhloli** [comment]
未能上传有效测试文档
