### ISSUE TITLE
api调用短时间上传相同pdf出现could not execute a primitive错误

### ISSUE THREAD

**Issue by dehua6666666** [opendatalab/MinerU#618]
### Description of the bug | 错误描述

封装为接口，采用api调用的方式，短时间上传相同pdf时，出现500，could not execute a primitive错误

### How to reproduce the bug | 如何复现

封装为接口，api调用，短时间上传相同pdf

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
cpu的paddle在linux有这个问题，在windows使用cpu或者在linux使用gpu的paddle则问题消失，所以推荐使用gpu环境搭建服务
