### ISSUE TITLE
【QA】magic-pdf解析pdf后资源没有即刻释放

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#619]
### Description of the bug | 错误描述

cuda模式下用pytest框架连续执行多个magic-pdf命令行的case，前面几个解析正常运行，后面就会OOM

### How to reproduce the bug | 如何复现

用pytest框架连续执行多个magic-pdf命令行的case，前面几个解析正常运行，后面就会OOM
![image](https://github.com/user-attachments/assets/0715dc9f-f8f3-4daf-94db-daa326afcd92)

![image](https://github.com/user-attachments/assets/b9f9db54-05da-4cbb-a15d-47fc591f4a79)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
已修复

https://github.com/opendatalab/MinerU/pull/672/commits/4c9bf8abd58038f93c15ba70114cd438f45a0e77
