### ISSUE TITLE
magic-pdf.exe在电脑上不可用

### ISSUE THREAD

**Issue by Gene1343** [opendatalab/MinerU#620]
### Description of the bug | 错误描述

conda activate MinerU

(MinerU) C:\Users\DLX>C:\ProgramData\Anaconda3\envs\MinerU\Scripts\magic-pdf.exe -v
拒绝访问。

然后弹出弹窗：此应用无法在你的电脑上运行若要找到适用于你的电脑的版本，请咨询软件发布者。

### How to reproduce the bug | 如何复现

![Uploading 1726317626730.jpg…]()

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by Gene1343** [comment]
试了一下 0.8.1也不行

C:\Users\DLX>pip index versions magic-pdf
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
magic-pdf (0.8.1)
Available versions: 0.8.1, 0.8.0, 0.7.1, 0.6.1, 0.6.0, 0.5.13, 0.5.12, 0.5.11, 0.5.10, 0.5.9, 0.5.8, 0.5.7, 0.5.6, 0.5.5, 0.5.4
  INSTALLED: 0.8.1
  LATEST:    0.8.1

**Comment by Gene1343** [comment]
但是退回到0.6.1后可以使用
cd /d D:\software\MinerU-magic_pdf-0.6.2b1-released
进入MinerU目录,使用conda activate MinerU 进入虚拟环境
使用命令

magic-pdf pdf-command --pdf "D:\files\zotero files\zoterpdf-File\1. 项目内容\项目9 前列腺癌病理BCR分型\2024\Amgad 等 - 2024 - A population-level digital histologic biomarker for enhanced prognosis of invasive breast cancer.pdf" --inside_model true

这个是可以运行的

**Comment by myhloli** [comment]
系统不兼容，你的系统版本是？
