### ISSUE TITLE
| ERROR    | magic_pdf.cli.magicpdf:do_parse:114 - need model list input

### ISSUE THREAD

**Issue by HSDCLZ** [opendatalab/MinerU#623]
### Description of the bug | 错误描述

![微信截图_20240915122532](https://github.com/user-attachments/assets/5e1aef10-f4e1-426b-afb8-cb31c358277d)

### How to reproduce the bug | 如何复现

magic-pdf pdf-command --pdf {pdf path} --method auto

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
请在更新到最新版本
pip install -U magic-pdf[full]==0.8.1

不支持python3.11，请使用3.10版本

**Comment by stavismed** [comment]
Thanks, magic-pdf==0.9.3 and python 3.10.15 on Windows solved the problem for me!
