### ISSUE TITLE
layoutlmv3的标签体系，可以公布一下么，这样可以换成自己训练微调

### ISSUE THREAD

**Issue by FHhui** [opendatalab/MinerU#625]

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/master/docs/output_file_zh_cn.md

可以参考中xxxx model.json一节

**Comment by FHhui** [comment]
map={
1:"title",
2:"plain text",
3:"abandon",
4:"figure",
5:"figure_caption",
6:"table",
7:"table_caption",
8:"table_footnote",
9:"isolate_formula",
10:"formula_caption"
}
请问是这个么

**Comment by myhloli** [comment]
> map={
> 
> 1:"title",
> 
> 2:"plain text",
> 
> 3:"abandon",
> 
> 4:"figure",
> 
> 5:"figure_caption",
> 
> 6:"table",
> 
> 7:"table_caption",
> 
> 8:"table_footnote",
> 
> 9:"isolate_formula",
> 
> 10:"formula_caption"
> 
> }
> 
> 请问是这个么

title = 0               # 标题
     plain_text = 1          # 文本
     abandon = 2             # 包括页眉页脚页码和页面注释
     figure = 3              # 图片
     figure_caption = 4      # 图片描述
     table = 5               # 表格
     table_caption = 6       # 表格描述
     table_footnote = 7      # 表格注释
     isolate_formula = 8     # 行间公式
     formula_caption = 9     # 行间公式的标号

     embedding = 13          # 行内公式
     isolated = 14           # 行间公式
     text = 15               # ocr 识别结果

这个

**Comment by FHhui** [comment]
layoutlmv3使用的是detectron2训练的，0不应该是背景么，而且我看只有到formulacaption被传入了layoutlmv3的metaconfig，剩下这三个不应是paddle加进来的标签么，我想问的是单纯布局分析这一部分。

**Comment by myhloli** [comment]
> layoutlmv3使用的是detectron2训练的，0不应该是背景么，而且我看只有到formulacaption被传入了layoutlmv3的metaconfig，剩下这三个不应是paddle加进来的标签么，我想问的是单纯布局分析这一部分。

纯layout那就是你的1到10再加个0

**Comment by FHhui** [comment]
好的，可以问一下你们的layout模型是使用什么数据集微调的么，还是自己打的？

**Comment by ouyanglinke** [comment]
> layoutlmv3使用的是detectron2训练的，0不应该是背景么，而且我看只有到formulacaption被传入了layoutlmv3的metaconfig，剩下这三个不应是paddle加进来的标签么，我想问的是单纯布局分析这一部分。

Layoutlmv3训练数据格式是COCO，类别信息如下：
{"categories": [{"supercategory": "", "id": 1, "name": "title"}, {"supercategory": "", "id": 2, "name": "plain text"}, {"supercategory": "", "id": 3, "name": "abandon"}, {"supercategory": "", "id": 4, "name": "figure"}, {"supercategory": "", "id": 5, "name": "figure_caption"}, {"supercategory": "", "id": 6, "name": "table"}, {"supercategory": "", "id": 7, "name": "table_caption"}, {"supercategory": "", "id": 8, "name": "table_footnote"}, {"supercategory": "", "id": 9, "name": "isolate_formula"}, {"supercategory": "", "id": 10, "name": "formula_caption"}], "annotations": [], "images": []}

模型是在官方提供的预训练权重的基础上微调的，用的是我们自己的数据集，训练数据集不会开源。

**Comment by FHhui** [comment]
好的，感谢。

**Comment by linchen111** [comment]
> > map={
> > 1:"title",
> > 2:"plain text",
> > 3:"abandon",
> > 4:"figure",
> > 5:"figure_caption",
> > 6:"table",
> > 7:"table_caption",
> > 8:"table_footnote",
> > 9:"isolate_formula",
> > 10:"formula_caption"
> > }
> > 请问是这个么
> 
> title = 0 # 标题 plain_text = 1 # 文本 abandon = 2 # 包括页眉页脚页码和页面注释 figure = 3 # 图片 figure_caption = 4 # 图片描述 table = 5 # 表格 table_caption = 6 # 表格描述 table_footnote = 7 # 表格注释 isolate_formula = 8 # 行间公式 formula_caption = 9 # 行间公式的标号
> 
> ```
>  embedding = 13          # 行内公式
>  isolated = 14           # 行间公式
>  text = 15               # ocr 识别结果
> ```
> 
> 这个

请问为啥行间公式有两个？
