### ISSUE TITLE
能否增加页眉页脚剔除开关参数，控制是否剃除页眉页脚内容

### ISSUE THREAD

**Issue by guoguo0646** [opendatalab/MinerU#626]
目前版本[0.8.1]识别出pdf文档中的页眉页脚并做了自动剃除，在有些场景下由于页眉页脚里包含了些比较重要的内容需要在最终解析结果里保留页眉页脚的内容，能否增加页眉页脚剔除开关全局参数，并通过此参数控制是否剃除页眉页脚内容？

**Comment by myhloli** [comment]
middle.json中的discarded_blocks存储了每页被剔除的文本信息，可以自己写个逻辑转存出来。

**Comment by skyantao** [comment]
书本的页码没有被识别出来，我需要页码用于业务定位，怎么能输出呢？

discarded_blocks 里面也没有

**Comment by myhloli** [comment]
> 书本的页码没有被识别出来，我需要页码用于业务定位，怎么能输出呢？
> 
> 
> 
> discarded_blocks 里面也没有

只要页码的话，contentlist中有个pageidx字段代表页码

**Comment by skyantao** [comment]
我需要从目录 的页码指向  对应的位置，page_index 从0 开始的，前面有封面、版号、目录、序言等，导致无法获取正确的页码

**Comment by ZXTHB** [comment]
> middle.json中的discarded_blocks存储了每页被剔除的文本信息，可以自己写个逻辑转存出来。

没看见discard_block里有内容

**Comment by Crescentz** [comment]
同意，包含很重要信息

**Comment by skatehy** [comment]
> 目前版本[0.8.1]识别出pdf文档中的页眉页脚并做了自动剃除，在有些场景下由于页眉页脚里包含了些比较重要的内容需要在最终解析结果里保留页眉页脚的内容，能否增加页眉页脚剔除开关全局参数，并通过此参数控制是否剃除页眉页脚内容？

> middle.json中的discarded_blocks存储了每页被剔除的文本信息，可以自己写个逻辑转存出来。

多用于论文(脚注很多)。但是生成文件中将脚注剔除了，导致很多信息丢失。转存的话不知道如何添加的原有的文件内容中，是否可以考虑增加这一功能？

**Comment by Huaweidev** [comment]
+1，有时候一两页的合同或者技术文档，页眉页脚有必要的信息，识别后直接导出为docx格式时，如果能直接包括了页眉页脚，将会非常方便。
图A:

<img width="258" height="229" alt="Image" src="https://github.com/user-attachments/assets/76afd4a9-9559-4c4c-9779-aa88497e39e8" />
