### ISSUE TITLE
报错ValueError: zero-size array to reduction operation maximum which has no identity 

### ISSUE THREAD

**Issue by maicaijian** [opendatalab/MinerU#629]
### Description of the bug | 错误描述

报错ValueError: zero-size array to reduction operation maximum which has no identity 

### How to reproduce the bug | 如何复现

执行识别发现版面识别会出现，right less than left报错，以及zero-size错误

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
需要上传pdf样本

**Comment by maicaijian** [comment]
[Uploading multicolumn_A-local-Fourier-convergence-analysis-of-a-multigrid-_2014_Journal-of-Symboli.pdf…]()

**Comment by myhloli** [comment]
> Uploading multicolumn_A-local-Fourier-convergence-analysis-of-a-multigrid-_2014_Journal-of-Symboli.pdf…

没上传成功

**Comment by maicaijian** [comment]
> > Uploading multicolumn_A-local-Fourier-convergence-analysis-of-a-multigrid-_2014_Journal-of-Symboli.pdf…
> 
> 没上传成功

[Uploading multicolumn_A-local-Fourier-convergence-analysis-of-a-multigrid-_2014_Journal-of-Symboli.pdf…]()

**Comment by maicaijian** [comment]
测试文件

**Comment by maicaijian** [comment]
https://github.com/user-attachments/files/16579086/1.pdf

**Comment by myhloli** [comment]
> https://github.com/user-attachments/files/16579086/1.pdf

使用在线demo测试可以正常解析，pdf内的文本存在部分乱码情况，需要手动勾选强制开启ocr，解析效果尚可
![image](https://github.com/user-attachments/assets/c6fac366-eccd-4384-a402-3ba3aefe36ef)

**Comment by myhloli** [comment]
> https://github.com/user-attachments/files/16579086/1.pdf

测试地址：
https://www.modelscope.cn/studios/OpenDataLab/MinerU
使用在线demo测试可以正常解析，pdf内的文本存在部分乱码情况，需要手动勾选强制开启ocr，解析效果尚可 ![image](https://private-user-images.githubusercontent.com/11393164/368492473-c6fac366-eccd-4384-a402-3ba3aefe36ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDk4ODUsIm5iZiI6MTcyNjY0OTU4NSwicGF0aCI6Ii8xMTM5MzE2NC8zNjg0OTI0NzMtYzZmYWMzNjYtZWNjZC00Mzg0LWE0MDItM2JhM2FlZmUzNmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA4NTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMzA3ZTNmNWU0OWE0OTcyNzZiNDQzNzFkYjRmYWVjOTFjMGI3ODg5NTJlMjcyYTBiMzBhZWQ2NmYxNWNiMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sFJMC9p0j8V_5WEcfQWFc1CySARQjhLSTNiZNzhoKCs)
