### ISSUE TITLE
在表格识别时内容缺失

### ISSUE THREAD

**Issue by YoungWWan** [opendatalab/MinerU#633]
### Description of the bug | 错误描述

目前我在进行表格识别时会遇到换行内容识别不全，我查看源码发现在进行图片识别时使用的是原始的RGB图片，我使用cv2.cvtColor(np.asarray(new_image), cv2.COLOR_RGB2BGR)转成BGR后丢失的部分就正常识别了

### How to reproduce the bug | 如何复现

magic_pdf/model/pdf_extract_kit.py  380行
<img width="1318" alt="Snipaste_2024-09-19_11-06-48" src="https://github.com/user-attachments/assets/c496d371-9a95-4898-be83-1320d6767f75">
<img width="750" alt="Snipaste_2024-09-19_11-09-52" src="https://github.com/user-attachments/assets/8aae97db-0eeb-4911-a54b-50ab5d411a1a">
<img width="507" alt="Snipaste_2024-09-19_11-11-40" src="https://github.com/user-attachments/assets/e19e6f3c-2f34-438b-bebe-885e017d7d3e">

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
感谢反馈，@papayalove 看一下这个问题

**Comment by myhloli** [comment]
你是对的，我重新阅读了ppocr的源码，paddle在表格解析前是使用cv2读取图片，这样默认是BGR通道，我们是使用pillow截图，这样默认是RGB通道
