### ISSUE TITLE
识别表格的时候只给出了图片，不是json数据。

### ISSUE THREAD

**Issue by stormsea** [opendatalab/MinerU#634]
### Description of the bug | 错误描述

识别表格的时候，md文件里只有表格的图片，不是json数据。这样的话就毫无意义。

### How to reproduce the bug | 如何复现

无

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
参考：
https://github.com/opendatalab/MinerU/blob/master/README_zh-CN.md#3-拷贝配置文件并进行配置

表格识别功能需手动开启
