### ISSUE TITLE
希望能保留下划线等占位符，希望能保留

### ISSUE THREAD

**Issue by jeremyWangJun03** [opendatalab/MinerU#638]
### Description of the bug | 错误描述

原文：
<img width="695" alt="image" src="https://github.com/user-attachments/assets/54e3f5ef-b931-414e-a3dc-e60b3556154f">

识别：
<img width="453" alt="image" src="https://github.com/user-attachments/assets/753a3253-1b40-4508-af32-d6fab0106979">

希望能够保留这些占位符号

### How to reproduce the bug | 如何复现

用带有__的pdf就会复现

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
扫描版文档的下划线受ocr功能限制很难识别出来
