### ISSUE TITLE
这种手写的图片转成的PDF识别不了文字嘛

### ISSUE THREAD

**Issue by THEONEBUKE** [opendatalab/MinerU#648]
### Description of the bug | 错误描述

[test_images.pdf](https://github.com/user-attachments/files/17095069/test_images.pdf)

### How to reproduce the bug | 如何复现

content_list.json：
[
    {
        "type": "image",
        "page_idx": 0,
        "img_path": "images/38a10f4323a9f1ebccc1b82e6d057a7eecdf986b485f34694d5cb14f8555e754.jpg"
    }
]

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
因为layout模型没有使用这种样本训练过，所以在一开始layout模型会把这页pdf识别成一张图片，那么在后续的处理过程中，都不会对图片中的文本进行提取操作，也就没能提取到这页里面的文本。
