### ISSUE TITLE
【QA】研报中文章标题被识别为Table xx

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#651]
### Description of the bug | 错误描述
识别结果：
![image](https://github.com/user-attachments/assets/424d9a34-40da-41b8-9eae-657e4c3655fa)
原文：
![image](https://github.com/user-attachments/assets/aafa01ba-f6ae-4d7e-9bdd-8e83c3189dc2)

### How to reproduce the bug | 如何复现

[research_report_c65b5243c6c1f03723f83075b08134a2.zip](https://github.com/user-attachments/files/17095968/research_report_c65b5243c6c1f03723f83075b08134a2.zip)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
经验证，
1. 该文档重要声明处复制文本为：[Table_Reputation]
2. 投资评级说明处复制文本为：[Table_RankIntroduction]
