### ISSUE TITLE
下载后一直是0.6.1版本 强制选定版本就会报缺少其它包

### ISSUE THREAD

**Issue by Twilight-Spider** [opendatalab/MinerU#653]
### Description of the bug | 错误描述

使用文中的命令下载后一直是0.6.1版本 强制选定版本就会报缺少其它包

### How to reproduce the bug | 如何复现

使用链接下载

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
如果python版本是3.10没错的话，看看cpu是不是arm架构的，目前我们在linux和windows上是不支持arm的

**Comment by Twilight-Spider** [comment]
确认过 是x86_64架构的  python版本也是新建的环境装的3.10

**Comment by myhloli** [comment]
可以试试能不能安装上这个包

pip install https://wheels-1251341229.cos.ap-shanghai.myqcloud.com/assets/whl/detectron2/detectron2-0.6-cp310-cp310-linux_x86_64.whl

如果能装上可以继续执行magic-pdf的安装命令

**Comment by myhloli** [comment]
或者你直接指定安装magic-pdf==0.8.1，上传一下报错信息，看看是哪个包不兼容

**Comment by Twilight-Spider** [comment]
刚才安装上detectron2后直接按安装文档里的命令  可以看到先下载了0.8.1版本 但全部安装完后  查看--version还是0.6.1  我现在试试指定版本

**Comment by Twilight-Spider** [comment]
直接指定安装版本的话也可以安装成功 但是运行会有好几个包报 no module named  cv2 PIL torch torchtext PIllow  ultralytics pycocotools  这些错误

**Comment by myhloli** [comment]
> 直接指定安装版本的话也可以安装成功 但是运行会有好几个包报 no module named cv2 PIL torch torchtext PIllow ultralytics pycocotools 这些错误

写错了，是magic-pdf[full]==0.8.1

**Comment by Twilight-Spider** [comment]
这一次前面都装成功了（cuda加速的包也都装了） 运行的时候选了cpu或者cuda模式都报了这个错误 （是因为我这个是单位内网么 但之前同事用0.7.0b1版本可以运行）
![Uploading 批注 2024-09-24 103035.png…]()

**Comment by Twilight-Spider** [comment]
![批注 2024-09-24 103035](https://github.com/user-attachments/assets/a7e38e3b-939d-4de6-8728-f9c06e66f008)

**Comment by myhloli** [comment]
需要下载约10m的paddleocr模型，可以在有网的机器上下载并拷贝用户目录中.paddleocr目录到你的内网设备

**Comment by Twilight-Spider** [comment]
刚往上翻了翻才翻到这个错误 是不是就是这个地址 然后按这个位置拷贝过去
![Uploading 批注 2024-09-24 103035.png…]()

**Comment by Twilight-Spider** [comment]
![Uploading 批注 2024-09-24 103035.png…]()

**Comment by Twilight-Spider** [comment]
刚往上翻了翻才翻到这个错误的详细描述 有模型地址和要拷贝的地址 
感谢感谢 麻烦了您一上午 终于是安装成功了~ 再次感谢感谢！！！
