### ISSUE TITLE
能否提供简易的更新方法

### ISSUE THREAD

**Issue by XSR-WatchPioneer** [opendatalab/MinerU#654]
GPU版本的安装本来就有点繁琐，想更新不知道怎么办，只能把教程里的部分命令重新跑
```
pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com -i https://pypi.tuna.tsinghua.edu.cn/simple
```
以及花很多流量重新下载一次模型，因为不知道更新后那一堆模型是不是有变化。

**Comment by myhloli** [comment]
更新magic-pdf使用你上面发的这条命令即可，0.6.x到0.8.x模型是没有变化的，不需要更新模型。
在0.9.x更新时，需要更新模型，支持增量更新，不需要全部重新下载，到时候会有相应的模型更新文档

**Comment by XSR-WatchPioneer** [comment]
> 更新magic-pdf使用你上面发的这条命令即可，0.6.x到0.8.x模型是没有变化的，不需要更新模型。 在0.9.x更新时，需要更新模型，支持增量更新，不需要全部重新下载，到时候会有相应的模型更新文档

我重新下载了模型并对比了文件结构，还是有很多差异的，不过好歹根据自己的理解更新成功了，很好用的工具，感谢你们的开源
