### ISSUE TITLE
gradio怎么显示行内符号和图片？

### ISSUE THREAD

**Issue by sunzx8** [opendatalab/MinerU#656]
我用的代码为
with gr.Blocks() as demo:
    gr.Markdown("# PDF Parsing with OCR")
    
    with gr.Row():
        with gr.Column():
            pdf_file = gr.File(label="Upload PDF", type="filepath")
            parse_method = gr.Radio(choices=["ocr_span"], label="Parse Method", value="ocr_span")
            submit_button = gr.Button("Submit")
            gallery = gr.Gallery(label="PDF Images")

        with gr.Column():
            markdown_output = gr.Markdown(label="Parsed Markdown")
    
    submit_button.click(
        fn=gradio_interface, 
        inputs=[pdf_file, parse_method], 
        outputs=[gallery, markdown_output]
    )

遇到的问题是
1.行内数字符号不转译
2.图片不显示
图片地址给的是

![](/home/ubuntu/shawn/new_demo/local_pdf_processer/pdf_parse_output/28552-Article Text-32606-1-2-20240324/images/6098807fc839ac2aac4b82b013c5f7d068ff29081d7922473e08d0ada40761c0.jpg)  

请问我该怎么做

**Comment by myhloli** [comment]
gradio代码可以参考这个project

https://github.com/opendatalab/MinerU/tree/dev/projects/gradio_app

**Comment by sunzx8** [comment]
谢谢
