### ISSUE TITLE
文档标题无法识别

### ISSUE THREAD

**Issue by Ceceliachenen** [opendatalab/MinerU#657]
### Description of the bug | 错误描述

这篇文档"Model S”无法识别为标题，但是"Model 3"却能被识别为标题。且图片识别不全，只截取了车的图片，没有识别出图片上部分的文字介绍。

### How to reproduce the bug | 如何复现

直接运行即可复现。pdf文件在附件。
[multi_modal_test_tesla.pdf](https://github.com/user-attachments/files/17109916/multi_modal_test_tesla.pdf)

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
这个文档有些字其实是图片，默认的auto提取不到，我试了下强制开启ocr之后效果还可以
命令行中开启ocr的方式是加入`-m ocr`
![image](https://github.com/user-attachments/assets/1c041b4b-ae12-4c6b-a624-712bca70882a)
![image](https://github.com/user-attachments/assets/f64b637d-90c8-4ef0-8dcf-0787493b9c87)

**Comment by Ceceliachenen** [comment]
想问下auto是自动分辨需要用text还是ocr模式吗？因为我发现有的文件是auto模式比较好，有的文件是ocr模式比较好，模式很难固定。

**Comment by myhloli** [comment]
> 想问下auto是自动分辨需要用text还是ocr模式吗？因为我发现有的文件是auto模式比较好，有的文件是ocr模式比较好，模式很难固定。

auto是自动选择text或者ocr的，主要是根据文档是否扫描版或者是否存在乱码来判断，
通常情况下auto即可，少部分文档会存在auto效果不如ocr的情况，需要手动选择ocr
