### ISSUE TITLE
Some content in pdf is not recognized

### ISSUE THREAD

**Issue by liangqf108** [opendatalab/MinerU#660]
### Description of the bug | 错误描述

hello, below image is my Question
![error_20240925153720](https://github.com/user-attachments/assets/4c38b9fe-e83b-4c35-a9b8-8622e6b3d43a)

### How to reproduce the bug | 如何复现

Some Linux msg:
Driver Version: 550.90.07      CUDA Version: 12.4  cuDNN version: 9.2.0  os-release: 22.04.4 LTS (Jammy Jellyfish)  

I deployed the service using docker

enter container later , I do the some operations

I magic-pdf, version 0.8.1

root@xxxxxxxxxx:/# cd /tmp/
root@xxxxxxxxxx:/tmp# ll ./pdf_ceshi.pdf
-rw-r--r-- 1 root root 92893 Sep 25 07:15 ./pdf_ceshi.pdf
root@xxxxxxxxxx:/tmp# /opt/mineru_venv/bin/magic-pdf -p pdf_ceshi.pdf -o ./ -m auto

The command was executed successfully, but some of the above mentioned contents were not recognized

orgin file:
[pdf_ceshi.pdf](https://github.com/user-attachments/files/17127404/pdf_ceshi.pdf)

parsered files:
pdf_ceshi.md: 
[pdf_ceshi.md](https://github.com/user-attachments/files/17127360/pdf_ceshi.md)

pdf_ceshi_layout.pdf:
[pdf_ceshi_layout.pdf](https://github.com/user-attachments/files/17127375/pdf_ceshi_layout.pdf)

pdf_ceshi_middle.json:
[pdf_ceshi_middle.json](https://github.com/user-attachments/files/17127381/pdf_ceshi_middle.json)

pdf_ceshi_middle.json:
[pdf_ceshi_model.json](https://github.com/user-attachments/files/17127386/pdf_ceshi_model.json)

pdf_ceshi_spans.pdf:
[pdf_ceshi_spans.pdf](https://github.com/user-attachments/files/17127393/pdf_ceshi_spans.pdf)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
Our layout model is trained through normal typesetting documents, so poor recognition may occur in this specially constructed test case, which is normal.
