### ISSUE TITLE
How to obtain a complete model file

### ISSUE THREAD

**Issue by jojocoding** [opendatalab/MinerU#663]
### Description of the bug | 错误描述

1.Retrieve the model file using the following command：
   git lfs clone https://huggingface.co/opendatalab/PDF-Extract-Kit 

2.But the model file is missing TableMaster：
<img width="661" alt="image" src="https://github.com/user-attachments/assets/f197ba4f-64a3-4fed-aac4-e122d902e4e2">

3.In the official document of MinerU,it can be seen that there are complete model files，including TableMaster：
<img width="666" alt="image" src="https://github.com/user-attachments/assets/cba103fd-c55e-46a5-858d-de226be22835">

4. So, how can I obtain the complete model file,thanks!

### How to reproduce the bug | 如何复现

It's not a problem with the program running,there's no need to reproduce it.

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
`git pull` or use python script to update model files
https://github.com/opendatalab/MinerU/blob/dev/docs/how_to_download_models_en.md

**Comment by jojocoding** [comment]
> `git pull` or use python script to update model files https://github.com/opendatalab/MinerU/blob/dev/docs/how_to_download_models_en.md

Thanks,the method has taken effect and the problem has been solved.
