### ISSUE TITLE
1464474399@qq.com

### ISSUE THREAD

**Issue by republicline** [opendatalab/MinerU#664]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。

PDF解析这块的问题, 这里我们是将PDF解析成了结构化的数据md, 如果我希望做一些文本替换的操作, 比如:  PDF版的一篇论文, 我对论文有润色需求, 是否可以将PDF解析好的 数据保存成一个结构化的 json格式  例如 title: 标题A context: 文本A,  然后将文本A输入到其他的模型中, 将返回的结果替换掉  {title: "标题A", context: "替换过的文本A"},  然后利用模板引擎 读取 这个json 渲染成md, 也就是说PDF 渲染到md的过程中提供一个中间的操作, 是否有这样的接口呢. 

期望实现的内容就是按照以上方式 :  上传一个PDF论文(或其他形式), 解析好之后, 返回给我一个润色好的PDF(或其他形式的文件). 

清晰且简洁地描述您已经考虑过的任何替代解决方案
这里调研了阿里云的智能问答解析大模型, 会将docx解析成结构化数据, 但是并不能将结构化数据反向渲染成 docx. 与预期功能不符合.

**Comment by myhloli** [comment]
你的需求可以通过middle json实现，具体文件格式可以参考https://github.com/opendatalab/MinerU/blob/master/docs/output_file_zh_cn.md#some_pdf_middlejson

在middle json中做过的润色，可以通过mineru原本的抽取逻辑，转换成markdown或者content list.json
