### ISSUE TITLE
pip install magic-pdf安装不起效果

### ISSUE THREAD

**Issue by tongji-1** [opendatalab/MinerU#671]
### Description of the bug | 错误描述

ImportError: cannot import name 'preserve_channel_dim' from 'albucore.utils' (D:\Users\22525\anaconda3\envs\MinerU\lib\site-packages\albucore\utils.py)
2024-09-27 23:09:32.138 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:29 - Required dependency not installed, please install by 
"pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/"

### How to reproduce the bug | 如何复现

<img width="876" alt="5a81468cdea39d4bc960557c1b33822" src="https://github.com/user-attachments/assets/53f697b2-56a7-476e-b8a9-6580e33b0bcd">
<img width="737" alt="d7086709d6e151611e4f2eb38c0a9fa" src="https://github.com/user-attachments/assets/e9ce98eb-9b96-4313-ac42-1f5b4e499c4a">

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/issues/640
