### ISSUE TITLE
Intel XPU支持需求

### ISSUE THREAD

**Issue by duanrf1975** [opendatalab/MinerU#675]
Intel Arc GPU的笔记本上安装好了Intel XPU的相关程序包和依赖，只能用cpu跑，xpu会出现下面的错误。请求帮助！
 
ERROR    | magic_pdf.tools.cli:parse_doc:96 - **Could not run 'aten::empty_strided' with arguments from the 'XPU' backend.** This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty_strided' is only available for these backends: [CPU, Meta, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

**Comment by myhloli** [comment]
我们目前只支持在cuda上开启加速功能，不兼容的设备只提供基础的cpu运行兼容性。

**Comment by duanrf1975** [comment]
多谢，希望以后能够在更多设备设备上运行这个好用的工具

**Comment by zy6p** [comment]
实测可以跑，需要开启 XPU 的 transformers 支持
#4801
