### ISSUE TITLE
Config File issue

### ISSUE THREAD

**Issue by Akhilesh-pandey1** [opendatalab/MinerU#680]
is this config file structure is correct ? 
"""
{
    "models-dir": "D:\\work_easier_project\\AdityaOCR\\models",
    "device-mode": "cpu",
    "table-config": {
        "model": "TableMaster",
        "is_table_recog_enable": false,
        "max_time": 400
    },
    "ocr-config": {
        "enabled": false,
        "language": "eng"
    }
}
""" 

if not then please anyone give me correct structure, in which tell me how to specify OCR ? And what what thing I can specify with config file, tell me.

**Comment by myhloli** [comment]
you can't set ocr config in this json.
we use cli args to config ocr mode.
you can use `magic-pdf --help` to know how to use cli config.
