### ISSUE TITLE
CPU推理耗时比较大

### ISSUE THREAD

**Issue by hcws** [opendatalab/MinerU#681]
### Description of the bug | 错误描述

你好，
1. 我的系统是Ubuntu20.04 我使用CPU推理发现，推理demo1.pdf 可能需要1分钟，我的是64G 内存 3.4Ghz 的16核心处理器 请问下这是正常的么？
2. 请问使用GPU大约耗时多少呢？
3. Ubuntu20.04 可以使用GPU推理么

### How to reproduce the bug | 如何复现

双系统 Ubuntu20.04 
16核 3.4Ghz 64G内存台式机
使用CPU推理

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
是正常的，demo1使用gpu一般在10秒左右，根据网友反馈Ubuntu20可以使用gpu加速
