### ISSUE TITLE
Option to Disabling the LaTeX

### ISSUE THREAD

**Issue by Qasim-MJ** [opendatalab/MinerU#685]
Thank You for this amazing Project 

I'm having this problem of Miner U converting what is seems normal numbers ( Not math or complex equations ) to LaTeX
it's kind of troubling my expected result, I tried to find a solution because I want to use the text generated by Miner U in a react-native app

**_input :_** 
<img width="293" alt="Screenshot 2024-10-05 at 12 21 01 PM" src="https://github.com/user-attachments/assets/b63a87ec-f5f2-43e5-8f26-cf49f603e94a">

**_output :_** 
<img width="636" alt="Screenshot 2024-10-05 at 12 21 07 PM" src="https://github.com/user-attachments/assets/9c310d96-e0e3-4a45-8993-797b57a9f961">

**Comment by myhloli** [comment]
you can disable formula det and rec at

https://github.com/opendatalab/MinerU/blob/4ee1034cce56a6770ea374e9d87305e06d33376f/magic_pdf/model/doc_analyze_by_custom_model.py#L88

only add

`"apply_formula":False`

in dict can disable it.
