### ISSUE TITLE
Entry point in DLL not found (libtorchtext.pyd)

### ISSUE THREAD

**Issue by travek** [opendatalab/MinerU#688]
### Description of the bug | 错误描述

Hi!
I successfully installed MinerU (full-CPU).
I run pdf converting with commnd:
magic-pdf -p re_starts.pdf -o pdf_out -m auto
Execution fails with the following error
Entry point into procedure
??0Error@c10@@QEAA@V?$basic_string@DU?$char_traits@D@
std@@V?$allocator@D@2@@std@@OPEBX@Z is not found in 
library DLL
D:\my_path\Python311\Lib\site-packages\torchtext\lib\libtorchtext.pyd.

I reinstalled all packages torch, torchtext, magic-pdf BUT the issue remains.

What I can do to fix ?

### How to reproduce the bug | 如何复现

magic-pdf -p re_starts.pdf -o pdf_out -m auto

![image](https://github.com/user-attachments/assets/50949ac5-f05d-44f6-b34b-9d1c4d9ab0f6)

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by travek** [comment]
Trace of API call that fails with error

2024-10-05 21:39:00.124 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 18118, cid_chars_radio: 0.0
2024-10-05 21:39:04.645 | ERROR    | __main__:<module>:39 - [WinError 127] Не найдена указанная процедура
Traceback (most recent call last):

 
    │    │         │       └ <CDLL 'Python311\Lib\site-packages\torchtext\lib\libtorchtext.pyd', handle 0 at 0x1e3a23af250>
    │    │         └ <built-in function LoadLibrary>
    │    └ 0
    └ <CDLL '\Python311\Lib\site-packages\torchtext\lib\libtorchtext.pyd', handle 0 at 0x1e3a23af250>

OSError: [WinError 127] Не найдена указанная процедура

**Comment by myhloli** [comment]
As readme said, we don't support python3.11. You need to use conda to create a 3.10 environment and follow the steps in readme to install it.

In the virtual environment created by conda, you can successfully install the application with just one command according to the readme document without supplementing any missing dependency packages by yourself. If the installation is completed, you can check the version number through the `magic-pdf -v` command, which should output 0.8.1.
