### ISSUE TITLE
[Question] Is there a way to change the OCR model?

### ISSUE THREAD

**Issue by onaka-ga-pkpk** [opendatalab/MinerU#691]
I would like to OCR a PDF document written in Japanese. The accuracy of the layout recognition is great, but the OCR is useless.
So I researched the OCR engine PaddleOCR and found that there is a model for Japanese(japan_PP-OCRv3_rec).
I would like to replace the OCR engine, but how do I set it up?

**Comment by myhloli** [comment]
We will support select ocr language at next version.

https://github.com/opendatalab/MinerU/commit/4b372f3f7e4455fa96253089b6a592adc664f3e2
