### ISSUE TITLE
'fairscale'模块已经在pip列表，但是运行总是提示不存在

### ISSUE THREAD

**Issue by LJX-whu** [opendatalab/MinerU#692]
### Description of the bug | 错误描述

ModuleNotFoundError: No module named 'fairscale'
2024-10-08 09:05:26.543 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:29 - Required dependency not installed, please install by
"pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/"

### How to reproduce the bug | 如何复现

1、已经通过pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/指令下载了fairscale库，也利用pip list查到了fairscale，但是运行magic-pdf -p C:\Users\whu_l\Desktop\small_ocr.pdf -o C:\Users\whu_l\Desktop\就报错，没有fairscale模块；
2、尝试卸载fairscale再重装，还是有问题，怀疑是版本问题，通过pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/下载的fairscale版本为：0.4.13
3、所以fairscale的版本有什么要求吗？

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by tao-xiaoxin** [comment]
请查看一下你当前使用的环境，一般这种情况是使用了别的Python 环境，没有使用你命令行里面的Python 环境

**Comment by myhloli** [comment]
faq里有这个反馈，https://github.com/opendatalab/MinerU/blob/master/docs/FAQ_zh_cn.md#5%E9%81%87%E5%88%B0%E6%8A%A5%E9%94%99-modulenotfounderror--nomodulenamed-fairscale

根据反馈一般情况卸载重装这个库就可以了
