### ISSUE TITLE
Trying to build the docker image got https timeout while pip install

### ISSUE THREAD

**Issue by icoicqico** [opendatalab/MinerU#697]
### Description of the bug | 错误描述

Trying to build the docker image got https timeout while pip install, already set the timeout to very laarge number, maybe some files in https://pypi.tuna.tsinghua.edu.cn/simple is not avaliable.

### How to reproduce the bug | 如何复现

To reproduce the issue, just build the docker file.
wget https://github.com/opendatalab/MinerU/raw/master/Dockerfile
docker build -t mineru:latest .

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
If you are not in mainland China, please remove all instances of `-i https://pypi.tuna.tsinghua.edu.cn/simple` from your Dockerfile.
