### ISSUE TITLE
目录解析

### ISSUE THREAD

**Issue by EvanSong77** [opendatalab/MinerU#703]
### Description of the bug | 错误描述

目录解析效果很差
![snipaste_20241009_143832](https://github.com/user-attachments/assets/ea62346f-68b0-4dde-9543-0bfbd3731cbb)
![snipaste_20241009_143848](https://github.com/user-attachments/assets/1fa0f6b2-f1de-49ab-a6e7-7f34508c4198)

### How to reproduce the bug | 如何复现

magic-pdf -p Apex+Software+Integration+-+Initial+Overview.pdf  -o './'

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
目前已经加强了目录和列表的识别和解析能力，可以通过huggingface和modelscope的在线demo进行测试
