### ISSUE TITLE
为什么我的测试pdf中的表格不能转换成json，而是图片

### ISSUE THREAD

**Issue by Clint-chan** [opendatalab/MinerU#705]
#
[测试文章.pdf](https://github.com/user-attachments/files/17303736/default.pdf)
### How to reproduce the bug | 如何复现

magic-pdf -p "/data/测试文章.pdf" -o /data/output -m auto
打开了"is_table_recog_enable"

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
table是狭义的定义，特制表格，样本中的图表更接近图片而不是表格，因此按照图片逻辑处理是正常的。
