### ISSUE TITLE
Detection of Umlaut / vowel mutation in German OCR

### ISSUE THREAD

**Issue by myjob** [opendatalab/MinerU#708]
### Description of the bug | 错误描述

Processing PDF of type OCR with german vowel mutations (ä,ü,ö, Ä,Ü, Ö)  is broken and the chars are not detect or replaced by blanks.

**Example Json:**
Should be:  "Am Güterbahnhof." but result is:  "Am Giterbahnhof."
should be: "5. Floral Düngemittelverkaufsgesellschaft mbH." but result is: "5. Floral Dingemittelverkaufsgesellschaft mbH."

**Example MD:**
Should be:  "Am Güterbahnhof." but result is: "Am Gi ter bahnhof."
should be: "5. Floral Düngemittelverkaufsgesellschaft mbH." but result is: "Floral Ding emit tel ver kau fs gesellschaft mbH"

see orginal PDF, page 10
[CELEX-31980D0182_origin.pdf](https://github.com/user-attachments/files/17306492/CELEX-31980D0182_origin.pdf)
[CELEX-31980D0182_spans.pdf](https://github.com/user-attachments/files/17306496/CELEX-31980D0182_spans.pdf)

### How to reproduce the bug | 如何复现

magic-pdf -p {some_pdf} -o {some_output_dir} -m auto

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
We will support OCR for non-Chinese and non-English languages in the next version.
