### ISSUE TITLE
ubuntu版本是只支持22.04吗？

### ISSUE THREAD

**Issue by hit-wsy** [opendatalab/MinerU#714]
![image](https://github.com/user-attachments/assets/ce7bb5d2-0dc9-4194-8c4c-1fd4034e7cba)
ubuntu18.04版本，按步骤安装下来版本号是0.6.1，连基本的-p都无法使用

**Comment by myhloli** [comment]
18.04可能有点太老了，根据反馈20.04上甚至是centos7上也有人可以正常运行，我们内部的测试是在22.04上进行的，因为精力有限，不能对所有的Linux发行版进行测试，如果运行失败可以尝试使用docker构建镜像的方式。

**Comment by hit-wsy** [comment]
好的，谢谢，我尝试一下

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
