### ISSUE TITLE
Wrong detection and missing some details in the detection. 

### ISSUE THREAD

**Issue by Ab-AI-1** [opendatalab/MinerU#722]
![img_1](https://github.com/user-attachments/assets/d541cb89-2f05-4608-a20b-7fa4319088ee)

Why is it not able to detect a space-based table? Is there any configuration I should change, or what should I do, so It can detect a space-based table as a table rather than text? 

Also, it is missing some content in the detection.

**Comment by myhloli** [comment]
Since this table lacks any framing lines, the visual model may be more inclined to classify it as a text block rather than a table block.

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
