### ISSUE TITLE
帮我看下这个bug是咋回事啊

### ISSUE THREAD

**Issue by MovePhilip** [opendatalab/MinerU#726]
### Description of the bug | 错误描述

[10/11 20:53:16 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from C:\Users\admin\.cache\modelscope\hub\opendatalab\PDF-Extract-Kit/models\Layout/model_final.pth ...
[10/11 20:53:16 fvcore.common.checkpoint]: [Checkpointer] Loading from c:\Users\admin\.cache\modelscope\hub\opendatalab\PDF-Extract-Kit/models\Layout/model_final.pth ...
2024-10-11 20:53:16.923 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:248 - DocAnalysis init done!
2024-10-11 20:53:16.923 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:custom_model_init:98 - model init cost: 16.343394994735718
2024-10-11 20:53:26.523 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:259 - layout detection cost: 8.82

2024-10-11 20:53:29.501 | ERROR    | magic_pdf.tools.cli:parse_doc:96 - Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, Meta, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
Meta: registered at /dev/null:467 [kernel]
QuantizedCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:154 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:497 [backend fallback]
Functionalize: registered at ..\aten\src\ATen\FunctionalizeFallbackKernel.cpp:324 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:18 [backend fallback]
ZeroTensor: registered at ..\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:53 [backend fallback]
AutogradCPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:57 [backend fallback]
AutogradCUDA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:65 [backend fallback]
AutogradXLA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:69 [backend fallback]
AutogradMPS: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:77 [backend fallback]
AutogradXPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:61 [backend fallback]
AutogradHPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:90 [backend fallback]
AutogradLazy: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:73 [backend fallback]
AutogradMeta: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:81 [backend fallback]
Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:297 [backend fallback]
AutocastCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\autocast\nms_kernel.cpp:34 [kernel]
AutocastCUDA: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\autocast\nms_kernel.cpp:27 [kernel]
FuncTorchBatched: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:731 [backend fallback]
BatchedNestedTensor: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:758 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ..\aten\src\ATen\functorch\VmapModeRegistrations.cpp:27 [backend fallback]
Batched: registered at ..\aten\src\ATen\LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ..\aten\src\ATen\functorch\TensorWrapper.cpp:202 [backend fallback]
PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:162 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:493 [backend fallback]
PreDispatch: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:166 [backend fallback]
PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:158 [backend fallback]

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\py310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\ProgramData\Anaconda3\envs...
           │         └ <code object <module> at 0x000001C110247EC0, file "C:\ProgramData\Anaconda3\envs\py310\Scripts\magic-pdf.exe\__main__.py", li...
           └ <function _run_code at 0x000001C110231480>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\ProgramData\Anaconda3\envs...
         └ <code object <module> at 0x000001C110247EC0, file "C:\ProgramData\Anaconda3\envs\py310\Scripts\magic-pdf.exe\__main__.py", li...

  File "C:\ProgramData\Anaconda3\envs\py310\Scripts\magic-pdf.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
    │   │    └ <Command cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x000001C1106C51B0>
           └ <Command cli>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x000001C110298CA0>
         │    └ <function Command.invoke at 0x000001C1106C5C60>
         └ <Command cli>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'D:\\pycode\\PDF-Extract-Kit\\assets\\demo\\PDFs\\UniMERNet.pdf', 'output_dir': 'D:\\pycode\\PDF-Extract-Kit\\assets...
           │   │      │    │           └ <click.core.Context object at 0x000001C110298CA0>
           │   │      │    └ <function cli at 0x000001C177FD7130>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x000001C1106C49D0>
           └ <click.core.Context object at 0x000001C110298CA0>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'path': 'D:\\pycode\\PDF-Extract-Kit\\assets\\demo\\PDFs\\UniMERNet.pdf', 'output_dir': 'D:\\pycode\\PDF-Extract-Kit\\assets...
                       └ ()

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\magic_pdf\tools\cli.py", line 102, in cli
    parse_doc(path)
    │         └ 'D:\\pycode\\PDF-Extract-Kit\\assets\\demo\\PDFs\\UniMERNet.pdf'
    └ <function cli.<locals>.parse_doc at 0x000001C110283880>

> File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\magic_pdf\tools\cli.py", line 84, in parse_doc
    do_parse(
    └ <function do_parse at 0x000001C114186560>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\magic_pdf\tools\common.py", line 79, in do_parse
    pipe.pipe_analyze()
    │    └ <function OCRPipe.pipe_analyze at 0x000001C177FD63B0>
    └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x000001C14266F250>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\magic_pdf\pipe\OCRPipe.py", line 20, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True,
    │    │            │           │    └ b'%PDF-1.5\n%\x8f\n113 0 obj\n<< /Type /XObject /Subtype /Image /BitsPerComponent 8\n/ColorSpace /DeviceRGB /Filter /DCTDecod...
    │    │            │           └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x000001C14266F250>
    │    │            └ <function doc_analyze at 0x000001C112E55000>
    │    └ []
    └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x000001C14266F250>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 129, in doc_analyze
    result = custom_model(img)
             │            └ array([[[255, 255, 255],
             │                      [255, 255, 255],
             │                      [255, 255, 255],
             │                      ...,
             │                      [255, 255, 255],
             │                      [255...
             └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x000001C178000100>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 263, in __call__
    mfd_res = self.mfd_model.predict(image, imgsz=1888, conf=0.25, iou=0.45, verbose=True)[0]
              │    │         │       └ array([[[255, 255, 255],
              │    │         │                 [255, 255, 255],
              │    │         │                 [255, 255, 255],
              │    │         │                 ...,
              │    │         │                 [255, 255, 255],
              │    │         │                 [255...
              │    │         └ <function Model.predict at 0x000001C10C6F7D00>
              │    └ YOLO(
              │        (model): DetectionModel(
              │          (model): Sequential(
              │            (0): Conv(
              │              (conv): Conv2d(3, 64, kernel_size=(3, 3), ...
              └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x000001C178000100>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\ultralytics\engine\model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
           │    │         │                  │          │           │    │                │              └ False
           │    │         │                  │          │           │    │                └ array([[[255, 255, 255],
           │    │         │                  │          │           │    │                          [255, 255, 255],
           │    │         │                  │          │           │    │                          [255, 255, 255],
           │    │         │                  │          │           │    │                          ...,
           │    │         │                  │          │           │    │                          [255, 255, 255],
           │    │         │                  │          │           │    │                          [255...
           │    │         │                  │          │           │    └ <ultralytics.models.yolo.detect.predict.DetectionPredictor object at 0x000001C178000850>
           │    │         │                  │          │           └ YOLO(
           │    │         │                  │          │               (model): DetectionModel(
           │    │         │                  │          │                 (model): Sequential(
           │    │         │                  │          │                   (0): Conv(
           │    │         │                  │          │                     (conv): Conv2d(3, 64, kernel_size=(3, 3), ...
           │    │         │                  │          └ False
           │    │         │                  └ array([[[255, 255, 255],
           │    │         │                            [255, 255, 255],
           │    │         │                            [255, 255, 255],
           │    │         │                            ...,
           │    │         │                            [255, 255, 255],
           │    │         │                            [255...
           │    │         └ <function BasePredictor.predict_cli at 0x000001C10C7152D0>
           │    └ <ultralytics.models.yolo.detect.predict.DetectionPredictor object at 0x000001C178000850>
           └ YOLO(
               (model): DetectionModel(
                 (model): Sequential(
                   (0): Conv(
                     (conv): Conv2d(3, 64, kernel_size=(3, 3), ...

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\ultralytics\engine\predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
                │    │                │       │       │       └ {}
                │    │                │       │       └ ()
                │    │                │       └ None
                │    │                └ array([[[255, 255, 255],
                │    │                          [255, 255, 255],
                │    │                          [255, 255, 255],
                │    │                          ...,
                │    │                          [255, 255, 255],
                │    │                          [255...
                │    └ <function BasePredictor.stream_inference at 0x000001C10C715510>
                └ <ultralytics.models.yolo.detect.predict.DetectionPredictor object at 0x000001C178000850>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               │   └ <method 'send' of 'generator' objects>
               └ <generator object BasePredictor.stream_inference at 0x000001C18F8E3D10>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\ultralytics\engine\predictor.py", line 261, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
    │    │         │    │           │      │   └ [array([[[255, 255, 255],
    │    │         │    │           │      │             [255, 255, 255],
    │    │         │    │           │      │             [255, 255, 255],
    │    │         │    │           │      │             ...,
    │    │         │    │           │      │             [255, 255, 255],
    │    │         │    │           │      │             [25...
    │    │         │    │           │      └ tensor([[[[0.4471, 0.4471, 0.4471,  ..., 0.4471, 0.4471, 0.4471],
    │    │         │    │           │                  [0.4471, 0.4471, 0.4471,  ..., 0.4471, 0.4471, 0....
    │    │         │    │           └ [tensor([[[ 3.4433e-01, -1.8919e-01, -4.9870e-02,  ...,  9.6874e+02,  1.0116e+03,  1.0810e+03],
    │    │         │    │                      [ 2.3767e-01,  9.317...
    │    │         │    └ <function DetectionPredictor.postprocess at 0x000001C10C7383A0>
    │    │         └ <ultralytics.models.yolo.detect.predict.DetectionPredictor object at 0x000001C178000850>
    │    └ None
    └ <ultralytics.models.yolo.detect.predict.DetectionPredictor object at 0x000001C178000850>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\ultralytics\models\yolo\detect\predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
            │   └ <function non_max_suppression at 0x000001C10C642DD0>
            └ <module 'ultralytics.utils.ops' from 'C:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\ultralytics\\utils\\ops.py'>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\ultralytics\utils\ops.py", line 292, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
        │           │   │   │      │       └ 0.45
        │           │   │   │      └ tensor([0.7520, 0.7956, 0.8031, 0.7794, 0.7255, 0.7583, 0.7792, 0.7581, 0.7326, 0.7413], device='cuda:0')
        │           │   │   └ tensor([[769.7549, 338.3597, 831.7670, 370.3329],
        │           │   │             [769.7441, 338.2330, 831.6693, 370.3158],
        │           │   │             [769.9012, 338.25...
        │           │   └ <function nms at 0x000001C102B56950>
        │           └ <module 'torchvision.ops' from 'C:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\torchvision\\ops\\__init__.py'>
        └ <module 'torchvision' from 'C:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\torchvision\\__init__.py'>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\torchvision\ops\boxes.py", line 41, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           │     │   │           │   │      │       └ 0.45
           │     │   │           │   │      └ tensor([0.7520, 0.7956, 0.8031, 0.7794, 0.7255, 0.7583, 0.7792, 0.7581, 0.7326, 0.7413], device='cuda:0')
           │     │   │           │   └ tensor([[769.7549, 338.3597, 831.7670, 370.3329],
           │     │   │           │             [769.7441, 338.2330, 831.6693, 370.3158],
           │     │   │           │             [769.9012, 338.25...
           │     │   │           └ <OpOverloadPacket(op='torchvision.nms')>
           │     │   └ <module 'torch.ops.torchvision' from 'torch.ops'>
           │     └ <module 'torch.ops' from '_ops.py'>
           └ <module 'torch' from 'C:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\torch\\__init__.py'>

  File "C:\ProgramData\Anaconda3\envs\py310\lib\site-packages\torch\_ops.py", line 854, in __call__
    return self_._op(*args, **(kwargs or {}))
           │     │    │        └ {}
           │     │    └ (tensor([[769.7549, 338.3597, 831.7670, 370.3329],
           │     │              [769.7441, 338.2330, 831.6693, 370.3158],
           │     │              [769.9012, 338.2...
           │     └ <built-in method nms of PyCapsule object at 0x000001C18F951650>
           └ <OpOverloadPacket(op='torchvision.nms')>

### How to reproduce the bug | 如何复现

Package                 Version
----------------------- ------------------
absl-py                 2.1.0
aiohappyeyeballs        2.4.3
aiohttp                 3.10.10
aiosignal               1.3.1
albucore                0.0.17
albumentations          1.4.18
annotated-types         0.7.0
antlr4-python3-runtime  4.9.3
anyio                   4.6.0
astor                   0.8.1
async-timeout           4.0.3
attrdict                2.0.1
attrs                   24.2.0
babel                   2.16.0
bce-python-sdk          0.9.23
beautifulsoup4          4.12.3
black                   24.10.0
blinker                 1.8.2
boto3                   1.35.38
botocore                1.35.38
braceexpand             0.1.7
Brotli                  1.1.0
cachetools              5.5.0
certifi                 2024.8.30
cffi                    1.17.1
charset-normalizer      3.4.0
click                   8.1.7
cloudpickle             3.0.0
colorama                0.4.6
colorlog                6.8.2
contourpy               1.3.0
cryptography            43.0.1
cssselect               1.2.0
cssutils                2.11.1
cycler                  0.12.1
Cython                  3.0.11
datasets                3.0.1
decorator               5.1.1
detectron2              0.6
dill                    0.3.8
et-xmlfile              1.1.0
eva-decord              0.6.1
eval_type_backport      0.2.0
evaluate                0.4.3
exceptiongroup          1.2.2
fairscale               0.4.13
fast-langdetect         0.2.0
fasttext-wheel          0.9.2
filelock                3.13.1
fire                    0.7.0
Flask                   3.0.3
flask-babel             4.0.0
fonttools               4.54.1
frozenlist              1.4.1
fsspec                  2024.2.0
ftfy                    6.3.0
future                  1.0.0
fvcore                  0.1.5.post20221221
grpcio                  1.66.2
h11                     0.14.0
httpcore                1.0.6
httpx                   0.27.2
huggingface-hub         0.25.2
hydra-core              1.3.2
idna                    3.10
imageio                 2.35.1
imgaug                  0.4.0
intel-openmp            2021.4.0
iopath                  0.1.9
itsdangerous            2.2.0
Jinja2                  3.1.3
jmespath                1.0.1
joblib                  1.4.2
kiwisolver              1.4.7
langdetect              1.0.9
lazy_loader             0.4
lmdb                    1.5.1
loguru                  0.7.2
lxml                    5.3.0
magic-pdf               0.8.1
Markdown                3.7
MarkupSafe              2.1.5
matplotlib              3.9.0
mkl                     2021.4.0
modelscope              1.18.1
more-itertools          10.5.0
mpmath                  1.3.0
multidict               6.1.0
multiprocess            0.70.16
mypy-extensions         1.0.0
networkx                3.2.1
numpy                   1.26.4
omegaconf               2.3.0
opencv-contrib-python   4.6.0.66
opencv-python           4.6.0.66
opencv-python-headless  4.10.0.84
openpyxl                3.1.5
opt-einsum              3.3.0
packaging               24.1
paddleocr               2.7.3
paddlepaddle            2.6.1
paddlepaddle-gpu        2.6.1.post120
pandas                  2.2.3
pathspec                0.12.1
pdf2docx                0.5.8
pdfminer.six            20231228
pillow                  10.4.0
pip                     24.2
platformdirs            4.3.6
portalocker             2.10.1
premailer               3.10.0
propcache               0.2.0
protobuf                3.20.2
psutil                  6.0.0
py-cpuinfo              9.0.0
pyarrow                 17.0.0
pybind11                2.13.6
pyclipper               1.3.0.post5
pycocotools             2.0.8
pycparser               2.22
pycryptodome            3.21.0
pydantic                2.7.4
pydantic_core           2.18.4
PyMuPDF                 1.24.11
pypandoc                1.14
pyparsing               3.1.4
python-dateutil         2.9.0.post0
python-docx             1.1.2
pytz                    2024.2
pywin32                 307
PyYAML                  6.0.2
RapidFuzz               3.10.0
rarfile                 4.2
regex                   2024.9.11
requests                2.32.3
robust-downloader       0.0.2
s3transfer              0.10.3
safetensors             0.4.5
scikit-image            0.24.0
scikit-learn            1.5.2
scipy                   1.14.1
seaborn                 0.13.2
setuptools              75.1.0
shapely                 2.0.6
six                     1.16.0
sniffio                 1.3.1
soupsieve               2.6
struct-eqtable          0.1.0
sympy                   1.12
tabulate                0.9.0
tbb                     2021.13.1
tensorboard             2.18.0
tensorboard-data-server 0.7.2
termcolor               2.5.0
threadpoolctl           3.5.0
tifffile                2024.9.20
timm                    0.9.16
tokenizers              0.19.1
tomli                   2.0.2
torch                   2.3.1+cu121
torchaudio              2.3.1+cu121
torchtext               0.18.0
torchvision             0.18.1
tqdm                    4.66.5
transformers            4.40.0
typing_extensions       4.12.2
tzdata                  2024.2
ultralytics             8.3.9
ultralytics-thop        2.0.9
unimernet               0.1.6
urllib3                 2.2.3
visualdl                2.5.3
Wand                    0.6.13
wcwidth                 0.2.13
webdataset              0.2.100
Werkzeug                3.0.4
wheel                   0.44.0
win32-setctime          1.1.0
wordninja               2.0.0
xxhash                  3.5.0
yacs                    0.1.8
yarl                    1.14.0

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
torch和cuda不兼容，别自己折腾环境了，按官方文档，用conda创建一个3.10的环境，用官方的一键命令安装，依赖会自己处理好的

**Comment by MovePhilip** [comment]
好吧，最后还是折腾成了，cuda12版本的
