### ISSUE TITLE
上传扫描版pdf进行解析时，报错了，RuntimeError:could not execute a primitive....

### ISSUE THREAD

**Issue by Fanxhion** [opendatalab/MinerU#727]
### Description of the bug | 错误描述

2024-10-12 10:23:52.110 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 5, cid_chars_radio: 0.0
2024-10-12 10:23:52.111 | WARNING  | magic_pdf.filter.pdf_classify_by_type:classify:334 - pdf is not classified by area and text_len, by_image_area: False, by_text: False, by_avg_words: False, by_img_num: True, by_text_layout: False, by_img_narrow_strips: True, by_invalid_chars: True
2024-10-12 10:23:53.077 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:170 - layout detection cost: 0.58

0: 1888x1344 (no detections), 256.2ms
Speed: 22.2ms preprocess, 256.2ms inference, 1.0ms postprocess per image at shape (1, 3, 1888, 1344)
2024-10-12 10:23:53.359 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:200 - formula nums: 0, mfr time: 0.0
2024-10-12 10:23:53.676 | ERROR    | __main__:pdf_parse_main:269 - could not execute a primitive
Traceback (most recent call last):

  File "/usr/local/bin/python3.11/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f6590855080>
    └ <Thread(Thread-2 (process_request_thread), started daemon 140020690183936)>
  File "/usr/local/bin/python3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f6590854d60>
    └ <Thread(Thread-2 (process_request_thread), started daemon 140020690183936)>
  File "/usr/local/bin/python3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-2 (process_request_thread), started daemon 140020690183936)>
    │    │        │    └ (<socket.socket fd=4, family=2, type=1, proto=0, laddr=('192.168.1.153', 7861), raddr=('192.1.113.3', 31585)>, ('192.1.113.3'...
    │    │        └ <Thread(Thread-2 (process_request_thread), started daemon 140020690183936)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x7f6444f8fb50>>
    └ <Thread(Thread-2 (process_request_thread), started daemon 140020690183936)>
  File "/usr/local/bin/python3.11/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('192.1.113.3', 31585)
    │    │              └ <socket.socket fd=4, family=2, type=1, proto=0, laddr=('192.168.1.153', 7861), raddr=('192.1.113.3', 31585)>
    │    └ <function BaseServer.finish_request at 0x7f64382f0a40>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7f6444f8fb50>
  File "/usr/local/bin/python3.11/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x7f6444f8fb50>
    │    │                   │        └ ('192.1.113.3', 31585)
    │    │                   └ <socket.socket fd=4, family=2, type=1, proto=0, laddr=('192.168.1.153', 7861), raddr=('192.1.113.3', 31585)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7f6444f8fb50>
  File "/usr/local/bin/python3.11/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f64378460c0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x7f5da066f290>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/local/bin/python3.11/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x7f64382f2de0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x7f5da066f290>
  File "/usr/local/bin/python3.11/lib/python3.11/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x7f5da066f290>>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <Flask 'main'>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7f6444f8fb50>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x7f5da066f290>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x7f5c94431300>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/werkzeug/serving.py", line 331, in execute
    application_iter = app(environ, start_response)
                       │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7f5c94431260>
                       │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=4>, 'wsgi.errors': <_io.TextIOWrap...
                       └ <Flask 'main'>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7f5c94431260>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=4>, 'wsgi.errors': <_io.TextIOWrap...
           │    └ <function Flask.wsgi_app at 0x7f64374d4f40>
           └ <Flask 'main'>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x7f64374d4680>
               └ <Flask 'main'>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x7f64374d45e0>
         └ <Flask 'main'>
  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'pdf_to_md'
           │    │           │    │              └ <Rule '/pdf_to_md' (OPTIONS, POST) -> pdf_to_md>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x7f643a3f9b20>, 'pdf_to_md': <function pdf_to_md at 0x7f64374d6f20>...
           │    │           └ <Flask 'main'>
           │    └ <function Flask.ensure_sync at 0x7f64374d4860>
           └ <Flask 'main'>

  File "/app/MinerU/main.py", line 36, in pdf_to_md
    md_content = pdf_parse_main(pdf_path=data["pdf_path"], output_dir=data['output_dir'], is_resumeTable=data['is_resumeTable'])
                 │                       │                            │                                  └ {'pdf_path': '/app/MinerU/tmp/test_table_in_PDF/PDF包含纯文本和简历类型表格1-520190124_19280782.pdf', 'output_dir': '/app/MinerU/tmp/test...
                 │                       │                            └ {'pdf_path': '/app/MinerU/tmp/test_table_in_PDF/PDF包含纯文本和简历类型表格1-520190124_19280782.pdf', 'output_dir': '/app/MinerU/tmp/test...
                 │                       └ {'pdf_path': '/app/MinerU/tmp/test_table_in_PDF/PDF包含纯文本和简历类型表格1-520190124_19280782.pdf', 'output_dir': '/app/MinerU/tmp/test...
                 └ <function pdf_parse_main at 0x7f64374d7740>

> File "/app/MinerU/main.py", line 241, in pdf_parse_main
    pipe.pipe_analyze()  # 解析
    │    └ <function UNIPipe.pipe_analyze at 0x7f6444feb420>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f63d44a5510>

  File "/app/MinerU/magic_pdf/pipe/UNIPipe.py", line 31, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True)
    │    │            │           │    └ b'%PDF-1.4\n%\xb0\xb8\xba\x95\n3 0 obj\n<</Parent 4 0 R/MediaBox[0 0 595 840]/Contents 5 0 R/Resources 6 0 R/Type/Page>>\nend...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f63d44a5510>
    │    │            └ <function doc_analyze at 0x7f64eb3f2840>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f63d44a5510>

  File "/app/MinerU/magic_pdf/model/doc_analyze_by_custom_model.py", line 119, in doc_analyze
    result = custom_model(img)
             │            └ array([[[255, 255, 255],
             │                      [255, 255, 255],
             │                      [255, 255, 255],
             │                      ...,
             │                      [255, 255, 255],
             │                      [255...
             └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x7f637c3420d0>

  File "/app/MinerU/magic_pdf/model/pdf_extract_kit.py", line 261, in __call__
    ocr_res = self.ocr_model.ocr(new_image, mfd_res=adjusted_mfdetrec_res)[0]
              │    │         │   │                  └ []
              │    │         │   └ array([[[255, 255, 255],
              │    │         │             [255, 255, 255],
              │    │         │             [255, 255, 255],
              │    │         │             ...,
              │    │         │             [255, 255, 255],
              │    │         │             [255...
              │    │         └ <function ModifiedPaddleOCR.ocr at 0x7f5df863f4c0>
              │    └ <magic_pdf.model.pek_sub_modules.self_modify.ModifiedPaddleOCR object at 0x7f5de025aad0>
              └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x7f637c3420d0>

  File "/app/MinerU/magic_pdf/model/pek_sub_modules/self_modify.py", line 209, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls, mfd_res=mfd_res)
                           │    │        │    │            └ []
                           │    │        │    └ True
                           │    │        └ array([[[255, 255, 255],
                           │    │                  [255, 255, 255],
                           │    │                  [255, 255, 255],
                           │    │                  ...,
                           │    │                  [255, 255, 255],
                           │    │                  [255...
                           │    └ <function ModifiedPaddleOCR.__call__ at 0x7f5df863f560>
                           └ <magic_pdf.model.pek_sub_modules.self_modify.ModifiedPaddleOCR object at 0x7f5de025aad0>

  File "/app/MinerU/magic_pdf/model/pek_sub_modules/self_modify.py", line 254, in __call__
    dt_boxes, elapse = self.text_detector(img)
                       │    │             └ array([[[255, 255, 255],
                       │    │                       [255, 255, 255],
                       │    │                       [255, 255, 255],
                       │    │                       ...,
                       │    │                       [255, 255, 255],
                       │    │                       [255...
                       │    └ <tools.infer.predict_det.TextDetector object at 0x7f5d90689610>
                       └ <magic_pdf.model.pek_sub_modules.self_modify.ModifiedPaddleOCR object at 0x7f5de025aad0>

  File "/usr/local/bin/python3.11/lib/python3.11/site-packages/paddleocr/tools/infer/predict_det.py", line 245, in __call__
    self.predictor.run()
    │    │         └ <instancemethod run at 0x7f5ec0320c40>
    │    └ <paddle.base.libpaddle.PaddleInferPredictor object at 0x7f5c94795930>
    └ <tools.infer.predict_det.TextDetector object at 0x7f5d90689610>

RuntimeError: could not execute a primitive

### How to reproduce the bug | 如何复现

附上测试用的pdf文档。[
[PDF包含纯文本和简历类型表格1-520190124_19280782.pdf](https://github.com/user-attachments/files/17348592/PDF.1-520190124_19280782.pdf)
](url)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
这个问题好像只有在linux设备上使用cpu版本的paddle服务化才会遇到，解决方案是在linux上使用服务化的mineru，使用gpu的paddle即可。

**Comment by fz5400** [comment]
> 这个问题好像只有在linux设备上使用cpu版本的paddle服务化才会遇到，解决方案是在linux上使用服务化的mineru，使用gpu的paddle即可。

服务化的mineru是指使用magic-pdf 指令去进行解析而不是用提供的demo代码解析吗？我也遇到了上面的问题。

**Comment by myhloli** [comment]
> > 这个问题好像只有在linux设备上使用cpu版本的paddle服务化才会遇到，解决方案是在linux上使用服务化的mineru，使用gpu的paddle即可。
> 
> 服务化的mineru是指使用magic-pdf 指令去进行解析而不是用提供的demo代码解析吗？我也遇到了上面的问题。

指的是只初始化一次模型，进程处于等待输入pdf的状态，输入的pdf可以直接进行解析而不用再重复初始化模型，pdf文件处理后，进程继续处于等待输入状态而不结束。

**Comment by fz5400** [comment]
``` python
def init_model():
    from magic_pdf.model.doc_analyze_by_custom_model import ModelSingleton
    try:
        model_manager = ModelSingleton()
        txt_model = model_manager.get_model(False, False)
        logger.info(f"txt_model init final")
        ocr_model = model_manager.get_model(True, False)
        logger.info(f"ocr_model init final")
        return 0
    except Exception as e:
        logger.exception(e)
        return -1


model_init = init_model()
logger.info(f"model_init: {model_init}")
```
我是在代码里增加了预加载模型的代码，减少每次加载模型的耗时，结果在进行OCR识别一次后，第二次就报了上面的错误，是因为没有清理内存导致的吗 @myhloli

**Comment by myhloli** [comment]
@fz5400 上面说了，cpu版本paddle的问题，服务化处理时需要使用gpu版本的paddle，cpu版本会报这个错。

**Comment by linguishi** [comment]
flask的问题，换成fastapi就好了

**Comment by cskkx1** [comment]
> flask的问题，换成fastapi就好了

我就是fastapi也报了同样的错

**Comment by cskkx1** [comment]
> [@fz5400](https://github.com/fz5400) 上面说了，cpu版本paddle的问题，服务化处理时需要使用gpu版本的paddle，cpu版本会报这个错。
我有paddlepaddle-3.0.0b1和paddlepaddle-gpu-3.0.0b1,把前者uninstall会报错

**Comment by myhloli** [comment]
@cskkx1 两个都uninstall之后重装paddlepaddle-gpu
