### ISSUE TITLE
公式右侧的序号没有识别

### ISSUE THREAD

**Issue by 1134018901** [opendatalab/MinerU#728]
### Description of the bug | 错误描述

![33333333](https://github.com/user-attachments/assets/e7f0fe9c-362c-47d9-bacb-9cff3e7fecf3)

### How to reproduce the bug | 如何复现

公式右侧的序号没有识别

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
layout模型有识别，但是由于公式序号识别和提取精度问题在后处理流程没有采用这个信息。
