### ISSUE TITLE
zsh: no matches found: magic-pdf[full]

### ISSUE THREAD

**Issue by immmor** [opendatalab/MinerU#729]
### Description of the bug | 错误描述

大佬们，这个命令行不行啊：`pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/`
大家知道咋解决吗？

### How to reproduce the bug | 如何复现

这个命令报错啦

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/master/docs/FAQ_zh_cn.md#1%E5%9C%A8%E8%BE%83%E6%96%B0%E7%89%88%E6%9C%AC%E7%9A%84mac%E4%B8%8A%E4%BD%BF%E7%94%A8%E5%91%BD%E4%BB%A4%E5%AE%89%E8%A3%85pip-install-magic-pdffull-zsh-no-matches-found-magic-pdffull
