### ISSUE TITLE
Is it possible to convert a PDF into a PDF/UA Format?

### ISSUE THREAD

**Issue by Samyssmile** [opendatalab/MinerU#731]
Is it possible to convert a PDF into a PDF/UA Format using this MinerU?

**Comment by myhloli** [comment]
We currently do not support converting PDFs into the PDF/UA format. However, we can provide some of the necessary data for conversion to UA format, such as tagging information for titles, text, and lists within PDF pages; position coordinates and reading order of different paragraphs; textual information corresponding to scanned documents; and caption information for figures or tables.

**Comment by Samyssmile** [comment]
@myhloli Thank you for your response.
Is there any Example fot extraction of that data?

Thank you for your work

**Comment by myhloli** [comment]
> @myhloli Thank you for your response. Is there any Example fot extraction of that data?
> 
> Thank you for your work

Here are some explanations regarding the format parsing of the intermediate state JSON output:

https://github.com/opendatalab/MinerU/blob/master/docs/output_file_en_us.md#some_pdf_middlejson

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
