### ISSUE TITLE
安装 mineru，版本号0.6.1

### ISSUE THREAD

**Issue by fuxuelinwudi** [opendatalab/MinerU#733]
### Description of the bug | 错误描述

pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com -i https://pypi.tuna.tsinghua.edu.cn/simple
magic-pdf --version

output;

0.6.1

### How to reproduce the bug | 如何复现

dasdakjsndalkshdalkshdals
djsaldjasjdaslkdjas
jdalsdjasd

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
需要使用python3.10的虚拟环境安装
