### ISSUE TITLE
python3.10, version 0.8.1

### ISSUE THREAD

**Issue by fuxuelinwudi** [opendatalab/MinerU#734]
### Description of the bug | 错误描述

libGL.so.1: cannot open shared object file: No such file or directory

### How to reproduce the bug | 如何复现

magic-pdf -p small_ocr.pdf -o ./

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
sudo apt-get install libgl1-mesa-glx
