### ISSUE TITLE
一直报错：非法指令 (核心已转储)

### ISSUE THREAD

**Issue by 1134018901** [opendatalab/MinerU#736]
### Description of the bug | 错误描述

![1q1q](https://github.com/user-attachments/assets/f957e0e6-4b33-4845-a96b-17a39aa81676)

### How to reproduce the bug | 如何复现

Ubuntu 22.0这是为啥呢

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
非法指令一般是cpu指令集不兼容，通常是缺少avx或者avx2指令集。

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
