### ISSUE TITLE
公式识别结果会出一长串

### ISSUE THREAD

**Issue by meng0423** [opendatalab/MinerU#738]
### Description of the bug | 错误描述

有些公式识别结果会出现一长串重复字符。

### How to reproduce the bug | 如何复现

识别结果如下：
![image](https://github.com/user-attachments/assets/28ddc3fe-728f-464d-9c85-5350f65d5668)
原书籍截图如下：
![image](https://github.com/user-attachments/assets/0e3d46a2-5e70-4e8f-ace4-09d8efce4701)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
在下个版本升级公式2.0后重复生成的情况会有改善

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by zzk2021** [comment]
这个公式识别mfr的权重更新了你可以看看，我已经改了

**Comment by myhloli** [comment]
已更新0.2版本公司识别模型
