### ISSUE TITLE
2个T4卡，如何设置不同的模型加载在不同的卡上，不是直接使用litserve的方案

### ISSUE THREAD

**Issue by dxjjhm** [opendatalab/MinerU#741]
配置文件中是否可以添加配置，不同的模型使用不同的显卡，进行加速。
目前开启表格识别后，发现表格识别是跑在cpu上的

**Comment by myhloli** [comment]
多个模型是串行执行，单任务分配多卡不能有效加速，如果有多卡可以每个卡分配一个进程并行执行。

**Comment by myhloli** [comment]
表格加速需要安装paddlegpu库，参考readme中ocr加速一节安装

**Comment by dxjjhm** [comment]
需要解决的是单个T4不能把所有的模型都运行起来，有报显存溢出的情况，把不同的模型放到不同的卡上，整体任务还是串行的，所以希望可以在代码层面更灵活的配置显卡与模型的分配。
比如 版面分析、 公式解析、识别、ocr 都放在0卡， 表格识别放在1卡上。

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by myhloli** [comment]
可以等月底发布的新版本，包含表格识别功能在内，单进程显存消耗降至10GB。
单个T4足够开启所有的加速功能。
目前所有的优化操作都是基于单卡实现的，将单任务分配到多卡操作繁琐且收益不高，因此官方推荐多卡环境适合每卡运行一个独立的解析任务，而不是将单个任务的多个步骤分配到多卡运行。

**Comment by sil-let** [comment]
> 模型放到不同的卡上，整体任务还是串行

请问怎么把不同模型放在不同卡上哇
