### ISSUE TITLE
OCR方案替换

### ISSUE THREAD

**Issue by MovePhilip** [opendatalab/MinerU#742]
你们能不能把代码中调用OCR接口暴露出来，方便替换其他的OCR方案

**Comment by xuboot** [comment]
@chinaphilip 这个快不快

**Comment by MovePhilip** [comment]
你自己跑下不就知道了，就paddleOCR嘛，OCR部分速度还行，可以用c++再优化

**Comment by myhloli** [comment]
ocr要配合公式检测的结果，在det阶段把公式mask掉，这个需要接入的ocr模块开源且用户有修改ocr源码的能力，所以不太好开放出来给用户自行修改。

**Comment by MovePhilip** [comment]
我觉得就用空白把公式盖住就行吧，这个接口应该不难写

**Comment by myhloli** [comment]
> 我觉得就用空白把公式盖住就行吧，这个接口应该不难写

试过不行，比较短的行内公式不能有效起到分割作用，det的时候还是一整行，然后公式就插不回去了

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
