### ISSUE TITLE
昨天运行正常，今天报错

### ISSUE THREAD

**Issue by userandpass** [opendatalab/MinerU#748]
### Description of the bug | 错误描述

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   at::_ops::conv2d::call(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::SymInt)
1   at::native::conv2d_symint(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::SymInt)
2   at::_ops::convolution::call(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, bool, c10::ArrayRef<c10::SymInt>, c10::SymInt)
3   at::_ops::convolution::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, bool, c10::ArrayRef<c10::SymInt>, c10::SymInt)
4   at::native::convolution(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long)
5   at::_ops::_convolution::call(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, bool, c10::ArrayRef<c10::SymInt>, c10::SymInt, bool, bool, bool, bool)
6   at::native::_convolution(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, bool, c10::ArrayRef<long>, long, bool, bool, bool, bool)
7   at::_ops::cudnn_convolution::call(at::Tensor const&, at::Tensor const&, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::ArrayRef<c10::SymInt>, c10::SymInt, bool, bool, bool)
8   at::native::cudnn_convolution(at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, bool)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1729068556 (unix time) try "date -d @1729068556" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x20000002eea) received by PID 717693 (TID 0x7f00bb34a740) from PID 12010 ***]

Segmentation fault (core dumped)

### How to reproduce the bug | 如何复现

magic-pdf -p test_2.pdf -o ./

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
昨天到今天有对运行环境做过改动吗，比如新装或者更新pip包

**Comment by userandpass** [comment]
> 昨天到今天有对运行环境做过改动吗，比如新装或者更新pip包

我好像是昨天执行的时候，提示我paddle没有用gpu，我就按照教程又装了paddlepaddle-gpu的包，后面没再测试，今天再用就不行了，但是我刚才尝试只保留paddlepaddle或者paddlepaddle-gpu，都不行，会报ModuleNotFoundError: No module named 'paddle'

**Comment by myhloli** [comment]
应该是系统环境和paddlegpu不兼容，可以先把paddle和paddlegpu都卸了再装paddlepaddle就可以了

**Comment by userandpass** [comment]
> 应该是系统环境和paddlegpu不兼容，可以先把paddle和paddlegpu都卸了再装paddlepaddle就可以了

刚才试了，还是报这个错，我只保留paddle和只保留paddlegpu都试了

**Comment by myhloli** [comment]
那可能是cuda环境被破坏了，可以试着创建一个新的conda环境，重新按教程装一遍

**Comment by userandpass** [comment]
> 那可能是cuda环境被破坏了，可以试着创建一个新的conda环境，重新按教程装一遍

我按照教程重装一遍的话，是不是不能再装paddlegpu了

**Comment by myhloli** [comment]
如果是环境不兼容的话，不推荐安装paddlegpu

**Comment by userandpass** [comment]
> 如果是环境不兼容的话，不推荐安装paddlegpu

好的，谢谢

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
