### ISSUE TITLE
magic-pdf version 0.6.1

### ISSUE THREAD

**Issue by 17Reset** [opendatalab/MinerU#749]
### Description of the bug | 错误描述

The correct version cannot be installed
Ubuntu 24.04.1 LTS
python 3.10.14

### How to reproduce the bug | 如何复现

pyenv shell 3.10.14

uv venv mineru_venv
source mineru_venv/bin/activate

uv pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
We not support Arm Linux, you need use x86_64 platform to use this project.

**Comment by 17Reset** [comment]
测试服务器不是Arm Linux，是 x86_64

**Comment by myhloli** [comment]
试试
pip install https://wheels-1251341229.cos.ap-shanghai.myqcloud.com/assets/whl/detectron2/detectron2-0.6-cp310-cp310-linux_x86_64.whl
先装这个再执行
pip install magic-pdf[full]

**Comment by 17Reset** [comment]
我使用的uv创建虚拟环境来安装就会出问题，直接使用python创建虚拟环境就可以安装最新版

**Comment by myhloli** [comment]
有没有可能你的uv环境里不是python3.10

**Comment by 17Reset** [comment]
我确保就是3.10.14，都同样是使用pyenv创建的python

**Comment by 17Reset** [comment]
使用步骤：
```
pyenv shell 3.10.14

uv venv mineru_venv
source mineru_venv/bin/activate

uv pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com/
```

```
pyenv shell 3.10.14

python -m venv mineru_venv
source mineru_venv/bin/activate

pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com/
```

**Comment by myhloli** [comment]
好吧，我也不是很了解uv的用法，目前还是推荐使用conda或者venv这种传统的方式创建虚拟环境

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
