### ISSUE TITLE
table 解析结果

### ISSUE THREAD

**Issue by xxlxms** [opendatalab/MinerU#750]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**

我看现在的table 解析都是 table tr td 标签这种，为啥不是| 。

**Describe the solution you'd like**
**描述您期望的解决方案**
清晰且简洁地描述您希望实现的内容。

**Describe alternatives you've considered**
**描述您已考虑的替代方案**
清晰且简洁地描述您已经考虑过的任何替代解决方案。

**Additional context**
**提供更多细节**
请附上任何相关截图、链接或文件，以帮助我们更好地理解您的请求。

**Comment by myhloli** [comment]
html格式的表格支持合并单元格操作，markdown原生的表格则不支持，另外markdown中可以直接渲染html表格，所以表格会使用html格式输出

**Comment by wukan1986** [comment]
是否提供一个开关选项呀？想输入到LLM中，markdown表格是不是比HTML表格更好？
