### ISSUE TITLE
pdf解析command疑问

### ISSUE THREAD

**Issue by eileenwsd** [opendatalab/MinerU#752]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/3b69b7e8-407d-40cc-805e-d97736cdf462)
1、我安装的magic-pdf无法直接使用命令-p，只能通过pdf-command来执行，但是结果显示需要输入json文件，但这个命令不是针对pdf文件么？这和我安装的python 3.12.5 版本有关系吗？
2、输出的文件可以指定路径吗？

### How to reproduce the bug | 如何复现

magic-pdf pdf-command --pdf "E:/oss/knovel/pdf/atlas-stre-stainless-steel.pdf" --method auto

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
有关系，你需要使用conda创建3.10的虚拟环境安装最新版本，新版本通过-o 指定输出目录

**Comment by eileenwsd** [comment]
我又重新用conda创建了3.10的虚拟环境，但是我按照pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com -i https://pypi.tuna.tsinghua.edu.cn/simple这条指令安装到的最新版本是0.6.1 最新版本是0.8吗？请问这是因为什么呀？

**Comment by eileenwsd** [comment]
> 有关系，你需要使用conda创建3.10的虚拟环境安装最新版本，新版本通过-o 指定输出目录

我又重新用conda创建了3.10的虚拟环境，但是我按照pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com/ -i [https://pypi.tuna.tsinghua.edu.cn/simple 这条指令安装到的最新版本是0.6.1](https://pypi.tuna.tsinghua.edu.cn/simple%E8%BF%99%E6%9D%A1%E6%8C%87%E4%BB%A4%E5%AE%89%E8%A3%85%E5%88%B0%E7%9A%84%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC%E6%98%AF0.6.1) 最新版本是0.8吗？请问这是因为什么呀？
