### ISSUE TITLE
detectron2 installation failure

### ISSUE THREAD

**Issue by nathanlll8** [opendatalab/MinerU#754]
### Description of the bug | 错误描述

when install detectron2, can not get access to  https://wheels-1251341229.cos.ap-shanghai.myqcloud.com/assets/whl/detectron2/detectron2-0.6-cp310-cp310-linux_x86_64.whl

### How to reproduce the bug | 如何复现

pip install https://wheels-1251341229.cos.ap-shanghai.myqcloud.com/assets/whl/detectron2/detectron2-0.6-cp310-cp310-linux_x86_64.whl

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/aa5e14aa-830f-4336-b730-600f1f909223)

Maybe you can use `wget` or browser  download to your local path.
