### ISSUE TITLE
公式检测是否需要

### ISSUE THREAD

**Issue by 520jefferson** [opendatalab/MinerU#755]
layoutlmv3不是有四个类别的公式标签吗？为何后续还需要用layout v8进行公示进检测，而不是直接识别呢？

- 布局检测：使用`LayoutLMv3`模型进行区域检测，如图像，表格,标题,文本等；
- 公式检测：使用`YOLOv8`进行公式检测，包含行内公式和行间公式；
- 公式识别：使用`UniMERNet`进行公式识别；

**Comment by myhloli** [comment]
参考技术报告中2.2.2 Formula Detection一节
https://arxiv.org/pdf/2409.18839

**Comment by 520jefferson** [comment]
感谢回复，我看标签体系是这样的，10类：https://github.com/opendatalab/MinerU/issues/625#issuecomment-2357344518，10类，

但是早期好像出现过这样的，取自：minerU/PDF-Extract-Kit/pdf_extract.py
            id2names = ["title", "plain_text", "abandon", "figure", "figure_caption", "table", "table_caption", "table_footnote", 
                        "isolate_formula", "formula_caption", " ", " ", " ", "inline_formula", "isolated_formula", "ocr_text"]
                        
 后者包含前者，好像是改过了是吧，只会出现10类？

**Comment by myhloli** [comment]
{0: 'title',              # Title
 1: 'plain text',         # Text
 2: 'abandon',            # Includes headers, footers, page numbers, and page annotations
 3: 'figure',             # Image
 4: 'figure_caption',     # Image caption
 5: 'table',              # Table
 6: 'table_caption',      # Table caption
 7: 'table_footnote',     # Table footnote
 8: 'isolate_formula',    # Display formula (this is a layout display formula, lower priority than 14)
 9: 'formula_caption',    # Display formula label

 13: 'inline_formula',    # Inline formula
 14: 'isolated_formula',  # Display formula
 15: 'ocr_text'}          # OCR result

以这个为准

**Comment by 520jefferson** [comment]
为了节约时间，不求那么精细，我能否将上述的标签中的isolate_formula, isolated_formula， inline_formula直接接上，UniMERNet模型呢？识别出公式，然后转成latex呢？会有什么问题不？

**Comment by myhloli** [comment]
13和14都是yolo的mfd输出的，而且yolo在总耗时中并不高，慢的是mfr

**Comment by 520jefferson** [comment]
不同公式的mfr差异很大吧？行内和行间差异也较多吧，会达到分钟级别吗？另外，复杂的公式识别如何控制时间呢？

**Comment by myhloli** [comment]
行内快行间慢，很复杂的也在秒级而不是分钟级，有token输出上限控制，不会超时特别久

**Comment by 520jefferson** [comment]
我只用了layoutlmv3，那其实不会有13，14，15了， 那layoutlmv3的isolate_formula能否直接接上公式检测+公式识别呢？感觉是可行的，我实验了一下，把layoutlmv3的isolate_formula给到pix2text，有时会超过分钟级别。不知道问题出在哪里了，大部分情况下在s级，有时会达到半分钟，2分钟

**Comment by myhloli** [comment]
慢是因为你没上显卡，我们的性能都是基于使用gpu的

**Comment by 520jefferson** [comment]
也不是，我在mac上，把9: 'formula_caption', # Display formula label，这个给到pix2text，包括（mfd,mfr, text模型），识别结果也在10s内，但是在测试环境（有gpu的情况下）大部分情况下s级，偶尔分钟级

**Comment by myhloli** [comment]
我们没有使用pix2text，有没有可能是pix2text的问题呢

**Comment by 520jefferson** [comment]
只能说有可能，那我能把9: 'formula_caption', # Display formula label的bording box的内容直接给到你们的公式检测UniMERNet不？

**Comment by myhloli** [comment]
9没有必要识别，只是个序号，为什么要识别他呢

**Comment by 520jefferson** [comment]
![image](https://github.com/user-attachments/assets/32cf1aa3-ae12-4565-ab2a-5ef376f4ed22)

9它会画出来一个bording box我把这个bording box部分的内容给到UniMERNet。目的是只识别布局检测识别为公式的这部分

**Comment by myhloli** [comment]
你说的应该是8？9是公式的序号。8对应的是行间公式，行间公式的复杂度对cpu来说是需要分钟级的处理时间的。

**Comment by 520jefferson** [comment]
哦哦，对8，序号从0算

**Comment by myhloli** [comment]
你可以直接使用unimernet识别8，但是需要注意的是8的精度不如14，而且在这里省0.0几秒一页并没有对处理速度带来本质性的提升。

**Comment by 520jefferson** [comment]
> 你可以直接使用unimernet识别8，但是需要注意的是8的精度不如14，而且在这里省0.0几秒一页并没有对处理速度带来本质性的提升。

明白了，感谢，我看看两种方案的实现难度，yolo这部分当初没摘，初步想就看标签的融合难度了，yolo识别到的bording box要从layoutlmv3中排除出来吧？ 比如行内公式yolo里都识别成text，一段text，yolo来了，就切成多段了

**Comment by myhloli** [comment]
行内公式是会切分文本段，你需要把识别到的公式以$$包裹再插入回去

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
