### ISSUE TITLE
行间公式编号识别

### ISSUE THREAD

**Issue by yiyibooks** [opendatalab/MinerU#756]
Dear developers,

MinerU 会在什么时候支持输出"识别行间公式编号"？

layout 模型能识别出行间公式编号的 block ，但是 MinerU 的输出不会带公式编号。请问将公式编号丢弃的代码在哪个文件的哪个函数里？我们试试能不能把公式编号加回来 ~

**Comment by yiyibooks** [comment]
Resoved

**Comment by Widlar** [comment]
What was the solution to this?

**Comment by beetter** [comment]
> 已解决

你好，能分享一下您的解决方案吗？
