### ISSUE TITLE
使用体验

### ISSUE THREAD

**Issue by liepinlxy** [opendatalab/MinerU#759]
我们尝试了大概50份文件，发现了一些存在的现象：
1、存在信息内容粘连情况。换行、空格等识别效果不太好
2、复杂结构容易出现内容错乱情况，比如左右结构的文档，比如：
文件内容：
![image](https://github.com/user-attachments/assets/57113364-a605-43ab-989f-d27bf451193b)
识别后模块：
![image](https://github.com/user-attachments/assets/04d5b86d-68d3-4196-b1c1-2d54f9f4a716)
3、个别字符前后会加上$符号，比如：
文件内容：
![image](https://github.com/user-attachments/assets/21b4af29-cbfb-4c33-92a2-5324e595ac6e)
识别后内容：
![image](https://github.com/user-attachments/assets/eea3e033-a55b-4856-bad0-655f7d7ecc2e)

问题1、2，我看文档应该是属于TODO部分-》【 基于语义的阅读顺序】，麻烦问下这个TODO预计什么时候解决呢？
类似问题3应该怎么处理？

**Comment by myhloli** [comment]
1、2的问题可以在modelscope的demo上测试下新版的效果，相对老版本会有一定改善
3的问题是默认开启了公式识别功能，后续会增加开关，在不需要公式识别的文档上可以单独关闭公式识别功能

**Comment by liepinlxy** [comment]
我测试了下，效果确实好了一些，现在是还没发版么？

**Comment by myhloli** [comment]
对，现在还在开发中，只在demo上开放测试

**Comment by liepinlxy** [comment]
麻烦问下，预计什么时候发版

**Comment by myhloli** [comment]
10月底

**Comment by liepinlxy** [comment]
10月底这一版会增加公式识别的开关么？

**Comment by liepinlxy** [comment]
demo发现了个新的问题，这个结构的数据会被丢弃
![image](https://github.com/user-attachments/assets/c673fc92-9c7f-42af-9b02-2919504bf714)
![image](https://github.com/user-attachments/assets/00e30015-a73a-481d-aa5e-74db4d1e9c40)

**Comment by liepinlxy** [comment]
demo发现个新的问题，这个结构上面的数据会被丢弃
![image](https://github.com/user-attachments/assets/09cb9191-e06e-4a83-9a1b-b02c3d25b88f)
![image](https://github.com/user-attachments/assets/464865f6-328c-443d-bc45-8285f82e5cfe)

**Comment by liepinlxy** [comment]
demo发现了个新的问题，这个结构上面的数据会被丢弃
![image](https://github.com/user-attachments/assets/cca58aa0-c8a0-4996-8903-265a3eb92ae2)
![image](https://github.com/user-attachments/assets/db562bb3-ea3c-4168-8ab8-aa412139ebaf)

**Comment by myhloli** [comment]
现在的训练数据没有见过这种类型的文档，这种上下边界较近的块会被当成header和footer丢掉

**Comment by liepinlxy** [comment]
类似这种结构的后续可以支持么？

**Comment by myhloli** [comment]
我们应该没有类似简历这种类型的数据来训练，不知道能否提供一批脱敏的文档给我们微调呢？

**Comment by liepinlxy** [comment]
我这里也不太多，目前只有这两份，我看看能不能把这份简历转成docx，然后提供这两种简历类型的docx模板给你们

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by myhloli** [comment]
我们集成了新的版面分析模型doclayout_yolo，在丢弃文本块方面有一些改善，目前已经同步该功能到huggingface和modelscope的demo了，可以自行在线测试效果。
