### ISSUE TITLE
Will support DocLayout-YOLO_ft? Like PDF-Extract Kit

### ISSUE THREAD

**Issue by Schumpeterx** [opendatalab/MinerU#761]

**Comment by myhloli** [comment]
We'll need some time to adapt, which will be updated in the future.

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by myhloli** [comment]
We have integrated doclayout_yolo, you can test it on hugging face demo or modelscope demo.
Also you can local deployment with next MinerU release version, it will at end of this month.
