### ISSUE TITLE
使用StructEqTable解析表格很慢

### ISSUE THREAD

**Issue by Schumpeterx** [opendatalab/MinerU#762]
StructEqTable解析一张表最慢要30S。最快大概7秒。请问有没有办法加速一下？
4090GPU

**Comment by syfzju** [comment]
同，ocr挺快的，表格解析很慢

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by PrinceVictor** [comment]
@Schumpeterx  @syfzju 

[StructEqTable](https://github.com/UniModal4Reasoning/StructEqTable-Deploy) has recently released a new version, adopting the InternVl2-1B as base model. It supports multiple output formats and can be accelerated using LMDeploy. You can pull the latest code for testing.

**Comment by myhloli** [comment]
新版本StructEqTable在解析速度上有较大优化，可以更新0.9.1进行尝试
