### ISSUE TITLE
请问大佬们如何识别小语种的文档，例如泰语、阿拉伯语等，是从哪个地方下载语言包吗

### ISSUE THREAD

**Issue by 040211** [opendatalab/MinerU#763]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
对存在的问题进行清晰且简洁的描述。例如：我一直很困扰的是 [...]

**Describe the solution you'd like**
**描述您期望的解决方案**
清晰且简洁地描述您希望实现的内容。

**Describe alternatives you've considered**
**描述您已考虑的替代方案**
清晰且简洁地描述您已经考虑过的任何替代解决方案。

**Additional context**
**提供更多细节**
请附上任何相关截图、链接或文件，以帮助我们更好地理解您的请求。

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by myhloli** [comment]
在下个版本会通过--lang参数支持小语种ocr，目前小语种识别功能已同步到huggingface和modelscope的demo中，可以自行在线测试。
