### ISSUE TITLE
丢失部分内容

### ISSUE THREAD

**Issue by guoguo0646** [opendatalab/MinerU#764]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/d6e103a5-e94b-4dac-9df6-2f59351f2fbc)

文章中的“中国分类号： TJ760；E87”在检测识别时被丢失掉了

### How to reproduce the bug | 如何复现

解析环境https://www.modelscope.cn/studios/OpenDataLab/MinerU，解析文档请见附件，
[分布式空中作战概念分析.pdf](https://github.com/user-attachments/files/17457460/default.pdf)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by myhloli** [comment]
可以尝试切换不同的layout检测模型，除之前的layoutlmv3模型外，mineru目前已接入我们自研的doclayout_yolo版面分析模型，该样本在新模型下识别效果良好。
![image](https://github.com/user-attachments/assets/e69bf53a-a4c8-40cb-9022-c5ee3fdb6010)
