### ISSUE TITLE
magic-pdf, version 0.6.1

### ISSUE THREAD

**Issue by lyc728** [opendatalab/MinerU#771]
magic-pdf, version 0.6.1
运行脚本python demo/magic_pdf_parse_main.py 
2024-10-23 14:06:29.396 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 3, text_len: 32914, cid_chars_radio: 9.119649805447471e-05
2024-10-23 14:06:30.906 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:24 - Required dependency not installed, please install by 
"pip install magic-pdf[full-cpu] detectron2 --extra-index-url https://myhloli.github.io/wheels/"如何解决  cuda12.2 torch 2.5.0

**Comment by myhloli** [comment]
按教程用conda创建python3.10的环境再装，目前正常安装应该是0.8.1的版本

**Comment by lyc728** [comment]
运行demo下的magic_pdf_parse_main.py 走的默认配置json为/root/magic-pdf.json  如何修改为自己目录呢

**Comment by myhloli** [comment]
你用root用户运行就是读取的root目录下的配置文件，这个是自动读取用户目录的，看你登录的用户是什么

**Comment by lyc728** [comment]
不能把这个放到某个路径下 自己去配置吗

**Comment by myhloli** [comment]
后续有计划通过环境变量传递配置文件的路径，目前还没有支持

**Comment by lyc728** [comment]
那能麻烦告知下 现在这个root/magic-pdf.json 是在哪个代码下传进去的呢？

**Comment by lyc728** [comment]
找到了

**Comment by lyc728** [comment]
这边加入表格识别后，直接就乱生成了
<img width="607" alt="企业微信截图_17296733857303" src="https://github.com/user-attachments/assets/56d9da31-f0de-4cf8-8fe3-fdf169933143">

**Comment by myhloli** [comment]
表格识别是测试版本，目前对于复杂表格效果较差属于已知问题。

**Comment by lyc728** [comment]
你好 这个json下有两个模型目录 ，请问 "layoutreader-model-dir": "/data/MinerU/layoutreader",这个模型是干什么的呢？同时这个"models-dir": "/data/MinerU/models",下面还有layloutlmv3 这两个模型有什么差异吗？对了opendatalab/PDF-Extract-Kit-1.0这个模型已经更新了 这边代码是没有更新适配吗？

**Comment by myhloli** [comment]
layoutreader-model-dir用于在下个版本提供段落排序
opendatalab/PDF-Extract-Kit-1.0已经在开发接入测试了，预计在mineru的下个版本同步更新

**Comment by lyc728** [comment]
意思是现在这个模型其实并没有使用上是吧

**Comment by myhloli** [comment]
0.8.1没用上

**Comment by lyc728** [comment]
发现结果中没有pdf进行保存，some_pdf_layout.pdf ，这个是测试的时候生效的？

**Comment by myhloli** [comment]
使用命令行的时候会保存

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
