### ISSUE TITLE
布局检测和公式检测放在一块卡上会干扰，如何降低干扰

### ISSUE THREAD

**Issue by 520jefferson** [opendatalab/MinerU#772]
布局检测文件如下，用官方默认的：[layoutlmv3_base_inference.txt](https://github.com/user-attachments/files/17487509/layoutlmv3_base_inference.txt)

如何降低布局检测gpu的使用率呢？比如batch我该调整哪个调小会有用
（但好像一篇文档进来也不需要batch吧,我是这样拿结果的：
    single_page_res = layout_model(np.array(image)[:,:,::-1], ignore_catids=[])['layout_dets']）
    
或者改什么配置合适？能降低gpu使用率

比如我通过：
1，限制memory（memory远远没超过，32g的 v100)
torch.cuda.set_per_process_memory_fraction(0.5, device=0)  # 对于第一个GPU

2, 限制（主要是它吧），但是我推理时输入的文档只有一个吧，这个设置也没啥用吧？
cfg.SOLVER.IMS_PER_BATCH = 1  # 设置每次处理的图像数量为1

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by myhloli** [comment]
干扰的意思是？
