### ISSUE TITLE
是否测试过用ARM架构cpu机器上的GPU来跑MinerU

### ISSUE THREAD

**Issue by zkitcast** [opendatalab/MinerU#780]
请问是否测试过用ARM架构cpu机器上的GPU来跑MinerU

**Comment by myhloli** [comment]
因为很多依赖包没有arm的预编译包，所以目前不支持在arm服务器上部署

**Comment by zkitcast** [comment]
> 因为很多依赖包没有arm的预编译包，所以目前不支持在arm服务器上部署
文档不是说macos的arm能支持么
![image](https://github.com/user-attachments/assets/f9afa947-086d-407c-a894-fe00a7ab8836)

**Comment by myhloli** [comment]
mac的arm生态比其他平台更强，所以仅在mac支持arm，但是Linux和windows都不支持arm。另外在mac上也没有显卡加速，只有纯cpu模式。
