### ISSUE TITLE
使用CPU离线环境运行程序，运行带有图片的pdf会自动下载ch_PP-OCRv4_det_infer.tar

### ISSUE THREAD

**Issue by qushencn** [opendatalab/MinerU#781]
### Description of the bug | 错误描述

使用CPU离线环境运行程序，运行带有图片的pdf会自动下载ch_PP-OCRv4_det_infer.tar，但是模型里面是使用CPU离线环境运行程序，运行带有图片的pdf会自动下载ch_PP-OCRv3_det_infer。没有网络下载不下来，手动下载ch_PP-OCRv4_det_infer放model下不生效。

### How to reproduce the bug | 如何复现

直接运行命令即可

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
https://huggingface.co/spaces/opendatalab/MinerU/tree/main/paddleocr
下载这个目录到本地，然后执行
```
cp -r paddleocr ~/.paddleocr
```

**Comment by OliverLiy** [comment]
> https://huggingface.co/spaces/opendatalab/MinerU/tree/main/paddleocr 下载这个目录到本地，然后执行
> 
> ```
> cp -r paddleocr ~/.paddleocr
> ```

1.2.2 遇到了同样的问题，但是上面这个路径已经不存在了，应该如何解决？ @myhloli

**Comment by myhloli** [comment]
> > https://huggingface.co/spaces/opendatalab/MinerU/tree/main/paddleocr 下载这个目录到本地，然后执行
> > ```
> > cp -r paddleocr ~/.paddleocr
> > ```
> 
> 1.2.2 遇到了同样的问题，但是上面这个路径已经不存在了，应该如何解决？ [@myhloli](https://github.com/myhloli)

目录存在的，需要开梯子

**Comment by OliverLiy** [comment]
> > > https://huggingface.co/spaces/opendatalab/MinerU/tree/main/paddleocr 下载这个目录到本地，然后执行
> > > ```
> > > cp -r paddleocr ~/.paddleocr
> > > ```
> > 
> > 
> > 1.2.2 遇到了同样的问题，但是上面这个路径已经不存在了，应该如何解决？ [@myhloli](https://github.com/myhloli)
> 
> 目录存在的，需要开梯子

解决了，多谢 @myhloli

**Comment by hongbo-miao** [comment]
多谢，一点修正 ☺️
正确的是

```sh
cp -r paddleocr/* ~/.paddleocr
```

**Comment by niuteng5618** [comment]
目录不存在了
