### ISSUE TITLE
MinerU这套代码支持训练自己的数据集吗？

### ISSUE THREAD

**Issue by scq6688** [opendatalab/MinerU#790]
您好，MinerU这套代码支持训练自己的数据集吗？何时支持识别图像中的文字？

**Comment by drunkpig** [comment]
训练相关请参考 PDF-Extract-Kit  https://github.com/opendatalab/PDF-Extract-Kit

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
