### ISSUE TITLE
A problem of code reuse of `magic_pdf_parse_main.py` on model `PDF-Extract-Kit-1.0`

### ISSUE THREAD

**Issue by bwnjnOEI** [opendatalab/MinerU#812]
### Description of the bug | 错误描述

![2024-10-30_04-10](https://github.com/user-attachments/assets/91c036db-c93e-4a02-a806-6f485658824b)

### How to reproduce the bug | 如何复现

Some model names differ from the default names used in demo codes, such as model in `MFD`, which changes from `weights.pt` to `YOLO/yolo_v8_ft.pt ` after version 1.0. Can the model name be updated as soon as possible or can the demo code be updated?

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
We have updated and adapted PDF-Extract-Kit 1.0, and we are about to release a new version of MinerU. The development has been completed and it is currently in the QA phase. Please be patient.

**Comment by anglewhite11** [comment]
I  have the same bug, and I tried to change the "mfd_model": "yolo_v8_ft" in the file “magic-pdf.json”, but still got the same bug.   
![屏幕截图_4-11-2024_103838_www kaggle com](https://github.com/user-attachments/assets/51fae73a-edaf-429c-9d07-794842174b9d)

Operating system | 操作系统
Linux

Python version | Python 版本
3.10.14

Software version | 软件版本 (magic-pdf --version)
0.8.1

Device mode | 设备模式
cuda

**Comment by myhloli** [comment]
> I have the same bug, and I tried to change the "mfd_model": "yolo_v8_ft" in the file “magic-pdf.json”, but still got the same bug. ![屏幕截图_4-11-2024_103838_www kaggle com](https://private-user-images.githubusercontent.com/138179453/382626746-51fae73a-edaf-429c-9d07-794842174b9d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2ODg0MDQsIm5iZiI6MTczMDY4ODEwNCwicGF0aCI6Ii8xMzgxNzk0NTMvMzgyNjI2NzQ2LTUxZmFlNzNhLWVkYWYtNDI5Yy05ZDA3LTc5NDg0MjE3NGI5ZC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMDI0MTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY4ZGVlYzA4YzZkMzliYzY3MDVhMTNlZTg1YjA1ODVhMWY0NzRmMDQ3NjhlNjQ0YWI1YjIxMTFlYTE2NTk0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VxQvHSoO54ih6q4Inz56CKLtOOzqNQFLnL5N3Sf1qSM)
> 
> Operating system | 操作系统 Linux
> 
> Python version | Python 版本 3.10.14
> 
> Software version | 软件版本 (magic-pdf --version) 0.8.1
> 
> Device mode | 设备模式 cuda

You need update magic-pdf to 0.9.0 to support PDF-Extract-Kit 1.0.

**Comment by anglewhite11** [comment]
> > I have the same bug, and I tried to change the "mfd_model": "yolo_v8_ft" in the file “magic-pdf.json”, but still got the same bug. ![屏幕截图_4-11-2024_103838_www kaggle com](https://private-user-images.githubusercontent.com/138179453/382626746-51fae73a-edaf-429c-9d07-794842174b9d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2ODg0MDQsIm5iZiI6MTczMDY4ODEwNCwicGF0aCI6Ii8xMzgxNzk0NTMvMzgyNjI2NzQ2LTUxZmFlNzNhLWVkYWYtNDI5Yy05ZDA3LTc5NDg0MjE3NGI5ZC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMDI0MTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY4ZGVlYzA4YzZkMzliYzY3MDVhMTNlZTg1YjA1ODVhMWY0NzRmMDQ3NjhlNjQ0YWI1YjIxMTFlYTE2NTk0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VxQvHSoO54ih6q4Inz56CKLtOOzqNQFLnL5N3Sf1qSM)
> > Operating system | 操作系统 Linux
> > Python version | Python 版本 3.10.14
> > Software version | 软件版本 (magic-pdf --version) 0.8.1
> > Device mode | 设备模式 cuda
> 
> You need update magic-pdf to 0.9.0 to support PDF-Extract-Kit 1.0.

please tell me how install magic-pdf to 0.9.0 or update , I followed the web(https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_en_US.md) to install magic-pdf but still got the version-0.8.1

**Comment by myhloli** [comment]
> > > I have the same bug, and I tried to change the "mfd_model": "yolo_v8_ft" in the file “magic-pdf.json”, but still got the same bug. ![屏幕截图_4-11-2024_103838_www kaggle com](https://private-user-images.githubusercontent.com/138179453/382626746-51fae73a-edaf-429c-9d07-794842174b9d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2ODg0MDQsIm5iZiI6MTczMDY4ODEwNCwicGF0aCI6Ii8xMzgxNzk0NTMvMzgyNjI2NzQ2LTUxZmFlNzNhLWVkYWYtNDI5Yy05ZDA3LTc5NDg0MjE3NGI5ZC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMDI0MTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY4ZGVlYzA4YzZkMzliYzY3MDVhMTNlZTg1YjA1ODVhMWY0NzRmMDQ3NjhlNjQ0YWI1YjIxMTFlYTE2NTk0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VxQvHSoO54ih6q4Inz56CKLtOOzqNQFLnL5N3Sf1qSM)
> > > Operating system | 操作系统 Linux
> > > Python version | Python 版本 3.10.14
> > > Software version | 软件版本 (magic-pdf --version) 0.8.1
> > > Device mode | 设备模式 cuda
> > 
> > 
> > You need update magic-pdf to 0.9.0 to support PDF-Extract-Kit 1.0.
> 
> please tell me how install magic-pdf to 0.9.0 or update , I followed the web(https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_en_US.md) to install magic-pdf but still got the version-0.8.1

pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com

**Comment by anglewhite11** [comment]
> > > > 我有同样的错误，我尝试更改文件“magic-pdf.json”中的“mfd_model”：“yolo_v8_ft”，但仍然得到相同的错误。![屏幕截图_4-11-2024_103838_www kaggle com](https://private-user-images.githubusercontent.com/138179453/382626746-51fae73a-edaf-429c-9d07-794842174b9d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2ODg0MDQsIm5iZiI6MTczMDY4ODEwNCwicGF0aCI6Ii8xMzgxNzk0NTMvMzgyNjI2NzQ2LTUxZmFlNzNhLWVkYWYtNDI5Yy05ZDA3LTc5NDg0MjE3NGI5ZC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMDI0MTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY4ZGVlYzA4YzZkMzliYzY3MDVhMTNlZTg1YjA1ODVhMWY0NzRmMDQ3NjhlNjQ0YWI1YjIxMTFlYTE2NTk0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VxQvHSoO54ih6q4Inz56CKLtOOzqNQFLnL5N3Sf1qSM)操作系统 |操作系统 Linux Python 版本 |Python 版本 3.10.14 软件版本 |软件版本 （magic-pdf --version） 0.8.1 设备模式 |设备模式 cuda
> > > 
> > > 
> > > 您需要将 magic-pdf 更新到 0.9.0 以支持 PDF-Extract-Kit 1.0。
> > 
> > 
> > 请告诉我如何将 magic-pdf 安装到 0.9.0 或更新，我按照 web（https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_en_US.md） 安装了 magic-pdf，但仍然得到了 0.8.1 版本
> 
> pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com

Thanks, it's working now! My mistake,I forgot to change the installation command in the previous notebook.
