### ISSUE TITLE
pdf识别不准

### ISSUE THREAD

**Issue by reneliury** [opendatalab/MinerU#813]
### Description of the bug | 错误描述

用的auto和txt模式，都发现有两个问题：
1.pdf解析后缺少文字，或错字
2.文章标题识别不准，有的章节能识别成标题，有的不被识别成标题。
请问有什么解决办法

### **1.pdf解析后缺少文字**
解析后缺少"3.1 算法标识"这几个字，这种缺字情况还不少
**原文：**
![image](https://github.com/user-attachments/assets/80dddd59-17e1-4081-87ed-24ed45968e50)

**解析后.md文件：**
![image](https://github.com/user-attachments/assets/a4e1e584-7c07-4fe1-b1a8-023624247adb)

### **2.文章标题识别不准，有的章节能识别成标题有的不被识别成标题。**
其中3.9节还识别错了，识别成3.y了
**原文：**
![image](https://github.com/user-attachments/assets/b5b9be1b-df18-4e70-ad1a-180ae647c752)

**解析后.md文件**
![image](https://github.com/user-attachments/assets/54aa4080-5ca6-4814-bbc8-1c8258cf32de)

**以下是mineru生成结果以及原文**
[信息安全技术密码设备应用接口规范.zip](https://github.com/user-attachments/files/17552628/default.zip)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
1.缺少文字的问题在新版本上验证已修复，可通过huggingface的demo进行验证
https://huggingface.co/spaces/opendatalab/MinerU
![image](https://github.com/user-attachments/assets/ba3647e4-a8b3-40a9-8ffb-e69ccbc35f80)

2.标题识别不准属于模型问题，可以在https://github.com/opendatalab/PDF-Extract-Kit的issue反馈

**Comment by reneliury** [comment]
> 1.缺少文字的问题在新版本上验证已修复，可通过huggingface的demo进行验证 https://huggingface.co/spaces/opendatalab/MinerU ![image](https://private-user-images.githubusercontent.com/11393164/381369528-ba3647e4-a8b3-40a9-8ffb-e69ccbc35f80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjA4NjMsIm5iZiI6MTczMDI2MDU2MywicGF0aCI6Ii8xMTM5MzE2NC8zODEzNjk1MjgtYmEzNjQ3ZTQtYThiMy00MGE5LThmZmItZTY5Y2NiYzM1ZjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAzNTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNWEzNzM2OWEzNWM5OGZhMmJjODJmMDI3NDQ0YjU1NTIzMTNlZmUxOTE4ZTQzOTA0M2I5NmU1OTY2YTgxY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4RzOrYkmxUx5HTswfpMqfokse1143xpU-kMIuF_m-8k)
> 
> 2.标题识别不准属于模型问题，可以在[https://github.com/opendatalab/PDF-Extract-Kit的issue反馈](https://github.com/opendatalab/PDF-Extract-Kit%E7%9A%84issue%E5%8F%8D%E9%A6%88)

请问修复的新版本什么时候会发布pip包呢？或者是否已经merge到git master源码，我重新安装即可

**Comment by myhloli** [comment]
最近就会发pip包出来，新版本有一些不兼容更新，所以直接覆盖安装是不可使用的，需要等测试完成后推送到master分支再运行更新脚本
