### ISSUE TITLE
Installation guide on Latest Ubuntu.

### ISSUE THREAD

**Issue by csv610** [opendatalab/MinerU#814]
### Description of the bug | 错误描述

Hello,
Struggling with installation on the latest Ubuntu ( with Nvidia GPU). Was anyone successful in making it work? Any help/suggestion will be very useful.

Thanks

### How to reproduce the bug | 如何复现

it__.py'>
  File "/media/csverma/M2Disk/Projects/PDFTools/pdfenv/lib/python3.12/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
    │      │    └ '/media/csverma/M2Disk/Projects/PDFTools/pdfenv/lib/python3.12/site-packages/torchtext/lib/libtorchtext.so'
    │      └ <class 'ctypes.CDLL'>
    └ <module 'ctypes' from '/home/linuxbrew/.linuxbrew/opt/python@3.12/lib/python3.12/ctypes/__init__.py'>
  File "/home/linuxbrew/.linuxbrew/opt/python@3.12/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
    │    │         │       │    │      └ 0
    │    │         │       │    └ '/media/csverma/M2Disk/Projects/PDFTools/pdfenv/lib/python3.12/site-packages/torchtext/lib/libtorchtext.so'
    │    │         │       └ <CDLL '/media/csverma/M2Disk/Projects/PDFTools/pdfenv/lib/python3.12/site-packages/torchtext/lib/libtorchtext.so', handle 0 a...
    │    │         └ <built-in function dlopen>
    │    └ 0
    └ <CDLL '/media/csverma/M2Disk/Projects/PDFTools/pdfenv/lib/python3.12/site-packages/torchtext/lib/libtorchtext.so', handle 0 a...

OSError: /media/csverma/M2Disk/Projects/PDFTools/pdfenv/lib/python3.12/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
We don't support python 3.12，you must use conda create a python 3.10 env.
