### ISSUE TITLE
电脑配置 Intel(R) Core(TM) i5-1145G7 @ 2.60GHz   1.50 GHz，内存16，无显卡，情况下解析一份286页的pdf 得两个小时以上，有没有办法优化一下？

### ISSUE THREAD

**Issue by myt-myt** [opendatalab/MinerU#816]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
对存在的问题进行清晰且简洁的描述。例如：我一直很困扰的是 [...]

**Describe the solution you'd like**
**描述您期望的解决方案**
清晰且简洁地描述您希望实现的内容。

**Describe alternatives you've considered**
**描述您已考虑的替代方案**
清晰且简洁地描述您已经考虑过的任何替代解决方案。

**Additional context**
**提供更多细节**
请附上任何相关截图、链接或文件，以帮助我们更好地理解您的请求。

**Comment by myhloli** [comment]
项目使用了比较多的视觉模型，对低配cpu并不友好，如果有长期大量数据处理的需求，请为设备添加gpu或使用云gpu进行加速。
