### ISSUE TITLE
Option to extract plain text only, ignoring images, etc.

### ISSUE THREAD

**Issue by WoodAsh2501** [opendatalab/MinerU#822]
Sometimes, it's necessary to extract only the plain text from a PDF, excluding images, formulas, and tables. Ignoring those may also make processing faster. I didn't find the option in CLI, can I do this by edit scripts?

有时只需要从pdf中提取纯文本，而忽略掉图片、公式和表格，这样处理起来或许也更快一些。我没有在命令行里看到这个选项，请问我可以通过改脚本实现这一点吗？

**Comment by myhloli** [comment]
We support disable formula and table recognition in next version, it will be release recently.
You can refer to this instruction for the function of switching.
https://github.com/opendatalab/MinerU/tree/dev#3-modify-the-configuration-file-for-additional-configuration

Layout parsing is mandatory and cannot be turned off.
If you don't need images or table output , you can add a parameter `md_make_mode="nlp_markdown"` at make markdown function 
https://github.com/myhloli/Magic-PDF/blob/76031a6d48f83a27f2d6518f5b04f76df35b038c/demo/magic_pdf_parse_main.py#L126
