### ISSUE TITLE
why pytorch is always be downloaded? i need pyroch 2.4 it defacult install 2.3.1

### ISSUE THREAD

**Issue by cqray1990** [opendatalab/MinerU#823]
### Description of the bug | 错误描述

why pytorch is always be downloaded? i need pyroch 2.4 it defacult install 2.3.1

### How to reproduce the bug | 如何复现

why pytorch is always be downloaded? i need pyroch 2.4 it defacult install 2.3.1

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
The highest version we support is torch 2.3.1, so when your environment is on version 2.4, you will need to downgrade to 2.3.1.
