### ISSUE TITLE
model.to(device).eval() 模型加载cuda问题

### ISSUE THREAD

**Issue by lyc728** [opendatalab/MinerU#832]
magic_pdf/pdf_parse_union_core_v2.py
我把表格识别打开 可以正常推理 关闭也能正常加载初始化
但是我把表格组件换成其它的以后 这里初始化就有问题
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by myhloli** [comment]
0.9.0版本只适配了tablemaster，暂不支持更换表格模型

**Comment by lyc728** [comment]
> 0.9.0版本只适配了tablemaster，暂不支持更换表格模型

我是自己改的组件 model.to(device)这个是顺序模型和表格模型没有关联吧

**Comment by myhloli** [comment]
没看懂这句
> 但是我把表格组件换成其它的以后 这里初始化就有问题

**Comment by lyc728** [comment]
我自己有一个表格识别模型，换成这个后推理也能正常返回 但是程序走到magic_pdf/pdf_parse_union_core_v2.py model.to(device).eval() 就会报上面的错

**Comment by myhloli** [comment]
> 我自己有一个表格识别模型，换成这个后推理也能正常返回 但是程序走到magic_pdf/pdf_parse_union_core_v2.py model.to(device).eval() 就会报上面的错

能把代码贴上来看看吗？

**Comment by lyc728** [comment]
我是觉得不应该 我表格的结果都拿到了 然而到排序模型这里报错
