### ISSUE TITLE
安装Master，显示版本号为0.6.1

### ISSUE THREAD

**Issue by wenxinmomo** [opendatalab/MinerU#836]
### Description of the bug | 错误描述

系统 ubuntu
架构 aarch
完全根据Master文档操作，但安装的是0.6.1版本，也用的conda3.10环境

### How to reproduce the bug | 如何复现

系统 ubuntu
架构 aarch
完全根据Master文档操作，但安装的是0.6.1版本，也用的conda3.10环境

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
有些依赖包不支持arm架构，因此无法正常安装使用本项目。

**Comment by wenxinmomo** [comment]
您了解支持的arm最高版本是多少吗

**Comment by wenxinmomo** [comment]
请问有支持华为Atlas NPU的计划嘛

**Comment by myhloli** [comment]
很抱歉，我们的任何版本都没有适配arm（macOS除外）。

**Comment by myhloli** [comment]
> 请问有支持华为Atlas NPU的计划嘛

最近有跟华为的生态同事做对接，可能未来能适配华为的鲲鹏服务器或加速卡，但是具体适配方式与时间节点未知。

**Comment by wenxinmomo** [comment]
好的，感谢

**Comment by wenxinmomo** [comment]
<img width="805" alt="报错" src="https://github.com/user-attachments/assets/ae0a467d-48cf-4abb-90e4-fd75ac933918">
再咨询下，这个错误在arm上是正常的嘛，是因为没有没有匹配arm结构的依赖吗

**Comment by myhloli** [comment]
正常的，armlinux缺少一些需要预编译的依赖包，是无法运行的

**Comment by wenxinmomo** [comment]
👌👌谢谢
