### ISSUE TITLE
OCR结果返回问题

### ISSUE THREAD

**Issue by lyc728** [opendatalab/MinerU#837]
1、首先代码将布局检测后的图送入ocr，进行文本识别，我觉得重复进行调用太耗时，这里我将整张图送入ocr模型进行识别，然后将结果同布局检测后的坐标进行反匹配，这个时候有的布局检测效果不理想 我将检测后的坐标进行上下扩张，使得ocr结果更好，但是最后我发现会丢失某些ocr框的结果

**Comment by myhloli** [comment]
这就是为什么要先将block切块之后再做ocr的原因。

**Comment by lyc728** [comment]
那有的检测不到 不就没了

**Comment by myhloli** [comment]
layout检测是第一步，后续的所有流程都要信任layout返回的结果，这是基础。

**Comment by lyc728** [comment]
好的 那就只能优化layout了
