### ISSUE TITLE
`PDF-Extract-Kit-1.0`版本中`mfr_model`使用`unimernet_base`或`UniMERNet`模型会报错，`unimernet_small`则正常

### ISSUE THREAD

**Issue by bwnjnOEI** [opendatalab/MinerU#848]
### Description of the bug | 错误描述

![2024-11-03_14-23](https://github.com/user-attachments/assets/630c102b-8681-4dcd-b28c-58bc245ec905)

```bash
{
    // other config
    "layout-config": {
        "model": "layoutlmv3" // Please change to "doclayout_yolo" when using doclayout_yolo.
    },
    "formula-config": {
        "mfd_model": "yolo_v8_mfd",
        "mfr_model": "unimernet_base",
        "enable": true  // The formula recognition feature is enabled by default. If you need to disable it, please change the value here to "false".
    },
    "table-config": {
        "model": "tablemaster",  // When using structEqTable, please change to "struct_eqtable".
        "enable": false, // The table recognition feature is disabled by default. If you need to enable it, please change the value here to "true".
        "max_time": 400
    }
}
```
配置文件中的`mfr_model`只能指定`unimernet_small`，若想指定更大的模型`unimernet_base`或`UniMERNet`则会报错`KeyError`

### How to reproduce the bug | 如何复现

None

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
unimernet0.2与0.1不兼容，目前mineru使用的是0.2版本，只能在base small tiny中切换，目前为了减少用户磁盘空间占用，只下载了small模型，如需使用base和tiny需要自行下载对应的模型文件放在对应目录中

**Comment by bwnjnOEI** [comment]
我就是自行下载的
![2024-11-03_15-04](https://github.com/user-attachments/assets/e2ece5f9-c16e-4f1e-be07-bbc9bf16b49e)

**Comment by myhloli** [comment]
模型文件有放到json中配置的modeldir吗

**Comment by bwnjnOEI** [comment]
![2024-11-03_15-12](https://github.com/user-attachments/assets/91724436-7b2a-4b8a-859a-cbe252bc573e)
![2024-11-03_15-14](https://github.com/user-attachments/assets/7e494ad6-65fa-43ba-8e9b-0f88e8729919)

**Comment by bwnjnOEI** [comment]
上边第二个截图是small的

**Comment by pJahad** [comment]
I added `unimernet_base: MFR/unimernet_base` in `magic_pdf/resources/model_config/model_configs.yaml` and solved.

**Comment by bwnjnOEI** [comment]
能把`unimernet_base: MFR/unimernet_base`加入repo对应代码中吗，更新后还得自己手动加入
