### ISSUE TITLE
problem after releasing new version 

### ISSUE THREAD

**Issue by ZarCS** [opendatalab/MinerU#849]
Hi, I've got this error recently:

FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/hub/models--opendatalab--PDF-Extract-Kit/snapshots/a29caa466f6d07be0e4863bba64204009128931a/models/MFD/YOLO/yolo_v8_ft.pt'

which is caused by this line:
pipe.pipe_analyze()

**Comment by myhloli** [comment]
Due to the repository change for PDF-Extract-Kit 1.0, you need to re-download the model. Please refer to [How to Download Models](https://github.com/opendatalab/MinerU/blob/master/docs/how_to_download_models_en.md) for detailed steps.

**Comment by ZarCS** [comment]
thanks for quick responding but I'm using Google Colab. 

!wget https://github.com/opendatalab/MinerU/raw/master/docs/download_models_hf.py && pip install huggingface_hub

from huggingface_hub import snapshot_download
model_dir = snapshot_download('opendatalab/PDF-Extract-Kit')

!wget https://github.com/opendatalab/MinerU/raw/master/magic-pdf.template.json && mv magic-pdf.template.json ~/magic-pdf.json && sed -i 's|/tmp/models|{model_dir}/models|g' ~/magic-pdf.json

**Comment by myhloli** [comment]
The Colab tutorial has not been updated to the latest version; please refer to the instructions in the repository's README to complete the installation and configuration steps.

**Comment by myhloli** [comment]
fixed
