### ISSUE TITLE
Error: StructEqTable is Under Upgrade and Unsupported in Current magic-pdf Version During OCR Mode Execution

### ISSUE THREAD

**Issue by cnm13ryan** [opendatalab/MinerU#850]
### Description of the bug | 错误描述

When executing the magic-pdf command in OCR mode, an error related to the StructEqTable component occurs, indicating that it is currently under upgrade and unsupported in the current version of the software. This prevents successful OCR processing of PDF files.
```shell
2024-11-03 20:19:14.512 | ERROR | magic_pdf.model.pdf_extract_kit:table_model_init:48 - StructEqTable is under upgrade, the current version does not support it.
```

with the `magic-pdf.json` config of 
```json
{
    "bucket_info": {
        "bucket-name-1": ["ak", "sk", "endpoint"],
        "bucket-name-2": ["ak", "sk", "endpoint"]
    },
    "models-dir": "/home/usr/PDF-Extract-Kit/models",
    "device-mode": "cuda",
    "layout-config": {
        "model": "doclayout_yolo"
    },
    "formula-config": {
        "mfd_model": "yolo_v8_mfd",
        "mfr_model": "unimernet_small",
        "enable": true
    },
    "table-config": {
        "model": "struct_eqtable",
        "enable": true,
        "max_time": 400
    }
}
```

magic-pdf version is 0.9.0

### How to reproduce the bug | 如何复现

```shell
magic-pdf -p "$INPUT_PATH" -o "$OUTPUT_PATH" -m ocr
```

- Replace "$INPUT_PATH" with the path to your input PDF file.
- Replace "$OUTPUT_PATH" with the desired path for the output PDF file.

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
As the error message describes, due to the upgrade of the struct eqtable, we do not support this model in version 0.9.0. The good news is that we will adapt to this model as soon as possible and introduce support in the next release.
