### ISSUE TITLE
中文文档标题识别特别不准确，以及英文检测文件layout和spans错乱

### ISSUE THREAD

**Issue by aodingpeng** [opendatalab/MinerU#859]

**Comment by myhloli** [comment]
中文的这篇我试了下没发现标题识别不出和多字的情况，英文这篇第一页是扫描时页面存在90度旋转，可视化渲染目前对旋转pdf是不支持的，解析出的内容看了下没有什么问题。

**Comment by aodingpeng** [comment]
> 中文的这篇我试了下没发现标题识别不出和多字的情况，英文这篇第一页是扫描时页面存在90度旋转，可视化渲染目前对旋转pdf是不支持的，解析出的内容看了下没有什么问题。

1.一级标题很准确，但是在二级标题（如3.x）时候就无法识别到；以及如3.1、3.2未扫描到
![image](https://github.com/user-attachments/assets/c9ec0f07-cf09-4ef8-9df4-15a6d193b8f4)
![image](https://github.com/user-attachments/assets/638d6eb2-730f-4472-86c0-8e8b38143e1e)

2.然后我重新安装minerU然后扫描发现依旧扫描“引言”，结果出现的是“引1開言”
![image](https://github.com/user-attachments/assets/0ac7862a-eb92-4a2b-af08-c859cd69908c)

3.最后请问一下英文pdf打开是正常的，为什么识别时候存在90°旋转
![image](https://github.com/user-attachments/assets/2f2502b1-4b0f-4be0-9cea-43abe6b78b30)

**Comment by myhloli** [comment]
中文的在线demo测出来正常
![image](https://github.com/user-attachments/assets/ae1c8948-f73e-4f3e-952c-398f3cfa18d0)
3.1 3.2模型输出的结果就缺少这两个区块，可能是模型本身的缺陷，因为视觉模型不能100%保证识别准确。
英文文档打开正常是因为浏览器识别到内置的旋转参数帮你转好了，源文件扫描的时候是横向扫描的，在程序内部处理会有旋转的情况。目前pymupdf库在写出的时候对旋转信息有丢失，所以会造成可视化结果错位。
