### ISSUE TITLE
magick-pdf 0.9.0新版本模型加载好像缺了点儿东西

### ISSUE THREAD

**Issue by 1134018901** [opendatalab/MinerU#861]
![image](https://github.com/user-attachments/assets/4924af83-edc2-4d8a-b7fd-f95c1f09f7cb)
这是为什么呢？试了好几种办法都是这样

**Comment by myhloli** [comment]
update下unimernet

**Comment by 1134018901** [comment]
但是unimernet已经是最新的了，重新下载过的

**Comment by myhloli** [comment]
看看版本呢？unimernet应该是0.2.1
