### ISSUE TITLE
最新版本0.9.0与paddlepaddle-gpu 3.0.0b1依赖cudnn包冲突

### ISSUE THREAD

**Issue by yuanyuan25** [opendatalab/MinerU#862]
### Description of the bug | 错误描述

通过以下方式安装0.9.0版本
pip install -U magic-pdf[full]=0.9.0 --extra-index-url https://wheels.myhloli.com

使用以下安装paddle
python3 -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu123/ --timeout 120

安装提示，0.9.0依赖torch版本为2.3.1，此版本依赖cuda与paddle冲突
![image](https://github.com/user-attachments/assets/163cfb9c-6b22-4ab2-b9e7-94887d1a62d6)

### How to reproduce the bug | 如何复现

pip install -U magic-pdf[full]==0.9.0 --extra-index-url https://wheels.myhloli.com -i https://mirrors.aliyun.com/pypi/simple --timeout 120 && \
    python3 -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu123/ --timeout 120 

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
按教程来，paddle装cu118的版本，和torch不冲突的
