### ISSUE TITLE
解析PDF超链接时的解析bug

### ISSUE THREAD

**Issue by ouwen18** [opendatalab/MinerU#863]
### Description of the bug | 错误描述

![14](https://github.com/user-attachments/assets/d20acfb3-161e-4f62-bddb-597fb6db6c6b)
![15](https://github.com/user-attachments/assets/6009c2ee-7fe9-4553-8e20-d771560c3262)
第一个图是原始文档，第二个图是解析的片段。
会把=解析成":="格式，还有一些奇奇怪怪的公式描述。

### How to reproduce the bug | 如何复现

我理解是只要超链接里包含=号就会出现这个问题。给一个示例文档。
[https.pdf](https://github.com/user-attachments/files/17626877/https.pdf)

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by ouwen18** [comment]
请帮忙看看能否解决，谢谢

**Comment by myhloli** [comment]
升级到0.9以后关闭公式解析功能再试试，我试了下可以正常解析![image](https://github.com/user-attachments/assets/b9e15c42-f4ed-41c0-a293-b4245d0f1f2b)

**Comment by ouwen18** [comment]
> 升级到0.9以后关闭公式解析功能再试试，我试了下可以正常解析![image](https://private-user-images.githubusercontent.com/11393164/383006127-b9e15c42-f4ed-41c0-a293-b4245d0f1f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODcwODMsIm5iZiI6MTczMDc4Njc4MywicGF0aCI6Ii8xMTM5MzE2NC8zODMwMDYxMjctYjllMTVjNDItZjRlZC00MWMwLWEyOTMtYjQyNDVkMGYxZjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA2MDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3N2ZlZDBlYTFjZTU0YzFkZDU1NjJiMDgxOTc4YTUwN2QyYzg1ZTA2OTZkMjYxYmQ3MTM5MTdhYWRjN2ZkNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._dw9uQN6CeEHAtVGwkiztGXTcDpOUyKDm6Gujsat7bg)
    

我的版本好像是0.9.0 

![image](https://github.com/user-attachments/assets/ba4c4f51-6b69-42a9-8707-2bd80f975e90)

下面是我调用的代码 
from magic_pdf.pipe.UNIPipe import UNIPipe
from magic_pdf.rw.DiskReaderWriter import DiskReaderWriter
def get_markdown(file_name):
    current_script_dir = os.path.dirname(os.path.abspath(__file__))
    pdf_path = os.path.join(current_script_dir, f"{file_name}.pdf")
    pdf_bytes = open(pdf_path, "rb").read()
    jso_useful_key = {"_pdf_type": "", "model_list": []}
    local_image_dir = os.path.join(current_script_dir, 'images')
    image_dir = str(os.path.basename(local_image_dir))
    image_writer = DiskReaderWriter(local_image_dir)
    pipe = UNIPipe(pdf_bytes, jso_useful_key, image_writer)
    pipe.pipe_classify()
    pipe.pipe_analyze()
    pipe.pipe_parse()
    md_content = pipe.pipe_mk_markdown(image_dir, drop_mode="none")
    # print(md_content)
    with open(f"{file_name}.md", "w", encoding="utf-8") as f:
        f.write(md_content)
        
这是什么情况

**Comment by myhloli** [comment]
参考这个链接修改配置文件
https://github.com/opendatalab/MinerU/blob/master/README_zh-CN.md#3-%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BB%A5%E8%BF%9B%E8%A1%8C%E9%A2%9D%E5%A4%96%E9%85%8D%E7%BD%AE
