### ISSUE TITLE
预处理中get_most_common_bbox 代码存在BUG

### ISSUE THREAD

**Issue by imgits** [opendatalab/MinerU#864]
### Description of the bug | 错误描述

get_most_common_bbox 代码存在BUG:

代码位置：/MinerU/tree/master/magic_pdf/pre_proc/detect_footer_header_by_statistics.py 第157行:

`top_y, bottom_y = page_w*page_range_threshold, page_h*(1-page_range_threshold)`

存在的BUG：误将页面高度page_h写成了页面宽度page_w，因为top_y是高度值

个人理解正确代码应该是将原代码中的page_w换成page_h，即：
`top_y, bottom_y = page_h*page_range_threshold, page_h*(1-page_range_threshold)`

### How to reproduce the bug | 如何复现

no

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
这应该是上古代码了，很多个版本之前就没有用到了，应该不影响现在的逻辑
