### ISSUE TITLE
0.9.0分支的的阅读顺序的逻辑是怎么用的

### ISSUE THREAD

**Issue by qrsssh** [opendatalab/MinerU#865]
### Description of the bug | 错误描述

非常感谢在0.9.0分支提供了阅读顺序规则的代码, 但是没看到代码中有被调用的接口.
试了一下magic_pdf->bbox_sort.py ->bbox_sort(函数) 返回的结果是 x,y的坐标, 请问最终 阅读顺序是按先X,后Y来排序做为阅读顺序吗 

### How to reproduce the bug | 如何复现

非常感谢在0.9.0分支提供了阅读顺序规则的代码, 但是没看到代码中有被调用的接口.
试了一下magic_pdf->bbox_sort.py ->bbox_sort(函数) 返回的结果是 x,y的坐标, 请问最终 阅读顺序是按先X,后Y来排序做为阅读顺序吗 

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by qrsssh** [comment]
> ### Description of the bug | 错误描述
> 非常感谢在0.9.0分支提供了阅读顺序规则的代码, 但是没看到代码中有被调用的接口. 试了一下magic_pdf->bbox_sort.py ->bbox_sort(函数) 返回的结果是 x,y的坐标, 请问最终 阅读顺序是按先X,后Y来排序做为阅读顺序吗
> 
> ### How to reproduce the bug | 如何复现
> 非常感谢在0.9.0分支提供了阅读顺序规则的代码, 但是没看到代码中有被调用的接口. 试了一下magic_pdf->bbox_sort.py ->bbox_sort(函数) 返回的结果是 x,y的坐标, 请问最终 阅读顺序是按先X,后Y来排序做为阅读顺序吗
> 
> ### Operating system | 操作系统
> Linux
> 
> ### Python version | Python 版本
> 3.12
> 
> ### Software version | 软件版本 (magic-pdf --version)
> 0.6.x
> 
> ### Device mode | 设备模式
> cuda

@myhloli

**Comment by myhloli** [comment]
0.9是使用的https://github.com/ppaanngggg/layoutreader 这个项目的模型进行排序的

**Comment by qrsssh** [comment]
> 0.9是使用的https://github.com/ppaanngggg/layoutreader 这个项目的模型进行排序的

试了一下， 只传入对应的布局的bbox坐标，不依赖对应的视觉信息， 返回结果 完全不对， 是我打开方式有问题吗， 求解答

**Comment by myhloli** [comment]
> > 0.9是使用的https://github.com/ppaanngggg/layoutreader 这个项目的模型进行排序的
> 
> 
> 
> 试了一下， 只传入对应的布局的bbox坐标，不依赖对应的视觉信息， 返回结果 完全不对， 是我打开方式有问题吗， 求解答

他的模型训练是基于文本行的数据，排序的时候需要先把所有line的信息传进去，排好后再用line的排序反推block的顺序
