### ISSUE TITLE
maigic-pdf解析pdf结果文件中middle.json的来源，是否可以用来在页面前段渲染解析获取的md文件，还原pdf的页面格式

### ISSUE THREAD

**Issue by liy-a** [opendatalab/MinerU#868]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
对存在的问题进行清晰且简洁的描述。例如：我一直很困扰的是 [...]

**Describe the solution you'd like**
**描述您期望的解决方案**
清晰且简洁地描述您希望实现的内容。

**Describe alternatives you've considered**
**描述您已考虑的替代方案**
清晰且简洁地描述您已经考虑过的任何替代解决方案。

**Additional context**
**提供更多细节**
请附上任何相关截图、链接或文件，以帮助我们更好地理解您的请求。

**Comment by liy-a** [comment]
我这边从对咱们解析后的文件中的md文件和middle.json在页面上渲染和还原pdf的原始格式，例如分栏这种格式，请问这个方案可行么

**Comment by myhloli** [comment]
middlejson中有对应的内容块坐标和文本/图像内容，可以在块级别和行级别进行一定程度的排版还原
