### ISSUE TITLE
关于项目的webdemo一些问题咨询

### ISSUE THREAD

**Issue by lidaoming** [opendatalab/MinerU#881]
你好 ，有关该项目线上演示在线pdf解析，要做到这种速度，具体的硬件和显卡配置方便给出么，另外docx 和ppt 也是本项目提取解析的么

**Comment by myhloli** [comment]
一般8核+32G的机器，配单卡a10/L4即可，docx和ppt会先转换成pdf再使用本项目提取

**Comment by lidaoming** [comment]
您好  该项目转换的ppt docx 等文档为pdf 使用的什么方案方便指点么

**Comment by lidaoming** [comment]
> 您好 该项目转换的ppt docx 等文档为pdf 使用的什么方案方便指点么

**Comment by myhloli** [comment]
libreoffice
