### ISSUE TITLE
中文公式识别

### ISSUE THREAD

**Issue by revalue-it** [opendatalab/MinerU#891]
当公式中包含中文时，是否可以正确识别？

**Comment by myhloli** [comment]
目前不支持包含中文的公式

**Comment by ignore1999** [comment]
> 目前不支持包含中文的公式

请问后续更新是否考虑支持包含中文的公式

**Comment by revalue-it** [comment]
> 目前不支持包含中文的公式

@myhloli 请问后续更新是否考虑支持包含中文的公式

**Comment by myhloli** [comment]
目前没有排期，建议根据https://github.com/opendatalab/UniMERNet 这个项目的训练教程，自行准备一批包含中文的公式进行训练优化
