### ISSUE TITLE
识别内容缺失

### ISSUE THREAD

**Issue by hanqingwu** [opendatalab/MinerU#892]
### Description of the bug | 错误描述

使用审计法pdf 测试， 第四十九条内容缺失1,2,3,5
![image](https://github.com/user-attachments/assets/64deb944-f28d-41ef-9f64-25ac8dc37499)
![image](https://github.com/user-attachments/assets/e59d1289-8d70-4d5b-be29-173007c41986)

modelscope 上测试同样异常
![image](https://github.com/user-attachments/assets/2c18fb68-2abc-4f02-8ff8-2e3621638345)
只有https://opendatalab.com/OpenSourceTools/Extracto 正常
![image](https://github.com/user-attachments/assets/208c9d95-c4bd-47d3-ad04-92bf0df165d1)

不知是何原因？

### How to reproduce the bug | 如何复现

使用审计法pdf 测试， 第四十九条内容缺失1,2,3,5

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
文本span的边界有些异常，不知道是不是因为不同平台使用的pymupdf版本不同导致的

**Comment by myhloli** [comment]
pdf文档能上传一份吗

**Comment by hanqingwu** [comment]
[中华人民共和国审计法.pdf](https://github.com/user-attachments/files/17657544/default.pdf)

**Comment by myhloli** [comment]
测了下，和pymupdf版本无关，是文档本身的span宽度和字符宽度严重不匹配导致的，opendatalab的demo能提取是因为那个版本使用的mineru版本比其他demo更新慢一个大版本，之前的span和block匹配阈值调低过一次，为了让这种异常span能保留，但是后来发现导致了更多的问题，就把阈值又回调了一些。

对于这种span明显异常的文档，建议开启强制ocr解析功能，依靠视觉模型圈出的文本边界进行处理，这样会更精确。

**Comment by hanqingwu** [comment]
请教下要如何开启强制ocr解析功能呢？

**Comment by myhloli** [comment]
命令行就加-m ocr参数，在线测试可以勾选ocr开关

**Comment by hanqingwu** [comment]
谢谢！明白了，试了，强制开启ocr 可以正常.

**Comment by hanqingwu** [comment]
@myhloli 再请教下，强制开启ocr后， 与auto相比，文档里的字符串中间的空格消失了，有什么办法保留吗？
![image](https://github.com/user-attachments/assets/477f2cc8-6d30-4e68-bf71-0c9efea9c8cb)

**Comment by myhloli** [comment]
没办法，ocr就是会丢空格

**Comment by hanqingwu** [comment]
好的，明白了，谢谢！
