### ISSUE TITLE
搭建的webapi，统一文件解析结果与MinerU在线解析结果不同，无法解析出章节数字

### ISSUE THREAD

**Issue by zhongxin129** [opendatalab/MinerU#893]
### Description of the bug | 错误描述

![QQ20241107-144143](https://github.com/user-attachments/assets/242189b7-eb4f-459d-9e9e-a04fad32f53b)
如图所示，红色标记部分在MinerU在线能解析出来，在自己部署的webapi，解析不出来，[第2.0.1条]直接变成了 [第条]

### How to reproduce the bug | 如何复现

[水泥混凝土路面施工及验收规范.pdf](https://github.com/user-attachments/files/17657298/default.pdf)
这是需要解析的pdf文件

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
这个2.0.1不是文本，我试了下在浏览器里直接打开，复制出来的内容也是没有2.0.1的。
默认的auto能够提取所有可以复制的文本，对于这种使用图像代替文本的情况，请使用强制ocr模式。
