### ISSUE TITLE
按照流程装完之后，执行magic-pdf提示Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zemofreedom** [opendatalab/MinerU#896]
### Description of the bug | 错误描述

(MinerU) kas@kas-job-24623:~/xxx/code/service_layout/MinerU/demo$ magic-pdf -p demo1.pdf -o ./output
2024-11-07 18:17:37.937 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 9, text_len: 32388, cid_chars_radio: 0.000278344776396363
Segmentation fault (core dumped)
cpu也是支持avx
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp_epp avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

### How to reproduce the bug | 如何复现

pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com -i https://mirrors.aliyun.com/pypi/simple
配置完模型后，在demo路径下执行

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by bottleofwater11** [comment]
> ### Description of the bug | 错误描述
> (MinerU) kas@kas-job-24623:~/xxx/code/service_layout/MinerU/demo$ magic-pdf -p demo1.pdf -o ./output 2024-11-07 18:17:37.937 | INFO | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 9, text_len: 32388, cid_chars_radio: 0.000278344776396363 Segmentation fault (core dumped) cpu也是支持avx flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp_epp avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities
> 
> ### How to reproduce the bug | 如何复现
> pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com -i https://mirrors.aliyun.com/pypi/simple 配置完模型后，在demo路径下执行
> 
> ### Operating system | 操作系统
> Linux
> 
> ### Python version | Python 版本
> 3.10
> 
> ### Software version | 软件版本 (magic-pdf --version)
> 0.9.x
> 
> ### Device mode | 设备模式
> cuda

请问是怎么解决的
