### ISSUE TITLE
安装报错提示:ERROR: Failed building wheel for simsimd

### ISSUE THREAD

**Issue by windowLiu** [opendatalab/MinerU#897]
### Description of the bug | 错误描述

    gcc版本尝试了4.8到9.3都不行 是否需要降级到4.6以下才可以？ 
    In file included from include/simsimd/curved.h:29,
                       from include/simsimd/simsimd.h:106,
                       from c/lib.c:48:
      include/simsimd/spatial.h: In function ‘_simsimd_substract_bf16x32_genoa’:
      include/simsimd/spatial.h:1676:26: note: The ABI for passing parameters with 64-byte alignment has changed in GCC 4.6
       SIMSIMD_INTERNAL __m512i _simsimd_substract_bf16x32_genoa(__m512i a_i16, __m512i b_i16) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      error: command '/opt/rh/devtoolset-8/root/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simsimd
Failed to build simsimd
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (simsimd)

### How to reproduce the bug | 如何复现

执行  pip install -U magic-pdf[full]==0.8.1 --extra-index-url https://wheels.myhloli.com -i https://pypi.tuna.tsinghua.edu.cn/simple
时报错

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
挺奇怪的其实，因为我在各种设备上装都没遇到过需要安装这个simsimd的情况，可以反馈下具体是在什么系统和版本上安装的吗

**Comment by windowLiu** [comment]
阿里云 centos7.9 conda环境进行安装 gpu为T4 16g显存  32G内存

**Comment by myhloli** [comment]
我查看了项目安装完成的pip list，应该是没有simsimd这个库的依赖的，而且即使需要安装这个库，看了下[pypi](https://pypi.org/project/simsimd/6.0.1/#files)上，应该也是有预编译的whl的，所以完全没办法理解为什么pip会要求在本机编译simsimd这个库。

如果你这台阿里云的机器方便重装系统的话，可以试试安装ubuntu22.04，再尝试按教程安装mineru，希望能够帮到你。

**Comment by Sakura4036** [comment]
是 [Muitl-GPU项目](https://github.com/opendatalab/MinerU/blob/master/projects/multi_gpu/README.md)中安装会出现的问题：
```
pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118
```

我也遇到这个问题，`sinsimd`仓库中也有相关issue:[Error while pip install simsimd: Building wheel for simsimd (pyproject.toml) ... error](https://github.com/ashvardanian/SimSIMD/issues/221), 但没有给出解决方案。

**Comment by Sakura4036** [comment]
如果忽略这个问题，继续运行`python server.py`，提示安装`fitz`， `frontend`等安装包，继续运行报错：
```
**python server.py 
Traceback (most recent call last):
  File "/home/github/MinerU/server.py", line 2, in <module>
    import fitz
  File "/home/anaconda3/envs/mineru/lib/python3.10/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
  File "/home/anaconda3/envs/mineru/lib/python3.10/site-packages/frontend/__init__.py", line 1, in <module>
    from .events import *
  File "/home/anaconda3/envs/mineru/lib/python3.10/site-packages/frontend/events/__init__.py", line 1, in <module>
    from .clipboard import *
  File "/home/anaconda3/envs/mineru/lib/python3.10/site-packages/frontend/events/clipboard.py", line 2, in <module>
    from ..dom import Event
  File "/home/anaconda3/envs/mineru/lib/python3.10/site-packages/frontend/dom.py", line 439, in <module>
    from . import dispatcher
  File "/home/anaconda3/envs/mineru/lib/python3.10/site-packages/frontend/dispatcher.py", line 15, in <module>
    from . import config, server
  File "/home/anaconda3/envs/mineru/lib/python3.10/site-packages/frontend/server.py", line 24, in <module>
    app.mount(config.STATIC_ROUTE, StaticFiles(directory=config.STATIC_DIRECTORY), name=config.STATIC_NAME)
  File "/home/anaconda3/envs/mineru/lib/python3.10/site-packages/starlette/staticfiles.py", line 56, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'static/' does not exist
```

**Comment by windowLiu** [comment]
重新安装了ubuntu22.04系统 目前可以使用了

**Comment by maikouSart** [comment]
我centos的服务器也出现了上面的问题，目前还没找到解决方法，但是之前只有0.8版本的时候是可以装成功的，现在出了0.9.2版本后0.8的也装不成功了，不知道是不是环境也做了更新。

**Comment by Sakura4036** [comment]
> 重新安装了ubuntu22.04系统 目前可以使用了

请问服务器不能重装系统怎么办呢？

**Comment by myhloli** [comment]
> > 重新安装了ubuntu22.04系统 目前可以使用了
> 
> 请问服务器不能重装系统怎么办呢？

用docker

**Comment by frxg0918** [comment]
我有一个包需要simsimd>=5.9.2，但是这个版本simsimd需要的glibc版本高于我的机器。我的情况中前置是albucore，我把albucore降级之后需要的simsimd版本也下降了，我的glibc就符合要求了。

**Comment by myhloli** [comment]
也许simsimd刚刚修复了这个问题

https://github.com/ashvardanian/SimSIMD/issues/229

**Comment by Sakura4036** [comment]
还是不行，用docker吧

**Comment by arwinleecg** [comment]
大家有解决了的吗？

**Comment by A-cracker** [comment]
> 我centos的服务器也出现了上面的问题，目前还没找到解决方法，但是之前只有0.8版本的时候是可以装成功的，现在出了0.9.2版本后0.8的也装不成功了，不知道是不是环境也做了更新。

一样的问题，之前可以安装，最近安装不成功了。报错如下：
![image](https://github.com/user-attachments/assets/e18cd2ed-f79d-4043-b52d-06f70db5f532)

**Comment by myhloli** [comment]
@windowLiu @Sakura4036 @frxg0918 @arwinleecg @A-cracker 
https://github.com/opendatalab/MinerU/issues/1004 update

**Comment by szhang67** [comment]
安装albumentations库的时候遇到了这个error。盲解决方法就是尝试找到旧版本的albumentations安装就可以解决，建议可以看看在装那个包的时候报的这个错，然后尝试指定几个低版本的

**Comment by myhloli** [comment]
> 安装albumentations库的时候遇到了这个error。盲解决方法就是尝试找到旧版本的albumentations安装就可以解决，建议可以看看在装那个包的时候报的这个错，然后尝试指定几个低版本的

有支持centos7的最高版本albumentations库信息吗，我贴到上面置顶里面

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/issues/1004 应该可以解决了。

**Comment by shellyfung** [comment]
> > 安装albumentations库的时候遇到了这个error。盲解决方法就是尝试找到旧版本的albumentations安装就可以解决，建议可以看看在装那个包的时候报的这个错，然后尝试指定几个低版本的
> 
> 有支持centos7的最高版本albumentations库信息吗，我贴到上面置顶里面

albumentations==1.3.1

**Comment by MovePhilip** [comment]
centos7
albumentations==1.4.19
安装没问题
