### ISSUE TITLE
请在安装过程中添加 Pillow 依赖

### ISSUE THREAD

**Issue by xianxingg** [opendatalab/MinerU#900]
### Description of the bug | 错误描述

![Xnip2024-11-08_10-54-10](https://github.com/user-attachments/assets/37c2cade-a651-4915-80e2-704ba93bd38f)

### How to reproduce the bug | 如何复现

按照文档进行本地安装后，运行 `magic-pdf -v` 时可能遇到报错。

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cpu

**Comment by xianxingg** [comment]
不确定是否由于我没有安装 [full] 版本的 magic-pdf，第一次执行 pip install -U magic-pdf[full] 的时候命令报错，我就把 [full] 去掉了。
现在发现可以这样执行 pip install -U "magic-pdf[full]"

**Comment by myhloli** [comment]
pillow应该会作为paddleocr的依赖安装进来，装full的时候会装上pillow的

**Comment by hzyywq** [comment]
使用 pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com 命令会默认安装0.6.1版本
使用pip install -U magic-pdf[full]==0.9.2 --extra-index-url https://wheels.myhloli.com 命令安装会出现以下报错
ERROR: Could not find a version that satisfies the requirement detectron2; extra == "full" (from magic-pdf[full]) (from versions: none)
ERROR: No matching distribution found for detectron2; extra == "full"

**Comment by myhloli** [comment]
> 使用 pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com 命令会默认安装0.6.1版本 使用pip install -U magic-pdf[full]==0.9.2 --extra-index-url https://wheels.myhloli.com 命令安装会出现以下报错 ERROR: Could not find a version that satisfies the requirement detectron2; extra == "full" (from magic-pdf[full]) (from versions: none) ERROR: No matching distribution found for detectron2; extra == "full"

https://[wheels.myhloli.com/detectron2/](https://wheels.myhloli.com/detectron2/)

从这个网页先选择符合自己系统平台的预编译包安装看看能不能装上
