### ISSUE TITLE
FatalError: `Erroneous arithmetic operation` is detected by the operating system.

### ISSUE THREAD

**Issue by bottleofwater11** [opendatalab/MinerU#908]
### Description of the bug | 错误描述

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   at::_ops::linear::call(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&)
1   at::native::linear(at::Tensor const&, at::Tensor const&, std::optional<at::Tensor> const&)
2   at::_ops::addmm::call(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar const&, c10::Scalar const&)
3   at::_ops::addmm::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::Scalar const&, c10::Scalar const&)

----------------------
Error Message Summary:
----------------------
FatalError: `Erroneous arithmetic operation` is detected by the operating system.
  [TimeInfo: *** Aborted at 1731057575 (unix time) try "date -d @1731057575" if you are using GNU date ***]
  [SignalInfo: *** SIGFPE (@0x7f6db8afd914) received by PID 146315 (TID 0x7f6efa521480) from PID 18446744072513116436 ***]

### How to reproduce the bug | 如何复现

magic-pdf -p kaiti.pdf -o . -m ocr 指令运行报错如上

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
看看是不是显存不足

**Comment by bottleofwater11** [comment]
> 看看是不是显存不足

![image](https://github.com/user-attachments/assets/4c4e0566-f3ca-4ce8-b2bb-e984c0c90e2c)
我指定的这张卡跑的

**Comment by bottleofwater11** [comment]
> 看看是不是显存不足

![image](https://github.com/user-attachments/assets/a91793ed-7c2e-4b7c-9ce1-da36614769d7)
这是跑的时候的状态，会不会是冲突了，上面还有部署的一些小模型

**Comment by myhloli** [comment]
H系列可能太新了，和cuda11.8不兼容

**Comment by bottleofwater11** [comment]
> H系列可能太新了，和cuda11.8不兼容

啊，之前就有过这个问题当时是0.8.1的版本，当时在V100可以跑，那后续会有优化么请问

**Comment by myhloli** [comment]
我看有人装了cu12的paddlegpu，说是能跑，你可以在issue里找下，我这边自测cu12的paddle好像和torch有冲突，实在不行就用cpu的paddle一样跑

**Comment by bottleofwater11** [comment]
> 我看有人装了cu12的paddlegpu，说是能跑，你可以在issue里找下，我这边自测cu12的paddle好像和torch有冲突，实在不行就用cpu的paddle一样跑

行，cpu处理太慢了，当时测得一个表格处理要两分钟

**Comment by myhloli** [comment]
表格我们后面会加rapidtable，用cpu会比tablemaster快很多

**Comment by bottleofwater11** [comment]
> 表格我们后面会加rapidtable，用cpu会比tablemaster快很多

好的好的
