### ISSUE TITLE
希望输出文件能有一个layout每个色块的分类和坐标，当前看着是按行给出的

### ISSUE THREAD

**Issue by charliedream1** [opendatalab/MinerU#933]
希望输出文件能有一个layout每个色块的分类和坐标，当前看着是按行给出的

**Comment by myhloli** [comment]
layout的输出是按块定义的，可以参考https://github.com/opendatalab/MinerU/blob/master/docs/output_file_zh_cn.md#%E7%BB%93%E6%9E%84%E5%AE%9A%E4%B9%89
