### ISSUE TITLE
报错：paddlepaddle的库函数找不到

### ISSUE THREAD

**Issue by vanchy-z** [opendatalab/MinerU#935]
### Description of the bug | 错误描述

![Snipaste_2024-11-12_14-46-59](https://github.com/user-attachments/assets/c2f7fc9d-db5c-47d5-9540-c03c3d22115d)
今天刚部署的0.9版本，按照教程部署的。然后在/demo/magic_pdf_parse_main.py函数中运行，输入的文件是/demo/demo1.pdf，运行时报了这个错，查了以下通义千问说可能是paddleocr的版本更新，请问这个问题应该怎么解决？

### How to reproduce the bug | 如何复现

demo/magic_pdf_parse_main.py
if __name__ == '__main__':
    pdf_path = r"demo1.pdf"
    pdf_parse_main(pdf_path)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
pip list
发一下所有paddle开头的包的版本

**Comment by vanchy-z** [comment]
![image](https://github.com/user-attachments/assets/b24ec269-90ce-4cbf-a73f-eb514d46f427)

**Comment by myhloli** [comment]
paddlepaddle和paddlepaddle-gpu版本不一致，不同版本不能混装
