### ISSUE TITLE
 layoutreader 进行阅读顺序排序

### ISSUE THREAD

**Issue by lyc728** [opendatalab/MinerU#936]
你好，关于这个排序模型，我理解应该写一个后处理代码就能cover这些情况吧，有必要用一个模型来进行处理吗？

**Comment by myhloli** [comment]
真实环境的阅读顺序恢复是相当困难也是相当重要的一环，绝不是简单的从左到右从上到下的简单罗列。使用算法排序总会遇到各种各样无法解决的badcase，使用模型做排序是必然的选择。

**Comment by lyc728** [comment]
这边有trt模型的转换吗？ 我其他模型已经转成trt的形式了 现在需要统一起来。有没有可以参考的代码

**Comment by lyc728** [comment]
<img width="743" alt="企业微信截图_17319219866163" src="https://github.com/user-attachments/assets/d04e711d-2a5f-41ae-9c26-4c2f4268059e">
这种简单的 不应该排序有问题吧

**Comment by myhloli** [comment]
> <img alt="企业微信截图_17319219866163" width="743" src="https://private-user-images.githubusercontent.com/88084847/387153526-d04e711d-2a5f-41ae-9c26-4c2f4268059e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MjI0MzUsIm5iZiI6MTczMTkyMjEzNSwicGF0aCI6Ii84ODA4NDg0Ny8zODcxNTM1MjYtZDA0ZTcxMWQtMmE1Zi00MWFlLTljMjYtNGMyZjQyNjgwNTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA5Mjg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YzY1YTRkNjNlNDc1NGY1M2ExOTdjYjVhNzEzNDY5NzkyY2FkMjkwMmY4OTEyNTU2MTA1MzA3ZDcxYTRlMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fJVYpDoPl1SO0c0nVkygpn5zSb59uHL3vWx3IwDbp7E"> 这种简单的 不应该排序有问题吧

你这个看着也没问题啊，假设这是个双栏结构，先下面再右边也是通顺的

**Comment by lyc728** [comment]
我理解这个下面是双栏，但是上面是标题信息把，这边我说的是日期（16）有问题 不是推荐（17这个没问题）

**Comment by myhloli** [comment]
排序模型只有bbox坐标，没有这些线来辅助判断啊，看位置分布的话，日期分到右侧也没啥问题
