### ISSUE TITLE
`markdown`的序号和标题之间没空格

### ISSUE THREAD

**Issue by bwnjnOEI** [opendatalab/MinerU#937]
### Description of the bug | 错误描述
目标： `1 Introduction`
实际：
<img width="1515" alt="image" src="https://github.com/user-attachments/assets/c3002a12-81b2-45d5-8a2a-f79efae23896">

如果目标为 `1. Introduction`, 则解析正确。

### How to reproduce the bug | 如何复现

如何才能避免或减少这种情况

模型配置如下：
<img width="616" alt="image" src="https://github.com/user-attachments/assets/eebefe55-ce81-4aef-9788-8ffa729297eb">

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
pdf文件可以上传一份吗？

**Comment by bwnjnOEI** [comment]
[What Evidence Do Language Models Find Convincing?.pdf](https://github.com/user-attachments/files/17726014/What.Evidence.Do.Language.Models.Find.Convincing.pdf)

arxiv序号和小标题间没`.`的论文基本都出现这种情况，代码用的是demo中的那个

**Comment by gcy0926** [comment]
+1，也遇到了这种情况

**Comment by myhloli** [comment]
@bwnjnOEI @gcy0926 已经定位到问题，会在下个版本修复
