### ISSUE TITLE
magic-pdf 使用方法 和 README说明不一致，且执行时报错

### ISSUE THREAD

**Issue by gcy0926** [opendatalab/MinerU#940]
### Description of the bug | 错误描述

mac os 解析pdf时使用magic-pdf 出错

### How to reproduce the bug | 如何复现

执行命令 magic-pdf pdf-command --pdf ./KAG.pdf  报错 2024-11-13 14:40:37.395 | ERROR    | magic_pdf.cli.magicpdf:do_parse:114 - need model list input

magic-pdf, version 0.6.1

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cpu

**Comment by gcy0926** [comment]
软件版本只有0.7及以上，但通过README安装为0.6.1

**Comment by gcy0926** [comment]
版本的问题，使用0.9.1版本没有问题了

**Comment by ChenziqiAdam** [comment]
您好，我也遇到了相同的问题，但是我是一步步按照README来的，请问最后是怎么升级版本的呢？
