### ISSUE TITLE
论文标题有字体大小差异时，会造成单词被拆分

### ISSUE THREAD

**Issue by gcy0926** [opendatalab/MinerU#942]
### Description of the bug | 错误描述

![单词字体不一致差费](https://github.com/user-attachments/assets/f564be48-537d-4a13-8d73-f651cb51ad14)

### How to reproduce the bug | 如何复现

RT，当pdf文本中存在字体大小不一致的情况时，解析后的单词被拆分。

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cpu

**Comment by gcy0926** [comment]
[Uploading RAG评估-A unified evaluation.pdf…]()

**Comment by myhloli** [comment]
> Uploading RAG评估-A unified evaluation.pdf…

没上传成功，能重传下吗

**Comment by gcy0926** [comment]
[Uploading RAG评估-A unified evaluation.pdf…]()

**Comment by gcy0926** [comment]
https://arxiv.org/abs/2409.12941

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/ff874a1c-11e0-4f53-9ff9-db9a3208ddb8)
这个问题在0.9修了，你用的是稳定版demo，那个更新会慢一个版本

**Comment by myhloli** [comment]
复测了你v1的论文，只能说尽力合并了，但是还是不能全合并上
![image](https://github.com/user-attachments/assets/9afbbc2b-c046-46d4-8756-47c226f38b66)
![image](https://github.com/user-attachments/assets/d784df96-cd3e-4ef4-ab2c-47af201ec39e)
因字体不统一，导致span提取的时候就被切开了，拼接的时候不会用太复杂的规则去做合并，目前只做了单字符的合并，如果是多个字符被切开是没办法合回去的

**Comment by gcy0926** [comment]
请问我需要拉哪个版本的代码使用呢？

**Comment by myhloli** [comment]
dev分支
