### ISSUE TITLE
标注序号和水印识别异常

### ISSUE THREAD

**Issue by simplew2011** [opendatalab/MinerU#947]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/274946ae-f43d-44ca-bd4d-48b7ddb13684)

### How to reproduce the bug | 如何复现

- https://github.com/opendatalab/MinerU/blob/master/demo/magic_pdf_parse_main.py
- [语文-1.pdf](https://github.com/user-attachments/files/17731515/-1.pdf)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.9

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
1. 可以试着直接在浏览器中打开pdf复制标号文本，再在文本编辑器中粘贴，可以看到标号虽然显示的是①②③形式，但在文档中储存的实际上是abc，因此以文本形式提取标号是abc是符合预期的。
2. 目前版本已经加了水印去除逻辑，但是仅限跨多个block的大型水印，完全被block包裹的小水印目前的逻辑无法做到识别和去除。
