### ISSUE TITLE
请教，为什么部署的webdemo和opendatalab上的webdemo不一样

### ISSUE THREAD

**Issue by sky84892070** [opendatalab/MinerU#950]
### Description of the bug | 错误描述

请教，为什么部署的webdemo和opendatalab上的webdemo不一样
缺少支持上传多个文件、查看全部任务和支持上传word、ppt？

### How to reproduce the bug | 如何复现

请教，为什么部署的webdemo和opendatalab上的webdemo不一样
缺少支持上传多个文件、查看全部任务和支持上传word、ppt？

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cpu

**Comment by decrystal** [comment]
目前开源的web demo与线上的demo迭代节奏&功能不太一样，预估这块会在下下个版本统一功能&完善

**Comment by sky84892070** [comment]
多久会发布下下个版本？

**Comment by Focusshang** [comment]
目前web功能更新主要会以opendatalab上的demo为主，暂时没人力维护开源的web demo，想使用全量功能还是上官网体验吧
