### ISSUE TITLE
新手关于项目中的单例模式和多进程之间的问题

### ISSUE THREAD

**Issue by lidaoming** [opendatalab/MinerU#954]
您好 我是个新手代码水平有限  我的需求是向做一个后端api (例如 fastapi 或者 flask )就像项目的web demo 那样 环境是CPU windows(我看了linux 好像之前有人提过bug是有问题 windows  cpu 则不会)
我在启动fastapi服务器前执行
def init_model():
    from magic_pdf.model.doc_analyze_by_custom_model import ModelSingleton
    try:
        model_manager = ModelSingleton()
        txt_model = model_manager.get_model(False, False)
        logger.info(f"txt_model init final")
        ocr_model = model_manager.get_model(True, False)
        logger.info(f"ocr_model init final")
        return 0
    except Exception as e:
        logger.exception(e)
        return -1

model_init = init_model()
logger.info(f"model_init: {model_init}")
...
app.run()
问题1 此时我是用多进程启动服务器 例如 gunicor -w 4 启动4个进程  或uvicorn --workers 4 此时我看到控制台输出了4次初始化的代码
我想多进程但是只初始化一次  如何操作 
问题2 单例化后我如何拿到该对象 由于不是很懂代码 我想获取该单例化后的对象 并想让其再过个进程中共享这一个对象 变为多进程单例  好不好操作  
问题 3  如果我不适用api这中方式  而是使用flask + celery  再celery的work 中执行Pdf 转化   当设置work 为4 或者更多的时候 如何让模型只初始化一次  
希望大佬们帮帮我 给一些代码提示 感恩orz

**Comment by drunkpig** [comment]
多进程共享一个模型实例基本不用想了，不容易控制。
