### ISSUE TITLE
能否实现倾斜pdf自动调整方向纠正

### ISSUE THREAD

**Issue by jiajunly** [opendatalab/MinerU#958]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**

目前对于倾斜的文本识别效果损失特别大，矫正后有一定提高

**Describe the solution you'd like**
**描述您期望的解决方案**

建议增加一个预处理步骤，先自动调整倾斜pdf的方向

**Describe alternatives you've considered**
**描述您已考虑的替代方案**

目前我的使用方式是，通过Adobe Acrobat Pro DC 自动调整 PDF 文件的角度，然后再进行处理，有点繁琐。

**Additional context**
**提供更多细节**

https://blog.csdn.net/edward_zcl/article/details/117065926

**Comment by myhloli** [comment]
感谢您的反馈，我们后面看看有没有好的优化方案。

**Comment by myhloli** [comment]
![image](https://github.com/user-attachments/assets/fcef8f2e-5285-4b2d-a325-b44208f95de7)
我们在新版本中加入了对倾斜文本的适配，一般倾斜的不是特别离谱的都能正常解析了

**Comment by jiajunly** [comment]
非常感谢，作者辛苦！看起来图片中检测效果不是很好呀，有很多错字呀。

**Comment by myhloli** [comment]
我直接在csdn截的图，这个图分辨率太低了，主要测试能解析就行
