### ISSUE TITLE
如何配置使用StructTable-InternVL2-1B进行表格提取

### ISSUE THREAD

**Issue by 77981836** [opendatalab/MinerU#962]
如题

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/master/README_zh-CN.md#3-%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BB%A5%E8%BF%9B%E8%A1%8C%E9%A2%9D%E5%A4%96%E9%85%8D%E7%BD%AE

参考readme修改一下配置文件
