### ISSUE TITLE
关于PDF文档转换问题和建议

### ISSUE THREAD

**Issue by Tian14267** [opendatalab/MinerU#963]
**当前功能有以下问题：
1：表格数据以图片形式展现的。这个希望报个数据能结构化输入，不要在用图片；
2：标识识别不准。所有标题都识别成了一级标题。需要按照标题自己的等级进行识别。一级，二级，三级，等等。
3：涉及到公式的地方，md文件展示的很差。建议公式改成图片形式展示就行了。
**

**Comment by myhloli** [comment]
1. 表格可以通过修改配置文件手动开启解析功能
2. 标题分级目前没有支持，实现方案还在调研，可能会在后续版本加入
3. 公式不能做到100%渲染，后续会考虑通过后处理的方式提高公式的渲染成功率

**Comment by Tian14267** [comment]
> 1. 表格可以通过修改配置文件手动开启解析功能
> 2. 标题分级目前没有支持，实现方案还在调研，可能会在后续版本加入
> 3. 公式不能做到100%渲染，后续会考虑通过后处理的方式提高公式的渲染成功率

好嘞，感谢回复。表格的配置在哪里开启。能给一下样例吗。公式的分级，我看这个[marker](https://github.com/VikParuchuri/marker)可以做，但是只能做到二级标题。我感觉最起码要到三级标题才有用。公式我感觉不需要提取内容，识别到位置直接截图展示也可以了。

非常期待能尽快进行改进和展示。做到上面几点，这个工具就非常nice了

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/master/README_zh-CN.md#3-%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BB%A5%E8%BF%9B%E8%A1%8C%E9%A2%9D%E5%A4%96%E9%85%8D%E7%BD%AE
可以参考readme开启表格识别开关

**Comment by Tian14267** [comment]
@myhloli 哈喽，不好意思打扰了。我没找表格识别的开关呀。现在的表格都直接截图的~

**Comment by myhloli** [comment]
在配置文件的table-config项目中配置enable为true即可
