### ISSUE TITLE
Python 3.11 及更高版本支持？

### ISSUE THREAD

**Issue by stevenhe1988** [opendatalab/MinerU#970]
由于公司Python版本的特定限制，不能使用Python3.10，使用Python3.11+Ubuntu22.04+cuda12.1解析时会报错
Segmentation fault (core dumped) 

请问不能使用Python3.11而必须使用3.10的制约是什么？是否有计划支持3.11？或我如何配置才可以在3.11上使用？

感谢

**Comment by myhloli** [comment]
有一个预编译的包detectron2只有3.10版本，如果你可以自己编译的话，应该也可以在3.11上使用

**Comment by myhloli** [comment]
Segmentation fault (core dumped)
更大的可能性是cpu不支持avx和avx2 指令集，可以参考faq中的相关说明
