### ISSUE TITLE
希望能添加控制输出结构的选项

### ISSUE THREAD

**Issue by yibie** [opendatalab/MinerU#978]
**Is your feature request related to a problem? Please describe.**
**您的特性请求是否与某个问题相关？请描述。**
对存在的问题进行清晰且简洁的描述。例如：我一直很困扰的是 [...]

现在的输出结果会同时提供好几个格式。但我可能只需要其中的 1、2 个。

**Describe the solution you'd like**
**描述您期望的解决方案**
清晰且简洁地描述您希望实现的内容。

简单来说，比如在命令行中提供更多的参数，比如：
magic-pdf -p /Volumes/Collect/archives/Indexing\ The\ Manual\ of\ Good\ Practice\ 2013.pdf -o ~/Documents/temp_convert/ -m auto -f md

**Describe alternatives you've considered**
**描述您已考虑的替代方案**
清晰且简洁地描述您已经考虑过的任何替代解决方案。

**Additional context**
**提供更多细节**
请附上任何相关截图、链接或文件，以帮助我们更好地理解您的请求。

**Comment by myhloli** [comment]
可以参考
https://github.com/opendatalab/MinerU/blob/master/demo/magic_pdf_parse_main.py

可以很方便的自由控制输出的结果
