### ISSUE TITLE
【QA】MinerU0.9.0 API版本从 Hugging Face 下载模型 error

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#981]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/a7a269e9-5e5d-4b03-8112-44d37c39f9c3)

### How to reproduce the bug | 如何复现

0.9.3分支的API文档下载model会error

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
使用huggingface作为模型源需要设备拥有外网访问权限，国内用户建议使用modelscope源
