### ISSUE TITLE
【QA】0.9.3版本 单词黏连问题

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/MinerU#983]
### Description of the bug | 错误描述

![image](https://github.com/user-attachments/assets/c29c2912-3608-4724-afbe-7a165a24d6df)
![image](https://github.com/user-attachments/assets/6a688b6e-7e91-45e9-b616-969bcc9073c7)

### How to reproduce the bug | 如何复现

MinerU docyolo+rapiaitable

复现文件：yanbaor2_yanbaoPPT_469 OCR模式

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
ocr单词黏连请使用--lang en参数调用英语ocr模型
