### ISSUE TITLE
how have you processed the blocks after finding out the layout order?

### ISSUE THREAD

**Issue by vikas-singh16** [opendatalab/MinerU#989]
Hi, 
first of all excellent work done guys. Very helpful for what u have done here guys. 

I want to understand, how were you able to organise the blocks (i.e text, title, table, etc) after finding out there order in the page. If possible can u explain in short and guide me to that particular code. 

Thank you

**Comment by myhloli** [comment]
If you have already obtained the correct reading order, then you just need to connect all the blocks in sequence. For the specific code, you can refer to:
https://github.com/opendatalab/MinerU/blob/master/magic_pdf/pdf_parse_union_core_v2.py

**Comment by vikas-singh16** [comment]
Thank you for the swift response.
