### ISSUE TITLE
3 requirements files are there which one should use

### ISSUE THREAD

**Issue by Akshaybhure111** [opendatalab/MinerU#990]
### Description of the bug | 错误描述

I am trying to run whole code locally which requirements files should I install. I am confused there are 3 different file are present for requirements.
and should I need to take whole folders of files from github for running locally or only needed files.
I am trying to run demo code scripts so please sujjest me.

### How to reproduce the bug | 如何复现

I am trying to run whole code locally which requirements files should I install. I am confused there are 3 different file are present for requirements.
and should I need to take whole folders of files from github for running locally or only needed files.
I am trying to run demo code scripts so please sujjest me.

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
please read the quick start tutorial.
https://github.com/opendatalab/MinerU?tab=readme-ov-file#quick-start
