### ISSUE TITLE
MinerU无法识别多级标题，识别的标题全部归为一级标题

### ISSUE THREAD

**Issue by JoshonSmith** [opendatalab/MinerU#994]
great work！！！

MinerU无法识别多级标题，识别的标题全部归为一级标题

是否有计划或者方案解决这个问题，很多场景需要这个多级标题的。

**Comment by drunkpig** [comment]
目前是这样的，标题涉及到字体颜色等非常复杂，留给用户自己定义规则实现

**Comment by JoshonSmith** [comment]
> 目前是这样的，标题涉及到字体颜色等非常复杂，留给用户自己定义规则实现

okk 希望MinerU越来越强大
