### ISSUE TITLE
在Django中启动项目后出现了内存溢出

### ISSUE THREAD

**Issue by haoweiwang0** [opendatalab/MinerU#995]
### Description of the bug | 错误描述

我使用本项目搭建了一个用于提取pdf内容的django服务（带有模型预加载），但每次处理较大规模pdf数据量时处理到一半进程就会被系统杀掉。使用`top`命令排查后发现该django进程的内存占用一直在不断增加，我在视图模块的返回前已经添加了`gc.collect()`但问题仍然存在。

### How to reproduce the bug | 如何复现

我使用了`memory_profiler`来定位内存泄露的源头发现这程序主要的内存泄露都集中在这四个函数（`dict_html2text`是可回收的）：
首次调用：
![微信截图_0](https://github.com/user-attachments/assets/41a58794-f23c-4564-b555-6871d082210a)
后续调用：
![微信截图_20241118112812](https://github.com/user-attachments/assets/a5270df3-fb48-4019-a5fd-2d6b8d161c08)
该项目使用了cuda加速，并且开启了公式识别与表格识别，具体模型设置如下：
![微信截图_20241118113353](https://github.com/user-attachments/assets/fb5a5d09-0efc-4f80-9393-e9f5914c0468)

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
目前内存泄露基本都是paddle框架导致的，建议table模型改成rapid_table,然后ocr开启gpu加速，这样内存泄露的会比较慢，30G内存可以坚持10~20w页解析，内存快满的时候重启下进程就好
