### ISSUE TITLE
如何使用RapidTable？改配置文件不生效

### ISSUE THREAD

**Issue by charliedream1** [opendatalab/MinerU#996]
### Description of the bug | 错误描述

如何使用RapidTable？改配置文件不生效

### How to reproduce the bug | 如何复现

改配置文件表格模型名字改为RapidTable不生效。另外阅读顺序的模型，需要在json里面配置吗？怎么配？

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
默认就是rapid_table，只需要把enable改成true即可

**Comment by charliedream1** [comment]
好的，layout reader用专门配置一下吗？



---原始邮件---
发件人: "Xiaomeng ***@***.***&gt;
发送时间: 2024年11月18日(周一) 中午12:12
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [opendatalab/MinerU] 如何使用RapidTable？改配置文件不生效 (Issue #996)




 
默认就是rapid_table，只需要把enable改成true即可

**Comment by myhloli** [comment]
其他不用调

**Comment by charliedream1** [comment]
好，谢谢



---原始邮件---
发件人: "Xiaomeng ***@***.***&gt;
发送时间: 2024年11月18日(周一) 中午12:13
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [opendatalab/MinerU] 如何使用RapidTable？改配置文件不生效 (Issue #996)




 
其他不用调

**Comment by charliedream1** [comment]
请教一下，如何更换StructTable-InternVL2-1B这个模型，这个模型的表格准确率会更高一些？
另外，运行过程中，看到有下面2个警告，安装这2个可以加速？这个主要是给哪个模型加速的？
import tensorrt_llm failed, if do not use tensorrt, ignore this message
import lmdeploy failed, if do not use lmdeploy, ignore this message

**Comment by charliedream1** [comment]
![image](https://github.com/user-attachments/assets/b0391df0-76dc-4083-be02-2d2ce19e01e9)
看着自动调的StructTable-InternVL2-1B，不是rapid table。需要改哪个配置。magic-pdf已经更新到0.9.3，模型下载脚本也重新执行了，但没有模型更新的消息。请问该怎么解决？

**Comment by myhloli** [comment]
"table-config": {
        "model": "rapid_table",
        "enable": true,
        "max_time": 400
    }

**Comment by charliedream1** [comment]
可以了，感谢。另外，咱们的文档里有哪些可更换的模型名称列表吗？我好像没有找到。

另外，警告中提示安装tensorRT或lmdploy. 如果按照这个的话，使用StructTable-InternVL2-1B是不是会更快？

**Comment by myhloli** [comment]
readme里有，目前推荐使用rapidtable，效率和精度都更高

**Comment by charliedream1** [comment]
我在json里设置的，"device-mode": "cpu", 但怎么报了CUDA显存不够了？

2024-11-18 13:51:09.646 | ERROR    | magic_pdf.user_api:parse_pdf:97 - CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):

  File "/home/magic_pdf_parse_main.py", line 155, in <module>
    pdf_parse_main(pdf_path, parse_method, None,
    │              │         └ 'auto'
    │              └ '/data/data/docs/1.pdf'
    └ <function pdf_parse_main at 0x7fb5affa2c20>

  File "/home/magic_pdf_parse_main.py", line 128, in pdf_parse_main
    pipe.pipe_parse()
    │    └ <function UNIPipe.pipe_parse at 0x7fb5affa1cf0>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fb5aff777c0>

**Comment by myhloli** [comment]
堆栈发最后几条，上面的看不到

**Comment by charliedream1** [comment]
2024-11-18 13:51:09.646 | ERROR    | magic_pdf.user_api:parse_pdf:97 - CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorre              ct.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):

  File "/home/remote_prg/llm_trainer_local/egs_func/a_misc_mdls/mdl_doc_parser/minu_test/magic_pdf_pa              rse_main.py", line 155, in <module>
    pdf_parse_main(pdf_path, parse_method, None,
    │              │         └ 'auto'
    │              └ '/data/nvme0/data/docs/1.pdf'
    └ <function pdf_parse_main at 0x7fb5affa2c20>

  File "/home/remote_prg/llm_trainer_local/egs_func/a_misc_mdls/mdl_doc_parser/minu_test/magic_pdf_pa              rse_main.py", line 128, in pdf_parse_main
    pipe.pipe_parse()
    │    └ <function UNIPipe.pipe_parse at 0x7fb5affa1cf0>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fb5aff777c0>

  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 44, in pipe              _parse
    self.pdf_mid_data = parse_union_pdf(self.pdf_bytes, self.model_list, self.image_writer,
    │    │              │               │    │          │    │           │    └ <magic_pdf.rw.DiskReaderWriter.DiskR              eaderWriter object at 0x7fb705783bb0>
    │    │              │               │    │          │    │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at               0x7fb5aff777c0>
    │    │              │               │    │          │    └ [{'layout_dets': [{'category_id': 5, 'poly': [194.885              6658935547, 207.9164581298828, 1456.0513916015625, 207.9164581298828, 14...
    │    │              │               │    │          └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fb5aff777c0>
    │    │              │               │    └ b'%PDF-1.7\n%\xc2\xb3\xc7\xd8\r\n3 0 obj\r<</Author (\xfe\xff[\x8by\x              c0t<) /Comments () /Company () /CreationDate (D:20240709...
    │    │              │               └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fb5aff777c0>
    │    │              └ <function parse_union_pdf at 0x7fb5affa1ab0>
    │    └ None
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fb5aff777c0>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/user_api.py", line 117, in parse_u              nion_pdf
    pdf_info_dict = parse_pdf(parse_pdf_by_ocr)
                    │         └ <function parse_pdf_by_ocr at 0x7fb5aff717e0>
                    └ <function parse_union_pdf.<locals>.parse_pdf at 0x7fb46d179bd0>
> File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/user_api.py", line 88, in parse_pd              f
    return method(
           └ <function parse_pdf_by_ocr at 0x7fb5aff717e0>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_by_ocr.py", line 14, in               parse_pdf_by_ocr
    return pdf_parse_union(dataset,
           │               └ <magic_pdf.data.dataset.PymuDocDataset object at 0x7fb4fc1ab370>
           └ <function pdf_parse_union at 0x7fb5affa17e0>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line               654, in pdf_parse_union
    page_info = parse_page_core(
                └ <function parse_page_core at 0x7fb5affa1750>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line               579, in parse_page_core
    sorted_bboxes = sort_lines_by_model(fix_blocks, page_w, page_h, line_height)
                    │                   │           │       │       └ 10
                    │                   │           │       └ 841.9000244140625
                    │                   │           └ 595.2999877929688
                    │                   └ [{'type': 'table_body', 'bbox': [70, 74, 524, 753], 'group_id': 0, 'lines'              : [{'bbox': [70, 74, 524, 300.33333333333337], 'spa...
                    └ <function sort_lines_by_model at 0x7fb5affa13f0>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line               340, in sort_lines_by_model
    model = model_manager.get_model('layoutreader')
            │             └ <function ModelSingleton.get_model at 0x7fb5affa1240>
            └ <magic_pdf.pdf_parse_union_core_v2.ModelSingleton object at 0x7fb55e3c5960>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line               162, in get_model
    self._models[model_name] = model_init(model_name=model_name)
    │    │       │             │                     └ 'layoutreader'
    │    │       │             └ <function model_init at 0x7fb5affa1090>
    │    │       └ 'layoutreader'
    │    └ {}
    └ <magic_pdf.pdf_parse_union_core_v2.ModelSingleton object at 0x7fb55e3c5960>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line               144, in model_init
    model.to(device).eval()
    │     │  └ device(type='cuda')
    │     └ <function Module.to at 0x7fb58fc52320>
    └ LayoutLMv3ForTokenClassification(
        (layoutlmv3): LayoutLMv3Model(
          (embeddings): LayoutLMv3TextEmbeddings(
            (word_em...
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2796,               in to
    return super().to(*args, **kwargs)
                       │       └ {}
                       └ (device(type='cuda'),)
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1173, in t              o
    return self._apply(convert)
           │    │      └ <function Module.to.<locals>.convert at 0x7fb46d179d80>
           │    └ <function Module._apply at 0x7fb5b1b325f0>
           └ LayoutLMv3ForTokenClassification(
               (layoutlmv3): LayoutLMv3Model(
                 (embeddings): LayoutLMv3TextEmbeddings(
                   (word_em...
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _a              pply
    module._apply(fn)
    │      │      └ <function Module.to.<locals>.convert at 0x7fb46d179d80>
    │      └ <function Module._apply at 0x7fb5b1b325f0>
    └ LayoutLMv3Model(
        (embeddings): LayoutLMv3TextEmbeddings(
          (word_embeddings): Embedding(50265, 1024, padding_idx=1)
          (...
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _a              pply
    module._apply(fn)
    │      │      └ <function Module.to.<locals>.convert at 0x7fb46d179d80>
    │      └ <function Module._apply at 0x7fb5b1b325f0>
    └ LayoutLMv3TextEmbeddings(
        (word_embeddings): Embedding(50265, 1024, padding_idx=1)
        (token_type_embeddings): Embedding(1, ...
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/nn/modules/module.py", line 779, in _a              pply
    module._apply(fn)
    │      │      └ <function Module.to.<locals>.convert at 0x7fb46d179d80>
    │      └ <function Module._apply at 0x7fb5b1b325f0>
    └ Embedding(50265, 1024, padding_idx=1)
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/nn/modules/module.py", line 804, in _a              pply
    param_applied = fn(param)
                    │  └ Parameter containing:
                    │    tensor([[-0.0850,  0.0107,  0.0737,  ...,  0.0471,  0.0132, -0.0229],
                    │            [ 0.0067, -0.0134,  0.013...
                    └ <function Module.to.<locals>.convert at 0x7fb46d179d80>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1159, in c              onvert
    return t.to(
           │ └ <method 'to' of 'torch._C.TensorBase' objects>
           └ Parameter containing:
             tensor([[-0.0850,  0.0107,  0.0737,  ...,  0.0471,  0.0132, -0.0229],
                     [ 0.0067, -0.0134,  0.013...

RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorre              ct.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2024-11-18 13:51:09.658 | ERROR    | __main__:pdf_parse_main:141 - Both parse_pdf_by_txt and parse_pdf_by_ocr failed              .
Traceback (most recent call last):

  File "/home/remote_prg/llm_trainer_local/egs_func/a_misc_mdls/mdl_doc_parser/minu_test/magic_pdf_pa              rse_main.py", line 155, in <module>
    pdf_parse_main(pdf_path, parse_method, None,
    │              │         └ 'auto'
    │              └ '/data/nvme0/data/docs/1.pdf'
    └ <function pdf_parse_main at 0x7fb5affa2c20>

> File "/home/remote_prg/llm_trainer_local/egs_func/a_misc_mdls/mdl_doc_parser/minu_test/magic_pdf_pa              rse_main.py", line 128, in pdf_parse_main
    pipe.pipe_parse()
    │    └ <function UNIPipe.pipe_parse at 0x7fb5affa1cf0>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fb5aff777c0>

  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 44, in pipe              _parse
    self.pdf_mid_data = parse_union_pdf(self.pdf_bytes, self.model_list, self.image_writer,
    │    │              │               │    │          │    │           │    └ <magic_pdf.rw.DiskReaderWriter.DiskR              eaderWriter object at 0x7fb705783bb0>
    │    │              │               │    │          │    │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at               0x7fb5aff777c0>
    │    │              │               │    │          │    └ [{'layout_dets': [{'category_id': 5, 'poly': [194.885              6658935547, 207.9164581298828, 1456.0513916015625, 207.9164581298828, 14...
    │    │              │               │    │          └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fb5aff777c0>
    │    │              │               │    └ b'%PDF-1.7\n%\xc2\xb3\xc7\xd8\r\n3 0 obj\r<</Author (\xfe\xff[\x8by\x              c0t<) /Comments () /Company () /CreationDate (D:20240709...
    │    │              │               └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fb5aff777c0>
    │    │              └ <function parse_union_pdf at 0x7fb5affa1ab0>
    │    └ None
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fb5aff777c0>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/user_api.py", line 119, in parse_u              nion_pdf
    raise Exception("Both parse_pdf_by_txt and parse_pdf_by_ocr failed.")

Exception: Both parse_pdf_by_txt and parse_pdf_by_ocr failed.



这是完整的错误信息

**Comment by myhloli** [comment]
排序调用的layoutreader模型，这个在有显卡的情况下会直接调用显卡，不会受device-mode的控制，因为这个模型占用的显存比较小，大概1个g就够了，能问下您的显卡是什么型号呢？

**Comment by charliedream1** [comment]
l40s

**Comment by myhloli** [comment]
nvidia-smi看一下，1个g显存都没有了？

**Comment by charliedream1** [comment]
主要在跑着别的模型，刚才把卡空出来，就能跑了

**Comment by charliedream1** [comment]
layoutreader模型要能控制一下设备最好。因为没资源了，所以刚才跑的cpu先试试

**Comment by myhloli** [comment]
这个懒得改了，我们目前只有两种环境用，一个是纯cpu的spark环境跑后处理，没有显卡就不会调用cuda，另外有显卡的环境都不会小于1g显存，应该是没有必要配置这个设备项的

**Comment by charliedream1** [comment]
好，知道了

**Comment by charliedream1** [comment]
另外，想问下，咱们后续能出一个word解析到markdown的工具吗？因为走模型总有识别错误，而且速度慢。word本来所有信息都能直接读取，但目前没找到好用的工具转markdown

**Comment by myhloli** [comment]
https://github.com/opendatalab/magic-doc
这个项目可以直接解析word，但是不会导出图片，我们目前没有人力继续维护了，如果有兴趣可以自己改着用下

**Comment by charliedream1** [comment]
这个之前试了下，调用的时候我看还是启动了模型。另外，word格式没法完全还原，标题的级别无法正确解析

**Comment by myhloli** [comment]
word没调用模型，就是python-docx库，你也可以自己基于这个库做二次开发

**Comment by charliedream1** [comment]
好的，知道了，感谢每次都这么光速回复
