### ISSUE TITLE
使用Quick CPU Demo中的命令下载预编译错误

### ISSUE THREAD

**Issue by coolinli** [opendatalab/MinerU#997]
### Description of the bug | 错误描述

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/mx/04ys855x6f57139j_j0vngzm0000gn/T/pip-install-ygg02oop/detectron2_5abc864f3e1244b2a7fec309a1a0f9f3/setup.py", line 10, in <module>
          import torch_npu
      ModuleNotFoundError: No module named 'torch_npu'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### How to reproduce the bug | 如何复现

输入指令pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com ，提示我没npu，不太懂我想弄cpu的为啥会提示npu

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
detectron2是一个预编译包，只需要保证你的python是3.10版本，都可以直接安装

**Comment by coolinli** [comment]
> detectorron2是一个预编译包，只需要保证你的python是3.10版本，都可以直接安装

Python的版本是3.10.15，但执行上面的命令时，就会报
`  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/mx/04ys855x6f57139j_j0vngzm0000gn/T/pip-install-cfoppeid/detectron2_bc04e10cf20a4edb9764d6d62ed8432e/setup.py", line 10, in <module>
          import torch_npu
      ModuleNotFoundError: No module named 'torch_npu'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by myhloli** [comment]
https://wheels.myhloli.com/detectron2/
在这个链接下载适配你的平台的包直接安装试试呢？

**Comment by yq-warehouse** [comment]
> https://wheels.myhloli.com/detectron2/ 在这个链接下载改装你的平台的包直接安装试试呢？

下载并安装后显示detectron2 is already installed，应该是可以了，但是我输入magic-pdf --version却显示zsh: command not found: magic-pdf

**Comment by coolinli** [comment]
> https://wheels.myhloli.com/detectron2/ 在这个链接下载适配你的平台的包直接安装试试呢？

感谢，已经显示ok了，将detectron2下载安装后，重新执行命令就可以了
